### ISSUE TITLE
[core] JadxRuntimeException in pass: ProcessVariables in a small method

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#1002]
Class `com.agoda.mobile.consumer.domain.ssr.sort.FilterMerger`
```java

    /* JADX DEBUG: Failed to insert an additional move for type inference into block B:5:0x0014 */
    /* JADX DEBUG: Multi-variable search result rejected for r2v0, resolved type: java.util.List<? extends T> */
    /* JADX DEBUG: Multi-variable search result rejected for r2v3, resolved type: java.util.List */
    /* JADX WARN: Multi-variable type inference failed */
    /* JADX WARN: Type inference failed for: r2v4 */
    /*  JADX ERROR: JadxRuntimeException in pass: ProcessVariables
        jadx.core.utils.exceptions.JadxRuntimeException: Code variable not set in r2v4 ??
        	at jadx.core.dex.instructions.args.SSAVar.getCodeVar(SSAVar.java:207)
        	at jadx.core.dex.visitors.regions.variables.ProcessVariables.collectCodeVars(ProcessVariables.java:142)
        	at jadx.core.dex.visitors.regions.variables.ProcessVariables.visit(ProcessVariables.java:47)
        */
    public final <T, K> java.util.List<T> merge(java.util.List r2, java.util.Set<? extends T> r3, kotlin.jvm.functions.Function1<? super T, ? extends K> r4) {
        /*
            r1 = this;
            java.lang.String r0 = "distinctBy"
            kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull(r4, r0)
            if (r3 == 0) goto L_0x0017
            if (r2 == 0) goto L_0x0013
            r0 = r2
            java.util.Collection r0 = (java.util.Collection) r0
            java.lang.Iterable r3 = (java.lang.Iterable) r3
            java.util.List r3 = com.agoda.mobile.consumer.data.extensions.CollectionExtensions.union(r0, r3, r4)
            goto L_0x0014
        L_0x0013:
            r3 = 0
        L_0x0014:
            if (r3 == 0) goto L_0x0017
            r2 = r3
        L_0x0017:
            if (r2 == 0) goto L_0x001a
            goto L_0x001e
        L_0x001a:
            java.util.List r2 = kotlin.collections.CollectionsKt.emptyList()
        L_0x001e:
            return r2
        */
        throw new UnsupportedOperationException("Method not decompiled: com.agoda.mobile.consumer.domain.ssr.sort.FilterMerger.merge(java.util.List, java.util.Set, kotlin.jvm.functions.Function1):java.util.List");
    }
```

APK: https://drive.google.com/file/d/1Hmwjs-Qc8kKc7mx90oC_n1YagOd01jar/view?usp=sharing

**Comment by skylot** [comment]
Fixed.
