### ISSUE TITLE
[core] APK isn't decompiled

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#1007]
Hey @skylot,
I'm using jadx-cli to decompile an apk, but nothing is saved. Args:
```
bin/jadx/bin/jadx --no-replace-consts --show-bad-code --threads-count 8 --no-inline-anonymous --no-imports --deobf --deobf-min 2 --deobf-rewrite-cfg --output-dir TEST 461ec55f-affb-461a-b307-6678e46e284b.apk 
```

I see only this using `jstack`
```
2020-11-05 02:38:11
Full thread dump Java HotSpot(TM) 64-Bit Server VM (14.0.2+12-46 mixed mode, sharing):

Threads class SMR info:
_java_thread_list=0x00007fdf16ee9260, length=11, elements={
0x00007fdf18009000, 0x00007fdf1700b800, 0x00007fdf1700e800, 0x00007fdf17020000,
0x00007fdf1700d800, 0x00007fdf17023000, 0x00007fdf1780b000, 0x00007fdf1981d800,
0x00007fdf1780c800, 0x00007fdf17830800, 0x00007fde7203e800
}

"main" #1 prio=5 os_prio=31 cpu=12090.82ms elapsed=198.69s tid=0x00007fdf18009000 nid=0x1d03 runnable  [0x0000700001e1d000]
   java.lang.Thread.State: RUNNABLE
	at java.util.LinkedList.linkLast(java.base@14.0.2/LinkedList.java:146)
	at java.util.LinkedList.add(java.base@14.0.2/LinkedList.java:342)
	at jadx.core.dex.nodes.parser.SignatureParser.consumeMethodArgs(SignatureParser.java:315)
	at jadx.core.dex.visitors.SignatureProcessor.parseMethodSignature(SignatureProcessor.java:106)
	at jadx.core.dex.visitors.SignatureProcessor.visit(SignatureProcessor.java:37)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:11)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$0(DepthTraversal.java:12)
	at jadx.core.dex.visitors.DepthTraversal$$Lambda$102/0x0000000800bda440.accept(Unknown Source)
	at java.util.ArrayList.forEach(java.base@14.0.2/ArrayList.java:1511)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:12)
	at jadx.core.dex.nodes.RootNode.runPreDecompileStage(RootNode.java:233)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:103)
	at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:42)
	at jadx.cli.JadxCLI.execute(JadxCLI.java:34)
	at jadx.cli.JadxCLI.main(JadxCLI.java:18)

   Locked ownable synchronizers:
	- None

"Reference Handler" #2 daemon prio=10 os_prio=31 cpu=0.66ms elapsed=198.68s tid=0x00007fdf1700b800 nid=0x3403 waiting on condition  [0x0000700003332000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ref.Reference.waitForReferencePendingList(java.base@14.0.2/Native Method)
	at java.lang.ref.Reference.processPendingReferences(java.base@14.0.2/Reference.java:241)
	at java.lang.ref.Reference$ReferenceHandler.run(java.base@14.0.2/Reference.java:213)

   Locked ownable synchronizers:
	- None

"Finalizer" #3 daemon prio=8 os_prio=31 cpu=0.15ms elapsed=198.68s tid=0x00007fdf1700e800 nid=0x3e03 in Object.wait()  [0x0000700004235000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@14.0.2/Native Method)
	- waiting on <0x0000000441197490> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@14.0.2/ReferenceQueue.java:155)
	- locked <0x0000000441197490> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@14.0.2/ReferenceQueue.java:176)
	at java.lang.ref.Finalizer$FinalizerThread.run(java.base@14.0.2/Finalizer.java:170)

   Locked ownable synchronizers:
	- None

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 cpu=0.30ms elapsed=198.67s tid=0x00007fdf17020000 nid=0x5703 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Service Thread" #5 daemon prio=9 os_prio=31 cpu=0.78ms elapsed=198.67s tid=0x00007fdf1700d800 nid=0x5903 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread0" #6 daemon prio=9 os_prio=31 cpu=2149.88ms elapsed=198.67s tid=0x00007fdf17023000 nid=0xa603 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

   Locked ownable synchronizers:
	- None

"C1 CompilerThread0" #14 daemon prio=9 os_prio=31 cpu=186.35ms elapsed=198.67s tid=0x00007fdf1780b000 nid=0xa403 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

   Locked ownable synchronizers:
	- None

"Sweeper thread" #18 daemon prio=9 os_prio=31 cpu=8.29ms elapsed=198.67s tid=0x00007fdf1981d800 nid=0xa303 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Notification Thread" #19 daemon prio=9 os_prio=31 cpu=0.04ms elapsed=198.66s tid=0x00007fdf1780c800 nid=0x9f03 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Common-Cleaner" #20 daemon prio=8 os_prio=31 cpu=0.90ms elapsed=198.66s tid=0x00007fdf17830800 nid=0x6303 in Object.wait()  [0x0000700009256000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@14.0.2/Native Method)
	- waiting on <0x0000000441165d78> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@14.0.2/ReferenceQueue.java:155)
	- locked <0x0000000441165d78> (a java.lang.ref.ReferenceQueue$Lock)
	at jdk.internal.ref.CleanerImpl.run(java.base@14.0.2/CleanerImpl.java:148)
	at java.lang.Thread.run(java.base@14.0.2/Thread.java:832)
	at jdk.internal.misc.InnocuousThread.run(java.base@14.0.2/InnocuousThread.java:134)

   Locked ownable synchronizers:
	- None

"Attach Listener" #21 daemon prio=9 os_prio=31 cpu=0.92ms elapsed=87.50s tid=0x00007fde7203e800 nid=0x6907 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"VM Thread" os_prio=31 cpu=11862.63ms elapsed=198.68s tid=0x00007fdf181ab000 nid=0x4303 runnable  

"GC Thread#0" os_prio=31 cpu=63457.39ms elapsed=198.69s tid=0x00007fdf18035800 nid=0x4c03 runnable  

"GC Thread#1" os_prio=31 cpu=77285.57ms elapsed=198.10s tid=0x00007fdf171a2800 nid=0x6c03 runnable  

"GC Thread#2" os_prio=31 cpu=66693.22ms elapsed=198.10s tid=0x00007fdf18211000 nid=0x9703 runnable  

"GC Thread#3" os_prio=31 cpu=87571.40ms elapsed=198.10s tid=0x00007fdf18211800 nid=0x6d03 runnable  

"GC Thread#4" os_prio=31 cpu=75987.30ms elapsed=198.10s tid=0x00007fdee701d800 nid=0x6f03 runnable  

"GC Thread#5" os_prio=31 cpu=87515.31ms elapsed=198.10s tid=0x00007fdee701e000 nid=0x7103 runnable  

"GC Thread#6" os_prio=31 cpu=64368.84ms elapsed=198.10s tid=0x00007fdee701f000 nid=0x9503 runnable  

"GC Thread#7" os_prio=31 cpu=101284.31ms elapsed=198.10s tid=0x00007fdf18224000 nid=0x7303 runnable  

"GC Thread#8" os_prio=31 cpu=78493.55ms elapsed=198.10s tid=0x00007fdf18225000 nid=0x7503 runnable  

"GC Thread#9" os_prio=31 cpu=88772.71ms elapsed=198.10s tid=0x00007fdf18225800 nid=0x7603 runnable  

"GC Thread#10" os_prio=31 cpu=66549.80ms elapsed=198.10s tid=0x00007fdee701f800 nid=0x7803 runnable  

"GC Thread#11" os_prio=31 cpu=63695.34ms elapsed=198.10s tid=0x00007fdf198e2800 nid=0x7903 runnable  

"GC Thread#12" os_prio=31 cpu=110703.43ms elapsed=198.10s tid=0x00007fdf181f1000 nid=0x9003 runnable  

"G1 Main Marker" os_prio=31 cpu=0.38ms elapsed=198.69s tid=0x00007fdf18045000 nid=0x4a03 runnable  

"G1 Conc#0" os_prio=31 cpu=6325.73ms elapsed=198.69s tid=0x00007fdf18046000 nid=0x4603 runnable  

"G1 Conc#1" os_prio=31 cpu=6328.30ms elapsed=172.20s tid=0x00007fde72008800 nid=0x990b runnable  

"G1 Conc#2" os_prio=31 cpu=6328.42ms elapsed=172.20s tid=0x00007fde72009000 nid=0x680b runnable  

"G1 Refine#0" os_prio=31 cpu=306.26ms elapsed=198.69s tid=0x00007fdf1817a800 nid=0x4503 runnable  

"G1 Refine#1" os_prio=31 cpu=156.78ms elapsed=197.99s tid=0x00007fdeb78aa800 nid=0x8003 runnable  

"G1 Refine#2" os_prio=31 cpu=126.38ms elapsed=197.99s tid=0x00007fdeb7096000 nid=0x8503 runnable  

"G1 Refine#3" os_prio=31 cpu=98.45ms elapsed=197.99s tid=0x00007fde77029000 nid=0x8303 runnable  

"G1 Refine#4" os_prio=31 cpu=85.53ms elapsed=197.99s tid=0x00007fdec7818800 nid=0xaa03 runnable  

"G1 Refine#5" os_prio=31 cpu=63.15ms elapsed=197.99s tid=0x00007fdea78ea000 nid=0xab03 runnable  

"G1 Refine#6" os_prio=31 cpu=56.52ms elapsed=197.99s tid=0x00007fdeb78ab800 nid=0x15203 runnable  

"G1 Refine#7" os_prio=31 cpu=47.97ms elapsed=197.99s tid=0x00007fde87036000 nid=0xac03 runnable  

"G1 Refine#8" os_prio=31 cpu=45.27ms elapsed=197.99s tid=0x00007fde5701f800 nid=0xae03 runnable  

"G1 Refine#9" os_prio=31 cpu=34.11ms elapsed=197.99s tid=0x00007fdeb7096800 nid=0x14f03 runnable  

"G1 Refine#10" os_prio=31 cpu=30.49ms elapsed=197.99s tid=0x00007fdeb78ad000 nid=0xaf03 runnable  

"G1 Refine#11" os_prio=31 cpu=28.01ms elapsed=197.88s tid=0x00007fde77057800 nid=0x14d03 runnable  

"G1 Refine#12" os_prio=31 cpu=27.89ms elapsed=197.88s tid=0x00007fdeb78de000 nid=0xb103 runnable  

"G1 Young RemSet Sampling" os_prio=31 cpu=1.66ms elapsed=198.69s tid=0x00007fdf1817b800 nid=0x3103 runnable  
"VM Periodic Task Thread" os_prio=31 cpu=69.62ms elapsed=198.66s tid=0x00007fdf1782f800 nid=0x9e03 waiting on condition  

JNI global refs: 18, weak refs: 0
```

APK: https://drive.google.com/file/d/1i6AUDIMj5Gv_8WIbOCd_7HWS8aRVemfV/view?usp=sharing

**Comment by bagipro** [comment]
jadx-gui also stucks, but outputs the following last exception
```
WARN  - Failed to parse method signature: (TCONTENTZ)Z in com.facebook.internal.FacebookDialogBase.ModeHandler.canShow(java.lang.Object, boolean):boolean
jadx.core.utils.exceptions.JadxRuntimeException: Can't parse type: (TCONTENTZ)Z at position 2 ('C'), unexpected: T
	at jadx.core.dex.nodes.parser.SignatureParser.consumeType(SignatureParser.java:172)
	at jadx.core.dex.nodes.parser.SignatureParser.consumeMethodArgs(SignatureParser.java:315)
	at jadx.core.dex.visitors.SignatureProcessor.parseMethodSignature(SignatureProcessor.java:106)
	at jadx.core.dex.visitors.SignatureProcessor.visit(SignatureProcessor.java:37)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:11)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$0(DepthTraversal.java:12)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:12)
	at jadx.core.dex.nodes.RootNode.runPreDecompileStage(RootNode.java:233)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:103)
	at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:43)
	at jadx.gui.ui.MainWindow.lambda$open$0(MainWindow.java:327)
	at jadx.gui.jobs.BackgroundExecutor$TaskWorker.doInBackground(BackgroundExecutor.java:100)
	at jadx.gui.jobs.BackgroundExecutor$TaskWorker.doInBackground(BackgroundExecutor.java:77)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at jadx.gui.jobs.BackgroundExecutor.lambda$execute$0(BackgroundExecutor.java:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by skylot** [comment]
@bagipro fixed. Thanks for report!
