### ISSUE TITLE
[GUI]  There was an error decompiling the JAR classes

### ISSUE THREAD

**Issue by caixiaomao** [skylot/jadx#1033]
**Describe error**
There was an error decompiling the JAR，The following is the error message：

ERROR: Failed to convert file: C:\Users\hejindong\Downloads\upms-service-1.0.0.jar
java.lang.RuntimeException: Java to dex conversion error, code: 1
 errors: 
PARSE ERROR:
com.android.dx.cf.iface.ParseException: class name (com/github/upms/UpmsApplication) does not match path (BOOT-INF/classes/com/github/upms/UpmsApplication.class)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:557)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:434)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:416)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:256)
	at com.android.dx.command.dexer.Main.parseClass(Main.java:773)
	at com.android.dx.command.dexer.Main.access$1600(Main.java:85)
	at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1766)
	at com.android.dx.command.dexer.Main.processClass(Main.java:756)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:724)
	at com.android.dx.command.dexer.Main.access$1200(Main.java:85)
	at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1719)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:285)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:165)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:143)
	at com.android.dx.command.dexer.Main.processOne(Main.java:678)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:575)
	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:365)
	at com.android.dx.command.dexer.Main.runDx(Main.java:286)
	at jadx.plugins.input.javaconvert.DxConverter.run(DxConverter.java:40)
	at jadx.plugins.input.javaconvert.JavaConvertLoader.convertJar(JavaConvertLoader.java:87)
	at jadx.plugins.input.javaconvert.JavaConvertLoader.lambda$processJars$1(JavaConvertLoader.java:41)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at jadx.plugins.input.javaconvert.JavaConvertLoader.processJars(JavaConvertLoader.java:39)
	at jadx.plugins.input.javaconvert.JavaConvertLoader.process(JavaConvertLoader.java:29)
	at jadx.plugins.input.javaconvert.JavaConvertPlugin.loadFiles(JavaConvertPlugin.java:21)
	at jadx.api.JadxDecompiler.loadInputFiles(JadxDecompiler.java:112)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:98)
	at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:46)
	at jadx.gui.ui.MainWindow.lambda$open$0(MainWindow.java:376)
	at jadx.gui.jobs.BackgroundExecutor$TaskWorker.doInBackground(BackgroundExecutor.java:100)
	at jadx.gui.jobs.BackgroundExecutor$TaskWorker.doInBackground(BackgroundExecutor.java:77)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at jadx.gui.jobs.BackgroundExecutor.lambda$execute$0(BackgroundExecutor.java:41)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
...while parsing BOOT-INF/classes/com/github/upms/UpmsApplication.class

1 error; aborting

	at jadx.plugins.input.javaconvert.DxConverter.run(DxConverter.java:46)
	at jadx.plugins.input.javaconvert.JavaConvertLoader.convertJar(JavaConvertLoader.java:87)
	at jadx.plugins.input.javaconvert.JavaConvertLoader.lambda$processJars$1(JavaConvertLoader.java:41)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at jadx.plugins.input.javaconvert.JavaConvertLoader.processJars(JavaConvertLoader.java:39)
	at jadx.plugins.input.javaconvert.JavaConvertLoader.process(JavaConvertLoader.java:29)
	at jadx.plugins.input.javaconvert.JavaConvertPlugin.loadFiles(JavaConvertPlugin.java:21)
	at jadx.api.JadxDecompiler.loadInputFiles(JadxDecompiler.java:112)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:98)
	at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:46)
	at jadx.gui.ui.MainWindow.lambda$open$0(MainWindow.java:376)
	at jadx.gui.jobs.BackgroundExecutor$TaskWorker.doInBackground(BackgroundExecutor.java:100)
	at jadx.gui.jobs.BackgroundExecutor$TaskWorker.doInBackground(BackgroundExecutor.java:77)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at jadx.gui.jobs.BackgroundExecutor.lambda$execute$0(BackgroundExecutor.java:41)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

What is the reason? 😢

**Comment by jpstotz** [comment]
Seems like the JAR files uses an unusual file-layout. Usually the root Java package is located in the root `/` of the JAR file, but in your case it is located in `INF/classes`. May be that is noted in the file  `META-INF/MANIFEST.MF`. I don't think that Jadx checks the MANIFEST.MF for the JAR-internal class path. 

As a work-around you can modify the JAR file using an archive editing tool and move all files and directories inside the JAR from `INF/classes` to `/`.

**Comment by caixiaomao** [comment]
It is a springboot fat jar 😢

**Comment by jpstotz** [comment]
Fat jars often contains JAR files within the fat JAR. Just unzip the fat jar and open the JAR file(s) in Jadx.
