### ISSUE TITLE
[code] can't decompile spring boot jar

### ISSUE THREAD

**Issue by lizhibin7530** [skylot/jadx#1066]
I download from the Latest release and decompiler a springboot project jar, the source code is blank. the log is :

```java
ERROR: Failed to convert file: C:\Users\lzb\Desktop\excutor\xxl-job-executor.jar
java.lang.RuntimeException: Java to dex conversion error, code: 1
 errors: 
PARSE ERROR:
com.android.dx.cf.iface.ParseException: class name (com/xxl/job/executor/XxlJobExecutorApplication) does not match path (BOOT-INF/classes/com/xxl/job/executor/XxlJobExecutorApplication.class)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:557)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:434)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:416)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:256)
	at com.android.dx.command.dexer.Main.parseClass(Main.java:773)
	at com.android.dx.command.dexer.Main.access$1600(Main.java:85)
	at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1766)
	at com.android.dx.command.dexer.Main.processClass(Main.java:756)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:724)
	at com.android.dx.command.dexer.Main.access$1200(Main.java:85)
	at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1719)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:285)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:165)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:143)
	at com.android.dx.command.dexer.Main.processOne(Main.java:678)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:575)
	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:365)
	at com.android.dx.command.dexer.Main.runDx(Main.java:286)
	at jadx.plugins.input.javaconvert.DxConverter.run(DxConverter.java:40)
	at jadx.plugins.input.javaconvert.JavaConvertLoader.convertJar(JavaConvertLoader.java:87)
	at jadx.plugins.input.javaconvert.JavaConvertLoader.lambda$processJars$1(JavaConvertLoader.java:41)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at jadx.plugins.input.javaconvert.JavaConvertLoader.processJars(JavaConvertLoader.java:39)
	at jadx.plugins.input.javaconvert.JavaConvertLoader.process(JavaConvertLoader.java:29)
	at jadx.plugins.input.javaconvert.JavaConvertPlugin.loadFiles(JavaConvertPlugin.java:21)
	at jadx.api.JadxDecompiler.loadInputFiles(JadxDecompiler.java:112)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:98)
	at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:46)
	at jadx.gui.ui.MainWindow.lambda$open$0(MainWindow.java:376)
	at jadx.gui.jobs.BackgroundExecutor$TaskWorker.doInBackground(BackgroundExecutor.java:100)
	at jadx.gui.jobs.BackgroundExecutor$TaskWorker.doInBackground(BackgroundExecutor.java:77)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at jadx.gui.jobs.BackgroundExecutor.lambda$execute$0(BackgroundExecutor.java:41)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
...while parsing BOOT-INF/classes/com/xxl/job/executor/XxlJobExecutorApplication.class

1 error; aborting

	at jadx.plugins.input.javaconvert.DxConverter.run(DxConverter.java:46)
	at jadx.plugins.input.javaconvert.JavaConvertLoader.convertJar(JavaConvertLoader.java:87)
	at jadx.plugins.input.javaconvert.JavaConvertLoader.lambda$processJars$1(JavaConvertLoader.java:41)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at jadx.plugins.input.javaconvert.JavaConvertLoader.processJars(JavaConvertLoader.java:39)
	at jadx.plugins.input.javaconvert.JavaConvertLoader.process(JavaConvertLoader.java:29)
	at jadx.plugins.input.javaconvert.JavaConvertPlugin.loadFiles(JavaConvertPlugin.java:21)
	at jadx.api.JadxDecompiler.loadInputFiles(JadxDecompiler.java:112)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:98)
	at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:46)
	at jadx.gui.ui.MainWindow.lambda$open$0(MainWindow.java:376)
	at jadx.gui.jobs.BackgroundExecutor$TaskWorker.doInBackground(BackgroundExecutor.java:100)
	at jadx.gui.jobs.BackgroundExecutor$TaskWorker.doInBackground(BackgroundExecutor.java:77)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at jadx.gui.jobs.BackgroundExecutor.lambda$execute$0(BackgroundExecutor.java:41)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jpstotz** [comment]
Can you please provide the JAR file you are trying to decompile? 
Please keep in mind that Jadx is primarily an Android dex code decompiler. It's Java jar/class decompilation capabilities are very limited.

**Comment by yangchunlan7530** [comment]
[demo.zip](https://github.com/skylot/jadx/files/5742568/demo.zip)

because my project file is to large，so I create a springboot demo project jar (thant is the attachment)，thant could show the error again。

**Comment by jpstotz** [comment]
The main problem with this JAR file is that it contains classes in an non-standard path: `BOOT-INF\classes`

Remove those classes and Jadx is able to convert and decompile the other classes. 

A second problem is that the JAR file contains nested JAR files. This is also not supported by Jadx.

**Comment by skylot** [comment]
I made a fix to allow loading spring boot jars.
