### ISSUE TITLE
[feature] Add support for Android App Bundle

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#1129]
*Describe your idea:*
Android App Bundle (`.aab`) is an official formal for Android apps. It's a container with default contents + configs for different devices (such as screen resolution)
![image](https://user-images.githubusercontent.com/15173437/110128000-f7db2000-7dce-11eb-87d7-ab5baabe54b1.png)

Decompiler works well for sources, but not for resources (that are not decompiled at all)
![image](https://user-images.githubusercontent.com/15173437/110128126-1f31ed00-7dcf-11eb-9864-988099a6b2ad.png)
![image](https://user-images.githubusercontent.com/15173437/110128331-57393000-7dcf-11eb-9fe2-fe137ca81b3e.png)

**Comment by bagipro** [comment]
Example: https://drive.google.com/file/d/1xin-UctM2xLkeb1uMtkoyD2eoC2EiAzO/view?usp=sharing

**Comment by bagipro** [comment]
I've discovered that all data can be deserialized using `com.android.aapt.Resources.XmlNode.parseFrom(byte[])` method. Looking for a better way to convert it to raw XML and integrate it into Jadx

**Comment by jpstotz** [comment]
When I use the latest version from master and open the Android app bundle linked in this issue I am getting in the log the following Exception:
```
ERROR - Failed to parse '.arsc' file
jadx.core.utils.exceptions.JadxException: Error decode: base/resources.pb
	at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:78)
	at jadx.core.dex.nodes.RootNode.loadResources(RootNode.java:153)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:107)
	at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:49)
	at jadx.gui.ui.MainWindow.lambda$open$0(MainWindow.java:384)
	at jadx.gui.jobs.BackgroundExecutor$TaskWorker.doInBackground(BackgroundExecutor.java:100)
	at jadx.gui.jobs.BackgroundExecutor$TaskWorker.doInBackground(BackgroundExecutor.java:77)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at jadx.gui.jobs.BackgroundExecutor.lambda$execute$0(BackgroundExecutor.java:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Not a table chunk, expected: 0x2, actual: 0xe612, offset: 0x2
	at jadx.core.xmlgen.ParserStream.throwException(ParserStream.java:118)
	at jadx.core.xmlgen.ParserStream.checkInt16(ParserStream.java:110)
	at jadx.core.xmlgen.ResTableParser.decodeTableChunk(ResTableParser.java:105)
	at jadx.core.xmlgen.ResTableParser.decode(ResTableParser.java:81)
	at jadx.core.dex.nodes.RootNode.lambda$loadResources$4(RootNode.java:155)
	at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:73)
	... 13 common frames omitted
```
