### ISSUE TITLE
[core] Reduced performance

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#1133]
Hey,

A few months ago, I noticed a change was introduced that led to a huge performance drop. For example, if you start decompilation of an app and run `jstack -l proc_id`, you will see that only one thread is running:
```
2021-03-09 23:20:17
Full thread dump Java HotSpot(TM) 64-Bit Server VM (14.0.2+12-46 mixed mode, sharing):

Threads class SMR info:
_java_thread_list=0x00007fb22b7c5950, length=21, elements={
0x00007fb29d961800, 0x00007fb29d810800, 0x00007fb29d00f800, 0x00007fb29d00e000,
0x00007fb29c069000, 0x00007fb29c80e000, 0x00007fb29c80f800, 0x00007fb26c808800,
0x00007fb26c80c000, 0x00007fb29d9a8800, 0x00007fb29db33800, 0x00007fb29e80a000,
0x00007fb29c9c9000, 0x00007fb29d4cc800, 0x00007fb26c8d5800, 0x00007fb29d2ca000,
0x00007fb26c8d9800, 0x00007fb1ee321000, 0x00007fb1ed8e5800, 0x00007fb1ee5e5800,
0x00007fb26c32c800
}

"Reference Handler" #2 daemon prio=10 os_prio=31 cpu=18.12ms elapsed=2151.56s tid=0x00007fb29d961800 nid=0x3a03 waiting on condition  [0x0000700002ef8000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ref.Reference.waitForReferencePendingList(java.base@14.0.2/Native Method)
	at java.lang.ref.Reference.processPendingReferences(java.base@14.0.2/Reference.java:241)
	at java.lang.ref.Reference$ReferenceHandler.run(java.base@14.0.2/Reference.java:213)

   Locked ownable synchronizers:
	- None

"Finalizer" #3 daemon prio=8 os_prio=31 cpu=8.27ms elapsed=2151.56s tid=0x00007fb29d810800 nid=0x4503 in Object.wait()  [0x0000700003dfb000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@14.0.2/Native Method)
	- waiting on <no object reference available>
	at java.lang.ref.ReferenceQueue.remove(java.base@14.0.2/ReferenceQueue.java:155)
	- locked <0x00000004400e4538> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@14.0.2/ReferenceQueue.java:176)
	at java.lang.ref.Finalizer$FinalizerThread.run(java.base@14.0.2/Finalizer.java:170)

   Locked ownable synchronizers:
	- None

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 cpu=0.27ms elapsed=2151.56s tid=0x00007fb29d00f800 nid=0xa903 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Service Thread" #5 daemon prio=9 os_prio=31 cpu=5.91ms elapsed=2151.56s tid=0x00007fb29d00e000 nid=0x5903 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread0" #6 daemon prio=9 os_prio=31 cpu=49476.53ms elapsed=2151.56s tid=0x00007fb29c069000 nid=0x5a03 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

   Locked ownable synchronizers:
	- None

"C1 CompilerThread0" #14 daemon prio=9 os_prio=31 cpu=2405.14ms elapsed=2151.56s tid=0x00007fb29c80e000 nid=0x5c03 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

   Locked ownable synchronizers:
	- None

"Sweeper thread" #18 daemon prio=9 os_prio=31 cpu=843.14ms elapsed=2151.56s tid=0x00007fb29c80f800 nid=0xa303 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Notification Thread" #19 daemon prio=9 os_prio=31 cpu=0.09ms elapsed=2151.54s tid=0x00007fb26c808800 nid=0xa003 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Common-Cleaner" #20 daemon prio=8 os_prio=31 cpu=4.16ms elapsed=2151.54s tid=0x00007fb26c80c000 nid=0x9d03 in Object.wait()  [0x0000700008e1c000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@14.0.2/Native Method)
	- waiting on <no object reference available>
	at java.lang.ref.ReferenceQueue.remove(java.base@14.0.2/ReferenceQueue.java:155)
	- locked <0x00000004400e11e0> (a java.lang.ref.ReferenceQueue$Lock)
	at jdk.internal.ref.CleanerImpl.run(java.base@14.0.2/CleanerImpl.java:148)
	at java.lang.Thread.run(java.base@14.0.2/Thread.java:832)
	at jdk.internal.misc.InnocuousThread.run(java.base@14.0.2/InnocuousThread.java:134)

   Locked ownable synchronizers:
	- None

"Timer-0" #21 daemon prio=5 os_prio=31 cpu=0.23ms elapsed=2151.11s tid=0x00007fb29d9a8800 nid=0x9803 in Object.wait()  [0x0000700009f25000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@14.0.2/Native Method)
	- waiting on <no object reference available>
	at java.lang.Object.wait(java.base@14.0.2/Object.java:321)
	at java.util.TimerThread.mainLoop(java.base@14.0.2/Timer.java:527)
	- locked <0x00000004400fea08> (a java.util.TaskQueue)
	at java.util.TimerThread.run(java.base@14.0.2/Timer.java:506)

   Locked ownable synchronizers:
	- None

"AppKit Thread" #23 daemon prio=5 os_prio=31 cpu=12165.08ms elapsed=2150.98s tid=0x00007fb29db33800 nid=0x307 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Java2D Queue Flusher" #25 daemon prio=10 os_prio=31 cpu=10488.20ms elapsed=2150.83s tid=0x00007fb29e80a000 nid=0xd607 in Object.wait()  [0x000070000c243000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@14.0.2/Native Method)
	- waiting on <no object reference available>
	at sun.java2d.opengl.OGLRenderQueue$QueueFlusher.run(java.desktop@14.0.2/OGLRenderQueue.java:205)
	- locked <0x00000004400eb1a8> (a sun.java2d.opengl.OGLRenderQueue$QueueFlusher)
	at java.lang.Thread.run(java.base@14.0.2/Thread.java:832)

   Locked ownable synchronizers:
	- None

"Java2D Disposer" #26 daemon prio=10 os_prio=31 cpu=44.96ms elapsed=2150.77s tid=0x00007fb29c9c9000 nid=0x9407 in Object.wait()  [0x000070000d146000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@14.0.2/Native Method)
	- waiting on <no object reference available>
	at java.lang.ref.ReferenceQueue.remove(java.base@14.0.2/ReferenceQueue.java:155)
	- locked <0x0000000440105670> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@14.0.2/ReferenceQueue.java:176)
	at sun.java2d.Disposer.run(java.desktop@14.0.2/Disposer.java:144)
	at java.lang.Thread.run(java.base@14.0.2/Thread.java:832)

   Locked ownable synchronizers:
	- None

"TimerQueue" #27 daemon prio=5 os_prio=31 cpu=2519.03ms elapsed=2149.28s tid=0x00007fb29d4cc800 nid=0xef17 runnable  [0x000070000e049000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@14.0.2/Native Method)
	- parking to wait for  <0x00000004400f4b60> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@14.0.2/LockSupport.java:252)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@14.0.2/AbstractQueuedSynchronizer.java:1661)
	at java.util.concurrent.DelayQueue.take(java.base@14.0.2/DelayQueue.java:229)
	at javax.swing.TimerQueue.run(java.desktop@14.0.2/TimerQueue.java:171)
	at java.lang.Thread.run(java.base@14.0.2/Thread.java:832)

   Locked ownable synchronizers:
	- <0x0000000440255e50> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)

"AWT-Shutdown" #29 prio=5 os_prio=31 cpu=0.63ms elapsed=2149.19s tid=0x00007fb26c8d5800 nid=0x1031b in Object.wait()  [0x000070000ef4c000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@14.0.2/Native Method)
	- waiting on <no object reference available>
	at java.lang.Object.wait(java.base@14.0.2/Object.java:321)
	at sun.awt.AWTAutoShutdown.run(java.desktop@14.0.2/AWTAutoShutdown.java:291)
	- locked <0x00000004400f8148> (a java.lang.Object)
	at java.lang.Thread.run(java.base@14.0.2/Thread.java:832)

   Locked ownable synchronizers:
	- None

"AWT-EventQueue-0" #31 prio=6 os_prio=31 cpu=12240.41ms elapsed=2149.13s tid=0x00007fb29d2ca000 nid=0xf103 waiting on condition  [0x000070000fe4f000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@14.0.2/Native Method)
	- parking to wait for  <0x00000004401c1c10> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@14.0.2/LockSupport.java:341)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(java.base@14.0.2/AbstractQueuedSynchronizer.java:505)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@14.0.2/ForkJoinPool.java:3137)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@14.0.2/AbstractQueuedSynchronizer.java:1614)
	at java.awt.EventQueue.getNextEvent(java.desktop@14.0.2/EventQueue.java:566)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@14.0.2/EventDispatchThread.java:190)
	at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@14.0.2/EventDispatchThread.java:124)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@14.0.2/EventDispatchThread.java:113)
	at java.awt.EventDispatchThread.pumpEvents(java.desktop@14.0.2/EventDispatchThread.java:109)
	at java.awt.EventDispatchThread.pumpEvents(java.desktop@14.0.2/EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.run(java.desktop@14.0.2/EventDispatchThread.java:90)

   Locked ownable synchronizers:
	- None

"DestroyJavaVM" #32 prio=5 os_prio=31 cpu=1208.65ms elapsed=2149.06s tid=0x00007fb26c8d9800 nid=0x1c03 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"SwingWorker-pool-9-thread-1" #83 daemon prio=5 os_prio=31 cpu=8.66ms elapsed=2045.18s tid=0x00007fb1ee321000 nid=0xb39f waiting on condition  [0x0000700013bb2000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@14.0.2/Native Method)
	- parking to wait for  <0x0000000440fef490> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@14.0.2/LockSupport.java:341)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(java.base@14.0.2/AbstractQueuedSynchronizer.java:505)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@14.0.2/ForkJoinPool.java:3137)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@14.0.2/AbstractQueuedSynchronizer.java:1614)
	at java.util.concurrent.LinkedBlockingQueue.take(java.base@14.0.2/LinkedBlockingQueue.java:435)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@14.0.2/ThreadPoolExecutor.java:1056)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@14.0.2/ThreadPoolExecutor.java:1116)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@14.0.2/ThreadPoolExecutor.java:630)
	at java.lang.Thread.run(java.base@14.0.2/Thread.java:832)

   Locked ownable synchronizers:
	- None

"SwingWorker-pool-9-thread-2" #121 daemon prio=5 os_prio=31 cpu=10.77ms elapsed=1660.94s tid=0x00007fb1ed8e5800 nid=0x16333 waiting on condition  [0x0000700012caf000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@14.0.2/Native Method)
	- parking to wait for  <0x0000000440fef490> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@14.0.2/LockSupport.java:341)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(java.base@14.0.2/AbstractQueuedSynchronizer.java:505)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@14.0.2/ForkJoinPool.java:3137)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@14.0.2/AbstractQueuedSynchronizer.java:1614)
	at java.util.concurrent.LinkedBlockingQueue.take(java.base@14.0.2/LinkedBlockingQueue.java:435)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@14.0.2/ThreadPoolExecutor.java:1056)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@14.0.2/ThreadPoolExecutor.java:1116)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@14.0.2/ThreadPoolExecutor.java:630)
	at java.lang.Thread.run(java.base@14.0.2/Thread.java:832)

   Locked ownable synchronizers:
	- None

"pool-14-thread-1" #155 prio=5 os_prio=31 cpu=434356.83ms elapsed=439.86s tid=0x00007fb1ee5e5800 nid=0x421b runnable  [0x0000700014ab4000]
   java.lang.Thread.State: RUNNABLE
	at jadx.core.dex.info.ClassInfo.makeRawFullName(ClassInfo.java:168)
	at jadx.core.dex.info.ClassInfo.makeFullClsName(ClassInfo.java:156)
	at jadx.core.dex.info.ClassInfo.makeRawFullName(ClassInfo.java:168)
	at jadx.core.dex.info.ClassInfo.makeFullClsName(ClassInfo.java:156)
	at jadx.core.dex.info.ClassInfo.makeRawFullName(ClassInfo.java:168)
	at jadx.core.dex.info.MethodInfo.getRawFullId(MethodInfo.java:106)
	at jadx.core.deobf.DeobfPresets.getForMth(DeobfPresets.java:174)
	at jadx.core.deobf.Deobfuscator.getAssignedAlias(Deobfuscator.java:521)
	at jadx.core.deobf.Deobfuscator.getMethodAlias(Deobfuscator.java:503)
	at jadx.core.deobf.Deobfuscator.renameMethod(Deobfuscator.java:210)
	at jadx.core.deobf.Deobfuscator.processClass(Deobfuscator.java:186)
	at jadx.core.deobf.Deobfuscator.processClass(Deobfuscator.java:189)
	at jadx.core.deobf.Deobfuscator.processClass(Deobfuscator.java:189)
	at jadx.core.deobf.Deobfuscator.process(Deobfuscator.java:156)
	at jadx.core.deobf.Deobfuscator.execute(Deobfuscator.java:77)
	at jadx.core.dex.visitors.RenameVisitor.process(RenameVisitor.java:41)
	at jadx.core.dex.visitors.RenameVisitor.init(RenameVisitor.java:34)
	at jadx.core.dex.nodes.RootNode.runPreDecompileStage(RootNode.java:246)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:108)
	at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:49)
	at jadx.gui.ui.MainWindow.lambda$open$0(MainWindow.java:384)
	at jadx.gui.ui.MainWindow$$Lambda$231/0x0000000800dcdc40.run(Unknown Source)
	at jadx.gui.jobs.BackgroundExecutor$TaskWorker.doInBackground(BackgroundExecutor.java:100)
	at jadx.gui.jobs.BackgroundExecutor$TaskWorker.doInBackground(BackgroundExecutor.java:77)
	at javax.swing.SwingWorker$1.call(java.desktop@14.0.2/SwingWorker.java:304)
	at java.util.concurrent.FutureTask.run(java.base@14.0.2/FutureTask.java:264)
	at javax.swing.SwingWorker.run(java.desktop@14.0.2/SwingWorker.java:343)
	at jadx.gui.jobs.BackgroundExecutor.lambda$execute$0(BackgroundExecutor.java:41)
	at jadx.gui.jobs.BackgroundExecutor$$Lambda$233/0x0000000800dcd440.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@14.0.2/ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@14.0.2/ThreadPoolExecutor.java:630)
	at java.lang.Thread.run(java.base@14.0.2/Thread.java:832)

   Locked ownable synchronizers:
	- <0x00000005117fe5c0> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"Attach Listener" #156 daemon prio=9 os_prio=31 cpu=0.71ms elapsed=2.23s tid=0x00007fb26c32c800 nid=0x9a1b waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"VM Thread" os_prio=31 cpu=2674.77ms elapsed=2151.57s tid=0x00007fb29c068800 nid=0x3703 runnable  

"GC Thread#0" os_prio=31 cpu=9270.66ms elapsed=2151.58s tid=0x00007fb29c038800 nid=0x4e03 runnable  

"GC Thread#1" os_prio=31 cpu=9217.56ms elapsed=2148.64s tid=0x00007fb29c346800 nid=0x1e21f runnable  

"GC Thread#2" os_prio=31 cpu=9293.55ms elapsed=2148.64s tid=0x00007fb29c347000 nid=0x1df03 runnable  

"GC Thread#3" os_prio=31 cpu=9273.31ms elapsed=2148.64s tid=0x00007fb23f0b9000 nid=0x1dd03 runnable  

"GC Thread#4" os_prio=31 cpu=9292.38ms elapsed=2148.64s tid=0x00007fb29c348000 nid=0x1db03 runnable  

"GC Thread#5" os_prio=31 cpu=9264.02ms elapsed=2148.64s tid=0x00007fb29c348800 nid=0x1d903 runnable  

"GC Thread#6" os_prio=31 cpu=9292.48ms elapsed=2148.64s tid=0x00007fb29c34c000 nid=0x1d707 runnable  

"GC Thread#7" os_prio=31 cpu=9254.04ms elapsed=2148.64s tid=0x00007fb29c34c800 nid=0x17403 runnable  

"GC Thread#8" os_prio=31 cpu=9237.57ms elapsed=2148.64s tid=0x00007fb29c34d800 nid=0x17307 runnable  

"GC Thread#9" os_prio=31 cpu=9265.07ms elapsed=2148.64s tid=0x00007fb29dd1f000 nid=0x17503 runnable  

"GC Thread#10" os_prio=31 cpu=9267.25ms elapsed=2148.64s tid=0x00007fb29dd32800 nid=0x1d303 runnable  

"GC Thread#11" os_prio=31 cpu=9271.62ms elapsed=2148.64s tid=0x00007fb29dd33800 nid=0x17703 runnable  

"GC Thread#12" os_prio=31 cpu=9285.71ms elapsed=2148.64s tid=0x00007fb29dd38800 nid=0x17803 runnable  

"G1 Main Marker" os_prio=31 cpu=26.15ms elapsed=2151.58s tid=0x00007fb29d809800 nid=0x3303 runnable  

"G1 Conc#0" os_prio=31 cpu=220337.51ms elapsed=2151.58s tid=0x00007fb29d82c000 nid=0x4c03 runnable  

"G1 Conc#1" os_prio=31 cpu=220287.73ms elapsed=2148.57s tid=0x00007fb29ca06000 nid=0x1c413 runnable  

"G1 Conc#2" os_prio=31 cpu=220307.19ms elapsed=2148.57s tid=0x00007fb29c812000 nid=0x18503 runnable  

"G1 Refine#0" os_prio=31 cpu=5086.41ms elapsed=2151.57s tid=0x00007fb29d961000 nid=0x4a03 runnable  

"G1 Refine#1" os_prio=31 cpu=1845.36ms elapsed=2100.43s tid=0x00007fb27c00b800 nid=0x14a03 runnable  

"G1 Refine#2" os_prio=31 cpu=1486.73ms elapsed=2100.43s tid=0x00007fb29c810800 nid=0xaf6f runnable  

"G1 Refine#3" os_prio=31 cpu=1255.92ms elapsed=2100.43s tid=0x00007fb29ca11800 nid=0x1cc1f runnable  

"G1 Refine#4" os_prio=31 cpu=1106.80ms elapsed=2100.43s tid=0x00007fb23f80f800 nid=0x1e833 runnable  

"G1 Refine#5" os_prio=31 cpu=958.84ms elapsed=2100.43s tid=0x00007fb258009000 nid=0x16627 runnable  

"G1 Refine#6" os_prio=31 cpu=857.87ms elapsed=2100.30s tid=0x00007fb22d153000 nid=0x1b70b runnable  

"G1 Refine#7" os_prio=31 cpu=788.91ms elapsed=2100.30s tid=0x00007fb22d154000 nid=0x19303 runnable  

"G1 Refine#8" os_prio=31 cpu=718.59ms elapsed=2100.30s tid=0x00007fb22d154800 nid=0x1b603 runnable  

"G1 Refine#9" os_prio=31 cpu=658.08ms elapsed=2099.86s tid=0x00007fb258092800 nid=0x1b41f runnable  

"G1 Refine#10" os_prio=31 cpu=612.64ms elapsed=2099.86s tid=0x00007fb22c0d7000 nid=0x1b303 runnable  

"G1 Refine#11" os_prio=31 cpu=553.83ms elapsed=2099.86s tid=0x00007fb27c1c6800 nid=0x19803 runnable  

"G1 Refine#12" os_prio=31 cpu=500.19ms elapsed=2099.86s tid=0x00007fb23c1d7800 nid=0x1b207 runnable  

"G1 Young RemSet Sampling" os_prio=31 cpu=417.85ms elapsed=2151.57s tid=0x00007fb29c039800 nid=0x4903 runnable  
"VM Periodic Task Thread" os_prio=31 cpu=1165.29ms elapsed=2151.54s tid=0x00007fb26c80b800 nid=0x6103 waiting on condition  

JNI global refs: 175, weak refs: 476
```

Is that intended to prevent deadlocks/access to shared resources?

**Comment by skylot** [comment]
@bagipro you catch deobfuscator stage, it was always single threaded. The last change was to fix overridden methods renaming (3bbb6b1058b81828eb83aa05333a2cea81526c27) that was not very optimal, so I already tried to improve it in b7ca898b772d7c0206c5b9fe8b2e810b899dcd69. But looks like this is not enough, I will check that code again. Thanks for the report!
If possible please share your test apk, maybe it has some uncommon code structure.

**Comment by bagipro** [comment]
@skylot 
Thanks! I wanted to file another bug, decompilation never finishes for that APK (however, on the same stage, so two different issues should be checked there):
https://drive.google.com/file/d/16mus08FFh0tflmchJM-PXu33lsZm1go0/view?usp=sharing

**Comment by bagipro** [comment]
Hi @skylot,

Did you have a chance to look at it?

**Comment by skylot** [comment]
@bagipro I spend some time, but still not sure how to better fix this. I will try to resolve this issue on the weekend :+1:

**Comment by skylot** [comment]
@bagipro I made a fix, deobfuscation works much faster now :smile:

**Comment by bagipro** [comment]
@skylot 
Thanks! What about the second issue with the freezed decompilation? Is that also fixed?

**Comment by skylot** [comment]
For me decompilation complete, although this app is quite big, so it takes several minutes.
