### ISSUE TITLE
jadx decode arsc fail

### ISSUE THREAD

**Issue by svnshing** [skylot/jadx#1138]
Error decode arsc
java.io.IOException: Unexpected type spec header size, expected: 0x10, actual: 0x0, offset: 0x1d1cd4
	at jadx.core.xmlgen.ParserStream.throwException(ParserStream.java:118)
	at jadx.core.xmlgen.ParserStream.checkInt16(ParserStream.java:110)
	at jadx.core.xmlgen.ResTableParser.parseTypeSpecChunk(ResTableParser.java:199)
	at jadx.core.xmlgen.ResTableParser.parsePackage(ResTableParser.java:163)
	at jadx.core.xmlgen.ResTableParser.decodeTableChunk(ResTableParser.java:113)
	at jadx.core.xmlgen.ResTableParser.decode(ResTableParser.java:81)
	at jadx.core.xmlgen.ResTableParser.decodeFiles(ResTableParser.java:86)

**Comment by jpstotz** [comment]
Can the newest apktool decode this app's resources? Can you share the APK file that causes this problem?

**Comment by skylot** [comment]
No reply
