### ISSUE TITLE
 Error saving class: kotlinx.coroutines.flow.FlowKt__ShareKt$launchSharing$1

### ISSUE THREAD

**Issue by xeinebiu** [skylot/jadx#1146]
INFO  - loading ...
INFO  - processing ...
ERROR - Error saving class: kotlinx.coroutines.flow.FlowKt__ShareKt$launchSharing$1
jadx.core.utils.exceptions.JadxRuntimeException: Failed to generate code for class: kotlinx.coroutines.flow.FlowKt__ShareKt$launchSharing$1
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:94)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:258)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:221)
	at jadx.api.JavaClass.getCodeInfo(JavaClass.java:53)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$1(JadxDecompiler.java:236)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: jadx.core.utils.exceptions.JadxRuntimeException: Codegen failed
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:90)
	... 7 common frames omitted
ERROR - Error saving class: kotlinx.coroutines.flow.internal.CombineKt$zipImpl$$inlined$unsafeFlow$1$lambda$1
jadx.core.utils.exceptions.JadxRuntimeException: Failed to generate code for class: kotlinx.coroutines.flow.internal.CombineKt$zipImpl$$inlined$unsafeFlow$1$lambda$1
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:94)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:258)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:221)
	at jadx.api.JavaClass.getCodeInfo(JavaClass.java:53)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$1(JadxDecompiler.java:236)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: jadx.core.utils.exceptions.JadxRuntimeException: Codegen failed
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:90)
	... 7 common frames omitted
ERROR - finished with errors, count: 13

**Comment by AndreMiras** [comment]
It did happen to me recently with https://play.google.com/store/apps/details?id=com.edilkamin.stufe
```
jadx --output-dir base base.apk                                                                                                                                                                 
INFO  - loading ...                                                                                                  
INFO  - processing ...                                                                                               
ERROR - Error saving class: kotlinx.coroutines.flow.FlowKt__ShareKt$launchSharing$1              
jadx.core.utils.exceptions.JadxRuntimeException: Failed to generate code for class: kotlinx.coroutines.flow.FlowKt__ShareKt$launchSharing$1
        at jadx.core.ProcessClass.generateCode(ProcessClass.java:94)              
        at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:258)                                               
        at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:221)                                                                                                                                                                      
        at jadx.api.JavaClass.getCodeInfo(JavaClass.java:53)                              
        at jadx.api.JadxDecompiler.lambda$appendSourcesSave$1(JadxDecompiler.java:236)                               
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                            
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                           
        at java.lang.Thread.run(Thread.java:748)                                                                     
Caused by: jadx.core.utils.exceptions.JadxRuntimeException: Codegen failed                                           
        at jadx.core.ProcessClass.generateCode(ProcessClass.java:90)                                                 
        ... 7 common frames omitted                                                                                  
ERROR - finished with errors, count: 20
```
APK attached: [base.tar.gz](https://github.com/skylot/jadx/files/8111552/base.tar.gz)

**Comment by xeinebiu** [comment]
> @xeinebiu can you share a sample app to reproduce this issue?

Sorry, I had missed this notification :(

**Comment by skylot** [comment]
@AndreMiras please try to use the latest version ([jadx-1.3.3.zip](https://github.com/skylot/jadx/releases/download/v1.3.3/jadx-1.3.3.zip)), using it I can't reproduce your issue.

**Comment by AndreMiras** [comment]
I confirm it does indeed solve the issue, see log below:
```
bin/jadx --output-dir base base.apk 
INFO  - loading ...
INFO  - processing ...
ERROR - finished with errors, count: 11
```
Thanks a mil
