### ISSUE TITLE
[core] CFG modification limit reached, blocks count: 315

### ISSUE THREAD

**Issue by gisthere** [skylot/jadx#1147]
Hi and thanks for your work!

Trying to decompile smali code using version from master branch (766e7193b9bb00bfd81bf2979d79a650bbf8c144)
`./build/jadx/bin/jadx -d out --log-level DEBUG 06H.smali`

and got following error:

> DEBUG - Loaded plugin: SmaliInput
> DEBUG - Loaded plugin: JavaConvert
> DEBUG - Loaded plugin: DexInput
> DEBUG - Effective jadx args: JadxArgs{inputFiles=[06H.smali], outDir=out, outDirSrc=out/sources, outDirRes=out/resources, threadsCount=4, cfgOutput=false, rawCFGOutput=false, fallbackMode=false, showInconsistentCode=false, useImports=true, skipResources=false, skipSources=false, deobfuscationOn=false, deobfuscationMapFile=null, deobfuscationForceSave=false, useSourceNameAsClassAlias=false, parseKotlinMetadata=false, deobfuscationMinLength=3, deobfuscationMaxLength=64, escapeUnicode=false, replaceConsts=true, respectBytecodeAccModifiers=false, exportAsGradleProject=false, fsCaseSensitive=false, renameFlags=[CASE, VALID, PRINTABLE], outputFormat=JAVA, codeCache=NoOpCodeCache, codeWriter=SimpleCodeWriter}
> INFO  - loading ...
> DEBUG - Loading dex: /tmp/jadx-6317635388376659855.dex
> INFO  - Loaded classes: 1, methods: 2, instructions: 1428
> DEBUG - Clst file loaded in 269ms, classes: 4750, methods: 48272
> DEBUG - '.arsc' file not found
> DEBUG - SignatureProcessor time: 2ms
> DEBUG - OverrideMethodVisitor time: 0ms
> DEBUG - ProcessAnonymous time: 0ms
> INFO  - Deobfuscation map file set to: /home/user/jadx/06H.jobf
> DEBUG - RenameVisitor time: 4ms
> DEBUG - UsageInfoVisitor time: 16ms
> INFO  - processing ...
> ERROR - [1383] JadxRuntimeException in pass: BlockProcessor in method: X.06H.A00(android.content.Context, android.content.Intent):boolean, file: /tmp/jadx-6317635388376659855.dex
> jadx.core.utils.exceptions.JadxRuntimeException: CFG modification limit reached, blocks count: 315
> 	at jadx.core.dex.visitors.blocksmaker.BlockProcessor.processBlocksTree(BlockProcessor.java:72)
> 	at jadx.core.dex.visitors.blocksmaker.BlockProcessor.visit(BlockProcessor.java:46)
> 	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:26)
> 	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
> 	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
> 	at jadx.core.ProcessClass.process(ProcessClass.java:58)
> 	at jadx.core.ProcessClass.generateCode(ProcessClass.java:87)
> 	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:253)
> 	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:218)
> 	at jadx.api.JavaClass.getCodeInfo(JavaClass.java:53)
> 	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$4(JadxDecompiler.java:279)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> ERROR - 1 errors occurred in following nodes:
> ERROR -   Method: X.06H.A00(android.content.Context, android.content.Intent):boolean
> ERROR - finished with errors, count: 1

`java --version`
> openjdk 11.0.10 2021-01-19
> OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
> OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

[06H.zip](https://github.com/skylot/jadx/files/6271462/06H.zip)

**Comment by gisthere** [comment]
No more errors, thanks! Can be closed.

BTW still has some warnings:

> DEBUG - Loaded plugin: SmaliInput
> DEBUG - Loaded plugin: JavaConvert
> DEBUG - Loaded plugin: DexInput
> DEBUG - Effective jadx args: JadxArgs{inputFiles=[06H.smali], outDir=out, outDirSrc=out/sources, outDirRes=out/resources, threadsCount=4, cfgOutput=false, rawCFGOutput=false, fallbackMode=false, showInconsistentCode=false, useImports=true, skipResources=false, skipSources=false, deobfuscationOn=false, deobfuscationMapFile=null, deobfuscationForceSave=false, useSourceNameAsClassAlias=false, parseKotlinMetadata=false, deobfuscationMinLength=3, deobfuscationMaxLength=64, escapeUnicode=false, replaceConsts=true, respectBytecodeAccModifiers=false, exportAsGradleProject=false, fsCaseSensitive=false, renameFlags=[CASE, VALID, PRINTABLE], outputFormat=JAVA, codeCache=NoOpCodeCache, codeWriter=SimpleCodeWriter}
> INFO  - loading ...
> DEBUG - Loading dex: /tmp/jadx-10927632456176634642.dex
> INFO  - Loaded classes: 1, methods: 2, instructions: 1428
> DEBUG - Clst file loaded in 338ms, classes: 4750, methods: 48272
> DEBUG - '.arsc' file not found
> DEBUG - SignatureProcessor time: 2ms
> DEBUG - OverrideMethodVisitor time: 0ms
> DEBUG - ProcessAnonymous time: 0ms
> INFO  - Deobfuscation map file set to: /home/user/jadx/06H.jobf
> DEBUG - RenameVisitor time: 5ms
> DEBUG - UsageInfoVisitor time: 19ms
> INFO  - processing ...
> WARN  - Can't compare types, unknown hierarchy: X.08L and java.lang.Throwable
> WARN  - Can't compare types, unknown hierarchy: X.08L and java.lang.Throwable
> WARN  - Can't compare types, unknown hierarchy: X.08L and java.lang.Throwable
> WARN  - Multi-variable type inference failed in X.06H.A00(android.content.Context, android.content.Intent):boolean
> WARN  - Type inference failed for: r10v0, types: [java.util.List] in X.06H.A00(android.content.Context, android.content.Intent):boolean
> WARN  - Type inference failed for: r10v1, types: [java.util.List] in X.06H.A00(android.content.Context, android.content.Intent):boolean
> WARN  - Type inference failed for: r10v2, types: [java.util.AbstractCollection, java.util.ArrayList] in X.06H.A00(android.content.Context, android.content.Intent):boolean
> DEBUG - Stop processing blocks after 'if': B:69:0x0187, method: X.06H.A00(android.content.Context, android.content.Intent):boolean
> WARN  - Removed duplicated region for block: B:250:? A[RETURN, SYNTHETIC] in method: X.06H.A00(android.content.Context, android.content.Intent):boolean, file: /tmp/jadx-10927632456176634642.dex
> WARN  - Removed duplicated region for block: B:43:0x0128 A[Catch:{ SecurityException -> 0x0565 }] in method: X.06H.A00(android.content.Context, android.content.Intent):boolean, file: /tmp/jadx-10927632456176634642.dex
> WARN  - Removed duplicated region for block: B:21:0x008a A[Catch:{ SecurityException -> 0x0565 }] in method: X.06H.A00(android.content.Context, android.content.Intent):boolean, file: /tmp/jadx-10927632456176634642.dex
> WARN  - Removed duplicated region for block: B:32:0x00e5 A[Catch:{ SecurityException -> 0x0565 }] in method: X.06H.A00(android.content.Context, android.content.Intent):boolean, file: /tmp/jadx-10927632456176634642.dex
> WARN  - Removed duplicated region for block: B:37:0x0108 A[Catch:{ SecurityException -> 0x0565 }] in method: X.06H.A00(android.content.Context, android.content.Intent):boolean, file: /tmp/jadx-10927632456176634642.dex
> WARN  - Removed duplicated region for block: B:43:0x0128 A[Catch:{ SecurityException -> 0x0565 }] in method: X.06H.A00(android.content.Context, android.content.Intent):boolean, file: /tmp/jadx-10927632456176634642.dex
> WARN  - Removed duplicated region for block: B:250:? A[RETURN, SYNTHETIC] in method: X.06H.A00(android.content.Context, android.content.Intent):boolean, file: /tmp/jadx-10927632456176634642.dex
> DEBUG - Duplicated block: X.06H.A00(android.content.Context, android.content.Intent):boolean - B:189:0x0505
> DEBUG - Duplicated block: X.06H.A00(android.content.Context, android.content.Intent):boolean - B:189:0x0505
> DEBUG - Duplicated block: X.06H.A00(android.content.Context, android.content.Intent):boolean - B:189:0x0505
> DEBUG - Duplicated block: X.06H.A00(android.content.Context, android.content.Intent):boolean - B:19:0x0082
> DEBUG - Duplicated block: X.06H.A00(android.content.Context, android.content.Intent):boolean - B:20:0x0088
> DEBUG - Duplicated block: X.06H.A00(android.content.Context, android.content.Intent):boolean - B:31:0x00e3
> DEBUG - Duplicated block: X.06H.A00(android.content.Context, android.content.Intent):boolean - B:35:0x00f4
> DEBUG - Duplicated block: X.06H.A00(android.content.Context, android.content.Intent):boolean - B:36:0x0106
> DEBUG - Duplicated block: X.06H.A00(android.content.Context, android.content.Intent):boolean - B:41:0x011e
> DEBUG - Duplicated block: X.06H.A00(android.content.Context, android.content.Intent):boolean - B:42:0x0126
> DEBUG - Duplicated block: X.06H.A00(android.content.Context, android.content.Intent):boolean - B:19:0x0082
> DEBUG - Duplicated block: X.06H.A00(android.content.Context, android.content.Intent):boolean - B:20:0x0088
> DEBUG - Duplicated block: X.06H.A00(android.content.Context, android.content.Intent):boolean - B:31:0x00e3
> DEBUG - Duplicated block: X.06H.A00(android.content.Context, android.content.Intent):boolean - B:35:0x00f4
> DEBUG - Duplicated block: X.06H.A00(android.content.Context, android.content.Intent):boolean - B:36:0x0106
> DEBUG - Duplicated block: X.06H.A00(android.content.Context, android.content.Intent):boolean - B:41:0x011e
> DEBUG - Duplicated block: X.06H.A00(android.content.Context, android.content.Intent):boolean - B:42:0x0126
> WARN  - Code restructure failed: missing block: B:69:0x0187, code lost:
>     if (r10.contains(r4) == false) goto L_0x0189;
>  in method: X.06H.A00(android.content.Context, android.content.Intent):boolean, file: /tmp/jadx-10927632456176634642.dex
> WARN  - Unknown variable types count: 1 in method: X.06H.A00(android.content.Context, android.content.Intent):boolean, file: /tmp/jadx-10927632456176634642.dex
> INFO  - done
