### ISSUE TITLE
[core]Error decode manifest

### ISSUE THREAD

**Issue by xmhwws** [skylot/jadx#1232]
apk link:https://drive.google.com/file/d/1kO75uhZ7hYJ08j-KF_HTYcZMaA40vCkW/view?usp=sharing

**Error decode manifest
java.io.IOException: Decode error: NAMESPACE header is not 0x0010, position: 0xdcbc
	at jadx.core.xmlgen.CommonBinaryParser.die(CommonBinaryParser.java:92)
	at jadx.core.xmlgen.BinaryXMLParser.parseNameSpace(BinaryXMLParser.java:151)
	at jadx.core.xmlgen.BinaryXMLParser.decode(BinaryXMLParser.java:111)
	at jadx.core.xmlgen.BinaryXMLParser.parse(BinaryXMLParser.java:79)**

![image](https://user-images.githubusercontent.com/42903751/130008739-5aa24b42-be7e-43e6-9984-00dadcac7310.png)

**Comment by jpstotz** [comment]
apktool also fails to decode `AndroidManifest.xml` of this app (`java.io.IOException: Invalid chunk type (1310976).`). 

Are you sure the app is usable on an Android device?

**Comment by xmhwws** [comment]
> Are you sure the app is usable on an Android device?

Yes, I'm sure this apk will work fine on Android phones.
This apk uses some kind of protective shell, which should be specially protected against decompiling tools, and that's why decompiling AndroidManifest.xml fails.

**Comment by jackwpa** [comment]
FWIW aapt, aapt2, JEB decode this manifest without problem.

**Comment by green9317** [comment]
I've been poking around and it appears that this manifest file has a chunk header size of 0x14. When reading the first namespace chunk (type 0x100).  Jadx currently searches for a size of 0x10 to ensure a valid header is found which is behavior I see in other apk parsers. 

I am having trouble finding a proper standard for the manifest but I think we could get jadx to read the file by removing the check.  Although, that might not be a great solution without knowing what the extra bytes are.

**Comment by jpstotz** [comment]
I tested the APK in [FlowDroid](https://github.com/secure-software-engineering/FlowDroid) which uses [Sable axml](https://github.com/Sable/axml) library for parsing AndroidManifest.xml. This library seems to ignore the namespace chunk type, it only has an error later as the read namespace prefix id is invalid (way too large) so [namespace parsing](https://github.com/Sable/axml/blob/master/src/pxb/android/axml/AxmlReader.java#L84) fails.

I have parsed thousand of Android apps using FlowDroid+axml, therefore I woudl assume that ignoring the namespace chunk type doesn't seem to be cause problems.
