### ISSUE TITLE
[core] Task exceeded time limit

### ISSUE THREAD

**Issue by google-mirror** [skylot/jadx#1269]
The latest unstable build will report 'Task exceeded time limit', but the latest release version not.

Already have '-DJADX_CLS_PROCESS_LIMIT=6000'

![111](https://user-images.githubusercontent.com/70927995/140920511-fea96a6e-c893-4282-9da7-263a64b34784.png)
![222](https://user-images.githubusercontent.com/70927995/140920522-51927e85-3e30-4eb0-849d-faa020302163.png)
![333](https://user-images.githubusercontent.com/70927995/140920530-fc58c42a-59f6-4686-ade3-a7663daed3a9.png)

**Comment by jpstotz** [comment]
Why do you close your issue https://github.com/skylot/jadx/issues/1267 and now open a new one?

I think you misunderstood me. I was talking about an environment variable not a Java system property (this is what you have done).

**Comment by skylot** [comment]
@google-mirror can you share apk sample? Timeout is quite big, so looks like something goes wrong during decompilation and without sample it is hard to say that exactly.

**Comment by google-mirror** [comment]
> @google-mirror can you share apk sample? Timeout is quite big, so looks like something goes wrong during decompilation and without sample it is hard to say what exactly.

https://dldir1.qq.com/wework/work_weixin/WeCom_android_3.1.19.18081_100001.apk

Only 'defpackage' and 'com.tencent.wework.**' included.

**Comment by jpstotz** [comment]
Wow that app is really a monster, 110MB of dex code. Decompiling the full app requires quite some time (40 minutes or more) even on a modern CPU with 6 threads and enough RAM. 

@skylot I have not checked it but my guess is that the number of classes to decompile only covers the classes selected by the include filter. But I assume that recursively also the classes used by those classes have to be decompiled, too. So the number of classes to decompile my be incorrect in this case and in the end causing the timeout.

**Comment by skylot** [comment]
@jpstotz yeah! This is a great sample for performance testing. Thank you @google-mirror!
Right now I am profiling it and found/fixed several issues: 
- some errors not caught and killing processing threads
- too many synchronizations at class index, as it executed with class decompilation, which cause processing threads stuck
- many more to come 🤣 

> I have not checked it but my guess is that the number of classes to decompile only covers the classes selected by the include filter.

I will check this, thanks!

**Comment by skylot** [comment]
I commit several fixes to speed up decompilation and indexing, redone usage info collection. Please check 👍🏽

**Comment by asLody** [comment]
@skylot Maybe it's time for a faster dom tree algorithm?

**Comment by skylot** [comment]
@asLody thanks for reminder! Sure, it is always nice to use linear algorithm instead of quadratic ([wiki](https://en.wikipedia.org/wiki/Dominator_(graph_theory)#Algorithms))

**Comment by google-mirror** [comment]
> I commit several fixes to speed up decompilation and indexing, redone usage info collection. Please check 👍🏽

It doesn't work.

```
ERROR: Decompile task execution failed
java.util.concurrent.ExecutionException: jadx.core.utils.exceptions.JadxRuntimeException: JavaClass not found by ClassNode: com.tencent.wework.R$raw
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
	at jadx.gui.ui.MainWindow.waitDecompileTask(MainWindow.java:550)
	at jadx.gui.ui.dialog.CommonSearchDialog$LoadTask.doInBackground(CommonSearchDialog.java:537)
	at jadx.gui.ui.dialog.CommonSearchDialog$LoadTask.doInBackground(CommonSearchDialog.java:527)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: jadx.core.utils.exceptions.JadxRuntimeException: JavaClass not found by ClassNode: com.tencent.wework.R$raw
	at jadx.api.JadxDecompiler.getJavaClassByNode(JadxDecompiler.java:462)
	at jadx.core.utils.Utils.collectionMapNoNull(Utils.java:216)
	at jadx.core.utils.DecompilerScheduler.lambda$buildBatches$0(DecompilerScheduler.java:37)
	at jadx.core.utils.Utils.collectionMap(Utils.java:205)
	at jadx.core.utils.DecompilerScheduler.buildBatches(DecompilerScheduler.java:37)
	at jadx.gui.JadxWrapper.buildDecompileBatches(JadxWrapper.java:92)
	at jadx.gui.jobs.DecompileTask.scheduleJobs(DecompileTask.java:58)
	at jadx.gui.jobs.BackgroundExecutor$TaskWorker.runJobs(BackgroundExecutor.java:103)
	at jadx.gui.jobs.BackgroundExecutor$TaskWorker.doInBackground(BackgroundExecutor.java:98)
	at jadx.gui.jobs.BackgroundExecutor$TaskWorker.doInBackground(BackgroundExecutor.java:77)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at jadx.gui.jobs.BackgroundExecutor.lambda$execute$0(BackgroundExecutor.java:44)
	... 3 common frames omitted

```

**Comment by skylot** [comment]
@google-mirror I commit a fix for that issue. Sorry for regression 😢
