### ISSUE TITLE
ERROR: JadxRuntimeException in pass: SSATransform [core]

### ISSUE THREAD

**Issue by LaryGala3** [skylot/jadx#1325]
A lot of function got error:  

  /*  JADX ERROR: JadxRuntimeException in pass: SSATransform
        jadx.core.utils.exceptions.JadxRuntimeException: Not initialized variable reg: 13, insn: 0x0864: MOVE  (r10 I:??[OBJECT, ARRAY]) = (r13 I:??[OBJECT, ARRAY]), block:B:387:0x0862
    at jadx.core.dex.visitors.ssa.SSATransform.renameVarsInBlock(SSATransform.java:171)
    at jadx.core.dex.visitors.ssa.SSATransform.renameVariables(SSATransform.java:143)
    at jadx.core.dex.visitors.ssa.SSATransform.process(SSATransform.java:60)
            */
    /*  JADX ERROR: Method generation error
        jadx.core.utils.exceptions.JadxRuntimeException: Code variable not set in r36v0 ??
        	at jadx.core.dex.instructions.args.SSAVar.getCodeVar(SSAVar.java:228)
        	at jadx.core.codegen.MethodGen.addMethodArguments(MethodGen.java:198)
        	at jadx.core.codegen.MethodGen.addDefinition(MethodGen.java:151)
        	at jadx.core.codegen.ClassGen.addMethodCode(ClassGen.java:364)
        	at jadx.core.codegen.ClassGen.addMethod(ClassGen.java:304)
        	at jadx.core.codegen.ClassGen.lambda$addInnerClsAndMethods$2(ClassGen.java:270)
        	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        	at java.util.ArrayList.forEach(Unknown Source)
        	at java.util.stream.SortedOps$RefSortingSink.end(Unknown Source)
        	at java.util.stream.Sink$ChainedReference.end(Unknown Source)
        */

**Comment by jpstotz** [comment]
First please name the used Jadx version. If you are using a release version re-check using the latest unstable version if the problem still exists.

Furthermore please always provide the APK file and name of the class + method that cause the problem.

**Comment by LaryGala3** [comment]
> First please name the used Jadx version. If you are using a release version re-check using the latest unstable version if the problem still exists.
> 
> Furthermore please always provide the APK file and name of the class + method that cause the problem.

Tested with latest and unstable version..
Test on tiktok apk and whatsapp apk.. I will provide soon the apk

**Comment by LaryGala3** [comment]
Apk attached.
class: com.google.android.gms.measurement.internal.e function f.
APK is 35MB, split into 2 parts:
[com.ss.android.ugc.trill.zip.002.zip](https://github.com/skylot/jadx/files/7815764/com.ss.android.ugc.trill.zip.002.zip)
[com.ss.android.ugc.trill.zip.001.zip](https://github.com/skylot/jadx/files/7815761/com.ss.android.ugc.trill.zip.001.zip)
