### ISSUE TITLE
[core] StackOverflowError error when decompiling app with deobfuscation enabled

### ISSUE THREAD

**Issue by JReverse** [skylot/jadx#1376]
**Checks before report**
- both done

**Describe error**
- Failed to decompile at all.

https://www.apkmirror.com/apk/snap-inc/snapchat/snapchat-11-65-0-31-release/snapchat-11-65-0-31-2-android-apk-download/

**Comment by jpstotz** [comment]
When deobfuscation is enabled and no jobf file exists then decompilation fails:

```
Caused by: java.lang.StackOverflowError: null
	at java.base/java.util.HashMap.putVal(HashMap.java:626)
	at java.base/java.util.HashMap.put(HashMap.java:607)
	at java.base/java.util.HashSet.add(HashSet.java:220)
	at jadx.core.utils.DecompilerScheduler.sumDeps(DecompilerScheduler.java:103)
	at jadx.core.utils.DecompilerScheduler.sumDeps(DecompilerScheduler.java:112)
	at jadx.core.utils.DecompilerScheduler.sumDeps(DecompilerScheduler.java:112)
```

**Comment by skylot** [comment]
Fixed. Just replace recursive dependency's sum with only first level.
