### ISSUE TITLE
[core] Renaming a class breaks already decompiled methods

### ISSUE THREAD

**Issue by oriori1703** [skylot/jadx#1378]
When renaming certain classes some of their methods break after already successfully decompiling before the rename.

- full name of method or class with error : **X.4f6.A00**
- full java stacktrace (no need to copy method fallback code (commented pseudocode)):
    - /*  JADX ERROR: JadxRuntimeException in pass: ModVisitor
        jadx.core.utils.exceptions.JadxRuntimeException: Method arg registers not loaded: X.4f8.<init>(X.0VB):void, class status: GENERATED_AND_UNLOADED
        	at jadx.core.dex.nodes.MethodNode.getArgRegs(MethodNode.java:247)
        	at jadx.core.dex.visitors.ModVisitor.processAnonymousConstructor(ModVisitor.java:460)
        	at jadx.core.dex.visitors.ModVisitor.replaceStep(ModVisitor.java:107)
        	at jadx.core.dex.visitors.ModVisitor.visit(ModVisitor.java:92)
        */

https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-192-0-0-35-123-release/

**Comment by skylot** [comment]
@oriori1703 fixed.
