### ISSUE TITLE
[core]  obfuscated samples 

### ISSUE THREAD

**Issue by eybisi** [skylot/jadx#1382]
I could analyze this sample in earlier versions of jadx. But lately some samples gave similar errors and jadx couldn't load any classes. I use unstable build for jadx. It also fails in stable build.

ERROR - [medusa.zip](https://github.com/skylot/jadx/files/8061561/medusa.zip): 
```
Load error in class: p0cc175b9, file: synthetic
jadx.core.utils.exceptions.JadxRuntimeException: Error decode class: p0cc175b9.p0cc175b9.p0cc175b9.p92eb5ffe.p0cc175b9.p0cc175b9.p0cc175b9
	at jadx.core.dex.nodes.ClassNode.initialLoad(ClassNode.java:130)
	at jadx.core.dex.nodes.ClassNode.<init>(ClassNode.java:101)
	at jadx.core.dex.nodes.RootNode.lambda$loadClasses$0(RootNode.java:92)
	at jadx.plugins.input.dex.DexReader.visitClasses(DexReader.java:35)
	at jadx.plugins.input.dex.DexLoadResult.visitClasses(DexLoadResult.java:27)
	at jadx.core.dex.nodes.RootNode.loadClasses(RootNode.java:90)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:114)
	at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:45)
	at jadx.gui.ui.MainWindow.lambda$open$0(MainWindow.java:421)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at jadx.plugins.input.dex.sections.DexAnnotationsConvert.convertSystemAnnotations(DexAnnotationsConvert.java:60)
	at jadx.plugins.input.dex.sections.DexAnnotationsConvert.appendAnnotations(DexAnnotationsConvert.java:45)
	at jadx.plugins.input.dex.sections.DexAnnotationsConvert.forClass(DexAnnotationsConvert.java:28)
	at jadx.plugins.input.dex.sections.DexClassData.getAttributes(DexClassData.java:200)
	at jadx.core.dex.nodes.ClassNode.initialLoad(ClassNode.java:106)
	... 11 common frames omitted
ERROR - Jadx init error
jadx.core.utils.exceptions.JadxRuntimeException: Class already exist: p0cc175b9
	at jadx.core.dex.nodes.ClassNode.addSyntheticClass(ClassNode.java:210)
	at jadx.core.dex.nodes.RootNode.addDummyClass(RootNode.java:130)
	at jadx.core.dex.nodes.RootNode.lambda$loadClasses$0(RootNode.java:94)
	at jadx.plugins.input.dex.DexReader.visitClasses(DexReader.java:35)
	at jadx.plugins.input.dex.DexLoadResult.visitClasses(DexLoadResult.java:27)
	at jadx.core.dex.nodes.RootNode.loadClasses(RootNode.java:90)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:114)
	at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:45)
	at jadx.gui.ui.MainWindow.lambda$open$0(MainWindow.java:421)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	```

**Comment by skylot** [comment]
@eybisi fixed :+1:
