### ISSUE TITLE
[core] JAR file does not load properly - permissions error?

### ISSUE THREAD

**Issue by TPXP** [skylot/jadx#1391]
Hello, first of all thanks so much for this awesome project. JADX is great and very powerful ! ❤️ 

I've recently tried to investigate an issue with a the GCP cloud storage emulator and found out that JADX has trouble loading it.

**Describe error**
- Attempt to import https://storage.googleapis.com/firebase-preview-drop/emulator/cloud-storage-rules-runtime-v1.0.0.jar
- It says "No classes loaded, nothing to decompile!"
<img width="309" alt="image" src="https://user-images.githubusercontent.com/56550972/155680021-a1721e45-b6b3-453e-b7ef-44143f737924.png">

- Nothing is loaded in JADX
- No error is logged into the terminal where I launched `jadx-gui`
```
$ jadx-gui
INFO  - output directory: cloud-storage-rules-runtime-v1.0.0
INFO  - loading ...
INFO  - Loaded classes: 0, methods: 0, instructions: 0
```

Test file: Google Cloud Storage emulator - https://storage.googleapis.com/firebase-preview-drop/emulator/cloud-storage-rules-runtime-v1.0.0.jar

**Manual import**
JADX is more verbose when I extract the JAR file manually and ask it to load it.
```
$ mkdir extracted
$ cd extracted
$ unzip ../cloud-storage-rules-runtime-v1.0.0.jar
$ jadx-gui .
INFO  - output directory:
INFO  - loading ...
ERROR - Failed to list files in directory: .
java.io.UncheckedIOException: java.nio.file.AccessDeniedException: ./org/antlr/v4/runtime/BailErrorStrategy.class
	at java.base/java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:87)
	at java.base/java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:103)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at jadx.core.utils.files.FileUtils.expandDir(FileUtils.java:56)
	at jadx.core.utils.files.FileUtils.expandDirs(FileUtils.java:46)
	at jadx.api.JadxDecompiler.loadInputFiles(JadxDecompiler.java:124)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:111)
	at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:45)
	at jadx.gui.ui.MainWindow.lambda$open$0(MainWindow.java:422)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.nio.file.AccessDeniedException: ./org/antlr/v4/runtime/BailErrorStrategy.class
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:226)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
	at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:374)
	at java.base/java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:83)
	... 18 common frames omitted
INFO  - Loaded classes: 0, methods: 0, instructions: 0
```

Adjusting permissions manually seems to address the issue.
```
chmod -R 755 .
jadx-gui .
```

I think JADX-GUI could try to handle these cases by itself, here are a few ideas I can think of:
- Ignore classes/directories for which it gets a permission denied error, but import the rest of the files
- Ignore permissions when extracting the jar file/fix them manually?

**Comment by jpstotz** [comment]
The reason why you can't open `cloud-storage-rules-runtime-v1.0.0.jar` is because it is not a valid ZIP file. It seems to be an ELF file with an attached ZIP archive. Most archive programs can open/unzip such files but technically it is not a valid ZIP file and the Java ZIP implementation does not support those "attached ZIP files".

**Comment by TPXP** [comment]
Hello, thanks for the prompt reply. 🤩 

The jar file runs fine with `java -jar`, thus I believe it would make sense to be able to open it with JADX.

```
$ java -jar cloud-storage-rules-runtime-v1.0.0.jar --help
    ~/Downloads  java -jar cloud-storage-rules-runtime-v1.0.1.jar --help                                      1 ✘
Usage: <main class> [options] [command] [command options]
  Options:
    --help
       Print usage and exit
       Default: false
    --licenses
       Print open-source dependencies and licenses, then exit
       Default: false
    --version
       Print version and exit
       Default: false
[...]
```

Just in case, the same issue occurs with version 1.0.1 : https://storage.googleapis.com/firebase-preview-drop/emulator/cloud-storage-rules-runtime-v1.0.1.jar

Perhaps the error message could be a little clearer as well? Like saying "Could not extract this JAR file, try extracting i manually"?

**Comment by jpstotz** [comment]
The Jadx java loader at the moment only checks the file-header which is not the one expected by a ZIP file, so the java loader is not applied. 

@skylot May be we can extend the file-type checking algorithm for ZIP/JAR files to not only check the header but similar to archive tools also check the last KB at the end of the file. If it finds there the hex code `50 4B 05 06` (end of central directory) then it is most likely a valid ZIP/JAR file.

**Comment by skylot** [comment]
@jpstotz point of checking header was to speed up file filter without loading whole file. So one way is to narrow by header checks type of files that can be a zip file and only next skips to the file end checks.
But I think it is better to pass this file by extension, because users expects it to open and if it is not supported by java ZipFile error will be thrown which will help to understand what happen.
I checked this file, and looks like ZipFile can process it without issues.

**Comment by skylot** [comment]
@TPXP, @jpstotz
I commit a fix to detect file type also by file extension, this resolve this issue, please check :)

> Ignore classes/directories for which it gets a permission denied error, but import the rest of the files

Not sure if this can be done, because exception thrown inside stream returned by `Files.walk`

> Ignore permissions when extracting the jar file

I don't see these issues in your sample after the fix, so maybe it is not an issue

**Comment by TPXP** [comment]
That was fast, thanks for the fast fix! I confirm it works with my test files.

Regarding the permissions issue, this one only occurred when I extracted the file manually with `unzip` so maybe it's the one at fault here. This is probably not an issue since JADX reads the file by itself.
