### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by AdminHcat** [skylot/jadx#1422]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.3.4.357-fe91d774
* Java version: 11.0.13
* Java VM: Amazon.com Inc. OpenJDK 64-Bit Server VM
* Platform: Windows 10 (10.0 amd64)
* Max heap size: 6206 MB
* Program args: -Xms443m -Xmx6206m -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -XX:+UseG1GC

```
java.lang.NullPointerException
	at jadx.gui.ui.dialog.UsageDialog.lambda$getMethodUseIn$1(UsageDialog.java:78)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at jadx.gui.ui.dialog.UsageDialog.getMethodUseIn(UsageDialog.java:78)
	at jadx.gui.ui.dialog.UsageDialog.collectUsageData(UsageDialog.java:66)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

com.corrodinggames.rts.game.units.am.c()
com.corrodinggames.rts.game.units.al  Line 2913

Error renaming
[game-lib.zip](https://github.com/skylot/jadx/files/8340230/game-lib.zip)

**Comment by jpstotz** [comment]
Thanks for reporting. Looks like we have to filter out null values in `JavaMethod.getOverrideRelatedMethods`. The null values are generated by `JadxDecompiler.convertNode(m)`

**Comment by skylot** [comment]
I commit a fix to correctly handle inlined (and moved) classes. Thanks, @AdminHcat!
