### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: -2, Tab count: 29

### ISSUE THREAD

**Issue by betteray** [skylot/jadx#1456]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.3.4
* Java version: 18
* Java VM: Homebrew OpenJDK 64-Bit Server VM
* Platform: Mac OS X (10.15.6 x86_64)
* Max heap size: 8192 MB
* Program args: -Xms128M -Xmx8g -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -XX:+UseG1GC

```
java.lang.IndexOutOfBoundsException: Index: -2, Tab count: 29
	at java.desktop/javax.swing.JTabbedPane.checkIndex(JTabbedPane.java:1794)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:622)
	at jadx.gui.ui.TabbedPane.lambda$new$0(TabbedPane.java:69)
	at java.desktop/java.awt.AWTEventMulticaster.mouseWheelMoved(AWTEventMulticaster.java:539)
	at java.desktop/java.awt.Component.processMouseWheelEvent(Component.java:6704)
	at java.desktop/java.awt.Component.processEvent(Component.java:6388)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4991)
	at java.desktop/java.awt.Container.dispatchEventToSelf(Container.java:2348)
	at java.desktop/java.awt.Component.dispatchMouseWheelToAncestor(Component.java:5136)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4888)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4823)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4604)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4823)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by shafqatsiyal** [comment]
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
