### ISSUE TITLE
"JadxOverflowException: Regions stack size limit reached" is thrown

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#146]
```java
   private static java.lang.String ˊ(byte r6, int r7, short r8) {
        /* JADX: method processing error */
/*
Error: jadx.core.utils.exceptions.JadxOverflowException: Regions stack size limit reached
	at jadx.core.utils.ErrorsCounter.addError(ErrorsCounter.java:37)
	at jadx.core.utils.ErrorsCounter.methodError(ErrorsCounter.java:61)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:33)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:17)
	at jadx.core.ProcessClass.process(ProcessClass.java:37)
	at jadx.core.ProcessClass.processDependencies(ProcessClass.java:59)
	at jadx.core.ProcessClass.process(ProcessClass.java:42)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:306)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
	at jadx.api.JadxDecompiler$1.run(JadxDecompiler.java:199)
*/
        /*
        r5 = ʽ;
        r8 = r8 * 16;
        r8 = 116 - r8;
        r4 = 0;
        r7 = r7 * 4;
        r7 = r7 + 4;
        r0 = new java.lang.String;
        r6 = r6 * 3;
        r6 = 6 - r6;
        r1 = new byte[r7];
        r7 = r7 + -1;
        if (r5 != 0) goto L_0x001c;
    L_0x0017:
        r2 = r6;
        r3 = r7;
    L_0x0019:
        r3 = -r3;
        r8 = r2 + r3;
    L_0x001c:
        r2 = (byte) r8;
        r1[r4] = r2;
        if (r4 != r7) goto L_0x0026;
    L_0x0021:
        r2 = 0;
        r0.<init>(r1, r2);
        return r0;
    L_0x0026:
        r2 = r8;
        r6 = r6 + 1;
        r4 = r4 + 1;
        r3 = r5[r6];
        goto L_0x0019;
        */
        throw new UnsupportedOperationException("Method not decompiled: o.ˁ.ˊ(byte, int, short):java.lang.String");
    }
```

**Comment by abozanona** [comment]
Did you find a solution for this problem?

**Comment by sergey-wowwow** [comment]
No, the bug is still present

**Comment by koxu1996** [comment]
I am also getting this error

**Comment by koxu1996** [comment]
@sergey-wowwow Why you closed issue? Is it solved?

**Comment by sergey-wowwow** [comment]
@koxu1996 No way to reproduce that, because APK is lost. But I'm sure that an issue with such exception was opened a few times, so no reason to keep that one opened
