### ISSUE TITLE
java.util.NoSuchElementException in com.google.android.gsf V5.1-1783956 (GAPPS)

### ISSUE THREAD

**Issue by cobalt232** [skylot/jadx#147]
Package: com.google.android.gsf
Class: com.google.android.gsf.subscribedfeeds.AbstractGDataSyncAdapter
Method: protected void getServerDiffsImpl

Downloadlink to package:
https://www.mycloud.ch/s/S009E717ACAB0559E2CCB51F28777100B35B0639B60F1400CDB96F9AF2369653

Error: java.util.NoSuchElementException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1431)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at jadx.core.dex.visitors.blocksmaker.BlockFinallyExtract.applyRemove(BlockFinallyExtract.java:517)
	at jadx.core.dex.visitors.blocksmaker.BlockFinallyExtract.extractFinally(BlockFinallyExtract.java:157)
	at jadx.core.dex.visitors.blocksmaker.BlockFinallyExtract.processExceptionHandler(BlockFinallyExtract.java:62)
	at jadx.core.dex.visitors.blocksmaker.BlockFinallyExtract.visit(BlockFinallyExtract.java:768)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:31)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:17)
	at jadx.core.ProcessClass.process(ProcessClass.java:37)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:311)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
	at jadx.api.JavaClass.getCode(JavaClass.java:48)

**Comment by cobalt232** [comment]
Any news on this one?

**Comment by mdtuyen** [comment]
+1

**Comment by sergey-wowwow** [comment]
@cobalt232 
This method contains known issues with exception handlers, but the original issue is not reproducible anymore
```java
    public void getServerDiffsImpl(com.google.android.gsf.subscribedfeeds.SyncableContentProvider tempProvider, java.lang.Class feedEntryClass, java.lang.String feedUrl, java.lang.Object syncInfo, int maxResults, com.google.android.gsf.subscribedfeeds.AbstractGDataSyncAdapter.GDataSyncData syncData, android.content.SyncResult syncResult) {
        com.google.wireless.gdata.parser.GDataParser parser;
        long entryLastUpdated;
        if (!this.mSyncCanceled) {
            com.google.android.gsf.subscribedfeeds.AbstractGDataSyncAdapter.GDataSyncData.FeedData feedSyncData = getFeedData(feedUrl, syncData);
            long lastSyncTime = 0;
            if (feedSyncData != null) {
                lastSyncTime = feedSyncData.lastUpdatedTime;
            }
            android.text.format.Time time = new android.text.format.Time("UTC");
            com.google.wireless.gdata.client.GDataServiceClient client = getGDataServiceClient();
            com.google.wireless.gdata.client.QueryParams params = client.createQueryParams();
            if (tempProvider.getContainsDiffs() && lastSyncTime > 0) {
                time.set(lastSyncTime);
                params.setUpdatedMin(time.format3339(false));
                params.setParamValue("requirealldeleted", "true");
            }
            int startIndex = 1;
            java.lang.String expectedFirstId = null;
            if (feedSyncData != null && feedSyncData.hasMoreEntriesToFetch) {
                startIndex = feedSyncData.endIndex;
                if (startIndex <= 0) {
                    throw new java.lang.IllegalArgumentException("bad startIndex, " + startIndex + ", it must be greater than 0, SyncData is " + feedSyncData);
                }
                params.setStartIndex(java.lang.String.valueOf(startIndex));
                maxResults++;
                expectedFirstId = feedSyncData.lastId;
            }
            params.setMaxResults(java.lang.String.valueOf(maxResults));
            java.lang.String lastId = null;
            int numResults = 0;
            com.google.wireless.gdata.parser.GDataParser parser2 = null;
            try {
                updateQueryParameters(params, feedSyncData);
                java.lang.String feedUrlToQuery = params.generateQueryUrl(feedUrl);
                try {
                    java.net.URI uri = new java.net.URI(feedUrlToQuery);
                    if (android.util.Log.isLoggable("Sync", 2)) {
                        android.util.Log.v("Sync", "Requesting feed " + feedUrlToQuery);
                    }
                    parser2 = client.getParserForFeed(feedEntryClass, feedUrlToQuery, this.mAuthToken);
                    this.mServerQueries++;
                    com.google.wireless.gdata.data.Feed feed = parser2.init();
                    java.lang.String feedUpdateDate = feed.getLastUpdated();
                    com.google.wireless.gdata.data.Entry entry = null;
                    long entryLastUpdated2 = lastSyncTime;
                    while (true) {
                        if (!parser2.hasMoreData() || numResults >= maxResults) {
                            if (feedUpdateDate == null) {
                                entryLastUpdated = 0;
                            } else {
                                time.parse3339(feedUpdateDate);
                                long feedUpdateMillis = time.toMillis(false);
                                if (300000 + feedUpdateMillis < java.lang.System.currentTimeMillis()) {
                                    feedUpdateMillis += 1000;
                                }
                                entryLastUpdated = feedUpdateMillis;
                            }
                        } else if (!this.mSyncCanceled) {
                            this.mServerEntries++;
                            numResults++;
                            entry = parser2.readNextEntry(entry);
                            if (android.util.Log.isLoggable("Sync", 2)) {
                                android.util.Log.v("Sync", "Read entry: " + entry.getTitle());
                            }
                            lastId = entry.getId();
                            if (numResults != 1 || expectedFirstId == null || expectedFirstId.equals(lastId)) {
                                if (android.util.Log.isLoggable("Sync", 2)) {
                                    android.util.Log.v("Sync", "getServerDiffs: updating provider with entry " + entry.getEditUri());
                                }
                                android.database.sqlite.SQLiteDatabase db = tempProvider.getDatabase();
                                if (db.inTransaction()) {
                                    throw new java.lang.IllegalStateException("we should not be in a transaction");
                                }
                                db.beginTransaction();
                                try {
                                    updateProvider(feed, null, entry, tempProvider, syncInfo, feedSyncData);
                                    android.content.SyncStats syncStats = syncResult.stats;
                                    syncStats.numEntries++;
                                    java.lang.String updateDate = entry.getUpdateDate();
                                    if (updateDate != null) {
                                        time.parse3339(updateDate);
                                        long updated = time.toMillis(false);
                                        if (updated > entryLastUpdated2) {
                                            entryLastUpdated2 = updated;
                                        }
                                    }
                                    db.setTransactionSuccessful();
                                    db.endTransaction();
                                } catch (com.google.wireless.gdata.parser.ParseException e) {
                                    android.content.SyncStats syncStats2 = syncResult.stats;
                                    syncStats2.numSkippedEntries++;
                                    db.endTransaction();
                                } catch (java.lang.RuntimeException e2) {
                                    android.content.SyncStats syncStats3 = syncResult.stats;
                                    syncStats3.numSkippedEntries++;
                                    db.endTransaction();
                                } catch (Throwable th) {
                                    db.endTransaction();
                                    throw th;
                                }
                            } else {
                                feedSyncData.hasMoreEntriesToFetch = false;
                                getServerDiffsImpl(tempProvider, feedEntryClass, feedUrl, syncInfo, maxResults, syncData, syncResult);
                                if (parser2 == null) {
                                    return;
                                }
                            }
                        } else if (parser2 == null) {
                            return;
                        }
                    }
                } catch (java.net.URISyntaxException e3) {
                    android.util.Log.d("Sync", "the feed url " + feedUrlToQuery + " is not a valid URI", e3);
                    android.content.SyncStats syncStats4 = syncResult.stats;
                    syncStats4.numParseExceptions++;
                    if (0 == 0) {
                        return;
                    }
                }
            } catch (com.google.wireless.gdata.parser.ParseException pe) {
                android.util.Log.e("Sync", "Unable to process gdata feed", pe);
                android.content.SyncStats syncStats5 = syncResult.stats;
                syncStats5.numParseExceptions++;
                if (parser2 == null) {
                    return;
                }
            } catch (java.io.IOException e4) {
            } catch (com.google.wireless.gdata.client.HttpException e5) {
            } catch (Throwable th2) {
                if (parser != null) {
                    parser.close();
                }
                throw th2;
            }
            parser2.close();
        }
    }
```
