### ISSUE TITLE
SmaliDebugger: io.github.hqktech.JDWP$JdwpRuntimeException: Insufficient space for decoding

### ISSUE THREAD

**Issue by magicjva** [skylot/jadx#1471]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.3.5
* Java version: 11.0.5
* Java VM: Oracle Corporation Java HotSpot(TM) 64-Bit Server VM
* Platform: Windows 10 (10.0 amd64)
* Max heap size: 11296 MB
* Program args: -Xms806m -Xmx11296m -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -XX:+UseG1GC

```
io.github.hqktech.JDWP$JdwpRuntimeException: Insufficient space for decoding, size(693501952) > bytes.length(2915).
	at io.github.hqktech.JDWP.checkCapability(JDWP.java:337)
	at io.github.hqktech.JDWP.decodeRaw(JDWP.java:401)
	at io.github.hqktech.JDWP$JdwpString.decode(JDWP.java:7475)
	at io.github.hqktech.JDWP$ReferenceType$MethodsWithGeneric.decode(JDWP.java:2417)
	at jadx.gui.device.debugger.SmaliDebugger.getMethodSignatureInternal(SmaliDebugger.java:998)
	at jadx.gui.device.debugger.SmaliDebugger.access$500(SmaliDebugger.java:83)
	at jadx.gui.device.debugger.SmaliDebugger$4.lambda$onMethodEntry$0(SmaliDebugger.java:412)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by jpstotz** [comment]
It is difficult to guess if this is a Jadx problem or a problem of the used smali [debugging library](https://github.com/HQKTech/jdwp). 

In both cases without a lot more details on how details (e.g. the APK you were debugging) and what classes you were looking at when the error occurred and so on. @magicjva Can you please provide those details?

**Comment by george-hopkins** [comment]
I encountered the same issue and was able to debug the APK after applying HQKTech/jdwp#2.

**Comment by skylot** [comment]
I made a fork for jdwp library, apply @george-hopkins fix and switch jadx to my fork, so this issue should be fixed now.
Can anyone check latest unstable build? :slightly_smiling_face:

**Comment by george-hopkins** [comment]
Thank you for fixing the issue! I was able to debug the affected APK with jadx-1.4.4.86-29b64300.

**Comment by skylot** [comment]
@george-hopkins great! Thank you for patch and fix confirmation :+1:
