### ISSUE TITLE
jadx.core.utils.exceptions.JadxRuntimeException: Can't create directory C:\Program Files\Android\Android Studio\resources\assets\--Added-by-androiddeployqt--\qml\QtQuick\Controls\Private

### ISSUE THREAD

**Issue by revolutiongit** [skylot/jadx#1473]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.3.5
* Java version: 18.0.1
* Java VM: Oracle Corporation Java HotSpot(TM) 64-Bit Server VM
* Platform: Windows 11 (10.0 amd64)
* Max heap size: 11336 MB
* Program args: -Xms128M -XX:MaxRAMPercentage=70.0 -XX:+UseG1GC -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true

```
jadx.core.utils.exceptions.JadxRuntimeException: Can't create directory C:\Program Files\Android\Android Studio\resources\assets\--Added-by-androiddeployqt--\qml\QtQuick\Controls\Private
	at jadx.core.utils.files.FileUtils.makeDirs(FileUtils.java:91)
	at jadx.core.utils.files.FileUtils.makeDirsForFile(FileUtils.java:81)
	at jadx.core.xmlgen.ResourcesSaver.saveToFile(ResourcesSaver.java:77)
	at jadx.core.xmlgen.ResourcesSaver.save(ResourcesSaver.java:55)
	at jadx.core.xmlgen.ResourcesSaver.saveResources(ResourcesSaver.java:45)
	at jadx.core.xmlgen.ResourcesSaver.run(ResourcesSaver.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by jpstotz** [comment]
The directory `C:\Program Files` is only writable by administrators, so unless you have started Jadx as an administrator with elevated permissions you can not write anything there.
You also have not provided any description about the steps you performed before the error occurred. 

Please do only select an output directory for decompilation where you have write permission.
