### ISSUE TITLE
[core] Bad second byte

### ISSUE THREAD

**Issue by VanHoevenTR** [skylot/jadx#1495]
When dropping an APK, I got dex error even though checksum is already disabled in settings. Apktool can still decompile APK perfectly

APK link: https://apkcombo.com/apk-downloader/#package=com.joycity.cryptoball&arches=armeabi-v7a

```
ERROR: Jadx init error
jadx.plugins.input.dex.DexException: Bad second byte
	at jadx.plugins.input.dex.utils.MUtf8.decode(MUtf8.java:23)
	at jadx.plugins.input.dex.sections.SectionReader.getString(SectionReader.java:178)
	at jadx.plugins.input.dex.sections.SectionReader.getType(SectionReader.java:165)
	at jadx.plugins.input.dex.sections.DexClassData.getType(DexClassData.java:44)
	at jadx.core.dex.nodes.RootNode.addDummyClass(RootNode.java:118)
	at jadx.core.dex.nodes.RootNode.lambda$loadClasses$0(RootNode.java:95)
	at jadx.plugins.input.dex.DexReader.visitClasses(DexReader.java:35)
	at jadx.plugins.input.dex.DexLoadResult.visitClasses(DexLoadResult.java:27)
	at jadx.core.dex.nodes.RootNode.loadClasses(RootNode.java:91)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:122)
	at jadx.gui.JadxWrapper.open(JadxWrapper.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

```

**Comment by skylot** [comment]
@VanHoevenTR thanks for report!
Here jadx was trying to load `assets/.zuzewwy.dex` file, looks like that file was modified to prevent loading.
I commit a fix to skip/ignore such files, so now jadx can load apk just fine :+1:

Not sure if this was a good idea to load all dex files in apk, but sometimes it is helpful and show classes which loads at runtime.
