### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "jadx.api.JadxDecompiler.getPluginManager()" because the return value of "jadx.gui.JadxWrapper.getDecompiler()" is null

### ISSUE THREAD

**Issue by HarukaMomono** [skylot/jadx#1506]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.4.1
* Java version: 18.0.1.1
* Java VM: Oracle Corporation OpenJDK 64-Bit Server VM
* Platform: Windows 10 (10.0 amd64)
* Max heap size: 4356 MB

```
java.lang.NullPointerException: Cannot invoke "jadx.api.JadxDecompiler.getPluginManager()" because the return value of "jadx.gui.JadxWrapper.getDecompiler()" is null
	at jadx.gui.settings.JadxSettingsWindow.makePluginOptionsGroup(JadxSettingsWindow.java:583)
	at jadx.gui.settings.JadxSettingsWindow.initUI(JadxSettingsWindow.java:131)
	at jadx.gui.settings.JadxSettingsWindow.<init>(JadxSettingsWindow.java:99)
	at jadx.gui.ui.MainWindow$11.actionPerformed(MainWindow.java:834)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by HarukaMomono** [comment]
I just clicked the preferences

**Comment by skylot** [comment]
@jpstotz sorry I broke that again in 98c0416b20e73dc05f7654ee992a1de0422d602d :cry:
Turns out, 'blank' objects are not a good way to resolve NPE, because such objects can provide incorrect data or hold bad state (can lead to memory leaks). This time I will try to restrict access to `decompiler` internal field and provide data only by methods in jadx wrapper.

**Comment by skylot** [comment]
Fixed, again :rofl:

@HarukaMomono you can try [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master).

**Comment by skylot** [comment]
Fix included in release [1.4.2](https://github.com/skylot/jadx/releases/tag/v1.4.2)
