### ISSUE TITLE
NegativeArraySizeException in JDWP

### ISSUE THREAD

**Issue by yanqizhen99** [skylot/jadx#1524]
Jadx version : 1.4.1
Java version : 18.0.1.1
Java VM      : Oracle Corporation OpenJDK 64-Bit Server VM
Platform     : Windows 10 (10.0 amd64)
Max heap size: 6144 MB

java.lang.NegativeArraySizeException: -610911488
	at io.github.hqktech.JDWP.decodeRaw(JDWP.java:402)
	at io.github.hqktech.JDWP$JdwpString.decode(JDWP.java:7475)
	at io.github.hqktech.JDWP$VirtualMachine$AllClassesWithGeneric.decode(JDWP.java:1553)
	at jadx.gui.device.debugger.SmaliDebugger.getAllClasses(SmaliDebugger.java:1074)
	at jadx.gui.device.debugger.SmaliDebugger.getClassSignatureInternal(SmaliDebugger.java:983)
	at jadx.gui.device.debugger.SmaliDebugger.getClassSignatureSync(SmaliDebugger.java:291)
	at jadx.gui.device.debugger.DebugController.fetchStackFrameNames(DebugController.java:580)
	at jadx.gui.device.debugger.DebugController.updateAllStackFrames(DebugController.java:565)
	at jadx.gui.device.debugger.DebugController.lambda$updateAllInfo$16(DebugController.java:870)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by jpstotz** [comment]
This error means your phone has sent data to the Jadx integrated debugger that had an unexpected format. 
To be able to understand and potentially solve this error we need more details: 

1. Is the problem reproducible (does it always occur when you are debugging a certain app)?
2. What Android device was used for debugging (manufacturer, model, Android version)
3. What app were you debugging (please provide APK if possible)

**Comment by jpstotz** [comment]
No user feedback

**Comment by george-hopkins** [comment]
I encountered the same issue and think it might a duplicate of #1471.
