### ISSUE TITLE
OutOfMemoryError in the latest version 

### ISSUE THREAD

**Issue by koudle** [skylot/jadx#155]
I pull the lastet source code from github and build it with gradle,but when i use jadx,it has a OutOfMemoryError:

```
12:49:59 ERROR - OutOfMemoryError in pass: FinishTypeInference in method: com.tencent.mm.plugin.freewifi.e.<init>(android.app.Activity):void
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Collections$UnmodifiableCollection.iterator(Collections.java:1038) ~[na:1.8.0_111]
	at jadx.core.dex.visitors.typeinference.FinishTypeInference.visit(FinishTypeInference.java:21) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:31) [jadx-core-0.6.1.jar:na]
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:17) [jadx-core-0.6.1.jar:na]
	at jadx.core.ProcessClass.process(ProcessClass.java:37) [jadx-core-0.6.1.jar:na]
	at jadx.core.ProcessClass.processDependencies(ProcessClass.java:59) [jadx-core-0.6.1.jar:na]
	at jadx.core.ProcessClass.process(ProcessClass.java:42) [jadx-core-0.6.1.jar:na]
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:306) [jadx-core-0.6.1.jar:na]
	at jadx.api.JavaClass.decompile(JavaClass.java:62) [jadx-core-0.6.1.jar:na]
	at jadx.gui.jobs.DecompileJob$1.run(DecompileJob.java:17) [jadx-gui-0.6.1.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
12:49:59 ERROR - Inconsistent code in method: com.tencent.mm.plugin.freewifi.a.a(com.tencent.mm.plugin.freewifi.a$a):void
12:50:16 ERROR - OutOfMemoryError in pass: DebugInfoVisitor in method: com.tencent.mm.plugin.freewifi.b.1.onReceive(android.content.Context, android.content.Intent):void
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.ArrayList.iterator(ArrayList.java:834) ~[na:1.8.0_111]
	at jadx.core.dex.nodes.parser.DebugInfoParser.addrChange(DebugInfoParser.java:185) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.dex.nodes.parser.DebugInfoParser.process(DebugInfoParser.java:90) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.dex.visitors.DebugInfoVisitor.visit(DebugInfoVisitor.java:19) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:31) [jadx-core-0.6.1.jar:na]
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:17) [jadx-core-0.6.1.jar:na]
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14) [jadx-core-0.6.1.jar:na]
	at jadx.core.ProcessClass.process(ProcessClass.java:37) [jadx-core-0.6.1.jar:na]
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:306) [jadx-core-0.6.1.jar:na]
	at jadx.api.JavaClass.decompile(JavaClass.java:62) [jadx-core-0.6.1.jar:na]
	at jadx.gui.jobs.DecompileJob$1.run(DecompileJob.java:17) [jadx-gui-0.6.1.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
12:50:28 ERROR - OutOfMemoryError in pass: BlockProcessor in method: com.tencent.mm.plugin.freewifi.k.j(com.tencent.mm.plugin.freewifi.k, java.lang.String):java.lang.String
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.BitSet.initWords(BitSet.java:166) ~[na:1.8.0_111]
	at java.util.BitSet.<init>(BitSet.java:161) ~[na:1.8.0_111]
	at jadx.core.dex.visitors.blocksmaker.BlockProcessor.computeDominators(BlockProcessor.java:82) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.dex.visitors.blocksmaker.BlockProcessor.processBlocksTree(BlockProcessor.java:48) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.dex.visitors.blocksmaker.BlockProcessor.visit(BlockProcessor.java:38) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:31) [jadx-core-0.6.1.jar:na]
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:17) [jadx-core-0.6.1.jar:na]
	at jadx.core.ProcessClass.process(ProcessClass.java:37) [jadx-core-0.6.1.jar:na]
	at jadx.core.ProcessClass.processDependencies(ProcessClass.java:59) [jadx-core-0.6.1.jar:na]
	at jadx.core.ProcessClass.process(ProcessClass.java:42) [jadx-core-0.6.1.jar:na]
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:306) [jadx-core-0.6.1.jar:na]
	at jadx.api.JavaClass.decompile(JavaClass.java:62) [jadx-core-0.6.1.jar:na]
	at jadx.gui.jobs.DecompileJob$1.run(DecompileJob.java:17) [jadx-gui-0.6.1.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
12:50:38 ERROR - OutOfMemoryError in pass: CodeShrinker in method: com.tencent.mm.plugin.freewifi.k.b(android.content.Intent, boolean):com.tencent.mm.plugin.freewifi.k
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.ArrayList.iterator(ArrayList.java:834) ~[na:1.8.0_111]
	at jadx.core.utils.BlockUtils.foundWrappedInsn(BlockUtils.java:232) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.utils.BlockUtils.foundWrappedInsn(BlockUtils.java:238) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.utils.BlockUtils.foundWrappedInsn(BlockUtils.java:238) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.utils.BlockUtils.foundWrappedInsn(BlockUtils.java:238) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.utils.BlockUtils.getBlockByWrappedInsn(BlockUtils.java:200) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.utils.BlockUtils.getBlockByInsn(BlockUtils.java:173) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.dex.visitors.CodeShrinker.shrinkBlock(CodeShrinker.java:229) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.dex.visitors.CodeShrinker.shrinkMethod(CodeShrinker.java:38) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.dex.visitors.CodeShrinker.visit(CodeShrinker.java:30) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:31) [jadx-core-0.6.1.jar:na]
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:17) [jadx-core-0.6.1.jar:na]
	at jadx.core.ProcessClass.process(ProcessClass.java:37) [jadx-core-0.6.1.jar:na]
	at jadx.core.ProcessClass.processDependencies(ProcessClass.java:59) [jadx-core-0.6.1.jar:na]
	at jadx.core.ProcessClass.process(ProcessClass.java:42) [jadx-core-0.6.1.jar:na]
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:306) [jadx-core-0.6.1.jar:na]
	at jadx.api.JavaClass.decompile(JavaClass.java:62) [jadx-core-0.6.1.jar:na]
	at jadx.gui.jobs.DecompileJob$1.run(DecompileJob.java:17) [jadx-gui-0.6.1.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Exception in thread "pool-3-thread-1" java.lang.OutOfMemoryError: GC overhead limit exceeded
12:51:06 ERROR - OutOfMemoryError in pass: BlockProcessor in method: com.tencent.mm.plugin.freewifi.e.c.1.a(int, int, java.lang.String, com.tencent.mm.v.k):void
java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "Timer-0" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-3-thread-2" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "AWT-EventQueue-0" Exception in thread "pool-3-thread-3" java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "AWT-XAWT" Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-3-thread-4" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-3-thread-5" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-3-thread-6" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-3-thread-7" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "AWT-EventQueue-0" Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-3-thread-8" 

```

**Comment by WillPangZi** [comment]
Try to config the JVM in the start script:
EX: DEFAULT_JVM_OPTS="-Xmx5000m"
