### ISSUE TITLE
java.lang.IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by flaltangyi** [skylot/jadx#1552]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.4.2
* Java version: 18.0.1.1
* Java VM: Oracle Corporation OpenJDK 64-Bit Server VM
* Platform: Windows 11 (10.0 amd64)
* Max heap size: 4096 MB

```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.ComparableTimSort.mergeHi(Unknown Source)
	at java.base/java.util.ComparableTimSort.mergeAt(Unknown Source)
	at java.base/java.util.ComparableTimSort.mergeForceCollapse(Unknown Source)
	at java.base/java.util.ComparableTimSort.sort(Unknown Source)
	at java.base/java.util.Arrays.sort(Unknown Source)
	at java.desktop/sun.awt.shell.Win32ShellFolderManager2.get(Unknown Source)
	at java.desktop/sun.awt.shell.ShellFolder.get(Unknown Source)
	at java.desktop/javax.swing.plaf.metal.MetalFileChooserUI$DirectoryComboBoxModel.addItem(Unknown Source)
	at java.desktop/javax.swing.plaf.metal.MetalFileChooserUI.doDirectoryChanged(Unknown Source)
	at java.desktop/javax.swing.plaf.metal.MetalFileChooserUI$5.propertyChange(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.desktop/java.awt.Component.firePropertyChange(Unknown Source)
	at java.desktop/javax.swing.JFileChooser.setCurrentDirectory(Unknown Source)
	at java.desktop/javax.swing.JFileChooser.<init>(Unknown Source)
	at java.desktop/javax.swing.JFileChooser.<init>(Unknown Source)
	at jadx.gui.ui.dialog.FileDialog$FileChooser.<init>(FileDialog.java:155)
	at jadx.gui.ui.dialog.FileDialog$FileChooser.<init>(FileDialog.java:155)
	at jadx.gui.ui.dialog.FileDialog.buildFileChooser(FileDialog.java:137)
	at jadx.gui.ui.dialog.FileDialog.show(FileDialog.java:73)
	at jadx.gui.ui.MainWindow.addFiles(MainWindow.java:304)
	at jadx.gui.ui.MainWindow$5.actionPerformed(MainWindow.java:840)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by jpstotz** [comment]
The only occurrence of `Arrays.sort(..)` in `sun.awt.shell.Win32ShellFolderManager2` is:

```
File[] secondLevelFolders = checkFiles(desktop.listFiles());
Arrays.sort(secondLevelFolders);
```

So this error is caused by the `Comparable` implementation of `java.io.File`.

My guess is that this is a very rare Java bug. May be caused by a file that is deleted while sorting is in progress.

**Comment by Illutax** [comment]
I found that creating two JFileChooser on windows does exaclty that. Somehow when calling it the second time it will inject another Documents folder and the Sort will go nuts. I might create a java bug ticket for that.
