### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "sun.awt.shell.Win32ShellFolder2.getChildByPath(String)" because "<local1>" is null

### ISSUE THREAD

**Issue by Sharathsharu6** [skylot/jadx#1553]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.4.2
* Java version: 18.0.1.1
* Java VM: Oracle Corporation OpenJDK 64-Bit Server VM
* Platform: Windows 10 (10.0 amd64)
* Max heap size: 5248 MB

```
java.lang.NullPointerException: Cannot invoke "sun.awt.shell.Win32ShellFolder2.getChildByPath(String)" because "<local1>" is null
	at java.desktop/sun.awt.shell.Win32ShellFolderManager2.getPersonal(Unknown Source)
	at java.desktop/sun.awt.shell.Win32ShellFolderManager2.get(Unknown Source)
	at java.desktop/sun.awt.shell.ShellFolder.get(Unknown Source)
	at java.desktop/javax.swing.filechooser.FileSystemView.getDefaultDirectory(Unknown Source)
	at java.desktop/javax.swing.JFileChooser.setCurrentDirectory(Unknown Source)
	at java.desktop/javax.swing.JFileChooser.<init>(Unknown Source)
	at java.desktop/javax.swing.JFileChooser.<init>(Unknown Source)
	at jadx.gui.ui.dialog.FileDialog$FileChooser.<init>(FileDialog.java:155)
	at jadx.gui.ui.dialog.FileDialog$FileChooser.<init>(FileDialog.java:155)
	at jadx.gui.ui.dialog.FileDialog.buildFileChooser(FileDialog.java:137)
	at jadx.gui.ui.dialog.FileDialog.show(FileDialog.java:73)
	at jadx.gui.ui.MainWindow.openFileOrProject(MainWindow.java:295)
	at jadx.gui.ui.MainWindow.processCommandLineArgs(MainWindow.java:252)
	at jadx.gui.ui.MainWindow.init(MainWindow.java:247)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by skylot** [comment]
I commit a workaround for this issue, hope it will help. Please check latest unstable build.
Maybe this fix will also resolve #1552 because it occurs in the same method.
