### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "jadx.gui.ui.panel.ContentPanel.getTabbedPane()" because the return value of "jadx.gui.ui.codearea.SmaliArea.getContentPanel()" is null

### ISSUE THREAD

**Issue by mcirsta** [skylot/jadx#1559]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.4.2
* Java version: 18.0.1.1
* Java VM: Oracle Corporation OpenJDK 64-Bit Server VM
* Platform: Windows 10 (10.0 amd64)
* Max heap size: 15792 MB

```
java.lang.NullPointerException: Cannot invoke "jadx.gui.ui.panel.ContentPanel.getTabbedPane()" because the return value of "jadx.gui.ui.codearea.SmaliArea.getContentPanel()" is null
	at jadx.gui.ui.codearea.SmaliArea$DebugModel$SmaliV2Style.getFont(SmaliArea.java:328)
	at jadx.gui.ui.codearea.SmaliArea$DebugModel.getFont(SmaliArea.java:240)
	at jadx.gui.ui.codearea.SmaliArea.getFont(SmaliArea.java:142)
	at org.fife.ui.rsyntaxtextarea.SyntaxView.updateMetrics(SyntaxView.java:903)
	at org.fife.ui.rsyntaxtextarea.SyntaxView.updateDamage(SyntaxView.java:829)
	at org.fife.ui.rsyntaxtextarea.SyntaxView.changedUpdate(SyntaxView.java:130)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.changedUpdate(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$UpdateHandler.changedUpdate(Unknown Source)
	at java.desktop/javax.swing.text.AbstractDocument.fireChangedUpdate(Unknown Source)
	at org.fife.ui.rsyntaxtextarea.RSyntaxDocument.updateLastTokensBelow(RSyntaxDocument.java:620)
	at org.fife.ui.rsyntaxtextarea.RSyntaxDocument.fireRemoveUpdate(RSyntaxDocument.java:236)
	at java.desktop/javax.swing.text.AbstractDocument.handleRemove(Unknown Source)
	at java.desktop/javax.swing.text.AbstractDocument.remove(Unknown Source)
	at java.desktop/javax.swing.text.AbstractDocument.replace(Unknown Source)
	at java.desktop/javax.swing.text.JTextComponent.setText(Unknown Source)
	at jadx.gui.ui.codearea.AbstractCodeArea.dispose(AbstractCodeArea.java:371)
	at jadx.gui.ui.codearea.CodePanel.dispose(CodePanel.java:200)
	at jadx.gui.ui.codearea.ClassCodeContentPanel.dispose(ClassCodeContentPanel.java:183)
	at jadx.gui.ui.TabbedPane.closeCodePanel(TabbedPane.java:312)
	at jadx.gui.ui.TabbedPane.closeAllTabs(TabbedPane.java:350)
	at jadx.gui.ui.TabbedPane.reset(TabbedPane.java:372)
	at jadx.gui.ui.MainWindow.clearTree(MainWindow.java:671)
	at jadx.gui.ui.MainWindow.closeAll(MainWindow.java:478)
	at jadx.gui.ui.MainWindow.closeWindow(MainWindow.java:1454)
	at jadx.gui.ui.MainWindow.access$000(MainWindow.java:146)
	at jadx.gui.ui.MainWindow$1.windowClosing(MainWindow.java:243)
	at java.desktop/java.awt.AWTEventMulticaster.windowClosing(Unknown Source)
	at java.desktop/java.awt.Window.processWindowEvent(Unknown Source)
	at java.desktop/javax.swing.JFrame.processWindowEvent(Unknown Source)
	at java.desktop/java.awt.Window.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at com.formdev.flatlaf.ui.FlatTitlePane.close(FlatTitlePane.java:691)
	at com.formdev.flatlaf.ui.FlatTitlePane.lambda$createButtons$3(FlatTitlePane.java:225)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by mcirsta** [comment]
This happened when trying to save a project

**Comment by skylot** [comment]
Duplicate of #1545 (already fixed).
