### ISSUE TITLE
Bad class file magic (3276474c) or version (3050.4138)

### ISSUE THREAD

**Issue by securitykitten** [skylot/jadx#156]
Hello, 

When running some tests of jadx (against a corpus of malware jar files), I've noticed several different crashes.  I'll do my best to report them (and the offending files) to github.

The first exception that I encountered was a "UNEXPECTED TOP-LEVEL EXCEPTION" that happened on a jar, sha256sum ```829c694bdf925d759aaaf6acc6b9ce14f8151e45bc6df3f2efec9f3fe0ffb305```

I've attached the file here (https://drive.google.com/open?id=0B6sLf2D8GZIQS1pCcWh5QXU2N1U)  in a password protected 7zip, password is "infected".  

**Warning: File is a live sample of malware.**

Below is the log of running jadx.

Thank you for the time.

```
jadx 829c694bdf925d759aaaf6acc6b9ce14f8151e45bc6df3f2efec9f3fe0ffb305.jar
23:58:46 INFO  - output directory: 829c694bdf925d759aaaf6acc6b9ce14f8151e45bc6df3f2efec9f3fe0ffb305
23:58:46 INFO  - converting to dex: 829c694bdf925d759aaaf6acc6b9ce14f8151e45bc6df3f2efec9f3fe0ffb305.jar ...
23:58:47 ERROR - jadx error: java class to dex conversion error:
 
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dx.cf.iface.ParseException: bad class file magic (3276474c) or version (3050.4138)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.processClass(Main.java:704)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:82)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:279)
	at com.android.dx.command.dexer.Main.run(Main.java:245)
	at jadx.core.utils.files.JavaToDex.convert(JavaToDex.java:51)
	at jadx.core.utils.files.InputFile.loadFromJar(InputFile.java:123)
	at jadx.core.utils.files.InputFile.searchDexFiles(InputFile.java:64)
	at jadx.core.utils.files.InputFile.addFilesFrom(InputFile.java:34)
	at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:121)
	at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:29)
	at jadx.cli.JadxCLI.main(JadxCLI.java:18)
...while parsing Os1M6607YvE16UzK.class

1 error; aborting

jadx.core.utils.exceptions.DecodeException: java class to dex conversion error:
 
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dx.cf.iface.ParseException: bad class file magic (3276474c) or version (3050.4138)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.processClass(Main.java:704)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:82)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:279)
	at com.android.dx.command.dexer.Main.run(Main.java:245)
	at jadx.core.utils.files.JavaToDex.convert(JavaToDex.java:51)
	at jadx.core.utils.files.InputFile.loadFromJar(InputFile.java:123)
	at jadx.core.utils.files.InputFile.searchDexFiles(InputFile.java:64)
	at jadx.core.utils.files.InputFile.addFilesFrom(InputFile.java:34)
	at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:121)
	at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:29)
	at jadx.cli.JadxCLI.main(JadxCLI.java:18)
...while parsing Os1M6607YvE16UzK.class

1 error; aborting

	at jadx.core.utils.files.InputFile.loadFromJar(InputFile.java:132) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.utils.files.InputFile.searchDexFiles(InputFile.java:64) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.utils.files.InputFile.addFilesFrom(InputFile.java:34) ~[jadx-core-0.6.1.jar:na]
	at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:121) ~[jadx-core-0.6.1.jar:na]
	at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:29) ~[jadx-cli-0.6.1.jar:na]
	at jadx.cli.JadxCLI.main(JadxCLI.java:18) ~[jadx-cli-0.6.1.jar:na]
Caused by: jadx.core.utils.exceptions.JadxException: 
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dx.cf.iface.ParseException: bad class file magic (3276474c) or version (3050.4138)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.processClass(Main.java:704)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:82)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:279)
	at com.android.dx.command.dexer.Main.run(Main.java:245)
	at jadx.core.utils.files.JavaToDex.convert(JavaToDex.java:51)
	at jadx.core.utils.files.InputFile.loadFromJar(InputFile.java:123)
	at jadx.core.utils.files.InputFile.searchDexFiles(InputFile.java:64)
	at jadx.core.utils.files.InputFile.addFilesFrom(InputFile.java:34)
	at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:121)
	at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:29)
	at jadx.cli.JadxCLI.main(JadxCLI.java:18)
...while parsing Os1M6607YvE16UzK.class

1 error; aborting

	at jadx.core.utils.files.InputFile.loadFromJar(InputFile.java:125) ~[jadx-core-0.6.1.jar:na]
	... 5 common frames omitted
```

**Comment by asashour** [comment]
This happens because the class files can not be converted to dex, the major version is incorrect, error happens [here](https://android.googlesource.com/platform/dalvik2/+/master/dx/src/com/android/dx/cf/direct/DirectClassFile.java#460).

I am not sure if something can be done here.

**Comment by sergey-wowwow** [comment]
Seems an invalid input apk is the reason of this bug
