### ISSUE TITLE
BlockFinish in method

### ISSUE THREAD

**Issue by CptFox** [skylot/jadx#159]
When trying to decompile an app, I get quite a lot of these. Any clue on how to fix them ?

```java
12:17:59 ERROR - JadxRuntimeException in pass: BlockFinish in method: com.psa.carprotocol.smartapps.dao.AlertDAO.updateAlert(com.psa.carprotocol.interfaces.bo.AlertBO):com.psa.carprotocol.interfaces.bo.AlertBO
jadx.core.utils.exceptions.JadxRuntimeException: Can't find block by offset: 0x0079 in list []
	at jadx.core.utils.BlockUtils.getBlockByOffset(BlockUtils.java:42) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.dex.instructions.IfNode.initBlocks(IfNode.java:60) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.dex.visitors.blocksmaker.BlockFinish.initBlocksInIfNodes(BlockFinish.java:48) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.dex.visitors.blocksmaker.BlockFinish.visit(BlockFinish.java:33) ~[jadx-core-0.6.1.jar:na]
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:31) [jadx-core-0.6.1.jar:na]
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:17) [jadx-core-0.6.1.jar:na]
	at jadx.core.ProcessClass.process(ProcessClass.java:37) [jadx-core-0.6.1.jar:na]
	at jadx.core.ProcessClass.processDependencies(ProcessClass.java:59) [jadx-core-0.6.1.jar:na]
	at jadx.core.ProcessClass.process(ProcessClass.java:42) [jadx-core-0.6.1.jar:na]
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:306) [jadx-core-0.6.1.jar:na]
	at jadx.api.JavaClass.decompile(JavaClass.java:62) [jadx-core-0.6.1.jar:na]
	at jadx.api.JadxDecompiler$1.run(JadxDecompiler.java:199) [jadx-core-0.6.1.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
```

**Comment by asashour** [comment]
Could you provide a minimal case that shows that error? Something like [this](https://github.com/skylot/jadx/blob/master/jadx-core/src/test/java/jadx/tests/integration/switches/TestSwitch.java)

**Comment by sergey-wowwow** [comment]
Closing as a dup of https://github.com/skylot/jadx/issues/240 and https://github.com/skylot/jadx/issues/213

**Comment by tourze** [comment]
```
JADX WARNING: Code restructure failed
```

same issue.
