### ISSUE TITLE
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;

### ISSUE THREAD

**Issue by XomaDev** [skylot/jadx#1607]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: dev
* Java version: 1.8.0_342
* Java VM: Private Build OpenJDK 64-Bit Server VM
* Platform: Linux (5.15.0-43-generic amd64)
* Max heap size: 10962 MB
* Program args: -Xms128M -XX:MaxRAMPercentage=70.0 -XX:+UseG1GC -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true

```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at jadx.plugins.input.dex.sections.SectionReader.duplicate(SectionReader.java:60)
	at jadx.plugins.input.dex.sections.SectionReader.<init>(SectionReader.java:34)
	at jadx.plugins.input.dex.DexReader.<init>(DexReader.java:22)
	at jadx.plugins.input.dex.DexFileLoader.loadDexReader(DexFileLoader.java:84)
	at jadx.plugins.input.dex.DexFileLoader.load(DexFileLoader.java:67)
	at jadx.plugins.input.dex.DexFileLoader.loadDexFromFile(DexFileLoader.java:50)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at jadx.plugins.input.dex.DexFileLoader.collectDexFiles(DexFileLoader.java:45)
	at jadx.plugins.input.dex.DexInputPlugin.loadFiles(DexInputPlugin.java:37)
	at jadx.plugins.input.dex.DexInputPlugin.loadFiles(DexInputPlugin.java:33)
	at jadx.api.JadxDecompiler.loadInputFiles(JadxDecompiler.java:133)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:117)
	at jadx.gui.JadxWrapper.open(JadxWrapper.java:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

```

**Comment by skylot** [comment]
@XomaDev this issue already discussed in #1150, check https://github.com/skylot/jadx/issues/1150#issuecomment-1132272094.
In short: looks like you compile jadx with newer java version (like java 11) and next execute it in java 8, this cause usage of incompatible classpath versions. So please build jadx with version you are gone to use in runtime.
If this is not your case, let me know and share details how you build your jadx version.
