### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by XomaDev** [skylot/jadx#1642]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: dev
* Java version: 1.8.0_342
* Java VM: Private Build OpenJDK 64-Bit Server VM
* Platform: Linux (5.15.0-46-generic amd64)
* Max heap size: 10962 MB
* Program args: -Xms128M -XX:MaxRAMPercentage=70.0 -XX:+UseG1GC -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true

```
java.lang.NullPointerException
	at jadx.gui.ui.dialog.CommonSearchDialog$ResultsTableCellRenderer.makeCell(CommonSearchDialog.java:448)
	at jadx.gui.ui.dialog.CommonSearchDialog$ResultsTableCellRenderer.getTableCellRendererComponent(CommonSearchDialog.java:423)
	at javax.swing.JTable$AccessibleJTable.getAccessibleChild(JTable.java:7037)
	at javax.swing.JTable$AccessibleJTable.getAccessibleAt(JTable.java:7424)
	at javax.swing.JTable$AccessibleJTable.valueChanged(JTable.java:6939)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:154)
	at javax.swing.DefaultListSelectionModel.setValueIsAdjusting(DefaultListSelectionModel.java:685)
	at javax.swing.plaf.basic.BasicTableUI$Handler.setValueIsAdjusting(BasicTableUI.java:953)
	at javax.swing.plaf.basic.BasicTableUI$Handler.mouseReleased(BasicTableUI.java:1166)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by MrIkso** [comment]
Update java to 11+

**Comment by jpstotz** [comment]
@MrIkso Even if I agree with you that Java11+ is recommended (but not required) for Jadx-gui, I don't think it will resolve this issue. The NullPointerException occurs because `getTableCellRendererComponent` is called with `null` as element to display. The element is provided by Jadx, so the used Java version should not have an impact on this.

**Comment by skylot** [comment]
@jpstotz 
> The element is provided by Jadx

Turns out this is not jadx providing null, it is specified in [java doc](https://docs.oracle.com/javase/8/docs/api/javax/swing/table/TableCellRenderer.html#getTableCellRendererComponent-javax.swing.JTable-java.lang.Object-boolean-boolean-int-int-) that `null is a valid value` and indeed if you check sources for `javax.swing.JTable$AccessibleJTable.getAccessibleChild(JTable.java:7037)` frame [here](https://github.com/openjdk/jdk8/blob/6a383433a9f4661a96a90b2a4c7b5b9a85720031/jdk/src/share/classes/javax/swing/JTable.java#L7040-L7042) method called with null value.
For now, I don't know what I should do for that case, also docs don't say if it allowed to return null :rofl:

**Comment by skylot** [comment]
Ok. I commit a fix, hope it will work, because I don't know how to reproduce this issue :slightly_frowning_face:
