### ISSUE TITLE
jadx.core.utils.exceptions.JadxRuntimeException: Decompiler not yet loaded

### ISSUE THREAD

**Issue by totallylost-helpme** [skylot/jadx#1644]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.4.3
* Java version: 18.0.2
* Java VM: Oracle Corporation OpenJDK 64-Bit Server VM
* Platform: Windows 11 (10.0 amd64)
* Max heap size: 4096 MB

```
jadx.core.utils.exceptions.JadxRuntimeException: Decompiler not yet loaded
	at jadx.gui.JadxWrapper.getDecompiler(JadxWrapper.java:209)
	at jadx.gui.JadxWrapper.unloadClasses(JadxWrapper.java:76)
	at jadx.gui.ui.dialog.SearchDialog.unloadTempData(SearchDialog.java:491)
	at jadx.gui.ui.dialog.SearchDialog.lambda$dispose$0(SearchDialog.java:155)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by jpstotz** [comment]
Happens if you open and close the search dialog before an APK has been loaded into Jadx.

**Comment by skylot** [comment]
I implement a listener to disable actions if no files are loaded, also use it to close search and usage dialogs on project close.
This should resolve this issue.
