### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "sun.awt.shell.Win32ShellFolder2.getIShellFolder()" because the return value of "sun.awt.shell.Win32ShellFolderManager2.getNetwork()" is null

### ISSUE THREAD

**Issue by Joker2HAO** [skylot/jadx#1657]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.4.3
* Java version: 18.0.2
* Java VM: Oracle Corporation Java HotSpot(TM) 64-Bit Server VM
* Platform: Windows 10 (10.0 amd64)
* Max heap size: 4920 MB
* Program args: -Xms351m -Xmx4918m -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -XX:+UseG1GC

```
java.lang.NullPointerException: Cannot invoke "sun.awt.shell.Win32ShellFolder2.getIShellFolder()" because the return value of "sun.awt.shell.Win32ShellFolderManager2.getNetwork()" is null
	at java.desktop/sun.awt.shell.Win32ShellFolder2.getFileSystemPath(Win32ShellFolder2.java:628)
	at java.desktop/sun.awt.shell.Win32ShellFolder2$10.call(Win32ShellFolder2.java:836)
	at java.desktop/sun.awt.shell.Win32ShellFolder2$10.call(Win32ShellFolder2.java:827)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.desktop/sun.awt.shell.Win32ShellFolderManager2$ComInvoker$1.run(Win32ShellFolderManager2.java:595)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by jpstotz** [comment]
Thanks for reporting this problem. Unfortunately this is yet another bug in the Java provided file dialog on Windows 10/11.

This means it is a bug in the Java run-time library, not a problem of Jadx - there is nothing we can do in Jadx to fix this problem. The latest version contains a workaround for a different file dialog bug on Windows 10/11, but I don't think that it will have an impact on this problem. Anyway, please try Jadx 1.4.4.

**Comment by skylot** [comment]
Possible workarounds:
- enable `Preferences -> Other -> Use alternative file dialog` option, this will use another file open dialog implementation.
- use jadx bundle with included JRE, maybe issue is fixed in latest java verions
- try jadx [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master)
