### ISSUE TITLE
[core]The code after anti -compilation will fall into a dead cycle

### ISSUE THREAD

**Issue by 2219160052** [skylot/jadx#1659]
[Non-native English speakers, use Google Translate]
When using (jadx), decompile a class, and the decompiled code falls into an infinite loop. I think this should be a bug. The code before decompilation does not fall into an infinite loop, and I use (IDEA) After decompilation, it is found that the decompiled code does not use (while), but uses (for) loop, and the decompiled code running (IDEA) does not fall into an infinite loop.
I don't have the source code for this class, the problem is the checkSign method in the SignService class.

[ErrorClass.zip](https://github.com/skylot/jadx/files/9437946/ErrorClass.zip)

![image](https://user-images.githubusercontent.com/31033119/187029949-09d5135c-f213-41ec-8d6f-2816323163e7.png)
![image](https://user-images.githubusercontent.com/31033119/187030024-0942541b-3f70-4b22-bc97-4f0b80cc89ba.png)

**Comment by jpstotz** [comment]
This issue seems to be similar to #1637 (while true loop, if case inside but no break)

**Comment by oxou** [comment]
Log level: Error
Version: 1.4.4
Binary: [jadx-gui-1.4.4-no-jre-win.exe](https://github.com/skylot/jadx/releases/download/v1.4.4/jadx-gui-1.4.4-no-jre-win.exe)
File causing the error: [resources.arsc.zip](https://github.com/skylot/jadx/files/9479118/resources.arsc.zip)
Java VM:
```
openjdk version "18.0.1.1" 2022-04-22
OpenJDK Runtime Environment (build 18.0.1.1+2-6)
OpenJDK 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)
```


jadx Error:

```
ERROR: Failed to parse '.arsc' file
jadx.core.utils.exceptions.JadxException: Error decode: D:\download\browser\resources.arsc
	at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:78)
	at jadx.core.dex.nodes.RootNode.loadResources(RootNode.java:173)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:122)
	at jadx.gui.JadxWrapper.open(JadxWrapper.java:65)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: Config size < 28
	at jadx.core.xmlgen.ResTableParser.parseConfig(ResTableParser.java:373)
	at jadx.core.xmlgen.ResTableParser.parseTypeChunk(ResTableParser.java:221)
	at jadx.core.xmlgen.ResTableParser.parsePackage(ResTableParser.java:162)
	at jadx.core.xmlgen.ResTableParser.decodeTableChunk(ResTableParser.java:110)
	at jadx.core.xmlgen.ResTableParser.decode(ResTableParser.java:86)
	at jadx.core.xmlgen.ResDecoder.decode(ResDecoder.java:28)
	at jadx.core.dex.nodes.RootNode.lambda$loadResources$7(RootNode.java:173)
	at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:61)
	... 6 common frames omitted
```
