### ISSUE TITLE
Error when building from source

### ISSUE THREAD

**Issue by ClaudeHangui** [skylot/jadx#166]
I'm on a mac
I cloned the repository but i got this error (after placing myself inside jadx parent directory) when trying to execute ./gradlew dist 

Exception in thread "main" java.util.zip.ZipException: zip file is empty
    at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:215)
	at java.util.zip.ZipFile.<init>(ZipFile.java:145)
	at java.util.zip.ZipFile.<init>(ZipFile.java:159)
	at org.gradle.wrapper.Install.unzip(Install.java:159)
	at org.gradle.wrapper.Install.access$500(Install.java:26)
	at org.gradle.wrapper.Install$1.call(Install.java:69)
	at org.gradle.wrapper.Install$1.call(Install.java:46)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:46)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

**Comment by sergey-wowwow** [comment]
@ClaudeHangui 
You should cd not to jadx parent directory, but to jadx directory
