### ISSUE TITLE
java.lang.IndexOutOfBoundsException: len=-19

### ISSUE THREAD

**Issue by shenpan233** [skylot/jadx#1668]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.4.4
* Java version: 18.0.2.1
* Java VM: Oracle Corporation OpenJDK 64-Bit Server VM
* Platform: Windows 10 (10.0 amd64)
* Max heap size: 5560 MB

```
java.lang.IndexOutOfBoundsException: len=-19
	at java.desktop/sun.font.FontDesignMetrics.charsWidth(Unknown Source)
	at org.fife.ui.rsyntaxtextarea.TokenImpl.getWidthUpTo(TokenImpl.java:601)
	at org.fife.ui.rsyntaxtextarea.TokenImpl.getWidth(TokenImpl.java:570)
	at org.fife.ui.rsyntaxtextarea.TokenUtils.getSubTokenList(TokenUtils.java:122)
	at org.fife.ui.rsyntaxtextarea.WrappedSyntaxView$WrappedLine.calculateLineCount(WrappedSyntaxView.java:1193)
	at org.fife.ui.rsyntaxtextarea.WrappedSyntaxView$WrappedLine.getPreferredSpan(WrappedSyntaxView.java:1241)
	at java.desktop/javax.swing.text.View.getMinimumSpan(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.calculateMajorAxisRequirements(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.checkRequests(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.layout(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSize(Unknown Source)
	at org.fife.ui.rsyntaxtextarea.WrappedSyntaxView.setSize(WrappedSyntaxView.java:1023)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.setSize(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.modelToView(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.modelToView(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.modelToView(Unknown Source)
	at java.desktop/javax.swing.text.JTextComponent.modelToView(Unknown Source)
	at org.fife.ui.rtextarea.RTextAreaBase.possiblyUpdateCurrentLineHighlightLocation(RTextAreaBase.java:754)
	at org.fife.ui.rtextarea.RTextArea.fireCaretUpdate(RTextArea.java:602)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.fireCaretUpdate(RSyntaxTextArea.java:874)
	at org.fife.ui.rtextarea.RTextAreaBase.processComponentEvent(RTextAreaBase.java:816)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by shenpan233** [comment]
I downloaded the newest JADX and then I exclubed some package in setting.After it analyzed the app,I try to attach app for debugging.At last it throw this error message.

**Comment by jpstotz** [comment]
Seems to be the same problem as #1658. Have you changed Jadx configuration e.g. a different font or does your Windows use a special theme with a non-standard font?

**Comment by shenpan233** [comment]
ohoh thx,I chanaged my theme in the past,I think it's the reason.

**Comment by jpstotz** [comment]
Issue created in RSyntaxTextArea project: https://github.com/bobbylight/RSyntaxTextArea/issues/652

**Comment by jpstotz** [comment]
This type of error seems to related to the feature "line wrapping" of the code view. 

In all the related issues I have checked the stack trace shows either `WrappedSyntaxView$WrappedLine` or `LineNumberList.paintWrappedLineNumbers`
