### ISSUE TITLE
NullPointerException in pass: ClassModifier

### ISSUE THREAD

**Issue by yangguangftlp** [skylot/jadx#1734]
*Describe your idea:*
 JADX ERROR: NullPointerException in pass: ClassModifier
    java.lang.NullPointerException
    	at jadx.core.utils.BlockUtils.collectAllInsns(BlockUtils.java:987)
    	at jadx.core.dex.visitors.ClassModifier.removeBridgeMethod(ClassModifier.java:230)
    	at jadx.core.dex.visitors.ClassModifier.removeSyntheticMethods(ClassModifier.java:152)
    	at java.util.ArrayList.forEach(ArrayList.java:1257)
    	at jadx.core.dex.visitors.ClassModifier.visit(ClassModifier.java:62)

**Comment by anii1827** [comment]
hi @yangguangftlp 
**with below code changes we can handle the null pointer exception.**

```diff
public static List<InsnNode> collectAllInsns(List<BlockNode> blocks) {
		List<InsnNode> insns = new ArrayList<>();
+		if(blocks!=null){
+			blocks.forEach(block -> insns.addAll(block.getInstructions()));			
+		}
		return insns;
	}


public static List<InsnNode> collectAllInsns(List<BlockNode> blocks) {
		List<InsnNode> insns = new ArrayList<>();
-			blocks.forEach(block -> insns.addAll(block.getInstructions()));			
		return insns;
	}
```

**Comment by skylot** [comment]
@anii1827 looks like this issue caused by another error, but without sample, I can't reproduce it.
