### ISSUE TITLE
[core]APP parsing error, and the overlay cannot parse

### ISSUE THREAD

**Issue by w279287350** [skylot/jadx#1748]
```
INFO  - loading ...
ERROR - Failed to parse '.arsc' file
jadx.core.utils.exceptions.JadxException: Error decode: resources.arsc
        at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:78)
        at jadx.core.dex.nodes.RootNode.loadResources(RootNode.java:173)
        at jadx.api.JadxDecompiler.load(JadxDecompiler.java:122)
        at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:48)
        at jadx.cli.JadxCLI.execute(JadxCLI.java:36)
        at jadx.cli.JadxCLI.main(JadxCLI.java:20)
Caused by: java.io.IOException: Encountered unsupported chunk type TYPE_OVERLAY
at offset 0x5e0260
        at jadx.core.xmlgen.ResTableParser.parsePackage(ResTableParser.java:172)
        at jadx.core.xmlgen.ResTableParser.decodeTableChunk(ResTableParser.java:110)
        at jadx.core.xmlgen.ResTableParser.decode(ResTableParser.java:86)
        at jadx.core.xmlgen.ResDecoder.decode(ResDecoder.java:28)
        at jadx.core.dex.nodes.RootNode.lambda$loadResources$7(RootNode.java:173)
        at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:73)
        ... 5 common frames omitted
        
        
        and  Overlayable cannot be parsed
```

**Comment by w279287350** [comment]
[Uploading GoogleCellBroadcastApp.zip…]()

**Comment by jpstotz** [comment]
@w279287350 It seems like the app upload was interrupted and therefore does not work.

**Comment by Ylarod** [comment]
Same issue here.

[com.google.android.apps.maps.apk.zip](https://github.com/skylot/jadx/files/11008166/com.google.android.apps.maps.apk.zip)

```
Error decode arsc
java.io.IOException: Encountered unsupported chunk type TYPE_OVERLAY at offset 0x280000 
	at jadx.core.xmlgen.ResTableParser.parsePackage(ResTableParser.java:172)
	at jadx.core.xmlgen.ResTableParser.decodeTableChunk(ResTableParser.java:110)
	at jadx.core.xmlgen.ResTableParser.decode(ResTableParser.java:86)
	at jadx.core.xmlgen.ResTableParser.decodeFiles(ResTableParser.java:91)
```

**Comment by jpstotz** [comment]
@Ylarod Thanks for providing a sample file. using that sample file I was able to update Jadx to parse/skip TYPE_OVERLAY chunks.
