### ISSUE TITLE
java.lang.IndexOutOfBoundsException: len=-4

### ISSUE THREAD

**Issue by thoinv** [skylot/jadx#1749]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.4.5
* Java version: 17.0.3.1
* Java VM: Oracle Corporation Java HotSpot(TM) 64-Bit Server VM
* Platform: Windows 10 (10.0 amd64)
* Max heap size: 11376 MB
* Program args: -Xms128M -XX:MaxRAMPercentage=70.0 -XX:+UseG1GC -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -Djava.util.Arrays.useLegacyMergeSort=true

```
java.lang.IndexOutOfBoundsException: len=-4
	at java.desktop/sun.font.FontDesignMetrics.charsWidth(FontDesignMetrics.java:505)
	at org.fife.ui.rsyntaxtextarea.TokenImpl.getWidthUpTo(TokenImpl.java:601)
	at org.fife.ui.rsyntaxtextarea.TokenImpl.getWidth(TokenImpl.java:570)
	at org.fife.ui.rsyntaxtextarea.TokenUtils.getSubTokenList(TokenUtils.java:122)
	at org.fife.ui.rsyntaxtextarea.WrappedSyntaxView$WrappedLine.calculateLineCount(WrappedSyntaxView.java:1188)
	at org.fife.ui.rsyntaxtextarea.WrappedSyntaxView$WrappedLine.getPreferredSpan(WrappedSyntaxView.java:1236)
	at java.desktop/javax.swing.text.View.getMinimumSpan(View.java:248)
	at java.desktop/javax.swing.text.BoxView.calculateMajorAxisRequirements(BoxView.java:872)
	at java.desktop/javax.swing.text.BoxView.checkRequests(BoxView.java:931)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:330)
	at java.desktop/javax.swing.text.BoxView.layout(BoxView.java:710)
	at java.desktop/javax.swing.text.BoxView.setSize(BoxView.java:398)
	at org.fife.ui.rsyntaxtextarea.WrappedSyntaxView.setSize(WrappedSyntaxView.java:1018)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1826)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.modelToView(BasicTextUI.java:1107)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.modelToView(BasicTextUI.java:1085)
	at java.desktop/javax.swing.text.DefaultCaret.repaintNewCaret(DefaultCaret.java:1348)
	at java.desktop/javax.swing.text.DefaultCaret$1.run(DefaultCaret.java:1326)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by jpstotz** [comment]
Duplicate of #1668 and #1712.

Please try the [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master). (at the moment the unstable download link doesn't work as the server `nightly.link` seems to be unavailable).

**Comment by MrIkso** [comment]
@skylot close it, same as #1658
