### ISSUE TITLE
[core] java.lang.IllegalStateException: Zip entries count limit exceeded: 100000

### ISSUE THREAD

**Issue by geofflangenderfer** [skylot/jadx#1751]
I'm trying to decompile a 528 megabyte jar, but it seems like it's too big:

```
$ du -sch build/*
528M    large.jar
528M    total

$ jadx -d decompiled large.jar
INFO  - loading ...
ERROR - Failed to process zip file: large.jar
java.lang.RuntimeException: Failed to process zip file: large.jar
        at jadx.api.plugins.utils.ZipSecurity.visitZipEntries(ZipSecurity.java:115)
        at jadx.api.plugins.utils.ZipSecurity.readZipEntries(ZipSecurity.java:121)
        at jadx.plugins.input.dex.DexFileLoader.collectDexFromZip(DexFileLoader.java:90)
        at jadx.plugins.input.dex.DexFileLoader.load(DexFileLoader.java:73)
        at jadx.plugins.input.dex.DexFileLoader.loadDexFromFile(DexFileLoader.java:50)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at jadx.plugins.input.dex.DexFileLoader.collectDexFiles(DexFileLoader.java:45)
        at jadx.plugins.input.dex.DexInputPlugin.loadFiles(DexInputPlugin.java:37)
        at jadx.plugins.input.dex.DexInputPlugin.loadFiles(DexInputPlugin.java:33)
        at jadx.api.JadxDecompiler.loadInputFiles(JadxDecompiler.java:133)
        at jadx.api.JadxDecompiler.load(JadxDecompiler.java:117)
        at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:48)
        at jadx.cli.JadxCLI.execute(JadxCLI.java:36)
        at jadx.cli.JadxCLI.main(JadxCLI.java:20)
Caused by: java.lang.IllegalStateException: Zip entries count limit exceeded: 100000, last entry: com/amazonaws/services/identitymanagement/model/UploadSigningCertificateResult.class
        at jadx.api.plugins.utils.ZipSecurity.visitZipEntries(ZipSecurity.java:110)
        ... 20 common frames omitted
ERROR - Failed to process zip file: large.jar
java.lang.RuntimeException: Failed to process zip file: large.jar
        at jadx.api.plugins.utils.ZipSecurity.visitZipEntries(ZipSecurity.java:115)
        at jadx.api.plugins.utils.ZipSecurity.readZipEntries(ZipSecurity.java:121)
        at jadx.plugins.input.java.JavaFileLoader.collectFromZip(JavaFileLoader.java:83)
        at jadx.plugins.input.java.JavaFileLoader.loadReader(JavaFileLoader.java:63)
        at jadx.plugins.input.java.JavaFileLoader.loadFromFile(JavaFileLoader.java:42)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at jadx.plugins.input.java.JavaFileLoader.collectFiles(JavaFileLoader.java:37)
        at jadx.plugins.input.java.JavaInputPlugin.loadClassFiles(JavaInputPlugin.java:32)
        at jadx.plugins.input.java.JavaInputPlugin.loadFiles(JavaInputPlugin.java:28)
        at jadx.api.JadxDecompiler.loadInputFiles(JadxDecompiler.java:133)
        at jadx.api.JadxDecompiler.load(JadxDecompiler.java:117)
        at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:48)
        at jadx.cli.JadxCLI.execute(JadxCLI.java:36)
        at jadx.cli.JadxCLI.main(JadxCLI.java:20)
Caused by: java.lang.IllegalStateException: Zip entries count limit exceeded: 100000, last entry: com/amazonaws/services/identitymanagement/model/UploadSigningCertificateResult.class
        at jadx.api.plugins.utils.ZipSecurity.visitZipEntries(ZipSecurity.java:110)
        ... 20 common frames omitted
ERROR - Failed to load class data for file: large.jar:META-INF/native/osx/libjansi.jnilib
jadx.plugins.input.java.utils.JavaClassParseException: Unknown constant pool tag: 0
        at jadx.plugins.input.java.data.ConstantType.getTypeByTag(ConstantType.java:45)
        at jadx.plugins.input.java.data.ClassOffsets.readConstPool(ClassOffsets.java:27)
        at jadx.plugins.input.java.data.ClassOffsets.<init>(ClassOffsets.java:11)
        at jadx.plugins.input.java.data.JavaClassData.<init>(JavaClassData.java:34)
        at jadx.plugins.input.java.JavaClassReader.loadClassData(JavaClassReader.java:18)
        at jadx.plugins.input.java.JavaLoadResult.visitClasses(JavaLoadResult.java:32)
        at jadx.core.dex.nodes.RootNode.loadClasses(RootNode.java:92)
        at jadx.api.JadxDecompiler.load(JadxDecompiler.java:120)
        at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:48)
        at jadx.cli.JadxCLI.execute(JadxCLI.java:36)
        at jadx.cli.JadxCLI.main(JadxCLI.java:20)
ERROR - Process error:
java.lang.RuntimeException: Failed to process zip file: large.jar
        at jadx.api.plugins.utils.ZipSecurity.visitZipEntries(ZipSecurity.java:115)
        at jadx.api.ResourcesLoader.loadFile(ResourcesLoader.java:144)
        at jadx.api.ResourcesLoader.load(ResourcesLoader.java:46)
        at jadx.api.JadxDecompiler.getResources(JadxDecompiler.java:399)
        at jadx.api.JadxDecompiler.load(JadxDecompiler.java:122)
        at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:48)
        at jadx.cli.JadxCLI.execute(JadxCLI.java:36)
        at jadx.cli.JadxCLI.main(JadxCLI.java:20)
Caused by: java.lang.IllegalStateException: Zip entries count limit exceeded: 100000, last entry: com/amazonaws/services/identitymanagement/model/UploadSigningCertificateResult.class
        at jadx.api.plugins.utils.ZipSecurity.visitZipEntries(ZipSecurity.java:110)
        ... 7 common frames omitted

$
```

I [created a stackoverflow](https://stackoverflow.com/questions/74925538/java-lang-illegalstateexception-zip-entries-count-limit-exceeded-100000)

**Comment by jpstotz** [comment]
Please do not cross-post issues on Stackoverflow. As the error text indicates this is clearly a function of Jadx that is designed that way. Stackoverflow is for programming questions only, not for discussing Jadx implementation details.

The error is caused by a static, non-configurable check implemented in Jadx that is aiming to identify zip bombs and other manipulated ZIP files. 

May be we can add a configuration option for future versions that disables the ZipSecurity checks to allow such "edge cases" like your large JAR file.

**Comment by sandyz987** [comment]
I encountered the same problem

**Comment by skylot** [comment]
@sandyz987 using latest [unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master) it is possible to change maximum zip entries count using environment variable: `JADX_ZIP_MAX_ENTRIES_COUNT`. Also, with `JADX_DISABLE_ZIP_SECURITY=true` all zip security checks can be disabled completely.

Related issues: #980, #982.
