### ISSUE TITLE
java.lang.IllegalArgumentException: pos 43569 is not in range 43612-43612

### ISSUE THREAD

**Issue by TMThong** [skylot/jadx#1754]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.4.3
* Java version: 18.0.2
* Java VM: Oracle Corporation OpenJDK 64-Bit Server VM
* Platform: Windows 11 (10.0 amd64)
* Max heap size: 4096 MB

```
java.lang.IllegalArgumentException: pos 43569 is not in range 43612-43612
	at org.fife.ui.rsyntaxtextarea.TokenImpl.makeStartAt(TokenImpl.java:805)
	at org.fife.ui.rsyntaxtextarea.TokenUtils.getSubTokenList(TokenUtils.java:134)
	at org.fife.ui.rsyntaxtextarea.WrappedSyntaxView$WrappedLine.calculateLineCount(WrappedSyntaxView.java:1193)
	at org.fife.ui.rsyntaxtextarea.WrappedSyntaxView$WrappedLine.getPreferredSpan(WrappedSyntaxView.java:1241)
	at java.desktop/javax.swing.text.View.getMinimumSpan(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.calculateMajorAxisRequirements(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.checkRequests(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.layout(Unknown Source)
	at java.desktop/javax.swing.text.BoxView.setSize(Unknown Source)
	at org.fife.ui.rsyntaxtextarea.WrappedSyntaxView.setSize(WrappedSyntaxView.java:1023)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.setSize(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTextAreaUI.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.JComponent.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.JTextArea.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.ScrollPaneLayout.layoutContainer(Unknown Source)
	at java.desktop/java.awt.Container.layout(Unknown Source)
	at java.desktop/java.awt.Container.doLayout(Unknown Source)
	at java.desktop/java.awt.Container.validateTree(Unknown Source)
	at java.desktop/java.awt.Container.validateTree(Unknown Source)
	at java.desktop/java.awt.Container.validateTree(Unknown Source)
	at java.desktop/java.awt.Container.validateTree(Unknown Source)
	at java.desktop/java.awt.Container.validateTree(Unknown Source)
	at java.desktop/java.awt.Container.validateTree(Unknown Source)
	at java.desktop/java.awt.Container.validate(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$3.run(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.validateInvalidComponents(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by jpstotz** [comment]
Duplicate of #1730

**Comment by TMThong** [comment]
> Duplicate of #1730
> 
> Please try [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master)

Thank you
