### ISSUE TITLE
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters

### ISSUE THREAD

**Issue by FabioNevesRezende** [skylot/jadx#1757]
when navigatin through the file picker, if a file contains characters like Ç the program breaks with this error:

```
ERROR - Exception was thrown
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/fabio/TCC/anota????es-eng-reversa-android
        at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:145)
        at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
        at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at java.desktop/sun.awt.shell.ShellFolder.getShellFolder(ShellFolder.java:247)
        at java.desktop/javax.swing.filechooser.FileSystemView.getFiles(FileSystemView.java:523)
        at java.desktop/javax.swing.plaf.basic.BasicDirectoryModel$FilesLoader.run0(BasicDirectoryModel.java:300)
        at java.desktop/javax.swing.plaf.basic.BasicDirectoryModel$FilesLoader.run(BasicDirectoryModel.java:289)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by jpstotz** [comment]
This is not a Jadx specific problem, but a general Java problem that may be caused by your system settings. To what LOCALE/LANG is your Linux system configured? See also: https://stackoverflow.com/q/39185613/150978

**Comment by FabioNevesRezende** [comment]
$ echo $LANG

`en_US.UTF-8`

it is already set to utf-8

**Comment by FabioNevesRezende** [comment]
the error no longer happens if I run with:

```
LC_ALL="en_US.UTF-8" ./jadx-gui
```
