### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by nuresrasoylu** [skylot/jadx#1758]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.4.5
* Java version: 18.0.2.1
* Java VM: Oracle Corporation OpenJDK 64-Bit Server VM
* Platform: Windows 10 (10.0 amd64)
* Max heap size: 512 MB

```
java.lang.OutOfMemoryError: Java heap space
	at java.desktop/java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.desktop/java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.desktop/java.awt.GraphicsConfiguration.createCompatibleImage(Unknown Source)
	at java.desktop/java.awt.GraphicsConfiguration.createCompatibleImage(Unknown Source)
	at java.desktop/sun.awt.image.SunVolatileImage.getBackupImage(Unknown Source)
	at java.desktop/sun.awt.image.VolatileSurfaceManager.getBackupSurface(Unknown Source)
	at java.desktop/sun.awt.image.VolatileSurfaceManager.initialize(Unknown Source)
	at java.desktop/sun.awt.image.SunVolatileImage.<init>(Unknown Source)
	at java.desktop/sun.awt.image.SunVolatileImage.<init>(Unknown Source)
	at java.desktop/java.awt.GraphicsConfiguration.createCompatibleVolatileImage(Unknown Source)
	at java.desktop/java.awt.GraphicsConfiguration.createCompatibleVolatileImage(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.getVolatileOffscreenBuffer(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(Unknown Source)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(Unknown Source)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(Unknown Source)
	at java.desktop/java.awt.Container.paint(Unknown Source)
	at java.desktop/java.awt.Window.paint(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$4.run(Unknown Source)
	at java.base/java.security.AccessController.executePrivileged(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)

```

**Comment by jpstotz** [comment]
You have configured maximum heap size to 512MB which is not enough for Jadx. Most likely this happens if you don't start Jadx using the provided Jad-gui.exe file or your system has only 4GR RAM which is not enough (you should have at least 8GB of RAM better 16).
