### ISSUE TITLE
JADX ERROR: Failed to decode insn: 0x0017: INVOKE_CUSTOM

### ISSUE THREAD

**Issue by billpeace** [skylot/jadx#1760]
```
jadx.core.utils.exceptions.JadxRuntimeException: 'invoke-custom' instruction processing error:
Failed to process invoke-custom instruction:
CallSite{[
 {ENCODED_METHOD_HANDLE: INVOKE_STATIC: Ljava/lang/invoke/LambdaMetafactory;->altMetafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite;},
 apply,
 {ENCODED_METHOD_TYPE: ()Lcom/baomidou/mybatisplus/core/toolkit/support/SFunction;},
 {ENCODED_METHOD_TYPE: (Ljava/lang/Object;)Ljava/lang/Object;},
 {ENCODED_METHOD_HANDLE: INVOKE_INSTANCE: Lcn/gwssi/extranet/app/khd/codeset/entity/PCTMkDmpzDmjxxT;->getDmjpzRid()Ljava/lang/Long;},
 {ENCODED_METHOD_TYPE: (Lcn/gwssi/extranet/app/khd/codeset/entity/PCTMkDmpzDmjxxT;)Ljava/lang/Object;},
 {ENCODED_INT: 5},
 {ENCODED_INT: 0}
]}
```

**Comment by skylot** [comment]
@billpeace please share sample apk, overwise I will be unable to reproduce and fix this issue.

**Comment by billpeace** [comment]
> @billpeace please share sample apk, overwise I will be unable to reproduce and fix this issue.
[Desktop.zip](https://github.com/skylot/jadx/files/10420501/Desktop.zip)

JADX ERROR: Failed to decode insn: 0x0016: INVOKE_CUSTOM , method: cn.gwssi.extranet.app.khd.codeset.service.Impl.PCTMkDmpzDmjxxTServiceImpl.update(cn.gwssi.extranet.app.khd.codeset.model.req.PCTMkDmpzDmjxxTReqDTO):void
        jadx.core.utils.exceptions.JadxRuntimeException: 'invoke-custom' instruction processing error: Failed to process invoke-custom instruction: CallSite{[{ENCODED_METHOD_HANDLE: INVOKE_STATIC: Ljava/lang/invoke/LambdaMetafactory;->altMetafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite;}, apply, {ENCODED_METHOD_TYPE: ()Lcom/baomidou/mybatisplus/core/toolkit/support/SFunction;}, {ENCODED_METHOD_TYPE: (Ljava/lang/Object;)Ljava/lang/Object;}, {ENCODED_METHOD_HANDLE: INVOKE_INSTANCE: Lcn/gwssi/extranet/app/khd/codeset/entity/PCTMkDmpzDmjxxT;->getDmjpzRid()Ljava/lang/Long;}, {ENCODED_METHOD_TYPE: (Lcn/gwssi/extranet/app/khd/codeset/entity/PCTMkDmpzDmjxxT;)Ljava/lang/Object;}, {ENCODED_INT: 5}, {ENCODED_INT: 0}]}
        	at jadx.core.dex.instructions.InvokeCustomBuilder.build(InvokeCustomBuilder.java:34)
        	at jadx.core.dex.instructions.InsnDecoder.invokeCustom(InsnDecoder.java:581)
        	at jadx.core.dex.instructions.InsnDecoder.decode(InsnDecoder.java:440)
        	at jadx.core.dex.instructions.InsnDecoder.lambda$process$0(InsnDecoder.java:50)
        	at jadx.plugins.input.java.data.code.JavaCodeReader.visitInstructions(JavaCodeReader.java:82)
        	at jadx.core.dex.instructions.InsnDecoder.process(InsnDecoder.java:45)
        	at jadx.core.dex.nodes.MethodNode.load(MethodNode.java:145)
        	at jadx.core.dex.nodes.ClassNode.load(ClassNode.java:410)
        	at jadx.core.ProcessClass.process(ProcessClass.java:67)
        	at jadx.core.ProcessClass.generateCode(ProcessClass.java:115)
        	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:384)
        	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:308)
        Caused by: jadx.core.utils.exceptions.JadxRuntimeException: Failed to process invoke-custom instruction: CallSite{[{ENCODED_METHOD_HANDLE: INVOKE_STATIC: Ljava/lang/invoke/LambdaMetafactory;->altMetafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite;}, apply, {ENCODED_METHOD_TYPE: ()Lcom/baomidou/mybatisplus/core/toolkit/support/SFunction;}, {ENCODED_METHOD_TYPE: (Ljava/lang/Object;)Ljava/lang/Object;}, {ENCODED_METHOD_HANDLE: INVOKE_INSTANCE: Lcn/gwssi/extranet/app/khd/codeset/entity/PCTMkDmpzDmjxxT;->getDmjpzRid()Ljava/lang/Long;}, {ENCODED_METHOD_TYPE: (Lcn/gwssi/extranet/app/khd/codeset/entity/PCTMkDmpzDmjxxT;)Ljava/lang/Object;}, {ENCODED_INT: 5}, {ENCODED_INT: 0}]}
        	at jadx.core.dex.instructions.InvokeCustomBuilder.build(InvokeCustomBuilder.java:32)

**Comment by skylot** [comment]
@billpeace thanks for sample!
I commit a quick fix for this issue, please check [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master).
I still not sure if additional args in [`altMetafactory` method](https://docs.oracle.com/en/java/javase/19/docs/api//java.base/java/lang/invoke/LambdaMetafactory.html#altMetafactory(java.lang.invoke.MethodHandles.Lookup,java.lang.String,java.lang.invoke.MethodType,java.lang.Object...)) can be used, I will check this later.
Also, there are some other issues in the sample, I will try to resolve them too, so I will keep this issue open.

**Comment by billpeace** [comment]
> @billpeace thanks for sample! I commit a quick fix for this issue, please check [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master). I still not sure if additional args in [`altMetafactory` method](https://docs.oracle.com/en/java/javase/19/docs/api//java.base/java/lang/invoke/LambdaMetafactory.html#altMetafactory(java.lang.invoke.MethodHandles.Lookup,java.lang.String,java.lang.invoke.MethodType,java.lang.Object...)) can be used, I will check this later. Also, there are some other issues in the sample, I will try to resolve them too, so I will keep this issue open.

thanks very much

**Comment by hide955** [comment]
@skylot  hi, last version JADX ERROR: Failed to decode insn: 0x0007: INVOKE_CUSTOM
[invoke-custom.zip](https://github.com/skylot/jadx/files/10643721/invoke-custom.zip)

**Comment by MrIkso** [comment]
@skylot i'm tested sample, issue not available on latest jax version.
