### ISSUE TITLE
Failed to read AndroidManifest.xml

### ISSUE THREAD

**Issue by hujiayucc** [skylot/jadx#1768]
```java
com.android.apksig.apk.ApkFormatException: Failed to read AndroidManifest.xml
	at com.android.apksig.ApkVerifier.getAndroidManifestFromApk(ApkVerifier.java:600)
	at com.android.apksig.ApkVerifier.verify(ApkVerifier.java:186)
	at com.android.apksig.ApkVerifier.verify(ApkVerifier.java:135)
	at jadx.gui.treemodel.ApkSignature.getCodeInfo(ApkSignature.java:92)
	at jadx.gui.ui.panel.HtmlPanel.<init>(HtmlPanel.java:26)
	at jadx.gui.treemodel.ApkSignature.getContentPanel(ApkSignature.java:82)
	at jadx.gui.ui.TabbedPane.getContentPanel(TabbedPane.java:319)
	at jadx.gui.ui.TabbedPane.showNode(TabbedPane.java:208)
	at jadx.gui.ui.MainWindow.nodeClickAction(MainWindow.java:773)
	at jadx.gui.ui.MainWindow.access$1200(MainWindow.java:150)
	at jadx.gui.ui.MainWindow$28.mousePressed(MainWindow.java:1259)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6623)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: com.android.apksig.zip.ZipFormatException: Data Descriptor presence mismatch between Local File Header and Central Directory for entry AndroidManifest.xml. LFH: true, CD: false
	at com.android.apksig.internal.zip.LocalFileRecord.getRecord(LocalFileRecord.java:180)
	at com.android.apksig.internal.zip.LocalFileRecord.outputUncompressedData(LocalFileRecord.java:427)
	at com.android.apksig.internal.zip.LocalFileRecord.getUncompressedData(LocalFileRecord.java:451)
	at com.android.apksig.ApkSigner.getAndroidManifestFromApk(ApkSigner.java:865)
	at com.android.apksig.ApkVerifier.getAndroidManifestFromApk(ApkVerifier.java:596)
	... 42 more
```

**Comment by jpstotz** [comment]
Looking at the error message `ZipFormatException: Data Descriptor presence mismatch between Local File Header and Central Directory for entry AndroidManifest.xml. LFH: true, CD: false` I would assume that the APK file you have loaded into Jadx-gui is manipulated on ZIP level.

I seems like the error occurs when checking the APK signature (and should not affect general loading of APk in Jadx-gui or code decompilation - is this true?). The signature verification code Jadx-gui uses is from apksig library provided by Google, so we can not change it. 

Have you tried o install the APK on a real device? I would expect that the signature check also fails and thus the APK can not be installed.

**Comment by hujiayucc** [comment]
Maybe the apk file size is too large
