### ISSUE TITLE
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;

### ISSUE THREAD

**Issue by seanLimWeiRen** [skylot/jadx#1774]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
i tried to use this apk but it did not work
[aaf35b.zip](https://github.com/skylot/jadx/files/10555971/aaf35b.zip)

 * Jadx version: dev
* Java version: 1.8.0_362
* Java VM: Oracle Corporation OpenJDK 64-Bit Server VM
* Platform: Linux (6.1.7-arch1-1 amd64)
* Max heap size: 11046 MB
* Program args: -Xms128M -XX:MaxRAMPercentage=70.0 -XX:+UseG1GC -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -Djava.util.Arrays.useLegacyMergeSort=true

```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at jadx.plugins.input.dex.sections.SectionReader.duplicate(SectionReader.java:60)
	at jadx.plugins.input.dex.sections.SectionReader.<init>(SectionReader.java:34)
	at jadx.plugins.input.dex.DexReader.<init>(DexReader.java:22)
	at jadx.plugins.input.dex.DexFileLoader.loadDexReader(DexFileLoader.java:84)
	at jadx.plugins.input.dex.DexFileLoader.load(DexFileLoader.java:67)
	at jadx.plugins.input.dex.DexFileLoader.lambda$collectDexFromZip$2(DexFileLoader.java:92)
	at jadx.api.plugins.utils.ZipSecurity.lambda$readZipEntries$0(ZipSecurity.java:124)
	at jadx.api.plugins.utils.ZipSecurity.visitZipEntries(ZipSecurity.java:103)
	at jadx.api.plugins.utils.ZipSecurity.readZipEntries(ZipSecurity.java:121)
	at jadx.plugins.input.dex.DexFileLoader.collectDexFromZip(DexFileLoader.java:90)
	at jadx.plugins.input.dex.DexFileLoader.load(DexFileLoader.java:73)
	at jadx.plugins.input.dex.DexFileLoader.loadDexFromFile(DexFileLoader.java:50)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at jadx.plugins.input.dex.DexFileLoader.collectDexFiles(DexFileLoader.java:45)
	at jadx.plugins.input.dex.DexInputPlugin.loadFiles(DexInputPlugin.java:37)
	at jadx.plugins.input.dex.DexInputPlugin.loadFiles(DexInputPlugin.java:33)
	at jadx.api.JadxDecompiler.loadInputFiles(JadxDecompiler.java:133)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:117)
	at jadx.gui.JadxWrapper.open(JadxWrapper.java:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

```

**Comment by seanLimWeiRen** [comment]
I'm using jadx-gui-desktop from the AUR

**Comment by seanLimWeiRen** [comment]
i uninstalled and installed jadx-bin instead
