### ISSUE TITLE
Failed to parse '.arsc.' file

### ISSUE THREAD

**Issue by sethjones** [skylot/jadx#178]
INFO  - loading ...
ERROR - Failed to parse '.arsc' file
jadx.core.utils.exceptions.JadxException: Error decode: resources.arsc
        at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:65) ~[jadx-core-0.6.0.jar:na]
        at jadx.core.dex.nodes.RootNode.loadResources(RootNode.java:75) ~[jadx-core-0.6.0.jar:na]
        at jadx.api.JadxDecompiler.parse(JadxDecompiler.java:264) [jadx-core-0.6.0.jar:na]
        at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:118) [jadx-core-0.6.0.jar:na]
        at jadx.api.JadxDecompiler.loadFile(JadxDecompiler.java:103) [jadx-core-0.6.0.jar:na]
        at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:32) [jadx-gui-0.6.0.jar:na]
        at jadx.gui.ui.MainWindow.openFile(MainWindow.java:164) [jadx-gui-0.6.0.jar:na]
        at jadx.gui.ui.MainWindow.openFile(MainWindow.java:159) [jadx-gui-0.6.0.jar:na]
        at jadx.gui.ui.MainWindow.open(MainWindow.java:121) [jadx-gui-0.6.0.jar:na]
        at jadx.gui.JadxGUI$1.run(JadxGUI.java:27) [jadx-gui-0.6.0.jar:na]
        at java.awt.event.InvocationEvent.dispatch(Unknown Source) [na:1.8.0_131]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [na:1.8.0_131]
        at java.awt.EventQueue.access$500(Unknown Source) [na:1.8.0_131]
        at java.awt.EventQueue$3.run(Unknown Source) [na:1.8.0_131]
        at java.awt.EventQueue$3.run(Unknown Source) [na:1.8.0_131]
        at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_131]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [na:1.8.0_131]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) [na:1.8.0_131]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [na:1.8.0_131]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:1.8.0_131]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [na:1.8.0_131]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_131]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_131]
        at java.awt.EventDispatchThread.run(Unknown Source) [na:1.8.0_131]
Caused by: java.io.IOException: Decode error: Unexpected type header size: 0x4c, position: 0x1b1f44
        at jadx.core.xmlgen.CommonBinaryParser.die(CommonBinaryParser.java:96) ~[jadx-core-0.6.0.jar:na]
        at jadx.core.xmlgen.ResTableParser.parseTypeChunk(ResTableParser.java:164) ~[jadx-core-0.6.0.jar:na]
        at jadx.core.xmlgen.ResTableParser.parsePackage(ResTableParser.java:142) ~[jadx-core-0.6.0.jar:na]
        at jadx.core.xmlgen.ResTableParser.decodeTableChunk(ResTableParser.java:89) ~[jadx-core-0.6.0.jar:na]
        at jadx.core.xmlgen.ResTableParser.decode(ResTableParser.java:57) ~[jadx-core-0.6.0.jar:na]
        at jadx.core.dex.nodes.RootNode$1.decode(RootNode.java:78) ~[jadx-core-0.6.0.jar:na]
        at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:63) ~[jadx-core-0.6.0.jar:na]
        ... 23 common frames omitted

**Comment by sergey-wowwow** [comment]
@sethjones 
The parser was changed multiple times after your report. More over I tested numbers of ``` resources.arsc ``` files, and didn't have any processing issues. If you can reproduce the bug, reopen the issue with your ``` resources.arsc ``` file attached. Thanks!

**Comment by nx4dm1n** [comment]
I also got this error

**Comment by jpstotz** [comment]
> I also got this error

Please check if you are using the latest version of Jadx. If you are using the latest version it would be good if you could provide us the APK file that triggers this error.

**Comment by oxou** [comment]
Log level: Error
Version: 1.4.4
Binary: [jadx-gui-1.4.4-no-jre-win.exe](https://github.com/skylot/jadx/releases/download/v1.4.4/jadx-gui-1.4.4-no-jre-win.exe)
File causing the error: [resources.arsc.zip](https://github.com/skylot/jadx/files/9479118/resources.arsc.zip)
Java VM:
```
openjdk version "18.0.1.1" 2022-04-22
OpenJDK Runtime Environment (build 18.0.1.1+2-6)
OpenJDK 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)
```


jadx Error:

```
ERROR: Failed to parse '.arsc' file
jadx.core.utils.exceptions.JadxException: Error decode: D:\download\browser\resources.arsc
	at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:78)
	at jadx.core.dex.nodes.RootNode.loadResources(RootNode.java:173)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:122)
	at jadx.gui.JadxWrapper.open(JadxWrapper.java:65)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: Config size < 28
	at jadx.core.xmlgen.ResTableParser.parseConfig(ResTableParser.java:373)
	at jadx.core.xmlgen.ResTableParser.parseTypeChunk(ResTableParser.java:221)
	at jadx.core.xmlgen.ResTableParser.parsePackage(ResTableParser.java:162)
	at jadx.core.xmlgen.ResTableParser.decodeTableChunk(ResTableParser.java:110)
	at jadx.core.xmlgen.ResTableParser.decode(ResTableParser.java:86)
	at jadx.core.xmlgen.ResDecoder.decode(ResDecoder.java:28)
	at jadx.core.dex.nodes.RootNode.lambda$loadResources$7(RootNode.java:173)
	at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:61)
	... 6 common frames omitted
```

**Comment by jpstotz** [comment]
@oxou Thanks for the sample. 

Jadx currently has two problems with this sample: 

1. Our ResTableParser.parsePackage reads a very large size that can not be correct for the package chunk. Apktool seems to ignore the size and simple reads until it encounters a chunk of an unknown type.

2. Modifying Jadx to read the chunks the same way as apktool does we run into a chunk of type `0x0203` = TYPE_LIBRARY (called `Header.XML_TYPE_LIBRARY`in apktool). We don't have any code yet for loading such a chunk.

**Comment by jpstotz** [comment]
@oxou I have moved your bug report to a new issue.
