### ISSUE TITLE
[core]jadx.core.utils.exceptions.JadxRuntimeException: Method arg registers not loaded

### ISSUE THREAD

**Issue by choday** [skylot/jadx#1783]
/*  JADX ERROR: Method generation error
        jadx.core.utils.exceptions.JadxRuntimeException: Method arg registers not loaded: X.YcE.LIZ(java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object):void, class status: PROCESS_COMPLETE
        	at jadx.core.dex.nodes.MethodNode.getArgRegs(MethodNode.java:248)
        	at jadx.core.codegen.MethodGen.addDefinition(MethodGen.java:154)
        	at jadx.core.codegen.ClassGen.addMethodCode(ClassGen.java:372)
        	at jadx.core.codegen.ClassGen.addMethod(ClassGen.java:306)
        	at jadx.core.codegen.ClassGen.lambda$addInnerClsAndMethods$2(ClassGen.java:272)
        	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        	at java.util.ArrayList.forEach(ArrayList.java:1257)
        	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:390)
        	at java.util.stream.Sink$ChainedReference.end(Sink.java:258)
        */
    /*  JADX ERROR: NullPointerException in pass: SSATransform
        java.lang.NullPointerException
        	at jadx.core.dex.visitors.ssa.LiveVarAnalysis.runAnalysis(LiveVarAnalysis.java:31)
        	at jadx.core.dex.visitors.ssa.SSATransform.process(SSATransform.java:55)
        */

    /*  JADX ERROR: NullPointerException in pass: SSATransform
        java.lang.NullPointerException
        	at jadx.core.dex.visitors.ssa.LiveVarAnalysis.runAnalysis(LiveVarAnalysis.java:31)
        	at jadx.core.dex.visitors.ssa.SSATransform.process(SSATransform.java:55)
        	at jadx.core.dex.visitors.ssa.SSATransform.visit(SSATransform.java:41)
        */

**Comment by choday** [comment]
.method public static LIZ(Ljava/lang/Object;)V
    .registers 6

    .prologue

    sget-object v4, LX/YcE;->LIZ:Lcom/xx/hotfix/base/ChangeQuickRedirect;
    invoke-static {v4}, Lcom/xx/hotfix/PatchProxy;->isEnable(Lcom/xx/hotfix/base/ChangeQuickRedirect;)Z

    move-result v0

    if-eqz v0, :cond_19

    const/4 v3, 0x1

    new-array v2, v3, [Ljava/lang/Object;

    const/4 v0, 0x0

    aput-object p0, v2, v0

    const/4 v1, 0x0

    const/4 v0, 0x4

    invoke-static {v2, v1, v4, v3, v0}, Lcom/xx/hotfix/PatchProxy;->proxy([Ljava/lang/Object;Ljava/lang/Object;Lcom/xx/hotfix/base/ChangeQuickRedirect;ZI)Lcom/xx/hotfix/PatchProxyResult;

    move-result-object v0

    iget-boolean v0, v0, Lcom/xx/hotfix/PatchProxyResult;->isSupported:Z

    if-eqz v0, :cond_19

    return-void

    :cond_19
    if-eqz p0, :cond_1c

    return-void

    :cond_1c
    new-instance v0, Ljava/lang/NullPointerException;

    invoke-direct {v0}, Ljava/lang/NullPointerException;-><init>()V

    throw v0
.end method
