### ISSUE TITLE
[core] jcommander version constraint crashed baksmali

### ISSUE THREAD

**Issue by DKingAlpha** [skylot/jadx#1794]
### Steps to Reproduce

1. Copy and rename  `jadx` wrapper script to `jadx-toolchain`
2. Search and delete `jadx.cli.JadxCLI`  in `jadx-toolchain`
3. run `jadx-toolchain org.jf.baksmali.Main -h`. Java Stack backtrace will prints.

### Backtrace

```py
Exception in thread "main" java.lang.NoSuchMethodError: com.beust.jcommander.JCommander.getMainParameter()Lcom/beust/jcommander/ParameterDescription;
        at org.jf.util.jcommander.HelpFormatter.format(HelpFormatter.java:165)
        at org.jf.util.jcommander.Command.usage(Command.java:54)
        at org.jf.baksmali.Main.main(Main.java:97)
```

### Description

[JCommander version constraint](https://github.com/skylot/jadx/blob/master/jadx-plugins/jadx-dex-input/build.gradle#L13) `implementation 'com.beust:jcommander:1.81'` introducted an API change in JCommander, lead to a possible `NoSuchMethodError` crash in baksmali.

The "official" version is [com.beust:jcommander:1.64](https://github.com/JesusFreke/smali/blob/master/build.gradle#L59).

### Related code

baksmali:  [parameterArgumentNames(leafJc.getMainParameter())](https://github.com/JesusFreke/smali/blob/master/util/src/main/java/org/jf/util/jcommander/HelpFormatter.java#L166) 

```java
String[] argumentNames = ExtendedCommands.parameterArgumentNames(leafJc.getMainParameter());
```

[public static String[] parameterArgumentNames(ParameterDescription parameterDescription)](https://github.com/JesusFreke/smali/blob/master/util/src/main/java/org/jf/util/jcommander/ExtendedCommands.java) is expecting a ParameterDescription param,

while [in JCommander 1.64]:(https://github.com/cbeust/jcommander/blob/1.64/src/main/java/com/beust/jcommander/JCommander.java#L1279)
```java
    public ParameterDescription getMainParameter() {
        return mainParameterDescription;
    }
```

[in JCommander 1.81]:(https://github.com/cbeust/jcommander/blob/1.81/src/main/java/com/beust/jcommander/JCommander.java#L1056)

```java
    public MainParameter getMainParameter() {
        return mainParameter;
    }

    public ParameterDescription getMainParameterValue() {
        return mainParameter.description;
    }
```

### Possible fix

JCommander<=1.71 maybe.

**Comment by DKingAlpha** [comment]
btw once @skylot determined the fix method, I am happy to help with further fixes.

**Comment by DKingAlpha** [comment]
I need to export smali along with Java source code, jadx does not have the option. So I attempted to utilize the built-in library.

I am assuming that jadx maintains all latest tools as dependency libraries.
In that case I would only need to guarantee the latest jadx version for least effort and best performance.
