### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 9

### ISSUE THREAD

**Issue by FabioNevesRezende** [skylot/jadx#1796]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
The error occurred with the apk https://mas.owasp.org/crackmes/Android/#android-uncrackable-l1
When it hit a breakpoint set on the first instruction of the MainAcitivy.verify method

 * Jadx version: 1.4.6
* Java version: 11.0.18
* Java VM: Debian OpenJDK 64-Bit Server VM
* Platform: Linux (5.10.0-21-amd64 amd64)
* Max heap size: 5508 MB
* Program args: -Xms128M -XX:MaxRAMPercentage=70.0 -XX:+UseG1GC -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -Djava.util.Arrays.useLegacyMergeSort=true

```
java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 9
	at java.desktop/javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1446)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1389)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:648)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1680)
	at java.desktop/javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:795)
	at java.desktop/java.awt.Container.layout(Container.java:1537)
	at java.desktop/java.awt.Container.doLayout(Container.java:1526)
	at java.desktop/java.awt.Container.validateTree(Container.java:1722)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:745)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:742)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1889)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by jpstotz** [comment]
At a first glance this looks like a bug in Java, not in Jadx. However the exception is very close to this bug report here: https://bugs.openjdk.org/browse/JDK-6253801 And the outcome of this bug report is it was not a Java bug, but a developer problem: UI component were added outside of the main thread. 

So may be the the debugger window performs some UI changes on a non-main thread?

**Comment by jpstotz** [comment]
The PR reference is wrong, I accidentally used the wrong issue number.

**Comment by FabioNevesRezende** [comment]
Do you guys have any idea of when a version with this bug fix will be released? not to be annoying, the other option for debuggin smali is "smalidea" for Android Studio which is very worse and doesn't work well, this one seems to be the best solution out there and I'm also using jadx-gui for works. Thanks in advance

**Comment by jpstotz** [comment]
Unfortunately based on the error stack trace it is pretty complicated to identify the code section that is causing this error. Additionally such errors are very hard to reproduce as the execution timing and thus the OS, the used CPU, Java version and whatever have an impact if this error occurs or not. For example I have never seen this error and I can not reproduce it in my set-up.

If you often get this error and you are familiar with IntelliJ you could help us checking out Jadx GIT, open it in IntelliJ and then add an exception break point of `ArrayIndexOutOfBoundsException` https://www.jetbrains.com/help/idea/using-breakpoints.html#set-breakpoints. 

Then Start Jadx-GUI `jadx-gui/src/main/java/jadx/gui/JadxGUI.java` in debug mode.

If the break-point hits please check the IntelliJ debugger view what list is causing the error (e.g. what are the existing 8 elements and what is `this` or what UI component does not belong to).

**Comment by FabioNevesRezende** [comment]
Well, after changing to Java 17 this error is not happening anymore. However there are some things on the UI that are not very well, for example, the locals values that stands between the callstack and debugger log is not resizable. Also it always show "undefined" for every value of the registers, the main point for me to debug is to check how the variables are changing its values along the execution...

![Screenshot_20230401_084258](https://user-images.githubusercontent.com/42902918/229287082-c28f6dc5-012f-4677-93b5-9519defd5294.png)

It always show (JDWP Error Code:35) Invalid slot. for v1...

**Comment by FabioNevesRezende** [comment]
I'm using a qemu image of android-x86 running on virt-manager

https://www.android-x86.org/download.html
