### ISSUE TITLE
Encountered unsupported chunk type TYPE_STAGED_ALIAS at offset 0x4ce8c8

### ISSUE THREAD

**Issue by songtao542** [skylot/jadx#1803]
ERROR: Failed to parse '.arsc' file
jadx.core.utils.exceptions.JadxException: Error decode: resources.arsc
	at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:78)
	at jadx.core.dex.nodes.RootNode.loadResources(RootNode.java:173)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:117)
	at jadx.gui.JadxWrapper.open(JadxWrapper.java:65)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Encountered unsupported chunk type TYPE_STAGED_ALIAS at offset 0x4ce8c8 
	at jadx.core.xmlgen.ResTableParser.parsePackage(ResTableParser.java:175)
	at jadx.core.xmlgen.ResTableParser.decodeTableChunk(ResTableParser.java:110)
	at jadx.core.xmlgen.ResTableParser.decode(ResTableParser.java:86)
	at jadx.core.xmlgen.ResDecoder.decode(ResDecoder.java:28)
	at jadx.core.dex.nodes.RootNode.lambda$loadResources$7(RootNode.java:173)
	at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:73)
	... 6 common frames omitted

**Comment by jpstotz** [comment]
Can you provide the APK file that causes this error?

**Comment by jpstotz** [comment]
@MrIkso I dislike implement something just using apktool source as base. I had several cases where the code in apktool for parsing was wrong.

I just had a discussion with Connor the author of apktool on the correct way to parse the overlay chunk, therefore I prefer having a real example to make sure the code really works on real-world examples.

But now as I have found an example the fix is just a PR away...

**Comment by skylot** [comment]
Fixed in PR #1807 by @jpstotz
