### ISSUE TITLE
[core] arsc decode error

### ISSUE THREAD

**Issue by Ylarod** [skylot/jadx#1806]
```
INFO  - output directory: framework-res-14
INFO  - loading ...
INFO  - Loaded classes: 0, methods: 0, instructions: 0
ERROR - Failed to parse '.arsc' file
jadx.core.utils.exceptions.JadxException: Error decode: resources.arsc
	at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:78)
	at jadx.core.dex.nodes.RootNode.loadResources(RootNode.java:173)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:117)
	at jadx.gui.JadxWrapper.open(JadxWrapper.java:65)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: type chunk, res0, expected: 0x0, actual: 0x1, offset: 0xb0b196
	at jadx.core.xmlgen.ParserStream.throwException(ParserStream.java:118)
	at jadx.core.xmlgen.ParserStream.checkInt8(ParserStream.java:103)
	at jadx.core.xmlgen.ResTableParser.parseTypeChunk(ResTableParser.java:253)
	at jadx.core.xmlgen.ResTableParser.parsePackage(ResTableParser.java:162)
	at jadx.core.xmlgen.ResTableParser.decodeTableChunk(ResTableParser.java:110)
	at jadx.core.xmlgen.ResTableParser.decode(ResTableParser.java:86)
	at jadx.core.xmlgen.ResDecoder.decode(ResDecoder.java:28)
	at jadx.core.dex.nodes.RootNode.lambda$loadResources$7(RootNode.java:173)
	at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:73)
	... 6 common frames omitted
```

According to [aosp13 ResourceTypes.h](http://aospxref.com/android-13.0.0_r3/xref/frameworks/base/libs/androidfw/include/androidfw/ResourceTypes.h#1421), these two fields should be `flags` and `reserved` instead of `res0` and `res1`

Apk can be found -> [framework-res-14.apk](https://mega.nz/file/8DID3RpA#8DtUPb320sP_5plvju9G8HqxVasayH6PWd5afJVV96c)

**Comment by jpstotz** [comment]
@Ylarod Thank you very much for this sample. It contains multiple structures we not yet support in Jadx. I will update our resource parsing code to support it.

**Comment by jpstotz** [comment]
That sample is indeed interesting. It has the `flag` set to 1 which means it uses sparse entries which need a little bit different way of reading. 

And afterwards I discovered that it contains a `TYPE_STAGED_ALIAS` chunk, so the search for a sample file of #1803 is finally over.
