### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index 6 out of bounds for length 2

### ISSUE THREAD

**Issue by bluegatar** [skylot/jadx#1841]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.4.6
* Java version: 17.0.6
* Java VM: Oracle Corporation Java HotSpot(TM) 64-Bit Server VM
* Platform: Mac OS X (13.3.1 x86_64)
* Max heap size: 45888 MB
* Program args: -Xms128M -XX:MaxRAMPercentage=70.0 -XX:+UseG1GC -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -Djava.util.Arrays.useLegacyMergeSort=true

```
java.lang.IndexOutOfBoundsException: Index 6 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at jadx.gui.device.debugger.RegisterObserver.getInfo(RegisterObserver.java:81)
	at jadx.gui.device.debugger.DebugController.lambda$fetchAllRegisters$12(DebugController.java:675)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by jpstotz** [comment]
Please update to Jadx 1.4.7. This new version contains several improvements on the debugger view which might solve this problem. (see #1796).
