### ISSUE TITLE
[core] Jadx freezes when decompiling the app

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#1853]
Hey!

Jadx freezes when I try to decompile this app: https://apkcombo.com/quip-docs-chat-spreadsheets/com.quip.quip/

jstack outputs the following freezed trace:
```
"pool-9-thread-8" #74 prio=5 os_prio=31 cpu=94736.13ms elapsed=96.23s tid=0x00007f9bde00fc00 nid=0x6037 runnable  [0x0000700012a02000]
   java.lang.Thread.State: RUNNABLE
	at jadx.core.dex.visitors.finaly.InsnsSlice.addBlock(InsnsSlice.java:29)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:489)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:486)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.searchFromFirstBlock(MarkFinallyVisitor.java:355)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.searchDuplicateInsns(MarkFinallyVisitor.java:341)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.extractFinally(MarkFinallyVisitor.java:186)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.processTryBlock(MarkFinallyVisitor.java:91)
	at jadx.core.dex.visitors.finaly.MarkFinallyVisitor.visit(MarkFinallyVisitor.java:55)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:26)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
	at jadx.core.dex.visitors.DepthTraversal$$Lambda$505/0x0000000cc77b7308.accept(Unknown Source)
	at java.util.ArrayList.forEach(java.base@17.0.2/ArrayList.java:1511)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$0(DepthTraversal.java:13)
	at jadx.core.dex.visitors.DepthTraversal$$Lambda$504/0x0000000cc77b70d0.accept(Unknown Source)
	at java.util.ArrayList.forEach(java.base@17.0.2/ArrayList.java:1511)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:13)
	at jadx.core.ProcessClass.process(ProcessClass.java:72)
	- locked <0x000000012a6ea390> (a jadx.core.dex.info.ClassInfo)
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:107)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:375)
	- locked <0x000000012a62e2d0> (a jadx.core.dex.nodes.ClassNode)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:299)
	at jadx.api.JavaClass.getCodeInfo(JavaClass.java:65)
	at jadx.api.JavaClass.getCode(JavaClass.java:57)
	at jadx.gui.search.providers.CodeSearchProvider.getClassCode(CodeSearchProvider.java:100)
	at jadx.gui.search.providers.CodeSearchProvider.next(CodeSearchProvider.java:50)
	at jadx.gui.search.SearchJob.run(SearchJob.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.2/ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.2/ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(java.base@17.0.2/Thread.java:833)
```

**Comment by skylot** [comment]
@bagipro I commit a fix. It will prevent from revisiting already checked paths during finally extraction and should resolve the endless loop.
