### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by clm210** [skylot/jadx#1888]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.4.6
* Java version: 19.0.2
* Java VM: Oracle Corporation OpenJDK 64-Bit Server VM
* Platform: Windows 10 (10.0 amd64)
* Max heap size: 4096 MB

```
java.lang.ExceptionInInitializerError
	at java.base/javax.crypto.Cipher.getInstance(Unknown Source)
	at java.base/sun.security.ssl.SSLCipher.isTransformationAvailable(Unknown Source)
	at java.base/sun.security.ssl.SSLCipher.<init>(Unknown Source)
	at java.base/sun.security.ssl.SSLCipher.<clinit>(Unknown Source)
	at java.base/sun.security.ssl.CipherSuite.<clinit>(Unknown Source)
	at java.base/sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuites(Unknown Source)
	at java.base/sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at java.base/java.lang.Class.forName(Unknown Source)
	at java.base/java.security.Provider$Service.getImplClass(Unknown Source)
	at java.base/java.security.Provider$Service.getDefaultConstructor(Unknown Source)
	at java.base/java.security.Provider$Service.newInstanceOf(Unknown Source)
	at java.base/java.security.Provider$Service.newInstanceUtil(Unknown Source)
	at java.base/java.security.Provider$Service.newInstance(Unknown Source)
	at java.base/sun.security.jca.GetInstance.getInstance(Unknown Source)
	at java.base/sun.security.jca.GetInstance.getInstance(Unknown Source)
	at java.base/javax.net.ssl.SSLContext.getInstance(Unknown Source)
	at java.base/javax.net.ssl.SSLContext.getDefault(Unknown Source)
	at java.base/javax.net.ssl.SSLSocketFactory.getDefault(Unknown Source)
	at java.base/javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(Unknown Source)
	at java.base/javax.net.ssl.HttpsURLConnection.<init>(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(Unknown Source)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Unknown Source)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Unknown Source)
	at java.base/java.net.URL.openConnection(Unknown Source)
	at jadx.gui.update.JadxUpdate.get(JadxUpdate.java:82)
	at jadx.gui.update.JadxUpdate.checkForNewRelease(JadxUpdate.java:64)
	at jadx.gui.update.JadxUpdate.lambda$check$0(JadxUpdate.java:45)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
	at java.base/javax.crypto.JceSecurity.<clinit>(Unknown Source)
	... 30 more
Caused by: java.lang.SecurityException: Missing mandatory jurisdiction policy files: unlimited
	at java.base/javax.crypto.JceSecurity.setupJurisdictionPolicies(Unknown Source)
	at java.base/javax.crypto.JceSecurity$1.run(Unknown Source)
	at java.base/javax.crypto.JceSecurity$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	... 31 more

```

**Comment by jpstotz** [comment]
This looks more like a problem with the used Java Runtime. Please upgrade to latest version of Jadx and I strongly recommend to use the version with included JRE:
[jadx-gui-1.4.7-with-jre-win.zip](https://github.com/skylot/jadx/releases/download/v1.4.7/jadx-gui-1.4.7-with-jre-win.zip)

**Comment by jpstotz** [comment]
@clm210 Have you tested the version I have linked?

**Comment by skylot** [comment]
No reply
