### ISSUE TITLE
[gui] inlineAnonymousClasses lead to empty annoymous classes

### ISSUE THREAD

**Issue by yoavst** [skylot/jadx#1905]
**Describe error**
When `inlineAnonymousClasses` is enabled, If you enter an inlined class from the menu (probably from other places too, for example, when trying to use the bookmark script), it shows an empty screen, and throwing an error.

![image](https://github.com/skylot/jadx/assets/3912269/fd1713a0-8fee-463d-a72b-2bf745ee72e0)

```
java.lang.IllegalArgumentException: bad position: 65146
	at java.desktop/javax.swing.text.JTextComponent.setCaretPosition(JTextComponent.java:1685)
	at jadx.gui.ui.codearea.AbstractCodeArea.scrollToPos(AbstractCodeArea.java:313)
	at jadx.gui.ui.TabbedPane.scrollToPos(TabbedPane.java:253)
	at jadx.gui.ui.TabbedPane.showCode(TabbedPane.java:232)
	at jadx.gui.ui.TabbedPane.codeJump(TabbedPane.java:218)
	at jadx.gui.ui.TabbedPane.codeJump(TabbedPane.java:203)
	at jadx.gui.ui.MainWindow.nodeClickAction(MainWindow.java:777)
	at jadx.gui.ui.MainWindow$24.mousePressed(MainWindow.java:1243)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6385)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4995)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

[Ohel-Shem_7.6_Apkpure.zip](https://github.com/skylot/jadx/files/11712454/Ohel-Shem_7.6_Apkpure.zip)

**Comment by skylot** [comment]
As you mentioned in #1832 we need to move logic from 
https://github.com/skylot/jadx/blob/f558203a9d99ef0cac46b4732fce5f3dfe68fe2d/jadx-gui/src/main/java/jadx/gui/ui/dialog/CommonSearchDialog.java#L163-L164
into
https://github.com/skylot/jadx/blob/f558203a9d99ef0cac46b4732fce5f3dfe68fe2d/jadx-gui/src/main/java/jadx/gui/ui/TabbedPane.java#L201

But also add support for methods and fields from anonymous/moved classes.
