### ISSUE TITLE
[core] Code restructure failed: missing block

### ISSUE THREAD

**Issue by rndtrash** [skylot/jadx#1910]
It happens in class `i`, method `public void run()` on JADX v1.4.7 from FlatHub and on latest commit [b578479](https://github.com/skylot/jadx/commit/b578479270120aede90aabfe548dfdfea6a49aa7)

Stacktrace:
```
WARN : Removed duplicated region for block: B:22:0x018b A[LOOP:2: B:22:0x018b->B:24:0x0190, LOOP_START, PHI: r11 
  PHI: (r11v3 int) = (r11v2 int), (r11v4 int) binds: [B:21:0x0188, B:24:0x0190] A[DONT_GENERATE, DONT_INLINE]] in method: i.h():void, file: RidgeRacer_K800.jar:i.class
WARN : Removed duplicated region for block: B:34:0x01a6 A[SYNTHETIC] in method: i.h():void, file: RidgeRacer_K800.jar:i.class
WARN : Code restructure failed: missing block: B:138:0x0628, code lost:
    if (defpackage.i.F.b() == 0) goto L141;
 in method: i.run():void, file: RidgeRacer_K800.jar:i.class

ERROR: Exception was thrown
io.github.skylot.raung.disasm.impl.utils.RaungDisasmException: Failed to process input stream
	at io.github.skylot.raung.disasm.impl.RaungDisasmBuilder.executeForInputStream(RaungDisasmBuilder.java:124)
	at jadx.plugins.input.java.utils.DisasmUtils.useRaung(DisasmUtils.java:26)
	at jadx.plugins.input.java.utils.DisasmUtils.get(DisasmUtils.java:21)
	at jadx.plugins.input.java.data.JavaClassData.getDisassembledCode(JavaClassData.java:163)
	at jadx.core.dex.nodes.ClassNode.getDisassembledCode(ClassNode.java:755)
	at jadx.core.dex.nodes.ClassNode.getDisassembledCode(ClassNode.java:735)
	at jadx.api.JavaClass.getSmali(JavaClass.java:91)
	at jadx.gui.treemodel.JClass.getSmali(JClass.java:118)
	at jadx.gui.ui.codearea.SmaliArea$NormalModel.load(SmaliArea.java:184)
	at jadx.gui.ui.codearea.SmaliArea.load(SmaliArea.java:94)
	at jadx.gui.ui.codearea.CodePanel.load(CodePanel.java:117)
	at jadx.gui.ui.codearea.ClassCodeContentPanel.lambda$buildTabbedPane$0(ClassCodeContentPanel.java:89)
	at java.desktop/javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:444)
	at java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:295)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:148)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:79)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:648)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:623)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(BasicTabbedPaneUI.java:4101)
	at com.formdev.flatlaf.ui.FlatTabbedPaneUI$Handler.mousePressed(FlatTabbedPaneUI.java:2593)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6623)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: io.github.skylot.raung.disasm.impl.utils.RaungDisasmException: Unexpected frame type: -1
	at io.github.skylot.raung.disasm.impl.visitors.RaungMethodVisitor.visitFrame(RaungMethodVisitor.java:142)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2068)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1514)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:744)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at io.github.skylot.raung.disasm.impl.RaungDisasmExecutor.runForInputStream(RaungDisasmExecutor.java:53)
	at io.github.skylot.raung.disasm.impl.RaungDisasmExecutor.processInputStream(RaungDisasmExecutor.java:39)
	at io.github.skylot.raung.disasm.impl.RaungDisasmBuilder.executeForInputStream(RaungDisasmBuilder.java:122)
	... 50 common frames omitted
```

[RidgeRacer_K800.jar](https://github.com/skylot/jadx/files/11725963/RidgeRacer_K800.zip)

**Comment by skylot** [comment]
Fixed. Same issue as in #1932.
