### ISSUE TITLE
[jadx-script] Script execution with error

### ISSUE THREAD

**Issue by jygzyc** [skylot/jadx#1917]
I used the latest compiled jadx, but I found that besides the error caused by the dependency, there is still an issue that the script cannot be executed properly; I wrote a simple script, which cannot be executed correctly in my case.

```log
WARN : Script execution issue: Parameter 'mthSignature' is never used (example.jadx.kts:37:15)
WARN : Script execution issue: Parameter 'param' is never used (example.jadx.kts:37:37)
WARN : Compile issue: WARNING Parameter 'mthSignature' is never used (example.jadx.kts:37:15)
WARN : Compile issue: WARNING Parameter 'param' is never used (example.jadx.kts:37:37)
WARN : Lint issue: Missing spacing before "{" (37:60)(ruleId=standard:curly-spacing)
WARN : Lint issue: Expected a single white space before start of function body (37:60)(ruleId=standard:function-start-of-body-spacing)
WARN : Lint issue: First line in a method block should not be empty (38:1)(ruleId=standard:no-empty-first-line-in-method-block)
WARN : Lint issue: Needless blank line(s) (42:1)(ruleId=standard:no-consecutive-blank-lines)
INFO : reloading (passes only) ...
WARN : Script execution issue: Parameter 'mthSignature' is never used (example.jadx.kts:37:15)
WARN : Script execution issue: Parameter 'param' is never used (example.jadx.kts:37:37)
ERROR: [84] JadxRuntimeException in pass: ProcessVariables in method: androidx.core.FG.init(android.content.Context, boolean):void, file: classes.dex
jadx.core.utils.exceptions.JadxRuntimeException: Method arg registers not loaded: kotlinx.android.extensionss.kd.<init>(android.content.Context, java.lang.Thread$UncaughtExceptionHandler):void, class status: NOT_LOADED
	at jadx.core.dex.nodes.MethodNode.getArgRegs(MethodNode.java:289)
	at jadx.core.dex.visitors.regions.variables.ProcessVariables$1.isArgUnused(ProcessVariables.java:130)
	at jadx.core.dex.visitors.regions.variables.ProcessVariables$1.lambda$isVarUnused$0(ProcessVariables.java:115)
	at jadx.core.utils.ListUtils.allMatch(ListUtils.java:156)
	at jadx.core.dex.visitors.regions.variables.ProcessVariables$1.isVarUnused(ProcessVariables.java:115)
	at jadx.core.dex.visitors.regions.variables.ProcessVariables$1.processBlock(ProcessVariables.java:82)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseInternal(DepthRegionTraversal.java:64)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.lambda$traverseInternal$0(DepthRegionTraversal.java:68)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseInternal(DepthRegionTraversal.java:68)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.lambda$traverseInternal$0(DepthRegionTraversal.java:68)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseInternal(DepthRegionTraversal.java:68)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.lambda$traverseInternal$0(DepthRegionTraversal.java:68)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseInternal(DepthRegionTraversal.java:68)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.lambda$traverseInternal$0(DepthRegionTraversal.java:68)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseInternal(DepthRegionTraversal.java:68)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.lambda$traverseInternal$0(DepthRegionTraversal.java:68)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseInternal(DepthRegionTraversal.java:68)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.lambda$traverseInternal$0(DepthRegionTraversal.java:68)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseInternal(DepthRegionTraversal.java:68)
	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverse(DepthRegionTraversal.java:19)
	at jadx.core.dex.visitors.regions.variables.ProcessVariables.removeUnusedResults(ProcessVariables.java:73)
	at jadx.core.dex.visitors.regions.variables.ProcessVariables.visit(ProcessVariables.java:48)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:26)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
	at jadx.core.ProcessClass.process(ProcessClass.java:72)
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:107)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:374)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:298)
	at jadx.api.JavaClass.getCodeInfo(JavaClass.java:65)
	at jadx.gui.treemodel.JClass.getCodeInfo(JClass.java:114)
	at jadx.gui.ui.TabbedPane.lambda$codeJump$2(TabbedPane.java:209)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
WARN : Code restructure failed: missing block: B:51:0x0046, code lost:
    if (r2 == null) goto L53;
 in method: androidx.core.utils.ProcessUtils.c():java.lang.String, file: classes.dex
WARN : Removed duplicated region for block: B:253:0x007c A[Catch: all -> 0x0081, TRY_LEAVE, TryCatch #0 {all -> 0x0081, blocks: (B:251:0x0074, B:253:0x007c), top: B:345:0x0074 }] in method: com.blankj.utilcode.util.l.a.toString():java.lang.String, file: classes.dex
WARN : Removed duplicated region for block: B:263:0x00af  in method: com.blankj.utilcode.util.l.a.toString():java.lang.String, file: classes.dex
WARN : Removed duplicated region for block: B:258:0x008a  in method: com.blankj.utilcode.util.l.a.toString():java.lang.String, file: classes.dex
WARN : Can't wrap try/catch for region: R(10:8|9|10|(6:12|13|14|(1:16)|18|(3:20|(1:22)(1:24)|23)(2:25|(1:27)(2:28|(1:30)(2:31|(1:33)(2:34|(1:36)(2:37|(1:39)(2:40|(1:42)(2:43|(1:45)(2:46|(1:48)(3:49|(1:51)(2:53|(1:55)(2:56|(1:58)(2:59|(1:61)(2:62|(1:64)(2:65|(1:67)(2:68|(1:70)(2:71|(1:73)(2:74|(1:76)(2:77|(1:79)(2:80|(1:82)(1:83)))))))))))|52))))))))))|86|13|14|(0)|18|(0)(0)) in method: com.blankj.utilcode.util.l.a.toString():java.lang.String, file: classes.dex
```

The sample script and files are as follows.

```kotlin
import jadx.core.dex.instructions.ConstStringNode
import jadx.core.dex.instructions.InvokeNode
import jadx.core.dex.instructions.args.InsnArg
import jadx.core.dex.instructions.args.InsnWrapArg
import jadx.core.dex.instructions.args.RegisterArg

val jadx = getJadxInstance()

val mthSignature = "kotlinx.android.extensionss.qz.b(Ljava/lang/String;)Ljava/lang/String"

jadx.replace.insns { mth, insn ->
	if (insn is InvokeNode && insn.callMth.rawFullId == mthSignature) {
		val str = getConstStr(insn.getArg(0))
		log.info { "param: $str" }
		if (str != null) {
			val resultStr = getResult(mthSignature, str)
			log.info { "Decrypt '$str' to '$resultStr' in $mth" }
			return@insns ConstStringNode(resultStr)
		}
	}
	null
}

fun getConstStr(arg: InsnArg): String? {
	val insn = when (arg) {
		is InsnWrapArg -> arg.wrapInsn
		is RegisterArg -> arg.assignInsn
		else -> null
	}
	if (insn is ConstStringNode) {
		return insn.string
	}
	return null
}
fun getResult(mthSignature: String, param: String): String?{
	return "result"
}
```

[Demo.zip](https://github.com/skylot/jadx/files/11766278/Demo.zip)

**Comment by skylot** [comment]
@jygzyc actually, this error does not affect your script execution.
It is just a decompilation issue (maybe related to recent #1901 fix).

Looks like your script not work as you expect because you missed last semicolon in `mthSignature` constant, it should be:
```kotlin
val mthSignature = "kotlinx.android.extensionss.qz.b(Ljava/lang/String;)Ljava/lang/String;"
```
To simplify getting methods signature, you can use this script:
```kotlin
import jadx.core.dex.nodes.MethodNode

val jadx = getJadxInstance()
jadx.gui.ifAvailable {
	addPopupMenuAction(
		"Copy rawFullId",
		enabled = { it is MethodNode },
		keyBinding = "R",
	) {
		val mth = it as MethodNode
		val sign = mth.methodInfo.rawFullId
		jadx.log.info { "Method rawFullId: $sign" }
		jadx.gui.copyToClipboard(sign)
	}
}
```
Just click right-mouse-button on method name and select `Copy rawFullId`

**Comment by jygzyc** [comment]
Oh, sorry, this is indeed my mistake. Let me test it again and if it's confirmed to be correct, I will close this issue.

**Comment by jygzyc** [comment]
> @jygzyc actually, this error does not affect your script execution. It is just a decompilation issue (maybe related to recent #1901 fix).
> 
> Looks like your script not work as you expect because you missed last semicolon in `mthSignature` constant, it should be:
> 
> ```kotlin
> val mthSignature = "kotlinx.android.extensionss.qz.b(Ljava/lang/String;)Ljava/lang/String;"
> ```
> 
> To simplify getting methods signature, you can use this script:
> 
> ```kotlin
> import jadx.core.dex.nodes.MethodNode
> 
> val jadx = getJadxInstance()
> jadx.gui.ifAvailable {
> 	addPopupMenuAction(
> 		"Copy rawFullId",
> 		enabled = { it is MethodNode },
> 		keyBinding = "R",
> 	) {
> 		val mth = it as MethodNode
> 		val sign = mth.methodInfo.rawFullId
> 		jadx.log.info { "Method rawFullId: $sign" }
> 		jadx.gui.copyToClipboard(sign)
> 	}
> }
> ```
> 
> Just click right-mouse-button on method name and select `Copy rawFullId`

**Comment by jygzyc** [comment]
After testing, there should be no problems for now. I will close this issue. Thanks to @skylot for the help.
