### ISSUE TITLE
[cli] IllegalStateException during gradle export

### ISSUE THREAD

**Issue by alexandrogds** [skylot/jadx#1918]
```
PS C:\Users\Administrator\OneDrive> .\Downloads\jadx-1.4.7\bin\jadx -e -d .\wppb ".\Downloads\WhatsAppBusiness_2.23.11.78\"
INFO  - loading ...
INFO  - processing ...
ERROR - Process error:
java.lang.IllegalStateException: null
        at java.util.Optional.orElseThrow(Unknown Source)
        at jadx.api.JadxDecompiler.getSaveTasks(JadxDecompiler.java:276)
        at jadx.api.JadxDecompiler.getSaveExecutor(JadxDecompiler.java:261)
        at jadx.api.JadxDecompiler.getSaveExecutor(JadxDecompiler.java:249)
        at jadx.api.JadxDecompiler.save(JadxDecompiler.java:213)
        at jadx.cli.JadxCLI.save(JadxCLI.java:90)
        at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:54)
        at jadx.cli.JadxCLI.execute(JadxCLI.java:36)
        at jadx.cli.JadxCLI.main(JadxCLI.java:20)
```

**Comment by skylot** [comment]
@alexandrogs gradle export now expects an apk file as input.
We definitely need to improve error reporting here. Thanks :+1:

**Comment by skylot** [comment]
Fixed. Please check [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master).
