### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by happybeo** [skylot/jadx#1920]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: dev
* Java version: 17.0.7
* Java VM: Oracle Corporation Java HotSpot(TM) 64-Bit Server VM
* Platform: Windows 10 (10.0 amd64)
* Max heap size: 5564 MB
* Program args: -Xms397m -Xmx5564m -Xms128M -XX:MaxRAMPercentage=70.0 -XX:+UseG1GC -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -Djava.util.Arrays.useLegacyMergeSort=true -XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED

```
java.lang.IllegalStateException
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at jadx.core.export.ExportGradleTask.run(ExportGradleTask.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by happybeo** [comment]
yes, i was loading a apk file and tried to export to gradle, but i got this error info
