### ISSUE TITLE
can i use it in macos?

### ISSUE THREAD

**Issue by techgulesGu0** [skylot/jadx#193]
when i complie it in the macos it shows:

Unzipping /Users/techgules/.gradle/wrapper/dists/gradle-2.14.1-bin/ev4hc1s4g1oc9yuae0b81rdza/gradle-2.14.1-bin.zip to /Users/techgules/.gradle/wrapper/dists/gradle-2.14.1-bin/ev4hc1s4g1oc9yuae0b81rdza
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:215)
	at java.util.zip.ZipFile.<init>(ZipFile.java:145)
	at java.util.zip.ZipFile.<init>(ZipFile.java:159)
	at org.gradle.wrapper.Install.unzip(Install.java:159)
	at org.gradle.wrapper.Install.access$500(Install.java:26)
	at org.gradle.wrapper.Install$1.call(Install.java:69)
	at org.gradle.wrapper.Install$1.call(Install.java:46)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:46)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

how could i solve it?if you could give me some suggestion,i will appricate you very much.

**Comment by CodyToombs** [comment]
It looks like your version of Gradle is pretty old. Update it with a current version and try again.

**Comment by techgulesGu0** [comment]
thank you very much! i download a zip that complied completely ,and i can use it normally.
