### ISSUE TITLE
java.lang.InternalError: Unable to bind C:\Users\z9\Desktop\htdocs.lnk to parent

### ISSUE THREAD

**Issue by dalishen99** [skylot/jadx#1930]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.4.7
* Java version: 11.0.17
* Java VM: Oracle Corporation Java HotSpot(TM) 64-Bit Server VM
* Platform: Windows 10 (10.0 amd64)
* Max heap size: 30688 MB
* Program args: -Xms128M -XX:MaxRAMPercentage=70.0 -XX:+UseG1GC -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -Djava.util.Arrays.useLegacyMergeSort=true

```
java.lang.InternalError: Unable to bind C:\Users\z9\Desktop\htdocs.lnk to parent
	at java.desktop/sun.awt.shell.Win32ShellFolder2$4.call(Win32ShellFolder2.java:454)
	at java.desktop/sun.awt.shell.Win32ShellFolder2$4.call(Win32ShellFolder2.java:438)
	at java.desktop/sun.awt.shell.Win32ShellFolderManager2$ComInvoker.invoke(Win32ShellFolderManager2.java:616)
	at java.desktop/sun.awt.shell.ShellFolder.invoke(ShellFolder.java:519)
	at java.desktop/sun.awt.shell.Win32ShellFolder2.getIShellFolder(Win32ShellFolder2.java:438)
	at java.desktop/sun.awt.shell.Win32ShellFolder2$16.call(Win32ShellFolder2.java:1186)
	at java.desktop/sun.awt.shell.Win32ShellFolder2$16.call(Win32ShellFolder2.java:1184)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.desktop/sun.awt.shell.Win32ShellFolderManager2$ComInvoker$1.run(Win32ShellFolderManager2.java:586)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by dalishen99** [comment]
I use the 1.4.7 version. When try to click open file button, but in the next step it do not show my computer. when  i try to click some shortcut. It will crash. The crash error is above. But I use 1.4.5 everything works fine.

**Comment by skylot** [comment]
A possible workaround is to enable `Use alternative file dialog` at `Preferences -> Other` options.
Also, using [latest unstable version](https://nightly.link/skylot/jadx/workflows/build-artifacts/master) with included (and latest) JDK may help.
