### ISSUE TITLE
io.github.skylot.raung.disasm.impl.utils.RaungDisasmException: Failed to process input stream

### ISSUE THREAD

**Issue by raspiduino** [skylot/jadx#1932]
I just click the `Smali` tab and the app crash. [Here](https://github.com/skylot/jadx/files/11925586/diamondrus_lybcoaz8.zip) is the jar file. It's a J2ME game. Download and unzip it, since Github does not allow me to upload the jar file itself without zipping.

* Jadx version: 1.4.7
* Java version: 19.0.2
* Java VM: Oracle Corporation OpenJDK 64-Bit Server VM
* Platform: Windows 11 (10.0 amd64)
* Max heap size: 4096 MB

```
io.github.skylot.raung.disasm.impl.utils.RaungDisasmException: Failed to process input stream
	at io.github.skylot.raung.disasm.impl.RaungDisasmBuilder.executeForInputStream(RaungDisasmBuilder.java:124)
	at jadx.plugins.input.java.utils.DisasmUtils.useRaung(DisasmUtils.java:26)
	at jadx.plugins.input.java.utils.DisasmUtils.get(DisasmUtils.java:21)
	at jadx.plugins.input.java.data.JavaClassData.getDisassembledCode(JavaClassData.java:163)
	at jadx.core.dex.nodes.ClassNode.getDisassembledCode(ClassNode.java:755)
	at jadx.core.dex.nodes.ClassNode.getDisassembledCode(ClassNode.java:735)
	at jadx.api.JavaClass.getSmali(JavaClass.java:91)
	at jadx.gui.treemodel.JClass.getSmali(JClass.java:118)
	at jadx.gui.ui.codearea.SmaliArea$NormalModel.load(SmaliArea.java:184)
	at jadx.gui.ui.codearea.SmaliArea.load(SmaliArea.java:94)
	at jadx.gui.ui.codearea.CodePanel.load(CodePanel.java:117)
	at jadx.gui.ui.codearea.ClassCodeContentPanel.lambda$buildTabbedPane$0(ClassCodeContentPanel.java:89)
	at java.desktop/javax.swing.JTabbedPane.fireStateChanged(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(Unknown Source)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(Unknown Source)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndexImpl(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(Unknown Source)
	at com.formdev.flatlaf.ui.FlatTabbedPaneUI$Handler.mousePressed(FlatTabbedPaneUI.java:2593)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: io.github.skylot.raung.disasm.impl.utils.RaungDisasmException: Unexpected frame type: -1
	at io.github.skylot.raung.disasm.impl.visitors.RaungMethodVisitor.visitFrame(RaungMethodVisitor.java:142)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2068)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1514)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:744)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at io.github.skylot.raung.disasm.impl.RaungDisasmExecutor.runForInputStream(RaungDisasmExecutor.java:53)
	at io.github.skylot.raung.disasm.impl.RaungDisasmExecutor.processInputStream(RaungDisasmExecutor.java:39)
	at io.github.skylot.raung.disasm.impl.RaungDisasmBuilder.executeForInputStream(RaungDisasmBuilder.java:122)
	... 50 more

```

**Comment by skylot** [comment]
Fixed.
Although for java classes you will get not smali but disassemble for java bytecode using [raung](https://github.com/skylot/raung) project. If you really need a smali you can enable `Decompilation > Use dx/d8 to convert java bytecode` option, also sometimes it can improve decompilation result code.
