### ISSUE TITLE
[core][unstable] StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by psolyca** [skylot/jadx#1937]
jadx-1.4.7.182-c0c35f32

When I try to change an attribut value I get :
```
ERROR - Exception was thrown
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
        at java.base/java.lang.String.charAt(String.java:712)
        at jadx.core.dex.visitors.rename.RenameVisitor.fixClsShortName(RenameVisitor.java:134)
        at jadx.core.dex.visitors.rename.RenameVisitor.checkClassName(RenameVisitor.java:86)
        at jadx.core.dex.visitors.rename.RenameVisitor.checkNames(RenameVisitor.java:57)
        at jadx.core.dex.visitors.rename.RenameVisitor.process(RenameVisitor.java:44)
        at jadx.core.dex.visitors.rename.RenameVisitor.lambda$init$0(RenameVisitor.java:39)
        at jadx.core.dex.nodes.RootNode.lambda$notifyCodeDataListeners$10(RootNode.java:644)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at jadx.core.dex.nodes.RootNode.notifyCodeDataListeners(RootNode.java:644)
        at jadx.api.JadxDecompiler.reloadCodeData(JadxDecompiler.java:653)
        at jadx.gui.JadxWrapper.reloadCodeData(JadxWrapper.java:258)
        at jadx.gui.ui.dialog.RenameDialog.lambda$refreshState$4(RenameDialog.java:181)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

From `this.h` to `this.mBroadcastReceiver`

The name is not saved; when I reload, name is the original one.

**Comment by skylot** [comment]
@psolyca unfortunately I can't reproduce this issue. Looks like class alias was set to empty string, but it is impossible to trace back to root cause using this stacktrace. So I commit additional checks, please try latest unstable build, and share a new stacktrace :slightly_smiling_face:

**Comment by psolyca** [comment]
Testing the jadx-1.4.7.185-2d655943

On fiirst start of this version, the cache is reset again while previous unstable 182 has the cache reset corrected.
BTW, the exception has disappear and the attribut can be chaged again.
I closed Jadx and reopen the file and the cache was loaded correctly and I can change attributs again without problem.

So I really do not know...
