### ISSUE TITLE
java.lang.IllegalArgumentException: bad position: 22868

### ISSUE THREAD

**Issue by chuanwangchen** [skylot/jadx#1956]
Please describe what you did before the error occurred.
**IMPORTANT!** If the error occurs with a specific APK file please attach or provide link to apk file!
 * Jadx version: 1.4.5.97-22ed241d
* Java version: 17.0.5
* Java VM: Oracle Corporation Java HotSpot(TM) 64-Bit Server VM
* Platform: Windows 11 (10.0 amd64)
* Max heap size: 4096 MB

```
java.lang.IllegalArgumentException: bad position: 22868
	at java.desktop/javax.swing.text.JTextComponent.setCaretPosition(Unknown Source)
	at jadx.gui.ui.codearea.CodeContentPanel.restoreEditorViewState(CodeContentPanel.java:63)
	at jadx.gui.ui.TabbedPane.restoreEditorViewState(TabbedPane.java:280)
	at jadx.gui.ui.MainWindow.restoreOpenTabs(MainWindow.java:1512)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by xdatsec** [comment]
how did u fix?

**Comment by jpstotz** [comment]
@xdatsec This issue should have been fixed by commit f354f7de639d8a829ad69bdf5581e312daf47b67 thus it should be fixed since Jadx 1.4.6.

**Comment by xdatsec** [comment]
> [@xdatsec](https://github.com/xdatsec) This issue should have been fixed by commit [f354f7d](https://github.com/skylot/jadx/commit/f354f7de639d8a829ad69bdf5581e312daf47b67) thus it should be fixed since Jadx 1.4.6.

<img width="1280" height="1024" alt="Image" src="https://github.com/user-attachments/assets/11e214b8-d1c3-4093-95da-139f2cabf346" />

**Comment by xdatsec** [comment]
WARN : Invalid jump: Jump{DownloaderActivityBase$$ExternalSyntheticLambda2:0}
jadx.core.utils.exceptions.JadxRuntimeException
	at jadx.gui.ui.tab.TabbedPane.showCode(TabbedPane.java:233)
	at jadx.gui.ui.tab.TabbedPane.lambda$onTabCodeJump$1(TabbedPane.java:447)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
 sometimes work soemtimes didint and it shows error with

**Comment by jpstotz** [comment]
That is a totally different problem as you can see from the error message and the stack trace. Please open a new issue and also upload the APK (renamed to zip) that triggers this bug.
