### ISSUE TITLE
[core] JDK 11.0.20+9 breaks jadx decompilation functionality

### ISSUE THREAD

**Issue by zt64** [skylot/jadx#1962]
**Describe error**
JDK has recently updated and has changed how the ZipFile class functions. [JDK-8302483](https://www.oracle.com/java/technologies/javase/11-0-20-relnotes.html#JDK-8302483) breaks decompilation. Downgrading the installed JDK to versions older than 11.0.20 do indeed result in the error going away. 

```
java.lang.RuntimeException: Failed to process zip file: /home/nick/Documents/SM-S908U_NA_12/apk/atfwd.apk
        at jadx.api.plugins.utils.ZipSecurity.visitZipEntries(ZipSecurity.java:115)
        at jadx.api.plugins.utils.ZipSecurity.readZipEntries(ZipSecurity.java:121)
        at jadx.plugins.input.dex.DexFileLoader.collectDexFromZip(DexFileLoader.java:90)
        at jadx.plugins.input.dex.DexFileLoader.load(DexFileLoader.java:73)
        at jadx.plugins.input.dex.DexFileLoader.loadDexFromFile(DexFileLoader.java:50)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at jadx.plugins.input.dex.DexFileLoader.collectDexFiles(DexFileLoader.java:45)
        at jadx.plugins.input.dex.DexInputPlugin.loadFiles(DexInputPlugin.java:37)
        at jadx.plugins.input.dex.DexInputPlugin.loadFiles(DexInputPlugin.java:33)
        at jadx.api.JadxDecompiler.loadInputFiles(JadxDecompiler.java:128)
        at jadx.api.JadxDecompiler.load(JadxDecompiler.java:112)
        at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:48)
        at jadx.cli.JadxCLI.execute(JadxCLI.java:36)
        at jadx.cli.JadxCLI.main(JadxCLI.java:20)
Caused by: java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra data field size)
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1750)
        at java.base/java.util.zip.ZipFile$Source.checkExtraFields(ZipFile.java:1276)
        at java.base/java.util.zip.ZipFile$Source.checkAndAddEntry(ZipFile.java:1219)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1689)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1464)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1427)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:723)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:250)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:179)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:193)
        at jadx.api.plugins.utils.ZipSecurity.visitZipEntries(ZipSecurity.java:97)
        ... 20 common frames omitted
ERROR - Failed to process zip file: /home/nick/Documents/SM-S908U_NA_12/apk/atfwd.apk
java.lang.RuntimeException: Failed to process zip file: /home/nick/Documents/SM-S908U_NA_12/apk/atfwd.apk
        at jadx.api.plugins.utils.ZipSecurity.visitZipEntries(ZipSecurity.java:115)
        at jadx.api.plugins.utils.ZipSecurity.readZipEntries(ZipSecurity.java:121)
        at jadx.plugins.input.java.JavaInputLoader.collectFromZip(JavaInputLoader.java:91)
        at jadx.plugins.input.java.JavaInputLoader.loadReader(JavaInputLoader.java:71)
        at jadx.plugins.input.java.JavaInputLoader.loadFromFile(JavaInputLoader.java:50)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at jadx.plugins.input.java.JavaInputLoader.collectFiles(JavaInputLoader.java:37)
        at jadx.plugins.input.java.JavaInputPlugin.loadClassFiles(JavaInputPlugin.java:36)
        at jadx.plugins.input.java.JavaInputPlugin.loadFiles(JavaInputPlugin.java:32)
        at jadx.api.JadxDecompiler.loadInputFiles(JadxDecompiler.java:128)
        at jadx.api.JadxDecompiler.load(JadxDecompiler.java:112)
        at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:48)
        at jadx.cli.JadxCLI.execute(JadxCLI.java:36)
        at jadx.cli.JadxCLI.main(JadxCLI.java:20)
Caused by: java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra data field size)
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1750)
        at java.base/java.util.zip.ZipFile$Source.checkExtraFields(ZipFile.java:1276)
        at java.base/java.util.zip.ZipFile$Source.checkAndAddEntry(ZipFile.java:1219)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1689)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1464)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1427)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:723)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:250)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:179)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:193)
        at jadx.api.plugins.utils.ZipSecurity.visitZipEntries(ZipSecurity.java:97)
        ... 20 common frames omitted
ERROR - Process error:
java.lang.RuntimeException: Failed to process zip file: /home/nick/Documents/SM-S908U_NA_12/apk/atfwd.apk
        at jadx.api.plugins.utils.ZipSecurity.visitZipEntries(ZipSecurity.java:115)
        at jadx.api.ResourcesLoader.loadFile(ResourcesLoader.java:144)
        at jadx.api.ResourcesLoader.load(ResourcesLoader.java:46)
        at jadx.api.JadxDecompiler.getResources(JadxDecompiler.java:402)
        at jadx.api.JadxDecompiler.load(JadxDecompiler.java:117)
        at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:48)
        at jadx.cli.JadxCLI.execute(JadxCLI.java:36)
        at jadx.cli.JadxCLI.main(JadxCLI.java:20)
Caused by: java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra data field size)
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1750)
        at java.base/java.util.zip.ZipFile$Source.checkExtraFields(ZipFile.java:1276)
        at java.base/java.util.zip.ZipFile$Source.checkAndAddEntry(ZipFile.java:1219)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1689)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1464)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1427)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:723)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:250)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:179)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:193)
        at jadx.api.plugins.utils.ZipSecurity.visitZipEntries(ZipSecurity.java:97)
        ... 7 common frames omitted
```

**Comment by jpstotz** [comment]
Thanks for reporting. Based on the page you have linked it should be sufficient to set the system property `jdk.util.zip.disableZip64ExtraFieldValidation` to `true` at start-up of jadx and jadx-gui.   

According to the discussion in the apktools issue tracker about this JDK change: 
See also https://github.com/iBotPeaches/Apktool/issues/3174#issuecomment-1642697602

**Comment by jpstotz** [comment]
I just made some tests and realized that calling `System.setProperty("jdk.util.zip.disableZip64ExtraFieldValidation", "true");` at run-time has no effect:

This property is only read when `java.util.zip.ZipFile` is read. As the system class loader uses ZipFile to load the JAR files form class path the `jdk.util.zip.disableZip64ExtraFieldValidation` property is already before the first user class is executed. Therefore trying to set this property using `System.setProperty` is useless no matter how and where you add it. 

The only way to set this property is directly when starting the java run-time. In the end this means we have to change the start script and the Launch4j generated executable.

**Comment by skylot** [comment]
@jpstotz I commit fix for run scripts as you suggested, so this should resolve the issue. Thanks for help! :+1:

**Comment by jpstotz** [comment]
@sklot I am currently in contact with Lance Andersen from Oracle, the author of JDK-8302483. I have provided him several APK files which cause the `Invalid CEN header (invalid zip64 extra data field size)`. Not sure what will be the outcome of this, but the situation can only get better...

**Comment by iBotPeaches** [comment]
@jpstotz - Thank you for doing that. I was attempting that myself but struggled to make contact and provide samples.

**Comment by eirbjo** [comment]
For reference, the following OpenJDK PR seems to provide a solution to the problems mentioned in this issue:

https://github.com/openjdk/jdk/pull/15273
