### ISSUE TITLE
[core] Remapping failed: Can't change package for inner class

### ISSUE THREAD

**Issue by leumasme** [skylot/jadx#1997]
### Issue details

Using the new `--mappings-path` cli argument (using main branch at https://github.com/skylot/jadx/commit/2c92c6b0a60f7fca9a5b0c90925644f8c20b2aac), I attempted to apply a `.tiny` mappings file.
Instead, I got the below error and the output code was generated without mappings applied.

### Relevant log output or stacktrace

```java
ERROR - Visitor init failed: RenameVisitor
jadx.core.utils.exceptions.JadxRuntimeException: Can't change package for inner class
        at jadx.core.dex.info.ClassInfo.changePkg(ClassInfo.java:82)
        at jadx.core.dex.nodes.ClassNode.onParentPackageUpdate(ClassNode.java:624)
        at jadx.core.dex.nodes.PackageNode.updatePackages(PackageNode.java:129)
        at jadx.core.dex.nodes.PackageNode.onParentPackageUpdate(PackageNode.java:117)
        at jadx.core.dex.nodes.PackageNode.updatePackages(PackageNode.java:126)
        at jadx.core.dex.nodes.PackageNode.onParentPackageUpdate(PackageNode.java:117)
        at jadx.core.dex.nodes.PackageNode.updatePackages(PackageNode.java:126)
        at jadx.core.dex.nodes.PackageNode.updatePackages(PackageNode.java:121)
        at jadx.core.dex.nodes.RootNode.runPackagesUpdate(RootNode.java:444)
        at jadx.core.dex.visitors.rename.RenameVisitor.checkNames(RenameVisitor.java:78)
        at jadx.core.dex.visitors.rename.RenameVisitor.process(RenameVisitor.java:45)
        at jadx.core.dex.visitors.rename.RenameVisitor.init(RenameVisitor.java:39)
        at jadx.core.dex.nodes.RootNode.runPreDecompileStage(RootNode.java:333)
        at jadx.api.JadxDecompiler.load(JadxDecompiler.java:126)
        at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:50)
        at jadx.cli.JadxCLI.execute(JadxCLI.java:37)
        at jadx.cli.JadxCLI.main(JadxCLI.java:21)
```

### Jadx version

jadx-1.4.7.224-2c92c6b0 (nightly)

**Comment by leumasme** [comment]
After properly testing, it seems that the error isn't caused by using `--mappings-path`. I had wrongly assumed so because the error didn't appear in `1.4.7` but did appear in the nightly version which I only used for this CLI argument.
Nontheless, the error is logged and mappings are not applied, wether these two things are related or not I do not know.  
I simply ran jadx like 
```
jadx --mappings-path "path/to/mappings.tiny" -d output_remapped input/*.jar
```

**Comment by skylot** [comment]
@leumasme thanks for report! 
Sure, this issues caused by renaming inner class from mapping file. Because if both inner and outer classes in mappings file have different packages jadx will not be able to do such rename, that is why I reject package rename for inner classes.

For fix this I will check package names and if they are not same just log a warning, so mappings file processing will not be interrupted.

Until fix, as a workaround, you can disable inner class moving by disabling `Decompilation -> Move inner classes into parent` option in preferences.

**Comment by skylot** [comment]
Also, if possible, please share a sample apk, so it will be much easier to reproduce your issue.

**Comment by jackwilsdon** [comment]
I'm running into this at the moment - here's an example jar (zipped due to GitHub's upload limitations): [example.zip](https://github.com/user-attachments/files/22782514/example.zip)

It does seem to be mapping releated - this is the mapping file I used:

```text
CLASS com/example/IExample
	CLASS Inner RenamedInner
```

And the output:
```text
$ jadx --mappings-path enigma.mapping --verbose example.jar 
INFO  - output directory: example
DEBUG - Effective jadx args: JadxArgs{inputFiles=[example.jar], outDir=example, outDirSrc=example/sources, outDirRes=example/resources, threadsCount=6, decompilationMode=AUTO, showInconsistentCode=false, useImports=true, skipResources=false, skipSources=false, includeDependencies=false, userRenamesMappingsPath=enigma.mapping, userRenamesMappingsMode=READ, deobfuscationOn=false, generatedRenamesMappingFile=null, generatedRenamesMappingFileMode=READ, resourceNameSource=AUTO, useSourceNameAsClassNameAlias=NEVER, sourceNameRepeatLimit=10, useKotlinMethodsForVarNames=APPLY, insertDebugLines=false, extractFinally=true, deobfuscationMinLength=3, deobfuscationMaxLength=64, deobfuscationWhitelist=[android.support.v4.*, android.support.v7.*, android.support.v4.os.*, android.support.annotation.Px, androidx.core.os.*, androidx.annotation.Px], escapeUnicode=false, replaceConsts=true, restoreSwitchOverString=true, respectBytecodeAccModifiers=false, exportGradleType=null, skipXmlPrettyPrint=false, fsCaseSensitive=false, renameFlags=[CASE, VALID, PRINTABLE], outputFormat=JAVA, commentsLevel=INFO, codeCache=NoOpCodeCache, codeWriter=SimpleCodeWriter, useDxInput=false, pluginOptions={}, cfgOutput=false, rawCFGOutput=false, useHeadersForDetectResourceExtensions=false}
INFO  - loading ...
DEBUG - Loading system dirs ...
DEBUG - Loaded system dirs (0ms): config: /Users/jackwilsdon/Library/Application Support/io.github.skylot.jadx, cache: /Users/jackwilsdon/Library/Caches/io.github.skylot.jadx
DEBUG - Collected 12 plugins in 13ms
DEBUG - Loading plugin: aab-input
DEBUG - Loading plugin: apkm-input
DEBUG - Loading plugin: dex-input
DEBUG - Loading plugin: jadx-script
DEBUG - Loading plugin: java-convert
DEBUG - Loading plugin: java-input
DEBUG - Loading plugin: kotlin-metadata
DEBUG - Loading plugin: kotlin-smap
DEBUG - Loading plugin: raung-input
DEBUG - Loading plugin: rename-mappings
DEBUG - Loading plugin: smali-input
DEBUG - Loading plugin: xapk-input
DEBUG - Resolved plugins: [aab-input, apkm-input, dex-input, jadx-script, java-input, kotlin-metadata, kotlin-smap, raung-input, rename-mappings, smali-input, xapk-input]
DEBUG - Loaded custom passes: 5 [KotlinMetadataDecompile, CodeMappings, KotlinMetadataPrepare, LoadMappings, ApplyMappings]
DEBUG - Loaded using 1 inputs plugin in 4 ms
DEBUG - 'resources.arsc' or 'resources.pb' file not found
INFO  - Loaded classes: 2, methods: 1, instructions: 5
DEBUG - Clst file loaded in 94ms, android api: 34, classes: 6208, methods: 59962
DEBUG - Prepare pass: 'SignatureProcessor' - 0ms
DEBUG - Prepare pass: 'OverrideMethodVisitor' - 0ms
DEBUG - Prepare pass: 'AddAndroidConstants' - 31ms
DEBUG - Prepare pass: 'DeobfuscatorVisitor' - 0ms
DEBUG - Prepare pass: 'SourceFileRename' - 0ms
DEBUG - Prepare pass: 'KotlinMetadataPrepare' - 1ms
DEBUG - Prepare pass: 'LoadMappings' - 7ms
WARN  - Can't change package for inner class: com.example.IExample.Inner to com.example.IExample$RenamedInner in class: com.example.IExample.Inner, file: example.jar:com/example/IExample$Inner.class
DEBUG - Prepare pass: 'ApplyMappings' - 2ms
DEBUG - Prepare pass: 'RenameVisitor' - 2ms
DEBUG - Prepare pass: 'SaveDeobfMapping' - 0ms
DEBUG - Apply usage data in 0ms
DEBUG - Prepare pass: 'UsageInfoVisitor' - 7ms
DEBUG - Prepare pass: 'CollectConstValues' - 0ms
DEBUG - Prepare pass: 'ProcessAnonymous' - 1ms
DEBUG - Prepare pass: 'ProcessMethodsForInline' - 0ms
DEBUG - Kotlin Intrinsics class not found
DEBUG - Load finished
INFO  - processing ...
DEBUG - Build decompilation batches in 1ms for 1 classes
INFO  - done
$ cat example/sources/com/example/IExample.java 
package com.example;

/* loaded from: example.jar:com/example/IExample.class */
public interface IExample {

    /* JADX WARN: Can't change package for inner class: com.example.IExample.Inner to com.example.IExample$RenamedInner */
    /* loaded from: example.jar:com/example/IExample$Inner.class */
    public static abstract class Inner {
    }
}
```

I don't see this issue if I disable moving inner classes:
```text
$ jadx --mappings-path enigma.mapping --no-move-inner-classes --verbose example.jar
$ cat example/sources/com/example/IExample.java                                                                              
package com.example;

/* loaded from: example.jar:com/example/IExample.class */
public interface IExample {
}
$ cat example/sources/com/example/IExample\$RenamedInner.java 
package com.example;

/* renamed from: com.example.IExample$Inner */
/* loaded from: example.jar:com/example/IExample$Inner.class */
public abstract class IExample$RenamedInner {
}
```

**Comment by skylot** [comment]
@jackwilsdon I fixed your case. Thank you for report :+1:
