### ISSUE TITLE
[core] Error decompiling App from Android Beta m5-rc14 ROM

### ISSUE THREAD

**Issue by user0-tb** [skylot/jadx#1999]
### Issue details

An error occoures if i try to decompile an apk from Android Beta m5-rc14 ROM.

### Relevant log output or stacktrace

```java
ERROR: Failed to read zip entry: classes.dex
jadx.plugins.input.dex.DexException: Unexpected endian tag: 0x0
	at jadx.plugins.input.dex.sections.DexHeader.<init>(DexHeader.java:32)
	at jadx.plugins.input.dex.DexReader.<init>(DexReader.java:22)
	at jadx.plugins.input.dex.DexFileLoader.loadDexReader(DexFileLoader.java:84)
	at jadx.plugins.input.dex.DexFileLoader.load(DexFileLoader.java:67)
	at jadx.plugins.input.dex.DexFileLoader.lambda$collectDexFromZip$2(DexFileLoader.java:92)
	at jadx.api.plugins.utils.ZipSecurity.lambda$readZipEntries$0(ZipSecurity.java:124)
	at jadx.api.plugins.utils.ZipSecurity.visitZipEntries(ZipSecurity.java:103)
	at jadx.api.plugins.utils.ZipSecurity.readZipEntries(ZipSecurity.java:121)
	at jadx.plugins.input.dex.DexFileLoader.collectDexFromZip(DexFileLoader.java:90)
	at jadx.plugins.input.dex.DexFileLoader.load(DexFileLoader.java:73)
	at jadx.plugins.input.dex.DexFileLoader.loadDexFromFile(DexFileLoader.java:50)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at jadx.plugins.input.dex.DexFileLoader.collectDexFiles(DexFileLoader.java:45)
	at jadx.plugins.input.dex.DexInputPlugin.loadFiles(DexInputPlugin.java:37)
	at jadx.plugins.input.dex.DexInputPlugin.loadFiles(DexInputPlugin.java:33)
	at jadx.api.JadxDecompiler.loadInputFiles(JadxDecompiler.java:128)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:112)
	at jadx.gui.JadxWrapper.open(JadxWrapper.java:65)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
ERROR: Failed to parse '.arsc' file
jadx.core.utils.exceptions.JadxException: Error decode: resources.arsc
	at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:78)
	at jadx.core.dex.nodes.RootNode.loadResources(RootNode.java:174)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:117)
	at jadx.gui.JadxWrapper.open(JadxWrapper.java:65)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.io.IOException: Config size < 28
	at jadx.core.xmlgen.ResTableParser.parseConfig(ResTableParser.java:472)
	at jadx.core.xmlgen.ResTableParser.parseTypeChunk(ResTableParser.java:274)
	at jadx.core.xmlgen.ResTableParser.parsePackage(ResTableParser.java:164)
	at jadx.core.xmlgen.ResTableParser.decodeTableChunk(ResTableParser.java:112)
	at jadx.core.xmlgen.ResTableParser.decode(ResTableParser.java:88)
	at jadx.core.xmlgen.ResDecoder.decode(ResDecoder.java:28)
	at jadx.core.dex.nodes.RootNode.lambda$loadResources$7(RootNode.java:174)
	at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:73)
	... 6 common frames omitted
```

### Provide sample and class/method full name

All apks are available at [https://github.com/user0-tb/ApktoolDebug](https://github.com/user0-tb/ApktoolDebug)

### Jadx version

1.4.7

**Comment by skylot** [comment]
Wait, do you really need to check this very old versions?
Because dex here has version `013` which is not supported by jadx, and have different structure as mentioned in dex format docs (https://source.android.com/docs/core/runtime/dex-format#dex-file-magic):

> version 013 was used for the M5 releases of the Android platform (February–March 2008). In several respects, these earlier versions of the format differ significantly from the version described in this document.

So I don't think I will add support for this dex version :slightly_frowning_face:

**Comment by user0-tb** [comment]
I find the Launcher very good, and want to try to Port it to Android 10.

**Comment by user0-tb** [comment]
Is it fixable?

**Comment by skylot** [comment]
Well, I can't find a file format docs nor sources (looked at https://android.googlesource.com/platform/dalvik/, first commit dated 2008-10-21 and already describe modern format). And without format it is nearly impossible to parse binary file.
So it looks not fixable to me.

**Comment by user0-07161** [comment]
Which files do you need?

**Comment by user0-tb** [comment]
Maybe I have them.

**Comment by user0-tb** [comment]
@skylot I have the Source Code of dx.jar, maybe you can use it.

**Comment by skylot** [comment]
> I have the Source Code of dx.jar, maybe you can use it.

@user0-tb sure, please share, so I can check it :+1:

**Comment by user0-tb** [comment]
[dx.jar_src.zip](https://github.com/skylot/jadx/files/12539940/dx.jar_src.zip)
Here is it @skylot

**Comment by user0-tb** [comment]
It's decompiled, i don't know If it's usable. But i Hope, that you can use it😀.

**Comment by user0-tb** [comment]
@skylot If you need more Files, ask me, maybe I have them.

**Comment by skylot** [comment]
@user0-tb looks like there are too many differences in file structure, it will need too much work and I don't want to do this. Sorry :slightly_frowning_face:

**Comment by user0-tb** [comment]
OK, maybe someone can Work in it, maybe you can reopen and Label as "need Help", maybe someone can Work in this.

**Comment by user0-tb** [comment]
Or say me, what I need to do to implement it @skylot please

**Comment by hacked-prototype** [comment]
I have made these tables explaining DEX v009 and v013's header structure
# DEX Versions 009 and 013 Header Structures
These tables is based on dump of `dx` (Version 0.9) command, present in Android SDK's M3 and M5.

Note: Some values are constant or dynamic.

## DEX v009 (DEX Version used in Android Milestone 3 Builds's applications):
| Location | Value                 | Name                  | Readeable HEX       |
| ---      | ---                   | ---                   | ---                 |
| `000000` | `6465 780a 3030 3900` | `magic`               |                     |
| `000008` | `a73f fe2c`           | `checksum`            |                     |
| `00000c` | `cdd2 0e7b eb90 9dcd` | `signature`           |                     |
| `000014` | `a845 b0ad 15c1 97ba` |                       |                     |
| `00001c` | `b3b7 ef8d`           |                       |                     |
| `000020` | `9263 0b00`           | `file_size`           | `000b6392` (746386) |
| `000024` | `5c00 0000`           | `header_size`         | `0000005c` (92)     |
| `000028` | `0000 0000`           | `link_size`           | `0`                 |
| `00002c` | `0000 0000`           | `link_off`            | `0`                 |
| `000030` | `a614 0000`           | `string_ids_size`     | `000014a6` (5286)   |
| `000034` | `5c00 0000`           | `string_ids_off`      | `0000005c` (92)     |
| `000038` | `d404 0000`           | `string_objects_size` | `000004d4` (1236)   |
| `00003c` | `bc01 0000`           | `class_ids_size`      | `000001bc` (444)    |
| `000040` | `8ca5 0000`           | `class_ids_off`       | `0000a58c` (42380)  |
| `000044` | `9007 0000`           | `field_ids_size`      | `00000790` (1936)   |
| `000048` | `7cac 0000`           | `field_ids_off`       | `0000ac7c` (44156)  |
| `00004c` | `a60d 0000`           | `method_ids_size`     | `00000da6` (3494)   |
| `000050` | `3c07 0100`           | `method_ids_off`      | `0001073c` (67388)  |
| `000054` | `5501 0000`           | `class_defs_size`     | `00000155` (341)    |
| `000058` | `04ab 0100`           | `class_defs_off`      | `0001ab04` (109316) |

## DEX v013 (DEX Version used in Android Milestone 5 Builds's applications):
| Location | Value                 | Name                  | Readeable HEX       |
| ---      | ---                   | ---                   | ---                 |
| `000000` | `6465 780a 3031 3300` | `magic`               |                     |
| `000008` | `c8b7 197f`           | `checksum`            |                     |
| `00000c` | `2ae8 29a3 3d28 2928` | `signature`           |                     |
| `000014` | `fcf9 e332 f782 01a5` |                       |                     |
| `00001c` | `68c0 abc6`           |                       |                     |
| `000020` | `5d19 0a00`           | `file_size`           | `000a195d` (661853) |
| `000024` | `7c00 0000`           | `header_size`         | `0000007c` (124)    |
| `000028` | `0000 0000`           | `link_size`           | `0`                 |
| `00002c` | `0000 0000`           | `link_off`            | `0`                 |
| `000030` | `fc15 0000`           | `string_ids_size`     | `000015fc` (5628)   |
| `000034` | `7c00 0000`           | `string_ids_off`      | `0000007c` (124)    |
| `000038` | `4a05 0000`           | `string_objects_size` | `0000054a` (1354)   |
| `00003c` | `ed01 0000`           | `type_ids_size`       | `000001ed` (493)    |
| `000040` | `5cb0 0000`           | `type_ids_off`        | `0000b05c` (45148)  |
| `000044` | `3008 0000`           | `field_ids_size`      | `00000830` (2096)   |
| `000048` | `10b8 0000`           | `field_ids_off`       | `0000b810` (47120)  |
| `00004c` | `310f 0000`           | `method_ids_size`     | `00000f31` (3889)   |
| `000050` | `501a 0100`           | `method_ids_off`      | `00011a50` (72272)  |
| `000054` | `8001 0000`           | `class_defs_size`     | `00000180` (384)    |
| `000058` | `9cd0 0100`           | `class_defs_off`      | `0001d09c` (118940) |
| `00005c` | `a458 0200`           | `word_data_size`      | `000258a4` (153764) |
| `000060` | `a006 0200`           | `word_data_off`       | `000206a0` (132768) |
| `000064` | `4657 0300`           | `codes_size`          | `00035746` (218950) |
| `000068` | `445f 0400`           | `codes_off`           | `00045f44` (286532) |
| `00006c` | `16e0 0100`           | `string_data_size`    | `0001e016` (122902) |
| `000070` | `8ab6 0700`           | `string_data_off`     | `0007b68a` (505482) |
| `000074` | `bd82 0000`           | `byte_data_size`      | `000082bd` (33469)  |
| `000078` | `a096 0900`           | `byte_data_off`       | `000996a0` (628384) |
