### ISSUE TITLE
[core] Some dexfile decompile errors

### ISSUE THREAD

**Issue by mrknow001** [skylot/jadx#2014]
### Issue details

jadx.plugins.input.dex.DexException: Bad checksum: 0x10691c42, expected: 0xc5263138
	at jadx.plugins.input.dex.utils.DexCheckSum.verify(DexCheckSum.java:22)
	at jadx.plugins.input.dex.DexFileLoader.loadDexReader(DexFileLoader.java:82)
	at jadx.plugins.input.dex.DexFileLoader.load(DexFileLoader.java:67)
	at jadx.plugins.input.dex.DexFileLoader.loadDexFromFile(DexFileLoader.java:50)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at jadx.plugins.input.dex.DexFileLoader.collectDexFiles(DexFileLoader.java:45)
	at jadx.plugins.input.dex.DexInputPlugin.loadFiles(DexInputPlugin.java:37)
	at jadx.plugins.input.dex.DexInputPlugin.loadFiles(DexInputPlugin.java:33)
	at jadx.api.JadxDecompiler.loadInputFiles(JadxDecompiler.java:128)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:112)
	at jadx.gui.JadxWrapper.open(JadxWrapper.java:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### Relevant log output or stacktrace

```java
jadx.plugins.input.dex.DexException: Bad checksum: 0x10691c42, expected: 0xc5263138
	at jadx.plugins.input.dex.utils.DexCheckSum.verify(DexCheckSum.java:22)
	at jadx.plugins.input.dex.DexFileLoader.loadDexReader(DexFileLoader.java:82)
	at jadx.plugins.input.dex.DexFileLoader.load(DexFileLoader.java:67)
	at jadx.plugins.input.dex.DexFileLoader.loadDexFromFile(DexFileLoader.java:50)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at jadx.plugins.input.dex.DexFileLoader.collectDexFiles(DexFileLoader.java:45)
	at jadx.plugins.input.dex.DexInputPlugin.loadFiles(DexInputPlugin.java:37)
	at jadx.plugins.input.dex.DexInputPlugin.loadFiles(DexInputPlugin.java:33)
	at jadx.api.JadxDecompiler.loadInputFiles(JadxDecompiler.java:128)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:112)
	at jadx.gui.JadxWrapper.open(JadxWrapper.java:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Jadx version

1.4.7

**Comment by jpstotz** [comment]
If I remember correctly there is a command-line switch available to ignore bad checksum in DEX files.

**Comment by skylot** [comment]
@mrknow001option to disable dex checksum verification, available in:
- jadx-cli using `-Pdex-input.verify-checksum=no`
- jadx-gui in preferences `Plugins section -> dex input -> verify dex file checksum before load`

**Comment by marzaha** [comment]
```kotlin
 implementation("io.github.skylot:jadx-core:1.5.0-SNAPSHOT")
 implementation("io.github.skylot:jadx-dex-input:1.5.0-SNAPSHOT")
 implementation("io.github.skylot:jadx-plugins-tools:1.5.0-SNAPSHOT")
···

```kotlin
private fun apkFile2java(dexFile: File, outDirPath: String) {
        val jadxArgs = JadxArgs()
        jadxArgs.setInputFile(dexFile)
        jadxArgs.outDir = File(outDirPath)
        jadxArgs.setPluginLoader(JadxExternalPluginsLoader())
        try {
            JadxDecompiler(jadxArgs).use { jadx ->
                jadx.load()
                jadx.save()
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
```

jadx.plugins.input.dex.DexException: Bad checksum: 0xfeb6d6ad, expected: 0xbc3c71fa
	at jadx.plugins.input.dex.utils.DexCheckSum.verify(DexCheckSum.java:22)
	at jadx.plugins.input.dex.DexFileLoader.loadDexReader(DexFileLoader.java:81)
	at jadx.plugins.input.dex.DexFileLoader.load(DexFileLoader.java:66)
	at jadx.plugins.input.dex.DexFileLoader.loadDexFromFile(DexFileLoader.java:49)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at jadx.plugins.input.dex.DexFileLoader.collectDexFiles(DexFileLoader.java:44)
	at jadx.plugins.input.dex.DexInputPlugin.loadFiles(DexInputPlugin.java:40)
	at jadx.plugins.input.dex.DexInputPlugin.loadFiles(DexInputPlugin.java:36)
	at jadx.api.JadxDecompiler.loadInputFiles(JadxDecompiler.java:153)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:119)
	at tools.Dex.apkFile2java(Dex.kt:70)
	at tools.Dex.dex2java(Dex.kt:28)
	at ui.ApkDecompileKt$ApkDecompile$2$2$1$1$1$1.invokeSuspend(ApkDecompile.kt:91)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
