### ISSUE TITLE
[core] decompile to java error

### ISSUE THREAD

**Issue by billpeace** [skylot/jadx#2039]
### Issue details

jadx-gui-1.4.7.249-41d986bd.exe

### Relevant log output or stacktrace

```java
/*  JADX ERROR: Method load error
        jadx.core.utils.exceptions.DecodeException: Load method exception: JavaClassParseException: Unknown opcode: 0xa8 in method: org.apache.batik.util.RunnableQueue.run():void, file: ecloud-plugin-xml2pdf-fop-1.0.0-SNAPSHOT.jar:org/apache/batik/util/RunnableQueue.class
        	at jadx.core.dex.nodes.MethodNode.load(MethodNode.java:166)
        	at jadx.core.dex.nodes.ClassNode.load(ClassNode.java:417)
        	at jadx.core.ProcessClass.process(ProcessClass.java:70)
        	at jadx.core.ProcessClass.generateCode(ProcessClass.java:118)
        	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:391)
        	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:312)
        Caused by: jadx.plugins.input.java.utils.JavaClassParseException: Unknown opcode: 0xa8
        	at jadx.plugins.input.java.data.code.JavaCodeReader.visitInstructions(JavaCodeReader.java:71)
        	at jadx.core.dex.instructions.InsnDecoder.process(InsnDecoder.java:48)
        	at jadx.core.dex.nodes.MethodNode.load(MethodNode.java:156)
        	... 5 more
        */
    @Override // java.lang.Runnable
    public void run() {
        /*
        // Can't load method instructions: Load method exception: JavaClassParseException: Unknown opcode: 0xa8 in method: org.apache.batik.util.RunnableQueue.run():void, file: ecloud-plugin-xml2pdf-fop-1.0.0-SNAPSHOT.jar:org/apache/batik/util/RunnableQueue.class
        */
        throw new UnsupportedOperationException("Method not decompiled: org.apache.batik.util.RunnableQueue.run():void");
    }
```

### Provide sample and class/method full name

The source code：

https://github.com/apache/xmlgraphics-batik/blob/main/batik-util/src/main/java/org/apache/batik/util/RunnableQueue.java

[lib.zip](https://github.com/skylot/jadx/files/13222665/lib.zip)

### Jadx version

jadx-gui-1.4.7.249-41d986bd

**Comment by jpstotz** [comment]
Wow this is really some sort of historic software. The class file of org.apache.batik.util.RunnableQueue in lib.zip is in class file format 45 which means it is Java 1.1 format...

**Comment by skylot** [comment]
@billpeace thank you for report!
Looks like I miss this instruction (`jsr` -[ jump subroutine](https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-6.html#jvms-6.5.jsr)) because it works like dynamic `goto` and it is hard to convert to any exists static instructions. Also, it is not used by modern java compiler.
Anyway, I will give another try to support it.

As a workaround, for now, you can enable `Decompilation -> Use dx/d8 to convert java bytecode` in preferences, d8 works fine for your sample.
