### ISSUE TITLE
Export gradle for AAR files

### ISSUE THREAD

**Issue by Bourne-Koloh** [skylot/jadx#2044]
### Issue details

Click "File" > "Save as Gradle Project" > "Choose Folder" > "Save"

### Relevant log output or stacktrace

```java
Jadx version : 1.4.7.253-2d28da9b
Java version : 17.0.9
Java VM      : Oracle Corporation Java HotSpot(TM) 64-Bit Server VM
Platform     : Windows 11 (10.0 amd64)
Max heap size: 12704 MB

java.lang.IllegalStateException
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at jadx.core.export.ExportGradleTask.run(ExportGradleTask.java:47)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Jadx version

1.4.7.253-2d28da9b

**Comment by skylot** [comment]
@Bourne-Koloh looks like resources file (`.arsc`) not found, can you share apk file you are using?
https://github.com/skylot/jadx/blob/2d28da9b0e2b704a77946dcd5ef409d46944e2b2/jadx-core/src/main/java/jadx/core/export/ExportGradleTask.java#L47

**Comment by skylot** [comment]
> [lib.aar.zip](https://github.com/skylot/jadx/files/13418465/lib.aar.zip)

Oh, thanks! I always forget about AAR files :slightly_frowning_face:

**Comment by carl1990** [comment]
+1 

Jadx version : 1.5.1
Java version : 17.0.8
Java VM      : Oracle Corporation Java HotSpot(TM) 64-Bit Server VM
Platform     : Mac OS X (14.1 aarch64)
Max heap size: 12904 MB
Program args : -Xms128M -XX:MaxRAMPercentage=70.0 -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -Djava.util.Arrays.useLegacyMergeSort=true -Djdk.util.zip.disableZip64ExtraFieldValidation=true -XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED -Dsun.java2d.noddraw=true -Dsun.java2d.d3d=false -Dsun.java2d.ddforcevram=true -Dsun.java2d.ddblit=false -Dswing.useflipBufferStrategy=True

java.lang.IllegalStateException
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at jadx.core.export.ExportGradleTask.run(ExportGradleTask.java:46)
	at jadx.core.utils.tasks.TaskExecutor.wrapTask(TaskExecutor.java:166)
	at jadx.core.utils.tasks.TaskExecutor.runStages(TaskExecutor.java:142)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by skylot** [comment]
Fixed. Please check [latest unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master).
