### ISSUE TITLE
[core] jadx-cli fails to generate code for classes even if the gui version successfully generates them

### ISSUE THREAD

**Issue by nitanmarcel** [skylot/jadx#2053]
### Issue details

While using jadx from the terminal it fails to generate some classes while the gui version does not have any issues with this, on the default settings.

![image](https://github.com/skylot/jadx/assets/41646249/bfc3ab77-cc09-40cf-840b-2bf027396296)

### Relevant log output or stacktrace

```java
cat test/ll/sources/androidx/appcompat/app/AppCompatDialog.json
catjadx.core.utils.exceptions.JadxRuntimeException: Failed to generate code for class: androidx.appcompat.app.AppCompatDialog
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:121)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:383)
	at jadx.core.dex.nodes.ClassNode.getCode(ClassNode.java:331)
Caused by: jadx.core.utils.exceptions.JadxRuntimeException: Code generation error
	at jadx.core.codegen.CodeGen.wrapCodeGen(CodeGen.java:55)
	at jadx.core.codegen.CodeGen.generateJson(CodeGen.java:39)
	at jadx.core.codegen.CodeGen.generate(CodeGen.java:25)
	at jadx.core.ProcessClass.process(ProcessClass.java:77)
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:115)
	... 2 more
Caused by: jadx.core.utils.exceptions.JadxRuntimeException: Not class type: T extends android.view.View
	at jadx.core.dex.info.ClassInfo.checkClassType(ClassInfo.java:53)
	at jadx.core.dex.info.ClassInfo.fromType(ClassInfo.java:31)
	at jadx.core.codegen.json.JsonCodeGen.getTypeAlias(JsonCodeGen.java:213)
	at jadx.core.codegen.json.JsonCodeGen.addMethods(JsonCodeGen.java:151)
	at jadx.core.codegen.json.JsonCodeGen.processCls(JsonCodeGen.java:93)
	at jadx.core.codegen.json.JsonCodeGen.process(JsonCodeGen.java:58)
	at jadx.core.codegen.CodeGen.wrapCodeGen(CodeGen.java:45)
	... 6 more
```
```
package androidx.appcompat.app;

import android.app.Dialog;
import android.content.Context;
import android.content.DialogInterface;
import android.os.Bundle;
import android.util.TypedValue;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup;
import androidx.annotation.IdRes;
import androidx.annotation.LayoutRes;
import androidx.annotation.Nullable;
import androidx.annotation.RestrictTo;
import androidx.appcompat.R;
import androidx.appcompat.view.ActionMode;
import androidx.core.view.KeyEventDispatcher;

/* loaded from: classes.dex */
public class AppCompatDialog extends Dialog implements AppCompatCallback {
    private AppCompatDelegate mDelegate;
    private final KeyEventDispatcher.Component mKeyDispatcher;

    public AppCompatDialog(Context context) {
    }

    public AppCompatDialog(Context context, int i8) {
    }

    /* JADX INFO: Access modifiers changed from: protected */
    public AppCompatDialog(Context context, boolean z7, DialogInterface.OnCancelListener onCancelListener) {
    }

    private static int getThemeResId(Context context, int i8) {
    }

    @Override // android.app.Dialog
    public void addContentView(View view, ViewGroup.LayoutParams layoutParams) {
    }

    @Override // android.app.Dialog, android.content.DialogInterface
    public void dismiss() {
    }

    @Override // android.app.Dialog, android.view.Window.Callback
    }

    @Override // android.app.Dialog
    @Nullable
    public <T extends View> T findViewById(@IdRes int i8) {
    }

    public AppCompatDelegate getDelegate() {
        }
        return this.mDelegate;
    }

    public ActionBar getSupportActionBar() {
    }

    @Override // android.app.Dialog
    @RestrictTo({RestrictTo.Scope.LIBRARY_GROUP_PREFIX})
    public void invalidateOptionsMenu() {;
    }

    /* JADX INFO: Access modifiers changed from: protected */
    @Override // android.app.Dialog
    public void onCreate(Bundle bundle) {
    }

    @Override // android.app.Dialog
    protected void onStop() {
    }

    @Override // androidx.appcompat.app.AppCompatCallback
    public void onSupportActionModeFinished(ActionMode actionMode) {
    }

    @Override // androidx.appcompat.app.AppCompatCallback
    public void onSupportActionModeStarted(ActionMode actionMode) {
    }

    @Override // androidx.appcompat.app.AppCompatCallback
    @Nullable
    public ActionMode onWindowStartingSupportActionMode(ActionMode.Callback callback) {
    }

    @Override // android.app.Dialog
    public void setContentView(@LayoutRes int i8) {
    }

    @Override // android.app.Dialog
    public void setContentView(View view) {
    }

    @Override // android.app.Dialog
    public void setContentView(View view, ViewGroup.LayoutParams layoutParams) {
    }

    @Override // android.app.Dialog
    public void setTitle(int i8) {
    }

    @Override // android.app.Dialog
    public void setTitle(CharSequence charSequence) {
    }

    boolean superDispatchKeyEvent(KeyEvent keyEvent) {
    }

    public boolean supportRequestWindowFeature(int i8) {
    }
}
```

### Jadx version

1.4.7

**Comment by skylot** [comment]
@nitanmarcel looks like a multi-threading issue, so setting threads count to 1 (`--threads-count 1`) may help as a workaround. Also, if possible, please share a sample apk, so I can reproduce this issue.

**Comment by nitanmarcel** [comment]
> @nitanmarcel looks like a multi-threading issue, so setting threads count to 1 (`--threads-count 1`) may help as a workaround. Also, if possible, please share a sample apk, so I can reproduce this issue.

This is the APK I ran jadx on 
https://dumps.tadiphone.dev/dumps/nothing/pong/-/blob/qssi-user-14-UP1A.231005.007-2311021201-release-keys/system_ext/priv-app/NothingLauncher3/NothingLauncher3.apk

**Comment by nitanmarcel** [comment]
> @nitanmarcel looks like a multi-threading issue, so setting threads count to 1 (`--threads-count 1`) may help as a workaround. Also, if possible, please share a sample apk, so I can reproduce this issue.

I ran it with `--threads-count 1` and it didn't really did a difference

**Comment by nitanmarcel** [comment]
`jadx --output-format json -f NothingLauncher3.apk -d out --threads-count 1`

**Comment by nitanmarcel** [comment]
I compiled a test application to see if the issue persists here and it does. I also attached logs and the output directory

[jadxbugtest.zip](https://github.com/skylot/jadx/files/13719998/jadxbugtest.zip)

**Comment by nitanmarcel** [comment]
Ok, it seems that the issue happens when using json output, java works fine.

```
❯ cat java/sources/androidx/compose/runtime/saveable/Saver.java
package androidx.compose.runtime.saveable;
/* compiled from: Saver.kt */
@kotlin.Metadata(d1 = {"\u0000\u0018\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u0000\n\u0002\b\u0004\n\u0002\u0018\u0002\n\u0002\b\u0002\bf\u0018\u0000*\u0004\b\u0000\u0010\u0001*\b\b\u0001\u0010\u0002*\u00020\u00032\u00020\u0003J\u0017\u0010\u0004\u001a\u0004\u0018\u00018\u00002\u0006\u0010\u0005\u001a\u00028\u0001H&¢\u0006\u0002\u0010\u0006J\u001b\u0010\u0007\u001a\u0004\u0018\u00018\u0001*\u00020\b2\u0006\u0010\u0005\u001a\u00028\u0000H&¢\u0006\u0002\u0010\tø\u0001\u0000\u0082\u0002\u0006\n\u0004\b!0\u0001¨\u0006\nÀ\u0006\u0001"}, d2 = {"Landroidx/compose/runtime/saveable/Saver;", "Original", "Saveable", "", "restore", "value", "(Ljava/lang/Object;)Ljava/lang/Object;", "save", "Landroidx/compose/runtime/saveable/SaverScope;", "(Landroidx/compose/runtime/saveable/SaverScope;Ljava/lang/Object;)Ljava/lang/Object;", "runtime-saveable_release"}, k = 1, mv = {1, 8, 0}, xi = 48)
/* loaded from: classes.dex */
public interface Saver<Original, Saveable> {
    Original restore(Saveable r1);

    Saveable save(androidx.compose.runtime.saveable.SaverScope r1, Original r2);
}
~/apk/log 
❯ cat json/sources/androidx/compose/runtime/saveable/Saver.json 
jadx.core.utils.exceptions.JadxRuntimeException: Failed to generate code for class: androidx.compose.runtime.saveable.Saver
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:121)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:383)
	at jadx.core.dex.nodes.ClassNode.getCode(ClassNode.java:331)
Caused by: jadx.core.utils.exceptions.JadxRuntimeException: Code generation error
	at jadx.core.codegen.CodeGen.wrapCodeGen(CodeGen.java:55)
	at jadx.core.codegen.CodeGen.generateJson(CodeGen.java:39)
	at jadx.core.codegen.CodeGen.generate(CodeGen.java:25)
	at jadx.core.ProcessClass.process(ProcessClass.java:77)
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:115)
	... 2 more
Caused by: jadx.core.utils.exceptions.JadxRuntimeException: Not class type: Original
	at jadx.core.dex.info.ClassInfo.checkClassType(ClassInfo.java:53)
	at jadx.core.dex.info.ClassInfo.fromType(ClassInfo.java:31)
	at jadx.core.codegen.json.JsonCodeGen.getTypeAlias(JsonCodeGen.java:213)
	at jadx.core.codegen.json.JsonCodeGen.addMethods(JsonCodeGen.java:151)
	at jadx.core.codegen.json.JsonCodeGen.processCls(JsonCodeGen.java:93)
	at jadx.core.codegen.json.JsonCodeGen.process(JsonCodeGen.java:58)
	at jadx.core.codegen.CodeGen.wrapCodeGen(CodeGen.java:45)
	... 6 more
```

**Comment by skylot** [comment]
@nitanmarcel I fixed this issue.
Unfortunately there are many other issues both in java and json output :slightly_frowning_face:
Anyway, thank you for this report and feel free to open any new issues for json output. At this point, looks like json output not used much, so it may have many not yet reported issues.

**Comment by nitanmarcel** [comment]
> @nitanmarcel I fixed this issue. Unfortunately there are many other issues both in java and json output 🙁 Anyway, thank you for this report and feel free to open any new issues for json output. At this point, looks like json output not used much, so it may have many not yet reported issues.

Thanks. We'll keep an I on any errors

**Comment by trufae** [comment]
Will be good to have a new release with this fix, as long as it's a blocker for bringing back r2jadx at least :) (i'm rewriting it to use the internal qjs engine which is faster and also, better integrated with r2). I can pull the nightly builds or cook a special package for it meanwhile, but i'm just wondering about the eta for a new release so all users can benefit from the fix. thanks!
