### ISSUE TITLE
Stackoverflow for official Periscope app

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#207]
Hi, 
Run the following command:

> jadx --no-replace-consts --show-bad-code --deobf --deobf-use-sourcename --output-dir-src Periscope%20-%20Live%20Video_1.18.1_apk-dl.com/source --output-dir-res Periscope%20-%20Live%20Video_1.18.1_apk-dl.com/res Periscope%20-%20Live%20Video_1.18.1_apk-dl.com.apk 

It will crash with the following exception:

> Exception in thread "main" java.lang.StackOverflowError
> 	at jadx.core.deobf.Deobfuscator.resolveOverridingInternal(Deobfuscator.java:151)
> 	at jadx.core.deobf.Deobfuscator.resolveOverridingInternal(Deobfuscator.java:184)
> 	at jadx.core.deobf.Deobfuscator.resolveOverridingInternal(Deobfuscator.java:184)
> 	at ...

[Periscope%20-%20Live%20Video_1.18.1_apk-dl.com.apk.zip](https://github.com/skylot/jadx/files/1637081/Periscope.20-.20Live.20Video_1.18.1_apk-dl.com.apk.zip) (remove `.zip` from file name)

**Comment by sergey-wowwow** [comment]
@skylot 
I've turned on ``` --deobf ``` option, and a lot of apps are not decompiled because of that exception:
```
Exception in thread "main" java.lang.StackOverflowError
        at jadx.core.deobf.Deobfuscator.resolveOverridingInternal(Deobfuscator.java:150)
        at jadx.core.deobf.Deobfuscator.resolveOverridingInternal(Deobfuscator.java:162)
        at jadx.core.deobf.Deobfuscator.resolveOverridingInternal(Deobfuscator.java:162)
        at jadx.core.deobf.Deobfuscator.resolveOverridingInternal(Deobfuscator.java:162)
        at jadx.core.deobf.Deobfuscator.resolveOverridingInternal(Deobfuscator.java:162)
        at jadx.core.deobf.Deobfuscator.resolveOverridingInternal(Deobfuscator.java:162)
        at jadx.core.deobf.Deobfuscator.resolveOverridingInternal(Deobfuscator.java:162)
        ...
```

**Comment by skylot** [comment]
I rewrite code for resolving overridden methods, I hope it will fix such issues.
