### ISSUE TITLE
[gui]  jadx 1.4.7 open apk  Error decode manifest

### ISSUE THREAD

**Issue by kingouer** [skylot/jadx#2081]
### Issue details

Error decode manifest
java.io.IOException: Expected strings start, expected offset not reachable: 0x464, actual: 0x435c
	at jadx.core.xmlgen.ParserStream.skipToPos(ParserStream.java:132)
	at jadx.core.xmlgen.CommonBinaryParser.parseStringPoolNoType(CommonBinaryParser.java:29)
	at jadx.core.xmlgen.BinaryXMLParser.decode(BinaryXMLParser.java:110)
	at jadx.core.xmlgen.BinaryXMLParser.parse(BinaryXMLParser.java:82)

### Jadx version

1.4.7

### Java version

1.8

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by jpstotz** [comment]
Please provide the APK file you were trying to load. Without the APK file such problems can not be fixed.
