### ISSUE TITLE
Error in debug info parser 

### ISSUE THREAD

**Issue by zdongcoding** [skylot/jadx#209]
java.lang.IllegalArgumentException: position=67106099 length=7368164
	at com.android.dex.Dex.open(Dex.java:174) ~[dx-1.13.jar:na]
	at jadx.core.dex.nodes.DexNode.openSection(DexNode.java:199) ~[jadx-core-0.7.0.jar:na]
	at jadx.core.dex.nodes.parser.DebugInfoParser.<init>(DebugInfoParser.java:51) ~[jadx-core-0.7.0.jar:na]
	at jadx.core.dex.visitors.DebugInfoVisitor.processDebugInfo(DebugInfoVisitor.java:37) ~[jadx-core-0.7.0.jar:na]
	at jadx.core.dex.visitors.DebugInfoVisitor.visit(DebugInfoVisitor.java:26) ~[jadx-core-0.7.0.jar:na]
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:31) [jadx-core-0.7.0.jar:na]
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:17) [jadx-core-0.7.0.jar:na]
	at jadx.core.ProcessClass.process(ProcessClass.java:34) [jadx-core-0.7.0.jar:na]
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:323) [jadx-core-0.7.0.jar:na]
	at jadx.api.JavaClass.decompile(JavaClass.java:62) [jadx-core-0.7.0.jar:na]

**Comment by zdongcoding** [comment]
all method is empty

**Comment by skylot** [comment]
Same error as in #176, please check again in latest [unstable](https://bintray.com/skylot/jadx/unstable#files) version or share a link to problem apk
