### ISSUE TITLE
NullPointerException when parsing AndroidManifest.xml

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#211]
Error:
```
Error decode manifest
java.lang.NullPointerException
	at jadx.core.codegen.CodeWriter.add(CodeWriter.java:98)
	at jadx.core.xmlgen.BinaryXMLParser.parseAttribute(BinaryXMLParser.java:266)
	at jadx.core.xmlgen.BinaryXMLParser.parseElement(BinaryXMLParser.java:241)
	at jadx.core.xmlgen.BinaryXMLParser.decode(BinaryXMLParser.java:124)
	at jadx.core.xmlgen.BinaryXMLParser.parse(BinaryXMLParser.java:83)
	at jadx.api.ResourcesLoader.loadContent(ResourcesLoader.java:114)
	at jadx.api.ResourcesLoader.lambda$loadContent$0(ResourcesLoader.java:98)
	at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:80)
	at jadx.api.ResourcesLoader.loadContent(ResourcesLoader.java:98)
	at jadx.api.ResourceFile.loadContent(ResourceFile.java:53)
```

APK: 
[Hulu Stream TV Movies more_v3.17.1.250381_apkpure.com.apk.zip](https://github.com/skylot/jadx/files/1646071/Hulu.Stream.TV.Movies.more_v3.17.1.250381_apkpure.com.apk.zip) (remove `.zip` from name). 

Looks like that none of the resources is correctly decompiled, but I'm able to successfully install this app on the emulator

**Comment by sergey-wowwow** [comment]
If possible, please make it the highest priority task among my issues, because it's thrown in a half of APKs I'm decompiling.

**Comment by skylot** [comment]
I commit a fix for this issue. Can you check it?

**Comment by sergey-wowwow** [comment]
Hi, It works great, thanks!
It passes all my tests it previously failed. If I notice a bug in processing resources I will let know, but looks like it's fine now
