### ISSUE TITLE
Jadx fails to decompile some obfuscated methods

### ISSUE THREAD

**Issue by CrossSiteBit** [skylot/jadx#213]
Greetings,
I've worked in collaboration with my university on studying some Android apps and JADX 
worked well for hundreds of obfuscated classes. Unluckily few very important methods 
were not decompiled correctly using the latest official Jadx release. The problem 
seems to be caused by some advanced obfuscation by Dexguard.
I did reverse engineered the app Skrill taken from the Google PlayStore ( 
https://play.google.com/store/apps/details?id=com.moneybookers.skrillpayments ).
The class TrustDefenderMobile.java (called by Jadx ao.java) from the package 
"com.threatmetrix" had some of the most important methods not correctly compiled 
because of some Dexguard tricks.

The error on the resulting decompiled code looks like this:
![jadx error on bug](https://user-images.githubusercontent.com/35697108/35232057-bb7db060-ff9a-11e7-8504-261612a73de5.png)

The error on console is:
16:06:47 ERROR - JadxRuntimeException in pass: BlockFinish in method: 
com.threatmetrix.TrustDefenderMobile.ao.d():void
jadx.core.utils.exceptions.JadxRuntimeException: Can't find block by offset: 0x0066 in 
list []

And the warning raised by Jadx is:
Finally extract failed: remBlock pred: B:54:0x012b, [B:53:0x011d, B:62:0x0160], 
method: com.threatmetrix.TrustDefenderMobile.ao.d():void

We then identified that the problem is caused by these 3 lines in 
BlockFinallyExtract.applyRemove() method:
![3 lines jadx bug](https://user-images.githubusercontent.com/35697108/35232074-ce721256-ff9a-11e7-8a06-04c93000936d.png)

The block this class is examining does have somehow more than 1 predecessor and the IF 
is executed.

We did found a workaround but not a consistent permantent fix: commenting these 3 
lines of code allowed us to decompile the bugged methods with no apparent problems.

Hope this will help improving Jadx, even if against the obfuscators is always a 
difficult battle.

**Comment by skylot** [comment]
Hello, can you tell me version of app you decompile, because Google Play version 2.4.8 don't have such method. Or you can just upload apk here.

**Comment by enovella** [comment]
Version and hash of the APK please

**Comment by enovella** [comment]
Hi @CrossSiteBit,

what are you based on to say that's protected with DexGuard and not ProGuard?

Cheers

**Comment by enovella** [comment]
Similar issue https://github.com/skylot/jadx/issues/199

**Comment by CrossSiteBit** [comment]
Hello guys, sorry for the late response.
@skylot from the Manifest file: versionCode="20170512" and versionName="2.3.1"
@enovella I'm actually not sure if it's DexGuard or ProGuard. I thought it was DexGuard has I've seen some of those tricks using it. I must say that I have no other proof that it is actually DexGuard.

**Comment by skylot** [comment]
@CrossSiteBit thank you!
I found correct apk file: [com.moneybookers.skrillpayments_2.3.1.apk.zip](https://github.com/skylot/jadx/files/1657133/com.moneybookers.skrillpayments_2.3.1.apk.zip) (remove `.zip` from file name)
The problem, as you guess, is a issue in finally block extractor. It fails to detect similar code due to complex if/else structure. As easy workaround you can disable this pass by commenting:
``` java
	passes.add(new BlockFinallyExtract());
```
in `jadx-core/src/main/java/jadx/core/Jadx.java`
Without it jadx will generate correct code but with duplicated instruction (java compiler copied finally block in every catch blocks and other placed which leads to exit from try/catch clause) 

I will try to fix this, but it will be not easy because this method is big.
I made [CFG](https://user-images.githubusercontent.com/118523/35293800-dd33a08e-0085-11e8-80b1-c86e66ad779c.png) for this method, sometimes it helps to undestard what method do if jadx failed to restructure the code. I love CFGs :)

**Comment by sergey-wowwow** [comment]
In my case the most important methods are always not decompiled too lol even if they are short.
@skylot why it happens so? Because of tricky constructions or because of some not implemented bytes codes (if something new was added in Java8/9)?

**Comment by skylot** [comment]
@sergey-wowwow most of problems caused by try/catch blocks, it generates complex control flow graphs and that broke restructure of the method. Because catches affects even simple code with adding jumps to exception handler from any instruction. And jadx not good at dealing with them.

As for new instructions: 2 new invoke types was added to Dex version 38, but as soon as this version supported only on Android 8, I don't think that some apps use it right now. But if you try to decompile some jar with lambdas using java 8, jadx will fail, because it not support them right now, and I am still working on this issue.

**Comment by CrossSiteBit** [comment]
@skylot No problem, I knew it was something about the jumps of the catch blocks. I suppose a jump of one of these blocks goes backward (on a previous, already examined block) and Jadx doesn't like that.
Your CFG Graph is scarying and beautiful at the same time!

**Comment by nitrocode** [comment]
I'm having the same issue and https://github.com/skylot/jadx/issues/159 seems similar.

I tried commenting out [Jadx.java Line #65](https://github.com/skylot/jadx/blob/master/jadx-core/src/main/java/jadx/core/Jadx.java#L65) as @skylot suggested and recompiling. I ran `jadx` against the apk and this error returned over 16k times!

```
ERROR - NullPointerException in pass: RegionMakerVisitor in method: android.support.a.c.a.<init>(android.support.a.e):void, dex:
java.lang.NullPointerException: null
    at jadx.core.dex.instructions.IfNode.invertCondition(IfNode.java:50)
    at jadx.core.dex.regions.conditions.Compare.invert(Compare.java:32)
    at jadx.core.dex.regions.conditions.IfCondition.invert(IfCondition.java:116)
    at jadx.core.dex.regions.conditions.IfInfo.invert(IfInfo.java:36)
    at jadx.core.dex.visitors.regions.RegionMaker.processIf(RegionMaker.java:617)
    at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:127)
    at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:94)
    at jadx.core.dex.visitors.regions.RegionMakerVisitor.visit(RegionMakerVisitor.java:49)
    at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:31)
    at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:17)
    at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
    at jadx.core.ProcessClass.process(ProcessClass.java:34)
    at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:282)
    at jadx.api.JavaClass.decompile(JavaClass.java:62)
    at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:200)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by aquadevtechie** [comment]
NullPointerException in pass: RegionMakerVisitor occurs also jadx.core.utils.exceptions.JadxRuntimeException: Exception block dominator not found occurs as well
