### ISSUE TITLE
[gui] An error occurs when setting a breakpoint

### ISSUE THREAD

**Issue by Airsku** [skylot/jadx#2130]
### Issue details

```
Jadx version : 1.4.7
Java version : 19.0.2
Java VM      : Oracle Corporation OpenJDK 64-Bit Server VM
Platform     : Windows 11 (10.0 amd64)
Max heap size: 13952 MB

java.lang.NullPointerException: Cannot invoke "org.fife.ui.rtextarea.Gutter.removeTrackingIcon(org.fife.ui.rtextarea.GutterIconInfo)" because the return value of "jadx.gui.ui.codearea.SmaliArea$DebugModel.access$700(jadx.gui.ui.codearea.SmaliArea$DebugModel)" is null
	at jadx.gui.ui.codearea.SmaliArea$DebugModel$BreakpointLine.setDisabled(SmaliArea.java:399)
	at jadx.gui.ui.codearea.SmaliArea$DebugModel.setBreakpoint(SmaliArea.java:284)
	at jadx.gui.ui.codearea.SmaliArea$DebugModel$1.actionPerformed(SmaliArea.java:259)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(Unknown Source)
	at java.desktop/javax.swing.JComponent.processKeyBinding(Unknown Source)
	at java.desktop/javax.swing.JComponent.processKeyBindings(Unknown Source)
	at java.desktop/javax.swing.JComponent.processKeyEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```

### Jadx version

Jadx version : 1.4.7

### Java version

Java version : 19.0.2

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by MrIkso** [comment]
@skylot  same as https://github.com/skylot/jadx/issues/1755
