### ISSUE TITLE
jadx.plugins.input.java.utils.JavaClassParseException: Unknown opcode: 0xa8

### ISSUE THREAD

**Issue by yooo1999** [skylot/jadx#2138]
### Issue details

When decompil jar with jadx cli in Windows

```
ERROR - [225] Dependency scan failed in method: XXXXXXXXX.get():byte[], file: xxxx.jar:yyyyyy.class
jadx.plugins.input.java.utils.JavaClassParseException: Unknown opcode: 0xa8
        at jadx.plugins.input.java.data.code.JavaCodeReader.visitInstructions(JavaCodeReader.java:71)
        at jadx.core.dex.visitors.usage.UsageInfoVisitor.processInstructions(UsageInfoVisitor.java:82)
        at jadx.core.dex.visitors.usage.UsageInfoVisitor.processMethod(UsageInfoVisitor.java:67)
        at jadx.core.dex.visitors.usage.UsageInfoVisitor.processClass(UsageInfoVisitor.java:56)
        at jadx.core.dex.visitors.usage.UsageInfoVisitor.init(UsageInfoVisitor.java:41)
        at jadx.core.dex.nodes.RootNode.runPreDecompileStage(RootNode.java:282)
        at jadx.api.JadxDecompiler.load(JadxDecompiler.java:118)
        at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:48)
        at jadx.cli.JadxCLI.execute(JadxCLI.java:36)
        at jadx.cli.JadxCLI.main(JadxCLI.java:20)

```

```

java --version
openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment Microsoft-25199 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Microsoft-25199 (build 11.0.12+7, mixed mode)
```

### Jadx version

1.4.7

### Java version

openjdk 11.0.12 2021-07-20

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by jpstotz** [comment]
Please switch to the latest [unstable build](https://nightly.link/skylot/jadx/workflows/build-artifacts/master), it already supports opcode `0xa8`.
