### ISSUE TITLE
Can't encode constant CLASS as encoded value

### ISSUE THREAD

**Issue by yooo1999** [skylot/jadx#2139]
### Issue details

When decompile jar with jadx cli in Windows

```
ERROR - Dependency scan failed at insn: 0x0372: INVOKE_CUSTOM in method: io.vavr.CheckedFunction3.$deserializeLambda$(java.lang.invoke.SerializedLambda):java.lang.Object, file: XXXXXX.jar:io/YYY/CheckedFunction3.class
jadx.plugins.input.java.utils.JavaClassParseException: Can't encode constant CLASS as encoded value
        at jadx.plugins.input.java.data.ConstPoolReader.readAsEncodedValue(ConstPoolReader.java:230)
        at jadx.plugins.input.java.data.ConstPoolReader.resolveMethodCallSite(ConstPoolReader.java:117)
        at jadx.plugins.input.java.data.ConstPoolReader.getCallSite(ConstPoolReader.java:97)
        at jadx.plugins.input.java.data.code.JavaInsnData.getIndexAsCallSite(JavaInsnData.java:168)
        at jadx.plugins.input.java.data.code.decoders.InvokeDecoder.decode(InvokeDecoder.java:32)
        at jadx.plugins.input.java.data.code.JavaInsnData.decode(JavaInsnData.java:46)
        at jadx.core.dex.visitors.usage.UsageInfoVisitor.processInsn(UsageInfoVisitor.java:157)
        at jadx.core.dex.visitors.usage.UsageInfoVisitor.lambda$processInstructions$0(UsageInfoVisitor.java:114)
        at jadx.plugins.input.java.data.code.JavaCodeReader.visitInstructions(JavaCodeReader.java:81)
        at jadx.core.dex.visitors.usage.UsageInfoVisitor.processInstructions(UsageInfoVisitor.java:112)
        at jadx.core.dex.visitors.usage.UsageInfoVisitor.processMethod(UsageInfoVisitor.java:97)
        at jadx.core.dex.visitors.usage.UsageInfoVisitor.processClass(UsageInfoVisitor.java:86)
        at jadx.core.dex.visitors.usage.UsageInfoVisitor.buildUsageData(UsageInfoVisitor.java:71)
        at jadx.core.dex.visitors.usage.UsageInfoVisitor.init(UsageInfoVisitor.java:55)
        at jadx.core.dex.nodes.RootNode.runPreDecompileStage(RootNode.java:334)
        at jadx.api.JadxDecompiler.load(JadxDecompiler.java:128)
        at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:51)
        at jadx.cli.JadxCLI.execute(JadxCLI.java:38)
        at jadx.cli.JadxCLI.main(JadxCLI.java:22)
```

```
java --version
openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment Microsoft-25199 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Microsoft-25199 (build 11.0.12+7, mixed mode)
```

### Jadx version

jadx-1.4.7.304-43c082e4

### Java version

openjdk 11.0.12 2021-07-20

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by skylot** [comment]
Fixed.

**Comment by yooo1999** [comment]
@skylot So now more function will decompiled from the jar? 
How can I download that compiled jadx ?

**Comment by skylot** [comment]
> So now more function will decompiled from the jar?

Yes

> How can I download that compiled jadx ?

Download [latest unstable build.](https://nightly.link/skylot/jadx/workflows/build-artifacts/master)
