### ISSUE TITLE
[feature]  Show options of --log-level instead exception

### ISSUE THREAD

**Issue by yooo1999** [skylot/jadx#2140]
### Describe your idea

If I put wrong log level
`c:\Users\T\Downloads\jadx-1.4.7.305-8f969d4e\bin\jadx.bat --log-level ASDASD`

I got exception
```
ERROR - Process error:
java.lang.IllegalArgumentException: 'ASDASD' is unknown, possible values are: quiet, progress, error, warn, info, debug
        at jadx.cli.JadxCLIArgs$BaseEnumConverter.convert(JadxCLIArgs.java:629)
        at jadx.cli.JadxCLIArgs$BaseEnumConverter.convert(JadxCLIArgs.java:614)
        at com.beust.jcommander.JCommander.convertValue(JCommander.java:1406)
        at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:249)
        at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:951)
        at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:932)
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:762)
        at com.beust.jcommander.JCommander.parse(JCommander.java:368)
        at com.beust.jcommander.JCommander.parse(JCommander.java:347)
        at jadx.cli.JCommanderWrapper.parse(JCommanderWrapper.java:43)
        at jadx.cli.JadxCLIArgs.processArgs(JadxCLIArgs.java:257)
        at jadx.cli.JadxCLI.execute(JadxCLI.java:37)
        at jadx.cli.JadxCLI.main(JadxCLI.java:22)
```
Instead of that you can simply show the options of log level

**Comment by skylot** [comment]
Fixed
