### ISSUE TITLE
JADX: method processing error

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#218]
Exception:
```java
    private final void handleIntent(android.content.Intent r1) {
        /* JADX: method processing error */
/*
Error: jadx.core.utils.exceptions.DecodeException: Load method exception in method: com.retailzipline.mobile.zipline.dashboard.DashboardActivity.handleIntent(android.content.Intent):void
	at jadx.core.dex.nodes.MethodNode.load(MethodNode.java:116)
	at jadx.core.dex.nodes.ClassNode.load(ClassNode.java:249)
	at jadx.core.ProcessClass.process(ProcessClass.java:31)
	at jadx.core.ProcessClass.processDependencies(ProcessClass.java:56)
	at jadx.core.ProcessClass.process(ProcessClass.java:39)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:323)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:226)
Caused by: java.lang.NullPointerException
*/
        /*
        r0 = this;
        r2 = 0;
        r0 = r6;
        if (r0 == 0) goto L_0x0024;
    L_0x0004:
        r3 = r0.getAction();
    L_0x0008:
        if (r3 != 0) goto L_0x0026;
    L_0x000a:
        if (r0 == 0) goto L_0x0010;
    L_0x000c:
        r2 = r0.getData();
    L_0x0010:
        r1 = java.lang.String.valueOf(r2);
        r2 = r5.presenter;
        if (r2 != 0) goto L_0x001d;
    L_0x0018:
        r3 = "presenter";
        kotlin.jvm.internal.Intrinsics.throwUninitializedPropertyAccessException(r3);
    L_0x001d:
        r2.loadURL(r1);
        return;
    L_0x0024:
        r3 = r2;
        goto L_0x0008;
    L_0x0026:
        r4 = r3.hashCode();
        switch(r4) {
            case -1423083301: goto L_0x002e;
            case 1660302679: goto L_0x0043;
            default: goto L_0x002d;
        };
    L_0x002d:
        goto L_0x000a;
    L_0x002e:
        r4 = "ACTION_SHOW_DASHBOARD";
        r3 = r3.equals(r4);
        if (r3 == 0) goto L_0x000a;
    L_0x0036:
        r2 = r5.presenter;
        if (r2 != 0) goto L_0x003f;
    L_0x003a:
        r3 = "presenter";
        kotlin.jvm.internal.Intrinsics.throwUninitializedPropertyAccessException(r3);
    L_0x003f:
        r2.loadDashBoardScreen();
        goto L_0x0020;
    L_0x0043:
        r4 = "ACTION_SHOW_PUSH_NOTIFICATION";
        r3 = r3.equals(r4);
        if (r3 == 0) goto L_0x000a;
        r2 = r0.getExtras();
        r3 = "EXTRA_KEY_TARGET_URL";
        r2 = r2.get(r3);
        r1 = r2.toString();
        r2 = r5.presenter;
        if (r2 != 0) goto L_0x0062;
        r3 = "presenter";
        kotlin.jvm.internal.Intrinsics.throwUninitializedPropertyAccessException(r3);
        r2.loadPushNotificationURL(r1);
        goto L_0x0020;
        */
        throw new UnsupportedOperationException("Method not decompiled: com.retailzipline.mobile.zipline.dashboard.DashboardActivity.handleIntent(android.content.Intent):void");
    }
```

Method ``` com.retailzipline.mobile.zipline.dashboard.DashboardActivity.handleIntent(android.content.Intent):void ```

APK: 
[Zipline.apk.zip](https://github.com/skylot/jadx/files/1678111/Zipline.apk.zip)

**Comment by skylot** [comment]
This is strange but in latest unstable jadx I don't get this exception.
There are error in incorrect switch cases and this method marked as inconsistent, but I can see the code with option `--show-bad-code`: 
```java
    private final void handleIntent(Intent intent) {
        DashboardPresenter dashboardPresenter;
        String targetURL;
        Object obj = null;
        Intent it = intent;
        String action = it != null ? it.getAction() : null;
        if (action != null) {
            switch (action.hashCode()) {
                case -1423083301:
                    if (action.equals(ACTION_SHOW_DASHBOARD)) {
                        dashboardPresenter = this.presenter;
                        if (dashboardPresenter == null) {
                            Intrinsics.throwUninitializedPropertyAccessException("presenter");
                        }
                        dashboardPresenter.loadDashBoardScreen();
                        break;
                    }
                case 1660302679:
                    if (action.equals(ACTION_SHOW_PUSH_NOTIFICATION)) {
                        targetURL = it.getExtras().get(EXTRA_KEY_TARGET_URL).toString();
                        dashboardPresenter = this.presenter;
                        if (dashboardPresenter == null) {
                            Intrinsics.throwUninitializedPropertyAccessException("presenter");
                        }
                        dashboardPresenter.loadPushNotificationURL(targetURL);
                        break;
                    }
                default:
            }
        }
        if (it != null) {
            obj = it.getData();
        }
        targetURL = String.valueOf(obj);
        dashboardPresenter = this.presenter;
        if (dashboardPresenter == null) {
            Intrinsics.throwUninitializedPropertyAccessException("presenter");
        }
        dashboardPresenter.loadURL(targetURL);
    }
```
Can you check again in latest version?

P.S Need to implement switch case for strings :)

**Comment by sergey-wowwow** [comment]
Hi, looks like with that option it works good, thanks!

**Comment by sergey-wowwow** [comment]
Can you looks at ``` com.bumptech.glide.load.engine.DecodeJob.run() ```? But looks like known issue with try-catches

**Comment by AhmadNemati** [comment]
is it implemented -

> -show-bad-code

 in gui mode?

**Comment by Anderson-JA** [comment]
Tengo un problema parecido y ninguna de las formas que he intentado a dado solución.

Por favor ayudarme si tienen otra forma de hacerlo.


[sincroniza.zip](https://github.com/skylot/jadx/files/3282392/sincroniza.zip)

Esta es la APK, alguno de sus funciones mas importantes no ha des-compilado de la mejor manera y son de urgente necesidad.
