### ISSUE TITLE
[core] JadxRuntimeException: Failed to find switch 'out' block

### ISSUE THREAD

**Issue by pubiqq** [skylot/jadx#2246]
### Relevant log output or stacktrace

```java
jadx.core.utils.exceptions.JadxRuntimeException: Failed to find switch 'out' block (already processed)
  at jadx.core.dex.visitors.regions.RegionMaker.calcSwitchOut(RegionMaker.java:924)
  at jadx.core.dex.visitors.regions.RegionMaker.processSwitch(RegionMaker.java:798)
  at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:157)
  at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:91)
  at jadx.core.dex.visitors.regions.RegionMaker.makeEndlessLoop(RegionMaker.java:411)
  at jadx.core.dex.visitors.regions.RegionMaker.processLoop(RegionMaker.java:201)
  at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:135)
  at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:91)
  at jadx.core.dex.visitors.regions.RegionMakerVisitor.visit(RegionMakerVisitor.java:52)
```

### Provide sample and class/method full name

<details><summary>Test</summary>
<p>

```java
package jadx.tests.integration.switches;

import jadx.tests.api.IntegrationTest;
import jadx.tests.api.utils.assertj.JadxAssertions;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class TestSwitchInLoop3 extends IntegrationTest {
    public static class TestCls {
        public int test(int k) {
            int a = 0;
            while (true) {
                int x = 0;  // <= the only difference from TestSwitchInLoop.java
                switch (k) {
                    case 0:
                        return a;
                    default:
                        a++;
                        k >>= 1;
                }
            }
        }

        public void check() {
            assertThat(test(1)).isEqualTo(1);
        }
    }

    @Test
    public void test() {
        JadxAssertions.assertThat(getClassNode(TestCls.class))
                .code()
                .containsOne("switch (k) {")
                .containsOne("case 0:")
                .containsOne("return a;")
                .containsOne("default:")
                .containsOne("a++;")
                .containsOne("k >>= 1;");
    }
}
```

</p>
</details> 

### Jadx version

1.5.0

**Comment by skylot** [comment]
@pubiqq thank you for test case!
I commit a fix, but I don't think it is general enough to resolve similar cases. So if you find another simple case, fill free to share :slightly_smiling_face:

Related issues: #2054, #826
