### ISSUE TITLE
[core] java.lang.NullPointerException: Cannot read field "wordsInUse" because "set" is null

### ISSUE THREAD

**Issue by pubiqq** [skylot/jadx#2247]
### Relevant log output or stacktrace

```java
java.lang.NullPointerException: Cannot read field "wordsInUse" because "set" is null
    at java.base/java.util.BitSet.or(BitSet.java:943)
    at jadx.core.utils.BlockUtils.getPathCross(BlockUtils.java:772)
    at jadx.core.utils.BlockUtils.getPathCross(BlockUtils.java:851)
    at jadx.core.dex.visitors.regions.IfMakerHelper.restructureIf(IfMakerHelper.java:91)
    at jadx.core.dex.visitors.regions.RegionMaker.processIf(RegionMaker.java:712)
    at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:152)
    at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:91)
    at jadx.core.dex.visitors.regions.RegionMaker.processIf(RegionMaker.java:736)
    at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:152)
    at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:91)
    at jadx.core.dex.visitors.regions.RegionMakerVisitor.visit(RegionMakerVisitor.java:52)
```

### Provide sample and class/method full name

<details><summary>Smali</summary>
<p>

```
.method public static a(Landroid/app/Application;I)Z
    .registers 5

    sget v0, Landroid/os/Build$VERSION;->SDK_INT:I

    const/16 v1, 0x1d

    const/4 v2, 0x0

    if-lt v0, v1, :cond_1b

    const-string v0, "custom"

    invoke-static {v0}, LcB5;->b(Ljava/lang/String;)Z

    move-result v0

    if-nez v0, :cond_10

    goto :goto_1b

    :cond_10
    :try_start_10
    invoke-virtual {p0}, Landroid/content/Context;->getResources()Landroid/content/res/Resources;

    move-result-object p0

    invoke-virtual {p0, p1}, Landroid/content/res/Resources;->getInteger(I)I

    move-result p0

    :try_end_18
    .catch Ljava/lang/Exception; {:try_start_10 .. :try_end_18} :catch_1b

    if-eqz p0, :cond_1b

    const/4 v2, 0x1

    :catch_1b
    :cond_1b
    :goto_1b
    return v2
.end method
```

</p>
</details> 

### Jadx version

1.5.0

**Comment by skylot** [comment]
Fixed
