### ISSUE TITLE
XMLGen: Decode error: Type: 0xffff not yet implemented, position: 0x1b4f2

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#225]
Exception in ``` AndroidManifest.xml ```:
```
Error decode manifest
java.io.IOException: Decode error: Type: 0xffff not yet implemented, position: 0x1b4f2
	at jadx.core.xmlgen.CommonBinaryParser.die(CommonBinaryParser.java:97)
	at jadx.core.xmlgen.BinaryXMLParser.decode(BinaryXMLParser.java:138)
	at jadx.core.xmlgen.BinaryXMLParser.parse(BinaryXMLParser.java:90)
	at jadx.api.ResourcesLoader.loadContent(ResourcesLoader.java:99)
	at jadx.api.ResourcesLoader.lambda$loadContent$0(ResourcesLoader.java:83)
	at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:72)
	at jadx.api.ResourcesLoader.loadContent(ResourcesLoader.java:83)
	at jadx.api.ResourceFile.loadContent(ResourceFile.java:53)
```

APK: http://dl.apk-cloud.com/dl3/apk/2018/1/30/com.xiaomi.smarthome_60727.apk?id=com.xiaomi.smarthome&f=Mi%20Home_5.1.1_apk-dl.com.apk&dl=2

**Comment by gpedro** [comment]
same problem here!
> Caused by: java.io.IOException: Decode error: Type: 0xffff not yet implemented, position: 0x1e32

**Comment by kmayoral** [comment]
Just wanted to say thank you for this fix, it worked for me!
