### ISSUE TITLE
[gui] -java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0

### ISSUE THREAD

**Issue by chancerly** [skylot/jadx#2256]
### Issue details

ubuntu 22.04，open the jadx-gui，then close the pc screen, after open the screen, pop many error window.
Jadx version : 1.5.0
Java version : 11.0.23
Java VM      : Ubuntu OpenJDK 64-Bit Server VM
Platform     : Linux (6.5.0-44-generic amd64)
Max heap size: 30688 MB
Program args : -Xms128M -XX:MaxRAMPercentage=70.0 -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -Djava.util.Arrays.useLegacyMergeSort=true -Djdk.util.zip.disableZip64ExtraFieldValidation=true -XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED

java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
	at java.desktop/sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:75)
	at java.desktop/sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:122)
	at java.desktop/java.awt.GraphicsConfiguration.createCompatibleVolatileImage(GraphicsConfiguration.java:307)
	at java.desktop/java.awt.GraphicsConfiguration.createCompatibleVolatileImage(GraphicsConfiguration.java:241)
	at java.desktop/javax.swing.RepaintManager.getVolatileOffscreenBuffer(RepaintManager.java:1098)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1543)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:262)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1060)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:78)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:115)
	at java.desktop/java.awt.Container.paint(Container.java:2002)
	at java.desktop/java.awt.Window.paint(Window.java:3940)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:876)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1890)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

### Jadx version

1.5.0

### Java version

11.0.23

### OS

- [ ] Windows
- [X] Linux
- [ ] macOS

**Comment by jpstotz** [comment]
What do you mean by "close the pc screen" - are you talking about a laptop and you close the lid so that the display touches the keyboard? 

Most likely you are facing a Java bug: https://bugs.openjdk.org/browse/JDK-8287403

**Comment by chancerly** [comment]
> What do you mean by "close the pc screen" - are you talking about a laptop and you close the lid so that the display touches the keyboard?
> 
> Most likely you are facing a Java bug: https://bugs.openjdk.org/browse/JDK-8287403

yes，just like you said. but I can not solve it. through I update jdk to 21.

**Comment by zhujian198** [comment]
On Ubuntu 24.04 with JDK 21 or 23, jadx 1.5.0–1.5.2 crashes with java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0 after screen sleep/resume, whereas 1.4.7 works fine.
