### ISSUE TITLE
[core] Jadx on AndroidMainFest.xml decompilation issue of the APK

### ISSUE THREAD

**Issue by csasd4234234** [skylot/jadx#2290]
### Issue details

When I use jadx to decompile some apks, I find that the AndroidMainFest.xml cannot be parsed correctly, and when I perform dynamic debugging of the apk, jadx prompts not found app package. But I use GDA and JEB to parse AndroidMainFest.xml files normally.

### Relevant log output or stacktrace

```java
Error decode manifest
java.io.IOException: Decode error: startNS's attributeSize is not 0x14, position: 0x67fc
	at jadx.core.xmlgen.CommonBinaryParser.die(CommonBinaryParser.java:39)
	at jadx.core.xmlgen.BinaryXMLParser.parseElement(BinaryXMLParser.java:269)
	at jadx.core.xmlgen.BinaryXMLParser.decode(BinaryXMLParser.java:132)
	at jadx.core.xmlgen.BinaryXMLParser.parse(BinaryXMLParser.java:87)
```

### Provide sample and class/method full name

Error decode manifest
java.io.IOException: Decode error: startNS's attributeSize is not 0x14, position: 0x67fc
	at jadx.core.xmlgen.CommonBinaryParser.die(CommonBinaryParser.java:39)
	at jadx.core.xmlgen.BinaryXMLParser.parseElement(BinaryXMLParser.java:269)
	at jadx.core.xmlgen.BinaryXMLParser.decode(BinaryXMLParser.java:132)
	at jadx.core.xmlgen.BinaryXMLParser.parse(BinaryXMLParser.java:87)

### Jadx version

1.5.0

**Comment by csasd4234234** [comment]
I'm sorry I can't provide the app for some reason, but I'm guessing that some special characters in the app are used as the file name to cause the jadx compilation to fail.
![Uploading 2.png…]()

**Comment by jpstotz** [comment]
@csasd4234234 Sepecial characters in filename is something I can definitely exclude as cause. The error is about the binary content. But please text the [latest unstable version](https://nightly.link/skylot/jadx/workflows/build-artifacts/master), I am pretty sure that this problem has been already solved.

**Comment by jpstotz** [comment]
No user feedback
