### ISSUE TITLE
JADX: method processing error: NoSuchElementException

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#230]
Hi, getting new exception:
```java
    private void doProcessIntent(android.content.Intent r22) {
        /* JADX: method processing error */
/*
Error: java.util.NoSuchElementException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1496)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1517)
	at jadx.core.dex.visitors.blocksmaker.BlockFinallyExtract.applyRemove(BlockFinallyExtract.java:537)
	at jadx.core.dex.visitors.blocksmaker.BlockFinallyExtract.extractFinally(BlockFinallyExtract.java:176)
	at jadx.core.dex.visitors.blocksmaker.BlockFinallyExtract.processExceptionHandler(BlockFinallyExtract.java:81)
	at jadx.core.dex.visitors.blocksmaker.BlockFinallyExtract.visit(BlockFinallyExtract.java:52)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:31)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:17)
	at jadx.core.ProcessClass.process(ProcessClass.java:34)
	at jadx.core.ProcessClass.processDependencies(ProcessClass.java:56)
	at jadx.core.ProcessClass.process(ProcessClass.java:39)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:282)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:200)
*/
```

Method: ``` com.silentcircle.silentphone2.activities.DialerActivityInternal.doProcessIntent() ```

APK: 
[Silent Phone private calls_v6.1.1_apkpure.com.apk.zip](https://github.com/skylot/jadx/files/1722235/Silent.Phone.private.calls_v6.1.1_apkpure.com.apk.zip)

**Comment by sergey-wowwow** [comment]
And in the same APK in ``` com.silentcircle.messaging.services.SCloudService ``` tons of errors ``` SSA rename variables already executed ```

**Comment by sergey-wowwow** [comment]
Everything is fixed! Thanks!
