### ISSUE TITLE
[core] Mapping export failed

### ISSUE THREAD

**Issue by Gstalker** [skylot/jadx#2327]
### Issue details

Export mapping from a existing jadx project failed

### Relevant log output or stacktrace

```java
Jadx version : 1.5.0
Java version : 22.0.1
Java VM      : Homebrew OpenJDK 64-Bit Server VM
Platform     : Mac OS X (14.6.1 aarch64)
Max heap size: 22944 MB
Program args : -Xms128M -XX:MaxRAMPercentage=70.0 -Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true -Djava.util.Arrays.useLegacyMergeSort=true -Djdk.util.zip.disableZip64ExtraFieldValidation=true -XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.lang=ALL-UNNAMED

java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map$Entry.getValue()" is null
	at jadx.plugins.mappings.save.MappingExporter.exportMappings(MappingExporter.java:238)
	at jadx.gui.plugins.mappings.RenameMappingsGui.lambda$saveInBackground$11(RenameMappingsGui.java:247)
	at jadx.core.utils.tasks.TaskExecutor.wrapTask(TaskExecutor.java:166)
	at jadx.core.utils.tasks.TaskExecutor.runStages(TaskExecutor.java:142)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

### Jadx version

1.5.0

**Comment by Gstalker** [comment]
https://github.com/skylot/jadx/issues/2226
solved by compile jadx from latest commit, this issue is closed.
