### ISSUE TITLE
Error when opening APK, no subfolders nor decompiled code is shown

### ISSUE THREAD

**Issue by enovella** [skylot/jadx#233]
**Exception:**
```java
INFO  - loading ...
ERROR - Error load file: /tmp/087af5aacab8fc8bc7b1dcb7a138c3552d175c74b496056893299bc437422f95.apk
jadx.core.utils.exceptions.JadxRuntimeException: Error load file: /tmp/087af5aacab8fc8bc7b1dcb7a138c3552d175c74b496056893299bc437422f95.apk
	at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:126)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:87)
	at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:34)
	at jadx.gui.ui.MainWindow.openFile(MainWindow.java:169)
	at jadx.gui.ui.MainWindow.openFile(MainWindow.java:162)
	at jadx.gui.ui.MainWindow.open(MainWindow.java:124)
	at jadx.gui.JadxGUI.lambda$main$0(JadxGUI.java:27)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.android.dex.DexException: Unexpected magic: [0x9b, 0x9a, 0x87, 0xf5, 0xcf, 0xcc, 0xca, 0xff]
	at com.android.dex.TableOfContents.readHeader(TableOfContents.java:86)
	at com.android.dex.TableOfContents.readFrom(TableOfContents.java:72)
	at com.android.dex.Dex.loadFrom(Dex.java:142)
	at com.android.dex.Dex.<init>(Dex.java:98)
	at jadx.core.utils.files.InputFile.loadFromZip(InputFile.java:109)
	at jadx.core.utils.files.InputFile.searchDexFiles(InputFile.java:58)
	at jadx.core.utils.files.InputFile.addFilesFrom(InputFile.java:35)
	at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:124)
	... 20 common frames omitted
```
FYI; Opening the classes.dex works fine.

**Sample:** https://koodous.com/apks/087af5aacab8fc8bc7b1dcb7a138c3552d175c74b496056893299bc437422f95

**Comment by skylot** [comment]
Jadx trying load file `assets/ApkPacker/classes.dex` but this is not correct dex.
I made a fix which allows to loading other dex files and don't crash on this one.

**Comment by enovella** [comment]
FYI; Unpacking the APK and opening the classes.dex worked fine. I'll test the new fix! Thanks

**Comment by enovella** [comment]
Hi @skylot,

problem solved!
