### ISSUE TITLE
[gui] can not attach process running in android 15 emulator 

### ISSUE THREAD

**Issue by JerryRunner79** [skylot/jadx#2334]
### Issue details

ERROR - Debug error
jadx.gui.device.debugger.SmaliDebuggerException: jdwp handshake bad reply
	at jadx.gui.device.debugger.SmaliDebugger.handShake(SmaliDebugger.java:647)
	at jadx.gui.device.debugger.SmaliDebugger.initJDWP(SmaliDebugger.java:618)
	at jadx.gui.device.debugger.SmaliDebugger.attach(SmaliDebugger.java:148)
	at jadx.gui.device.debugger.DebugController.startDebugger(DebugController.java:82)
	at jadx.gui.ui.panel.JDebuggerPanel.showDebugger(JDebuggerPanel.java:391)
	at jadx.gui.ui.dialog.ADBDialog.attachProcess(ADBDialog.java:362)
	at jadx.gui.ui.dialog.ADBDialog.processSelected(ADBDialog.java:345)
	at jadx.gui.ui.dialog.ADBDialog$1.mouseClicked(ADBDialog.java:130)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6629)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4584)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

### Jadx version

1.5.0

### Java version

17.0.2

### OS

- [ ] Windows
- [ ] Linux
- [X] macOS

**Comment by bbetter173** [comment]
Do you have Android Studio open? I'm on an M2 Macbook Pro and get this error if it is.
