### ISSUE TITLE
[gui] Checking for updates question

### ISSUE THREAD

**Issue by greenozon** [skylot/jadx#2341]
### Issue details

run the app (1.5.1) and and open up logs (Help -> Log Viewer)

it will write:

```
INFO : Checking for updates... Update channel: STABLE, current version: 1.5.1
WARN : Jadx update error
java.lang.RuntimeException: Unable to create instance of class jadx.gui.update.Release. Registering an InstanceCreator or a TypeAdapter for this type, or adding a no-args constructor may fix this problem.
	at com.google.gson.internal.ConstructorConstructor$19.construct(ConstructorConstructor.java:422)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.createAccumulator(ReflectiveTypeAdapterFactory.java:552)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:505)
	at com.google.gson.Gson.fromJson(Gson.java:1361)
	at com.google.gson.Gson.fromJson(Gson.java:1262)
	at com.google.gson.Gson.fromJson(Gson.java:1199)
	at jadx.gui.update.JadxUpdate.getAndParse(JadxUpdate.kt:108)
	at jadx.gui.update.JadxUpdate.checkForNewStableRelease(JadxUpdate.kt:82)
	at jadx.gui.update.JadxUpdate.checkForNewRelease(JadxUpdate.kt:70)
	at jadx.gui.update.JadxUpdate.check$lambda$2(JadxUpdate.kt:47)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsupportedOperationException: Cannot allocate class jadx.gui.update.Release. Usage of JDK sun.misc.Unsafe is enabled, but it could not be used. Make sure your runtime is configured correctly.
	at com.google.gson.internal.UnsafeAllocator$4.newInstance(UnsafeAllocator.java:121)
	at com.google.gson.internal.ConstructorConstructor$19.construct(ConstructorConstructor.java:419)
	... 10 common frames omitted

```

### Jadx version

1.5.1

### Java version

23.0.1

### OS

- [X] Windows
- [ ] Linux
- [ ] macOS

**Comment by skylot** [comment]
@greenozon thanks for report :+1:
Looks like bundle with included JRE missing some modules:
- "jdk.unsupported" - add Unsafe class, used by GSON
- "jdk.crypto.cryptoki" - needed for "https" protocol to get plugins and updates

Not sure, why this issue came up only now, maybe new Java version become more strict or split some modules.

Anyway, I repackage and re-upload `jadx-gui-1.5.1-with-jre-win.zip` artifact, so the issue should be fixed.

**Comment by greenozon** [comment]
Thanks!
it did the fix!

>INFO : Checking for updates... Update channel: STABLE, current version: 1.5.1

and no stack trace anymore

kudos!
