### ISSUE TITLE
[core] source index -1 out of bounds for object array[6]

### ISSUE THREAD

**Issue by yooo1999** [skylot/jadx#2347]
### Issue details

Windows JADX 1.5.1, JAVA version 23.0.1

```

ERROR: Failed to decode insn: 0x0012: XXXXXXX in method: XXXXXXXXXX():long, file: XXXXXXXXXX.class
java.lang.ArrayIndexOutOfBoundsException: arraycopy: source index -1 out of bounds for object array[6]
	at java.base/java.lang.System.arraycopy(Native Method)
	at jadx.plugins.input.java.data.code.StackState.insert(StackState.java:52)
	at jadx.plugins.input.java.data.code.CodeDecodeState.insert(CodeDecodeState.java:137)
	at jadx.plugins.input.java.data.code.JavaInsnsRegister.dup2x1(JavaInsnsRegister.java:313)
	at jadx.plugins.input.java.data.code.JavaInsnData.decode(JavaInsnData.java:46)
	at jadx.core.dex.instructions.InsnDecoder.lambda$process$0(InsnDecoder.java:50)
	at jadx.plugins.input.java.data.code.JavaCodeReader.visitInstructions(JavaCodeReader.java:85)
	at jadx.core.dex.instructions.InsnDecoder.process(InsnDecoder.java:46)
	at jadx.core.dex.nodes.MethodNode.load(MethodNode.java:157)
	at jadx.core.dex.nodes.ClassNode.load(ClassNode.java:445)
	at jadx.core.dex.nodes.ClassNode.load(ClassNode.java:451)
	at jadx.core.ProcessClass.process(ProcessClass.java:69)
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:117)
	at jadx.core.dex.nodes.ClassNode.generateClassCode(ClassNode.java:402)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:390)
	at jadx.core.dex.nodes.ClassNode.getCode(ClassNode.java:340)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$2(JadxDecompiler.java:375)
	at jadx.core.utils.tasks.TaskExecutor.wrapTask(TaskExecutor.java:166)
	at jadx.core.utils.tasks.TaskExecutor.lambda$runStages$0(TaskExecutor.java:147)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Jadx version

1.5.1

**Comment by skylot** [comment]
No sample - no fix :rofl:
