### ISSUE TITLE
[core] restoreSwitchOverString fails

### ISSUE THREAD

**Issue by steelbytes** [skylot/jadx#2359]
### Issue details

switch over string fails

### Relevant log output or stacktrace

```java
/* JADX WARN: Can't fix incorrect switch cases order, some code will duplicate */
    /* JADX WARN: Failed to restore switch over string. Please report as a decompilation issue
    java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "jadx.core.dex.visitors.regions.SwitchOverStringVisitor$SwitchData.getNewCases()" is null
    	at jadx.core.dex.visitors.regions.SwitchOverStringVisitor.restoreSwitchOverString(SwitchOverStringVisitor.java:109)
    	at jadx.core.dex.visitors.regions.SwitchOverStringVisitor.visitRegion(SwitchOverStringVisitor.java:66)
    	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseIterativeStepInternal(DepthRegionTraversal.java:77)
    	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseIterativeStepInternal(DepthRegionTraversal.java:82)
    	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseIterative(DepthRegionTraversal.java:31)
    	at jadx.core.dex.visitors.regions.SwitchOverStringVisitor.visit(SwitchOverStringVisitor.java:60)
     */
    /* JADX WARN: Removed duplicated region for block: B:27:0x0070 A[ORIG_RETURN, RETURN] */
    /* JADX WARN: Removed duplicated region for block: B:5:0x006e A[RETURN, SYNTHETIC] */
    @Override // com.piaggio.bike.data.vehicle.IVehicleModel
    /*
        Code decompiled incorrectly, please refer to instructions dump.
    */
```

### Provide sample and class/method full name

apk from https://apkpure.com/piaggio/it.piaggio.app
class com.piaggio.bike.data.vehicle.VehicleModel method enableClockSync

**Comment by 6x68** [comment]
the switch over string visitor seems to have a bug where if you have 3+ nested switches (inside a default block, might work in case blocks too).
if you just want to break the restore switch over string visitor:
```java
switch (v) {
	case "a":
		return 0;
	default:
		switch (v) {
			case "b":
				return 1;
			default:
				switch (v) {
					case "c":
						return 2;
					default:
						return 3;
		}
	}
}
```
This seems to trigger the error shown in the issue 1:1:
```java
switch (v) {
	case "a":
		return 1;
	default:
		switch (v) {
			case "b":
				return 2;
			case "c":
				return 3;
			default:
				return 4;
		}
}
```
and outputs with:
```java
/* JADX INFO: loaded from: /tmp/jadx-10248292870374724768/classes.dex */
public class TestSwitchOverStrings3$TestCls {
    /* JADX WARN: Can't fix incorrect switch cases order, some code will duplicate */
    /* JADX WARN: Failed to restore switch over string. Please report as a decompilation issue */
    /* JADX WARN: Removed duplicated region for block: B:8:0x0015  */
    /*
        Code decompiled incorrectly, please refer to instructions dump.
    */
    public int test(String v) {
        boolean z;
        z = true;
        switch (v) {
            case "a":
                return 1;
            default:
                switch (v.hashCode()) {
                    case 98:
                        z = !v.equals("b") ? -1 : false;
                        break;
                    case 99:
                        if (!v.equals("c")) {
                        }
                        break;
                }
                switch (z) {
                    case false:
                        return 2;
                    case true:
                        return 3;
                    default:
                        return 4;
                }
        }
    }

    public void check() {
        Assertions.assertThat(test("a")).isEqualTo(1);
        Assertions.assertThat(test("b")).isEqualTo(2);
        Assertions.assertThat(test("c")).isEqualTo(3);
    }
}
```
the warnings stop when you remove the "c" case inside the 2nd switch, but the broken non-compiling logic (`boolean z` and `z = -1` 😭) is still there
this is the test source for the class decompiled above:
```java
package jadx.tests.integration.switches;

import jadx.tests.api.IntegrationTest;
import jadx.tests.api.utils.assertj.JadxAssertions;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class TestSwitchOverStrings3 extends IntegrationTest {

	public static class TestCls {
		public int test(String v) {
			switch (v) {
				case "a":
					return 1;
				default:
					switch (v) {
						case "b":
							return 2;
						case "c":
							return 3;
						default:
							return 4;
					}
			}
		}

		public void check() {
			assertThat(test("a")).isEqualTo(1);
			assertThat(test("b")).isEqualTo(2);
			assertThat(test("c")).isEqualTo(3);
			// default case
			assertThat(test("d")).isEqualTo(3);
		}
	}

	@Test
	public void test() {
		JadxAssertions.assertThat(getClassNode(TestSwitchOverStrings3.TestCls.class))
				.code()
				.countString(3, "case ")
				.countString(2, "default:")
				.countString(4, "return ");
	}
}
```

**Comment by jackwpa** [comment]
For reference, here is the code of the that method decompiled by JEB Pro version 5.35:

```
    @Override  // com.piaggio.bike.data.vehicle.IVehicleModel
    public boolean enableClockSync() {
        switch(this.modelId) {
            case "beverly_my_2020_350": 
            case "liberty_e5plus_150": 
            case "liberty_e5plus_50": 
            case "mp3_300_hpe_e5": 
            case "mp3_310": 
            case "mp3_400_e5": 
            case "mp3_500_e5": 
            case "p197": {
                return false;
            }
            case "liberty_e5plus_125": {
                return false;
            }
            default: {
                return true;
            }
        }
    }
```

**Comment by 6x68** [comment]
with:
```java
		public byte test(String a) {
			switch (a) {
				case "a": break;
				case "b":
					switch (a) {
						case "c":
							return 2;
						case "d":
							return 3;
						case "e":
							System.out.println("?");
							break;
						default:
							return 4;
					}
			}
			return 1;
		}
```

```log
ERROR - Insns.size() != 1: 0
ERROR - Extract mismatch! Extracted 2 cases, but there are a total of 3 cases
```

so it's this:
https://github.com/skylot/jadx/blob/220a2198a11ce0dde234a4c3b18aaf7d5c4ec129/jadx-core/src/main/java/jadx/core/dex/visitors/regions/SwitchOverStringVisitor.java#L168-L170

**Comment by skylot** [comment]
@6x68 thanks for test case, I commit a fix for it. Although issue in first apk still not fixed :slightly_frowning_face:
