### ISSUE TITLE
[core] NPE in pass: ProcessVariables

### ISSUE THREAD

**Issue by nitram84** [skylot/jadx#2380]
### Issue details

The method `Object a(Object) in class c.a.b.a.i.w.j.z` of https://apkpure.com/database-modeler-lite/adrian.adbm/download/1.4 can't be decompiled with latest git version. Deobfuscation was disabled for this test.

The decompiled code in simple mode seems to be correct:

```java
    @Override // c.a.b.a.i.w.j.b0.b
    public Object a(Object obj) {
        return b0.U((Cursor) obj);
    }
```

A simple check for null won't fix the issue.

### Relevant log output or stacktrace

```java
ERROR - NullPointerException in pass: ProcessVariables in method: c.a.b.a.i.w.j.z.a(java.lang.Object):java.lang.Object, file: classes.dex
java.lang.NullPointerException: Cannot invoke "jadx.core.dex.instructions.args.SSAVar.getUseList()" because "ssaVar" is null
        at jadx.core.dex.visitors.regions.variables.ProcessVariables$1.processBlock(ProcessVariables.java:96)
        at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseInternal(DepthRegionTraversal.java:64)
        at jadx.core.dex.visitors.regions.DepthRegionTraversal.lambda$traverseInternal$0(DepthRegionTraversal.java:68)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseInternal(DepthRegionTraversal.java:68)
        at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverse(DepthRegionTraversal.java:19)
        at jadx.core.dex.visitors.regions.variables.ProcessVariables.removeUnusedResults(ProcessVariables.java:73)
        at jadx.core.dex.visitors.regions.variables.ProcessVariables.visit(ProcessVariables.java:48)
        at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:25)
        at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:13)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:13)
        at jadx.core.ProcessClass.process(ProcessClass.java:74)
        at jadx.core.ProcessClass.generateCode(ProcessClass.java:112)
        at jadx.core.dex.nodes.ClassNode.generateClassCode(ClassNode.java:400)
        at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:388)
        at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:308)
        at jadx.api.JavaClass.load(JavaClass.java:132)
        at jadx.api.JavaClass.decompile(JavaClass.java:69)
        at jadx.gui.treemodel.JClass.lambda$getLoadTask$0(JClass.java:75)
        at jadx.core.utils.tasks.TaskExecutor.wrapTask(TaskExecutor.java:166)
        at jadx.core.utils.tasks.TaskExecutor.runStages(TaskExecutor.java:142)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Provide sample and class/method full name

Method `Object a(Object)` in class `c.a.b.a.i.w.j.z` of https://apkpure.com/database-modeler-lite/adrian.adbm/download/1.4

Partial deobfuscation of the package `c.a.b.a.i.w.j` is `com.google.b.a.i.w.j`

### Jadx version

1.5.2-SNAPSHOT, latest git version

**Comment by skylot** [comment]
Fixed.
Jadx tries to inline method with ternary instruction, I added support for such case.
Although, not sure if that was needed in attached sample :thinking:
