### ISSUE TITLE
[gui] this error happens in smali debugger both linux and windows

### ISSUE THREAD

**Issue by SmokyDev8** [skylot/jadx#2386]
### Issue details

Jadx version : 1.5.1
Java version : 23.0.1
Java VM      : Oracle Corporation OpenJDK 64-Bit Server VM
Platform     : Windows 11 (10.0 amd64)
Max heap size: 11264 MB

jadx.core.utils.exceptions.JadxRuntimeException: Decompiler not yet loaded
	at jadx.gui.JadxWrapper.getDecompiler(JadxWrapper.java:258)
	at jadx.gui.device.debugger.DbgUtils.parseAppData(DbgUtils.java:143)
	at jadx.gui.device.debugger.DebugController.getProcessName(DebugController.java:221)
	at jadx.gui.ui.dialog.ADBDialog.processSelected(ADBDialog.java:323)
	at jadx.gui.ui.dialog.ADBDialog$1.mouseClicked(ADBDialog.java:130)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

this is what it shows

### Jadx version

1.5.1

### Java version

jdk 11 and the windows included one

### OS

- [X] Windows
- [X] Linux
- [ ] macOS

**Comment by jpstotz** [comment]
Have you loaded an APK into Jadx before using the debugger?

**Comment by SmokyDev8** [comment]
Tried after loading and also before loading

**Comment by MrIkso** [comment]
@skylot same as #2547
