### ISSUE TITLE
Try/Catch NullPointerException

### ISSUE THREAD

**Issue by cobalt232** [skylot/jadx#250]
This code:

    private void safeCloseZip (ZipInput zipInput, ZipOutput zipOutput) {
        if (zipInput != null) {
            zipInput.close();
        }
        if (zipOutput != null) {
            try {
                zipOutput.close();
            } catch (IOException ignore) {
            }
        }
    }

decompiles to this:
       /* JADX: method processing error */
/*
Error: java.lang.NullPointerException
	at jadx.core.dex.visitors.regions.ProcessTryCatchRegions.searchTryCatchDominators(ProcessTryCatchRegions.java:75)
	at jadx.core.dex.visitors.regions.ProcessTryCatchRegions.process(ProcessTryCatchRegions.java:45)
	at jadx.core.dex.visitors.regions.RegionMakerVisitor.postProcessRegions(RegionMakerVisitor.java:63)
	at jadx.core.dex.visitors.regions.RegionMakerVisitor.visit(RegionMakerVisitor.java:58)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:31)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:17)
	at jadx.core.ProcessClass.process(ProcessClass.java:34)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:282)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
	at jadx.api.JavaClass.getCode(JavaClass.java:48)
*/
        /*
        r0 = this;
        if (r1 == 0) goto L_0x0005;
    L_0x0002:
        r1.close();
    L_0x0005:
        if (r2 == 0) goto L_0x000a;
    L_0x0007:
        r2.close();	 Catch:{ IOException -> 0x000a }
    L_0x000a:
        return;
        */

**Comment by sergey-wowwow** [comment]
I changed the code to (because ``` ZipInput ``` is unresolved type and ``` close() ``` throws ``` IOException ```)
```java
    private void safeCloseZip (ZipInputStream zipInput, ZipInputStream zipOutput) throws IOException {
        if (zipInput != null) {
            zipInput.close();
        }
        if (zipOutput != null) {
            try {
                zipOutput.close();
            } catch (IOException ignore) {
            }
        }
    }
```
and it's decompiled to
```java
    private void safeCloseZip(ZipInputStream zipInputStream, ZipInputStream zipInputStream2) throws IOException {
        if (zipInputStream != null) {
            zipInputStream.close();
        }
        if (zipInputStream2 != null) {
            try {
                zipInputStream2.close();
            } catch (IOException unused) {
            }
        }
    }
```
so everything is correct now

**Comment by cobalt232** [comment]
Great, thanks!
