### ISSUE TITLE
Stackoverflow in LoopRegionVisitor.assignOnlyInLoop

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#266]
Hi, @skylot 
Thanks for your bug fixes!
I've noticed a stackoverflow in different place
APK: https://drive.google.com/open?id=1dxd03Yh8jVlG1gMB0p-pKAPzbOlh79j2
Stacktrace:
```
Exception in thread "pool-1-thread-2" java.lang.StackOverflowError
	at jadx.core.utils.RegionUtils.isRegionContainsBlock(RegionUtils.java:173)
	at jadx.core.utils.RegionUtils.isRegionContainsBlock(RegionUtils.java:174)
	at jadx.core.utils.RegionUtils.isRegionContainsBlock(RegionUtils.java:174)
	at jadx.core.dex.visitors.regions.LoopRegionVisitor.argInLoop(LoopRegionVisitor.java:368)
	at jadx.core.dex.visitors.regions.LoopRegionVisitor.assignOnlyInLoop(LoopRegionVisitor.java:334)
	at jadx.core.dex.visitors.regions.LoopRegionVisitor.assignOnlyInLoop(LoopRegionVisitor.java:340)
	at jadx.core.dex.visitors.regions.LoopRegionVisitor.assignOnlyInLoop(LoopRegionVisitor.java:340)
	at jadx.core.dex.visitors.regions.LoopRegionVisitor.assignOnlyInLoop(LoopRegionVisitor.java:340)
```

Arguments (that stackoverflow is not logged to ``` logs.txt ```, because I noticed that error):
```
jadx --no-replace-consts --show-bad-code --threads-count 8 --no-imports --output-dir TEST jp.naver.line.android.apk > logs.txt
```

**Comment by sergey-wowwow** [comment]
One more, stacktrace
```
	at jadx.core.clsp.ClspGraph.searchCommonParent(ClspGraph.java:95)
	at jadx.core.clsp.ClspGraph.searchCommonParent(ClspGraph.java:95)
	at jadx.core.clsp.ClspGraph.searchCommonParent(ClspGraph.java:95)
	at jadx.core.clsp.ClspGraph.searchCommonParent(ClspGraph.java:95)
	at jadx.core.clsp.ClspGraph.searchCommonParent(ClspGraph.java:95)
	at jadx.core.clsp.ClspGraph.searchCommonParent(ClspGraph.java:95)
```
APK: https://drive.google.com/open?id=1uRFFtJTlD6sMnhse4Ouooo2BqIZJGYaP

**Comment by sergey-wowwow** [comment]
Not reproducible anymore
