### ISSUE TITLE
small dex with UnsupportedOperationException

### ISSUE THREAD

**Issue by artenie** [skylot/jadx#27]
First, thank you for this wonderful decompiler. It outputs very nice code.

This seems to me very low priority for the jadx project, but I found this dex which has 2 small methods (only 1-2 instructions). Seems to be a part of a new apk packer. Instructions could be something more exotic. Each method has output for decompiled code (example for method a):

public java.lang.String a() {
throw new UnsupportedOperationException("Method not decompiled: a.a.a.a.a.a():java.lang.String");
        /\* JADX: method processing error _/
/_
        Error: java.lang.NullPointerException
        at jadx.core.dex.visitors.regions.ProcessVariables.addToUsageMap(ProcessVariables.java:286)
        at jadx.core.dex.visitors.regions.ProcessVariables.visit(ProcessVariables.java:184)
        at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:27)
        at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:16)
        at jadx.core.ProcessClass.process(ProcessClass.java:22)
        at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:209)
        at jadx.api.JavaClass.decompile(JavaClass.java:59)
        at jadx.api.JadxDecompiler$1.run(JadxDecompiler.java:133)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
_/
        /_
        this = this;
        r44 = (r40 > r32 ? 1 : (r40 == r32 ? 0 : -1));
    L_0x0002:
        if (r11 != r6) goto L_0x0002;
        */

Fallback mode for jadx prints the same, without the stack trace. 

Thank you.

**Comment by sergey-wowwow** [comment]
APK links don't work anymore, and I didn't notice such errors last time, so I believe it's time to close it
