### ISSUE TITLE
Decompiler freezes (deadlock) 

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#274]
Hi, 
output from ``` jstack ```:
```
2018-05-14 15:12:05
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.74-b02 mixed mode):

"pool-1-thread-4" #13 prio=5 os_prio=0 tid=0x000000003d810800 nid=0xcac waiting for monitor entry [0x00000000449ae000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at jadx.core.ProcessClass.process(ProcessClass.java:28)
        - waiting to lock <0x000000040531edf8> (a jadx.core.dex.info.ClassInfo)
        at jadx.core.ProcessClass.processDependencies(ProcessClass.java:60)
        at jadx.core.ProcessClass.process(ProcessClass.java:39)
        - locked <0x0000000405304890> (a jadx.core.dex.info.ClassInfo)
        at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:282)
        at jadx.api.JavaClass.decompile(JavaClass.java:62)
        - locked <0x000000040ffa0b20> (a jadx.api.JavaClass)
        at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:200)
        at jadx.api.JadxDecompiler$$Lambda$8/1173346575.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
        - <0x0000000410070048> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"pool-1-thread-3" #12 prio=5 os_prio=0 tid=0x000000003d80f800 nid=0x1734 waiting for monitor entry [0x0000000043aae000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at jadx.core.ProcessClass.process(ProcessClass.java:28)
        - waiting to lock <0x0000000405304890> (a jadx.core.dex.info.ClassInfo)
        at jadx.core.ProcessClass.processDependencies(ProcessClass.java:60)
        at jadx.core.ProcessClass.process(ProcessClass.java:39)
        - locked <0x000000040531edf8> (a jadx.core.dex.info.ClassInfo)
        at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:282)
        at jadx.api.JavaClass.decompile(JavaClass.java:62)
        - locked <0x000000040ffa0bc0> (a jadx.api.JavaClass)
        at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:200)
        at jadx.api.JadxDecompiler$$Lambda$8/1173346575.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
        - <0x00000004100b9b08> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"pool-1-thread-2" #11 prio=5 os_prio=0 tid=0x000000003e1cd000 nid=0xa6c waiting for monitor entry [0x0000000042bae000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at jadx.core.ProcessClass.process(ProcessClass.java:28)
        - waiting to lock <0x000000040531edf8> (a jadx.core.dex.info.ClassInfo)
        at jadx.core.ProcessClass.processDependencies(ProcessClass.java:60)
        at jadx.core.ProcessClass.process(ProcessClass.java:39)
        - locked <0x0000000405353e28> (a jadx.core.dex.info.ClassInfo)
        at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:282)
        at jadx.api.JavaClass.decompile(JavaClass.java:62)
        - locked <0x000000040ffa0a58> (a jadx.api.JavaClass)
        at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:200)
        at jadx.api.JadxDecompiler$$Lambda$8/1173346575.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
        - <0x00000004100b9280> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"pool-1-thread-1" #10 prio=5 os_prio=0 tid=0x000000003d7dc000 nid=0x100c waiting for monitor entry [0x0000000041caf000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at jadx.core.ProcessClass.process(ProcessClass.java:28)
        - waiting to lock <0x0000000405304890> (a jadx.core.dex.info.ClassInfo)
        at jadx.core.ProcessClass.processDependencies(ProcessClass.java:60)
        at jadx.core.ProcessClass.process(ProcessClass.java:39)
        - locked <0x0000000405353f80> (a jadx.core.dex.info.ClassInfo)
        at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:282)
        at jadx.api.JavaClass.decompile(JavaClass.java:62)
        - locked <0x000000040ffa0940> (a jadx.api.JavaClass)
        at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:200)
        at jadx.api.JadxDecompiler$$Lambda$8/1173346575.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
        - <0x00000004100b9738> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"Service Thread" #9 daemon prio=9 os_prio=0 tid=0x000000003bc80000 nid=0x19d4 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"C1 CompilerThread2" #8 daemon prio=9 os_prio=2 tid=0x0000000036b07800 nid=0x1454 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"C2 CompilerThread1" #7 daemon prio=9 os_prio=2 tid=0x0000000036b04000 nid=0x10b0 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"C2 CompilerThread0" #6 daemon prio=9 os_prio=2 tid=0x0000000036b00800 nid=0x126c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Attach Listener" #5 daemon prio=5 os_prio=2 tid=0x0000000036aff000 nid=0xf84 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Signal Dispatcher" #4 daemon prio=9 os_prio=2 tid=0x0000000036afd800 nid=0x190c runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x00000000028ed000 nid=0x1918 in Object.wait() [0x0000000039a5f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x000000040526c180> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
        - locked <0x000000040526c180> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

   Locked ownable synchronizers:
        - None

"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x00000000028e2000 nid=0xce8 in Object.wait() [0x0000000038b5f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x0000000402386a48> (a java.lang.ref.Reference$Lock)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
        - locked <0x0000000402386a48> (a java.lang.ref.Reference$Lock)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

   Locked ownable synchronizers:
        - None

"main" #1 prio=5 os_prio=0 tid=0x00000000027f2800 nid=0xe1c waiting on condition [0x000000000385f000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000004100b9eb8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1465)
        at jadx.api.JadxDecompiler.save(JadxDecompiler.java:147)
        at jadx.api.JadxDecompiler.save(JadxDecompiler.java:132)
        at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:32)
        at jadx.cli.JadxCLI.main(JadxCLI.java:16)

   Locked ownable synchronizers:
        - None

"VM Thread" os_prio=2 tid=0x0000000036ac7000 nid=0x18b8 runnable

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x0000000002808000 nid=0x1b00 runnable

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x0000000002809800 nid=0xa30 runnable

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x000000000280b000 nid=0xdb8 runnable

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x000000000280c800 nid=0x1448 runnable

"VM Periodic Task Thread" os_prio=2 tid=0x000000003bcac800 nid=0x7d8 waiting on condition

JNI global references: 250


Found one Java-level deadlock:
=============================
"pool-1-thread-4":
  waiting to lock monitor 0x00000000028e9ea8 (object 0x000000040531edf8, a jadx.core.dex.info.ClassInfo),
  which is held by "pool-1-thread-3"
"pool-1-thread-3":
  waiting to lock monitor 0x000000003dffbbf8 (object 0x0000000405304890, a jadx.core.dex.info.ClassInfo),
  which is held by "pool-1-thread-4"

Java stack information for the threads listed above:
===================================================
"pool-1-thread-4":
        at jadx.core.ProcessClass.process(ProcessClass.java:28)
        - waiting to lock <0x000000040531edf8> (a jadx.core.dex.info.ClassInfo)
        at jadx.core.ProcessClass.processDependencies(ProcessClass.java:60)
        at jadx.core.ProcessClass.process(ProcessClass.java:39)
        - locked <0x0000000405304890> (a jadx.core.dex.info.ClassInfo)
        at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:282)
        at jadx.api.JavaClass.decompile(JavaClass.java:62)
        - locked <0x000000040ffa0b20> (a jadx.api.JavaClass)
        at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:200)
        at jadx.api.JadxDecompiler$$Lambda$8/1173346575.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
"pool-1-thread-3":
        at jadx.core.ProcessClass.process(ProcessClass.java:28)
        - waiting to lock <0x0000000405304890> (a jadx.core.dex.info.ClassInfo)
        at jadx.core.ProcessClass.processDependencies(ProcessClass.java:60)
        at jadx.core.ProcessClass.process(ProcessClass.java:39)
        - locked <0x000000040531edf8> (a jadx.core.dex.info.ClassInfo)
        at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:282)
        at jadx.api.JavaClass.decompile(JavaClass.java:62)
        - locked <0x000000040ffa0bc0> (a jadx.api.JavaClass)
        at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:200)
        at jadx.api.JadxDecompiler$$Lambda$8/1173346575.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Found 1 deadlock.
```

Commands used:
```
bin\jadx\bin\jadx.bat --no-replace-consts --show-bad-code --threads-count 4 --no-imports --output-dir TEST com.outfit7.talkinggingerfree.apk
```

APK:
https://drive.google.com/file/d/1Cz4ccHvabA8X8WOq8gw9bfU4pLplP_e4/view?usp=sharing

**Comment by bensh** [comment]
I also have this and have tested across a few laptops. The crashes seem to happen less on Java 10.

**Comment by sergey-wowwow** [comment]
@skylot 
Updated stacktrace
```
Found one Java-level deadlock:
=============================
"pool-1-thread-4":
  waiting to lock monitor 0x0000000002cf7f08 (object 0x0000000405280160, a jadx.core.dex.info.ClassInfo),
  which is held by "pool-1-thread-2"
"pool-1-thread-2":
  waiting to lock monitor 0x0000000002cfb1e8 (object 0x000000040271cb28, a jadx.core.dex.info.ClassInfo),
  which is held by "pool-1-thread-4"

Java stack information for the threads listed above:
===================================================
"pool-1-thread-4":
        at jadx.core.ProcessClass.process(ProcessClass.java:28)
        - waiting to lock <0x0000000405280160> (a jadx.core.dex.info.ClassInfo)
        at jadx.core.ProcessClass.lambda$processDependencies$0(ProcessClass.java:59)
        at jadx.core.ProcessClass$$Lambda$11/510523906.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at jadx.core.ProcessClass.processDependencies(ProcessClass.java:59)
        at jadx.core.ProcessClass.process(ProcessClass.java:39)
        - locked <0x000000040271cb28> (a jadx.core.dex.info.ClassInfo)
        at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:282)
        at jadx.api.JavaClass.decompile(JavaClass.java:62)
        - locked <0x000000040ecac850> (a jadx.api.JavaClass)
        at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:200)
        at jadx.api.JadxDecompiler$$Lambda$8/1752461090.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
"pool-1-thread-2":
        at jadx.core.ProcessClass.process(ProcessClass.java:28)
        - waiting to lock <0x000000040271cb28> (a jadx.core.dex.info.ClassInfo)
        at jadx.core.ProcessClass.lambda$processDependencies$0(ProcessClass.java:59)
        at jadx.core.ProcessClass$$Lambda$11/510523906.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at jadx.core.ProcessClass.processDependencies(ProcessClass.java:59)
        at jadx.core.ProcessClass.process(ProcessClass.java:39)
        - locked <0x0000000405280160> (a jadx.core.dex.info.ClassInfo)
        at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:282)
        at jadx.api.JavaClass.decompile(JavaClass.java:62)
        - locked <0x000000040ecac6f0> (a jadx.api.JavaClass)
        at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:200)
        at jadx.api.JadxDecompiler$$Lambda$8/1752461090.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Found 1 deadlock.
```

**Comment by sergey-wowwow** [comment]
@skylot 
Thanks for fixes of other freezes. Can you please look at this one too? It seems to be much more frequent

**Comment by skylot** [comment]
@sergey-wowwow can you check last commit? It work for this particular apk, but I am not sure that all such deadlocks will be fixed (

**Comment by sergey-wowwow** [comment]
@skylot 
I will test it on multiple of APKs soon and report results :)

**Comment by sergey-wowwow** [comment]
@skylot 
Seems to be fixed
