### ISSUE TITLE
Exception Unreachable block

### ISSUE THREAD

**Issue by 0110101111001** [skylot/jadx#294]
Hello,

when using latest unstable (b452), I'm running into some exception preventing the decompilation of a good number of methods of this APK :
https://apkpure.com/wearfit/com.wakeup.smartband

For an example, with method "com.wakeup.smartband.manager.CommandManager.broadcastData", I'm getting :
ERROR - JadxRuntimeException in pass: BlockProcessor in method: com.wakeup.smartband.manager.CommandManager.broadcastData(byte[]):void, dex: classes.dex
jadx.core.utils.exceptions.JadxRuntimeException: Unreachable block: B:1:0x0001

This issue is a followup of #259 (same APK, but going further thanks to your previous fix). Probably another code protector trick.

**Comment by amspeople** [comment]
https://yadi.sk/d/YSwP52_VyKY6Z/Viber

/*  JADX ERROR: JadxRuntimeException in pass: BlockProcessor
        jadx.core.utils.exceptions.JadxRuntimeException: Unreachable block: B:2:0x000c
        	at jadx.core.dex.visitors.blocksmaker.BlockProcessor.modifyBlocksTree(BlockProcessor.java:360)
        	at jadx.core.dex.visitors.blocksmaker.BlockProcessor.processBlocksTree(BlockProcessor.java:56)
        	at jadx.core.dex.visitors.blocksmaker.BlockProcessor.visit(BlockProcessor.java:38)
        	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:27)
        	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
        	at java.util.ArrayList.forEach(ArrayList.java:1257)
        	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
        	at jadx.core.ProcessClass.process(ProcessClass.java:32)
        	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:292)
        	at jadx.api.JavaClass.decompile(JavaClass.java:62)
        */
