### ISSUE TITLE
Exception block dominator not found

### ISSUE THREAD

**Issue by BenBaltz** [skylot/jadx#295]
/*
Error: jadx.core.utils.exceptions.JadxRuntimeException: Exception block dominator not found, method:o.jK.ˏ(java.lang.String, java.lang.String):java.lang.String. bs: []
	at jadx.core.dex.visitors.regions.ProcessTryCatchRegions.searchTryCatchDominators(ProcessTryCatchRegions.java:89)
	at jadx.core.dex.visitors.regions.ProcessTryCatchRegions.process(ProcessTryCatchRegions.java:45)
	at jadx.core.dex.visitors.regions.RegionMakerVisitor.postProcessRegions(RegionMakerVisitor.java:63)
	at jadx.core.dex.visitors.regions.RegionMakerVisitor.visit(RegionMakerVisitor.java:58)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:27)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
	at java.util.ArrayList.forEach(Unknown Source)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
	at jadx.core.ProcessClass.process(ProcessClass.java:34)
	at jadx.core.ProcessClass.lambda$processDependencies$0(ProcessClass.java:59)
	at java.lang.Iterable.forEach(Unknown Source)
	at jadx.core.ProcessClass.processDependencies(ProcessClass.java:59)
	at jadx.core.ProcessClass.process(ProcessClass.java:39)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:282)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:200)
*/

This are everywhere when trying to decompile the starbucks app, its on apk mirror if you'd like to reproduce. I'd love to help solve it, just not very experienced in this field.

**Comment by BenBaltz** [comment]
I also recompiled jadx with REGIONS_STACK_LIMIT = 100000 just to see if it would work but it did not even decompile file that time

**Comment by BenBaltz** [comment]
Just pulled,built and ran again. Most of the same problems are present just now called:
/* JADX WARNING: inconsistent code. */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    /* renamed from: ˏ */

there's also one specific file that gives 
/*
Error: jadx.core.utils.exceptions.JadxOverflowException: Regions stack size limit reached
	at jadx.core.utils.ErrorsCounter.addError(ErrorsCounter.java:37)
	at jadx.core.utils.ErrorsCounter.methodError(ErrorsCounter.java:61)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:29)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
	at java.util.ArrayList.forEach(Unknown Source)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
	at jadx.core.ProcessClass.process(ProcessClass.java:34)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:282)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:200)
*/

ive uploaded it here: https://transfer.sh/qjQ7w/C10485cj.java

**Comment by BenBaltz** [comment]
Any update on this @skylot?

**Comment by MichaelPriebe** [comment]
Getting this error as well!

**Comment by sergey-wowwow** [comment]
@skylot 
I see that examples are provided from roughly obfuscated codes. You may use the attached APK to reproduce the bug, sources are not obfuscated at all.

Class ``` com.samsung.knox.securefolder.switcher.B2CShareViaActivity ```, method:
```java
    private com.samsung.knox.securefolder.switcher.FileInfo makeFileByUri(android.content.Context r18, android.net.Uri r19, java.lang.String r20, int r21) {
        /* JADX: method processing error */
/*
Error: jadx.core.utils.exceptions.JadxRuntimeException: Exception block dominator not found, method:com.samsung.knox.securefolder.switcher.B2CShareViaActivity.makeFileByUri(android.content.Context, android.net.Uri, java.lang.String, int):com.samsung.knox.securefolder.switcher.FileInfo, dom blocks: [B:4:0x0017, B:15:0x0036]
	at jadx.core.dex.visitors.regions.ProcessTryCatchRegions.searchTryCatchDominators(ProcessTryCatchRegions.java:89)
	at jadx.core.dex.visitors.regions.ProcessTryCatchRegions.process(ProcessTryCatchRegions.java:45)
	at jadx.core.dex.visitors.regions.RegionMakerVisitor.postProcessRegions(RegionMakerVisitor.java:63)
	at jadx.core.dex.visitors.regions.RegionMakerVisitor.visit(RegionMakerVisitor.java:58)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:27)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
	at jadx.core.ProcessClass.process(ProcessClass.java:32)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:286)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:201)
*/
```

https://drive.google.com/open?id=1zzwyjlB-087IAuGxVIbgGC-tNJqkitf8
