### ISSUE TITLE
Multiple classes missing

### ISSUE THREAD

**Issue by jpstotz** [skylot/jadx#313]
I encountered a strange bug in Jadx analyzing the APK of the [Wire messenger](https://apkpure.com/de/wire-•-secure-messenger/com.wire/download/623-APK):

At least one class including inner classes is completely missing in the JadX class view.
I detail this this the class com/koushikdutta/async/AsyncSSLSocketWrapper which is located in the main classes.dex.

![jadx](https://user-images.githubusercontent.com/924885/42749959-d4a47112-88e5-11e8-8334-36e0ad9ad0c3.png)

Even the full text search for "AsyncSSLSocketWrapper" does not show any output. 

Apktool and other tools correctly see this class and decompile then, just Jadx completely ignores this class. Also no exception regarding this class can be seen on the command-line. 

This issue occurs with the current unstable version as well as with stable version 0.7.1. Also the Java version (10 or 1.8.0_171) makes no difference.

Tested platform: Windows 10

**Comment by jpstotz** [comment]
This bug is worse than I first thought: not one class is missing - hundred of classes are missing!
Jadx fails to decompile one class and all classes that should be processed afterwards are then silently ignored!

The following Exception is the root problem:

java.lang.NullPointerException: null
	at jadx.core.dex.nodes.parser.SignatureParser.consumeObjectType(SignatureParser.java:183)
	at jadx.core.dex.nodes.parser.SignatureParser.consumeType(SignatureParser.java:121)
	at jadx.core.dex.nodes.ClassNode.setFieldsTypesFromSignature(ClassNode.java:205)
	at jadx.core.dex.nodes.ClassNode.<init>(ClassNode.java:111)
	at jadx.core.dex.nodes.DexNode.loadClasses(DexNode.java:49)
	at jadx.core.dex.nodes.RootNode.load(RootNode.java:66)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:90)
	at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:34)
	at jadx.gui.ui.MainWindow.openFile(MainWindow.java:168)
	at jadx.gui.ui.MainWindow.open(MainWindow.java:125)
	at jadx.gui.JadxGUI.lambda$main$0(JadxGUI.java:27)


IMHO the Exception handling process in such a case should be changed. May be we could introduce an IDexNode implementation for error classes, or alternatively let ClassNode internally store and display the Exception.

**Comment by skylot** [comment]
@jpstotz thank you! This is a very bad error, sorry :(
And you are right about error handling. I need make error appear not only in the console but in UI and generated code.
For last, I think I will use attribute storage (exists in every node) - store all errors and show in code comments.
