### ISSUE TITLE
Method not decompiled: BlockUtils.getNextBlock() throws NullPointerException

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#317]
Hi, I see that a method wasn't decompiled, file ``` finam/protobuf/userinfo/UserInfoRequest.java ```
```java
    protected final java.lang.Object dynamicMethod(com.google.protobuf.GeneratedMessageLite.MethodToInvoke r13, java.lang.Object r14, java.lang.Object r15) {
        /* JADX: method processing error */
/*
Error: java.lang.NullPointerException
	at jadx.core.utils.BlockUtils.getNextBlock(BlockUtils.java:289)
	at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:131)
	at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:74)
	at jadx.core.dex.visitors.regions.RegionMaker.processIf(RegionMaker.java:642)
	at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:111)
	at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:74)
	at jadx.core.dex.visitors.regions.RegionMaker.processSwitch(RegionMaker.java:818)
	at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:116)
	at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:74)
	at jadx.core.dex.visitors.regions.RegionMakerVisitor.visit(RegionMakerVisitor.java:49)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:27)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
	at jadx.core.ProcessClass.process(ProcessClass.java:32)
	at jadx.core.ProcessClass.lambda$processDependencies$0(ProcessClass.java:51)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at jadx.core.ProcessClass.processDependencies(ProcessClass.java:51)
	at jadx.core.ProcessClass.process(ProcessClass.java:37)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:286)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:201)
*/
```

APK: https://drive.google.com/open?id=1W3e0_QR8Nc9h0lx1OoscfY2cNBPPwG6I

**Comment by skylot** [comment]
@sergey-wowwow  fixed!

**Comment by sergey-wowwow** [comment]
@skylot 
Thanks!
