### ISSUE TITLE
Method not decompiled: SSA rename variables already executed

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#318]
Hi, the same app as in issue #317 

Stacktrace from ``` finam/protobuf/marketdata/Quote.java ```:
```java
            private AdditionsOneofCase(int r3) {
                /* JADX: method processing error */
/*
Error: jadx.core.utils.exceptions.JadxRuntimeException: SSA rename variables already executed
	at jadx.core.dex.visitors.ssa.SSATransform.renameVariables(SSATransform.java:120)
	at jadx.core.dex.visitors.ssa.SSATransform.process(SSATransform.java:52)
	at jadx.core.dex.visitors.ssa.SSATransform.visit(SSATransform.java:42)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:27)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$0(DepthTraversal.java:13)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:13)
	at jadx.core.ProcessClass.process(ProcessClass.java:32)
	at jadx.core.ProcessClass.lambda$processDependencies$0(ProcessClass.java:51)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at jadx.core.ProcessClass.processDependencies(ProcessClass.java:51)
	at jadx.core.ProcessClass.process(ProcessClass.java:37)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:286)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:201)
*/
                /*
                r0 = this;
                r0.<init>(r1, r2);
                r0.value = r3;
                return;
                */
                throw new UnsupportedOperationException("Method not decompiled: finam.protobuf.marketdata.Quote.Additions.AdditionsOneofCase.<init>(java.lang.String, int, int):void");
            }
```

I remember that I already reported something like that, but I cannot find it.

APK: https://drive.google.com/open?id=1W3e0_QR8Nc9h0lx1OoscfY2cNBPPwG6I

**Comment by sergey-wowwow** [comment]
@skylot 
Can you please also look at https://drive.google.com/open?id=1Il9zNNl9OjEBUjIUHZnG-8DATSyH9dDe?
In ``` com.badoo.mobile.chatcom.model.message.ChatMessagePayload ``` still a lot of such errors, e.g.:
```java
            public int d() {
                /* JADX: method processing error */
/*
Error: jadx.core.utils.exceptions.JadxRuntimeException: SSA rename variables already executed
	at jadx.core.dex.visitors.ssa.SSATransform.renameVariables(SSATransform.java:120)
	at jadx.core.dex.visitors.ssa.SSATransform.process(SSATransform.java:52)
	at jadx.core.dex.visitors.ssa.SSATransform.visit(SSATransform.java:42)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:27)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1380)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$0(DepthTraversal.java:13)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1380)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:13)
	at jadx.core.ProcessClass.process(ProcessClass.java:32)
	at jadx.core.ProcessClass.lambda$processDependencies$0(ProcessClass.java:51)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at jadx.core.ProcessClass.processDependencies(ProcessClass.java:51)
	at jadx.core.ProcessClass.process(ProcessClass.java:37)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:286)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
*/
                /*
                r1 = this;
                r0 = r1.c;
                return r0;
                */
                throw new UnsupportedOperationException("Method not decompiled: com.badoo.mobile.chatcom.model.message.ChatMessagePayload.Image.Temporary.d():int");
            }
```

**Comment by skylot** [comment]
@sergey-wowwow thanks! The previous fix doesn't resolve the root cause of this issue.
