### ISSUE TITLE
Regression at commit 37ed9cd

### ISSUE THREAD

**Issue by S-trace** [skylot/jadx#321]
0.7.1 can decompile method public void handleMessage(android.os.Message r108) in class com.android.server.dsp.common.CommonManagerService$CommonManagerHandler with warning about inconsistent code, 0.7.2-unstable-b469-5d7f2c7 fails completely:
```
/*
Error: jadx.core.utils.exceptions.JadxRuntimeException: Unknown predecessor block by arg (r46_3 'data' android.dsp.bean.CInt3Pracel) in PHI: PHI: (r46_6 'data' android.dsp.bean.CInt3Pracel) = (r46_3 'data' android.dsp.bean.CInt3Pracel), (r46_5 'data' android.dsp.bean.CInt3Pracel) binds: {(r46_3 'data' android.dsp.bean.CInt3Pracel)=B:245:0x15b5, (r46_5 'data' android.dsp.bean.CInt3Pracel)=B:246:0x15b7}
	at jadx.core.dex.instructions.PhiInsn.replaceArg(PhiInsn.java:78)
	at jadx.core.dex.visitors.ModVisitor.processInvoke(ModVisitor.java:222)
	at jadx.core.dex.visitors.ModVisitor.replaceStep(ModVisitor.java:83)
	at jadx.core.dex.visitors.ModVisitor.visit(ModVisitor.java:68)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:27)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$0(DepthTraversal.java:13)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:13)
	at jadx.core.ProcessClass.process(ProcessClass.java:32)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:286)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
*/
```
JAR (just rename .zip to .jar): [services.zip](https://github.com/skylot/jadx/files/2229085/services.zip)

Thank You.

**Comment by S-trace** [comment]
Bisected this:
0.7.2-unstable-b408-882af04 decompiles with warning
0.7.2-unstable-b409-37ed9cd fails completely
commit 37ed9cd25baa66e766fc8fe5b0d4e57964af13a0 caused this regression.

**Comment by skylot** [comment]
@S-trace thanks, great work!
I will try to figure out how it can break decompilation, because after some debugging it is still not clear to me :(

**Comment by skylot** [comment]
@S-trace I fixed that regression. Thank you!
