### ISSUE TITLE
Method not decompiled: NullPointerException in BlockUtils.getPathCross()

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#327]
Hi @skylot , when I open ``` mp.MpUtils.getPaymentResponse(...) ``` I see:
```java

    public static mp.PaymentResponse getPaymentResponse(android.content.Context r5, long r6) {
        /* JADX: method processing error */
/*
Error: java.lang.NullPointerException
	at java.base/java.util.BitSet.and(BitSet.java:917)
	at jadx.core.utils.BlockUtils.getPathCross(BlockUtils.java:434)
	at jadx.core.dex.visitors.regions.IfMakerHelper.restructureIf(IfMakerHelper.java:80)
	at jadx.core.dex.visitors.regions.RegionMaker.processIf(RegionMaker.java:625)
	at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:118)
	at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:80)
	at jadx.core.dex.visitors.regions.RegionMaker.processExcHandler(RegionMaker.java:991)
	at jadx.core.dex.visitors.regions.RegionMaker.processTryCatchBlocks(RegionMaker.java:926)
	at jadx.core.dex.visitors.regions.RegionMakerVisitor.visit(RegionMakerVisitor.java:52)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:27)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1380)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
	at jadx.core.ProcessClass.process(ProcessClass.java:32)
	at jadx.core.ProcessClass.lambda$processDependencies$0(ProcessClass.java:51)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at jadx.core.ProcessClass.processDependencies(ProcessClass.java:51)
	at jadx.core.ProcessClass.process(ProcessClass.java:37)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:286)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
*/
        /*
        r3 = 0;
        r0 = r5.getApplicationContext();
        r5 = mp.lib.b.a(r0);
        r4 = r5.a();
        r0 = mp.lib.model.i.a(r4, r6);	 Catch:{ Exception -> 0x0048 }
        r3 = r0;	 Catch:{ Exception -> 0x0048 }
        if (r0 != 0) goto L_0x002f;	 Catch:{ Exception -> 0x0048 }
    L_0x0014:
        r0 = new java.lang.IllegalArgumentException;	 Catch:{ Exception -> 0x0048 }
        r1 = new java.lang.StringBuilder;	 Catch:{ Exception -> 0x0048 }
        r2 = "Message with id=";	 Catch:{ Exception -> 0x0048 }
        r1.<init>(r2);	 Catch:{ Exception -> 0x0048 }
        r1 = r1.append(r6);	 Catch:{ Exception -> 0x0048 }
        r2 = " not found";	 Catch:{ Exception -> 0x0048 }
        r1 = r1.append(r2);	 Catch:{ Exception -> 0x0048 }
        r1 = r1.toString();	 Catch:{ Exception -> 0x0048 }
        r0.<init>(r1);	 Catch:{ Exception -> 0x0048 }
        throw r0;	 Catch:{ Exception -> 0x0048 }
    L_0x002f:
        r0 = r3.e();	 Catch:{ Exception -> 0x0048 }
        if (r0 == 0) goto L_0x003c;	 Catch:{ Exception -> 0x0048 }
    L_0x0035:
        r0 = r3.e();	 Catch:{ Exception -> 0x0048 }
        r1 = 1;	 Catch:{ Exception -> 0x0048 }
        if (r0 != r1) goto L_0x0044;	 Catch:{ Exception -> 0x0048 }
    L_0x003c:
        r0 = new mp.lib.p;	 Catch:{ Exception -> 0x0048 }
        r0.<init>(r4);	 Catch:{ Exception -> 0x0048 }
        r0.a(r3);	 Catch:{ Exception -> 0x0048 }
    L_0x0044:
        r5.b();
        goto L_0x006e;
    L_0x0048:
        if (r3 != 0) goto L_0x0065;
    L_0x004a:
        r0 = new java.lang.IllegalArgumentException;	 Catch:{ all -> 0x0069 }
        r1 = new java.lang.StringBuilder;	 Catch:{ all -> 0x0069 }
        r2 = "Message with id=";	 Catch:{ all -> 0x0069 }
        r1.<init>(r2);	 Catch:{ all -> 0x0069 }
        r1 = r1.append(r6);	 Catch:{ all -> 0x0069 }
        r2 = " not found";	 Catch:{ all -> 0x0069 }
        r1 = r1.append(r2);	 Catch:{ all -> 0x0069 }
        r1 = r1.toString();	 Catch:{ all -> 0x0069 }
        r0.<init>(r1);	 Catch:{ all -> 0x0069 }
        throw r0;	 Catch:{ all -> 0x0069 }
    L_0x0065:
        r5.b();
        goto L_0x006e;
    L_0x0069:
        r6 = move-exception;
        r5.b();
        throw r6;
    L_0x006e:
        r5 = r3;
        r0 = new mp.PaymentResponse;
        r0.<init>(r5);
        return r0;
        */
        throw new UnsupportedOperationException("Method not decompiled: mp.MpUtils.getPaymentResponse(android.content.Context, long):mp.PaymentResponse");
    }
```

Can you look at it? Thanks

APK: https://drive.google.com/file/d/1Il9zNNl9OjEBUjIUHZnG-8DATSyH9dDe/view

**Comment by skylot** [comment]
@sergey-wowwow  I have fixed the NPE, but decompiled code is not correct: ` return` must be outside of try/catch and also I need to fix finally block extraction.

**Comment by sergey-wowwow** [comment]
I think this issue can be closed, because finally block extraction is different problem which is filed in many other reports
