### ISSUE TITLE
jadx:method processing error

### ISSUE THREAD

**Issue by zgfflc** [skylot/jadx#328]
I am from  china.First of all, thank you very much!The following problems are found during use 0.7.2.
/*
Error: jadx.core.utils.exceptions.JadxRuntimeException: Unknown predecessor block by arg (r22_1 'imagefile' java.io.File) in PHI: PHI: (r22_2 'imagefile' java.io.File) = (r22_1 'imagefile' java.io.File), (r22_3 'imagefile' java.io.File) binds: {(r22_1 'imagefile' java.io.File)=B:116:0x04e4, (r22_3 'imagefile' java.io.File)=B:124:0x0545}
	at jadx.core.dex.instructions.PhiInsn.replaceArg(PhiInsn.java:78)
	at jadx.core.dex.visitors.ModVisitor.processInvoke(ModVisitor.java:222)
	at jadx.core.dex.visitors.ModVisitor.replaceStep(ModVisitor.java:83)
	at jadx.core.dex.visitors.ModVisitor.visit(ModVisitor.java:68)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:27)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
	at java.util.ArrayList.forEach(Unknown Source)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
	at jadx.core.ProcessClass.process(ProcessClass.java:32)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:286)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
	at jadx.api.JavaClass.getCode(JavaClass.java:48)
*/

**Comment by zgfflc** [comment]
The github can not support upload apk file.Please give me your email.Thank you.
The error is:
com.signway.service.GetFileListService.onHandleIntent(Intent) : void 
com.signway.util.FileSplit.buildFile(File, boolean, boolean) : void 
com.signway.DigiSignage5161.PlayActivity1.checkPLSCanPlay(PlayActivity1$SimplifyProgramme,SchedulCache, String, int) : int
com.signway.DigiSignage5161.PlayActivity1.playTouchMediaWin(AreaVideo, int, int) : void 

In addition,the inconsistent code, if you are not sure, I suggest you refer to jeb.

**Comment by zgfflc** [comment]
[Uploading Droid.zip…]() Sorry, I now know to change to the compressed file can be uploaded

**Comment by zgfflc** [comment]
Because I am in China, I am afraid to sleep. So now, have you received my apk file?

**Comment by skylot** [comment]
@zgfflc I don't see you apk, looks like upload failed :(
Maybe you can share the link to this application on Google play or any other resources.
Or at least write a name of the application, so I can search it myself.

**Comment by sergey-wowwow** [comment]
@skylot 
I can provide a lot of APKs which have the same decompilation error, they probably have the same root cause

**Comment by skylot** [comment]
@sergey-wowwow thanks, if you find apk where this issue reproduced in a small method it will be very helpful. I already have a sample from #321 but there is a very big method and it is hard to debug and fix it :(

**Comment by skylot** [comment]
@zgfflc  @sergey-wowwow  fixed!
