### ISSUE TITLE
Method not decompiled: Not initialized variable reg

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#330]
Hi, I've noticed a new issue, class ``` com.samsung.android.service.EngineeringMode.IEngineeringModeService ```:
```java
            public int sendFuseCmd() throws android.os.RemoteException {
                /* JADX: method processing error */
/*
Error: jadx.core.utils.exceptions.JadxRuntimeException: Not initialized variable reg: 15, insn: 0x002e: RETURN  (r15 int), block:B:4:0x002e, method: com.samsung.android.service.EngineeringMode.IEngineeringModeService.Stub.Proxy.sendFuseCmd():int
	at jadx.core.dex.visitors.ssa.SSATransform.renameVar(SSATransform.java:161)
	at jadx.core.dex.visitors.ssa.SSATransform.renameVar(SSATransform.java:183)
	at jadx.core.dex.visitors.ssa.SSATransform.renameVar(SSATransform.java:183)
	at jadx.core.dex.visitors.ssa.SSATransform.renameVariables(SSATransform.java:132)
	at jadx.core.dex.visitors.ssa.SSATransform.process(SSATransform.java:52)
	at jadx.core.dex.visitors.ssa.SSATransform.visit(SSATransform.java:42)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:27)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$0(DepthTraversal.java:13)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:13)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$0(DepthTraversal.java:13)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:13)
	at jadx.core.ProcessClass.process(ProcessClass.java:32)
	at jadx.core.ProcessClass.lambda$processDependencies$0(ProcessClass.java:51)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at jadx.core.ProcessClass.processDependencies(ProcessClass.java:51)
	at jadx.core.ProcessClass.process(ProcessClass.java:37)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:286)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
*/
                /*
                r16 = this;
                r0 = r16;
                r1 = r0;
                r2 = android.os.Parcel.obtain();
                r3 = r2;
                r2 = android.os.Parcel.obtain();
                r4 = r2;
                r5 = "com.samsung.android.service.EngineeringMode.IEngineeringModeService";	 Catch:{ all -> 0x002f }
                r6 = r5;	 Catch:{ all -> 0x002f }
                r3.writeInterfaceToken(r6);	 Catch:{ all -> 0x002f }
                r2 = r0.mRemote;	 Catch:{ all -> 0x002f }
                r7 = 8;	 Catch:{ all -> 0x002f }
                r8 = 0;	 Catch:{ all -> 0x002f }
                r9 = r3;	 Catch:{ all -> 0x002f }
                r10 = r4;	 Catch:{ all -> 0x002f }
                r11 = r2.transact(r7, r9, r10, r8);	 Catch:{ all -> 0x002f }
                r4.readException();	 Catch:{ all -> 0x002f }
                r12 = r4.readInt();	 Catch:{ all -> 0x002f }
                r13 = r12;
                r4.recycle();
                r3.recycle();
                r15 = r12;
                return r15;
            L_0x002f:
                r14 = move-exception;
                r4.recycle();
                r3.recycle();
                throw r14;
                */
                throw new UnsupportedOperationException("Method not decompiled: com.samsung.android.service.EngineeringMode.IEngineeringModeService.Stub.Proxy.sendFuseCmd():int");
            }

```

APK: https://drive.google.com/open?id=1zzwyjlB-087IAuGxVIbgGC-tNJqkitf8

**Comment by sergey-wowwow** [comment]
Fixed in type-inference-wip
