### ISSUE TITLE
It miss a lot of code from v0.8.0

### ISSUE THREAD

**Issue by mdtuyen** [skylot/jadx#357]
I try decompile this file: https://apkpure.com/store/apps/details?id=com.appviet.tu.vung.tieng.anh

Compare with v0.7.1 and check file RowMyAds.java, RowMyPreferAds, ...
I see that in v0.8.0 many code have been trim that I don't know (no any comment, node in code decompiled)

Please fix it.

**Comment by asashour** [comment]
I guess this is fixed:

code in 0.7.1

```
/* compiled from: RowMyAds */
final class c extends com.generalUtils.ui.a.c<com.kiemvang.a.a, a> {

    /* compiled from: RowMyAds */
    static class a {
        ImageView a;
        TextView b;
        Button c;

        a(View view) {
            this.a = (ImageView) view.findViewById(com.kiemvang.b.a.imvIcon);
            this.b = (TextView) view.findViewById(com.kiemvang.b.a.tvTitle);
            this.c = (Button) view.findViewById(com.kiemvang.b.a.btnInstall);
        }
    }

    public final /* synthetic */ void a(android.view.View r4, java.lang.Object r5, int r6) {
        /* JADX: method processing error */
/*
Error: java.lang.NullPointerException
	at jadx.core.dex.visitors.regions.ProcessTryCatchRegions.searchTryCatchDominators(ProcessTryCatchRegions.java:75)
	at jadx.core.dex.visitors.regions.ProcessTryCatchRegions.process(ProcessTryCatchRegions.java:45)
	at jadx.core.dex.visitors.regions.RegionMakerVisitor.postProcessRegions(RegionMakerVisitor.java:63)
	at jadx.core.dex.visitors.regions.RegionMakerVisitor.visit(RegionMakerVisitor.java:58)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:31)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:17)
	at jadx.core.ProcessClass.process(ProcessClass.java:34)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:282)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
	at jadx.api.JavaClass.getCode(JavaClass.java:48)
*/
        /*
        r3 = this;
        r5 = (com.kiemvang.a.a) r5;
        r4 = 1;
        if (r6 == r4) goto L_0x0006;
    L_0x0005:
        goto L_0x004d;
    L_0x0006:
        r5 = r5.a;
        r6 = com.baseLibs.BaseApplication.h_();
        r0 = com.kiemvang.b.d.receive_200_gold_after_install;
        r4 = android.widget.Toast.makeText(r6, r0, r4);
        r4.show();
        com.kiemvang.TrackInstallReceiver.a();
        r4 = r3.b;	 Catch:{ ActivityNotFoundException -> 0x0033 }
        r6 = new android.content.Intent;	 Catch:{ ActivityNotFoundException -> 0x0033 }
        r0 = "android.intent.action.VIEW";	 Catch:{ ActivityNotFoundException -> 0x0033 }
        r1 = "market://details?id=";	 Catch:{ ActivityNotFoundException -> 0x0033 }
        r2 = java.lang.String.valueOf(r5);	 Catch:{ ActivityNotFoundException -> 0x0033 }
        r1 = r1.concat(r2);	 Catch:{ ActivityNotFoundException -> 0x0033 }
        r1 = android.net.Uri.parse(r1);	 Catch:{ ActivityNotFoundException -> 0x0033 }
        r6.<init>(r0, r1);	 Catch:{ ActivityNotFoundException -> 0x0033 }
        r4.startActivity(r6);	 Catch:{ ActivityNotFoundException -> 0x0033 }
        return;
    L_0x0033:
        r4 = r3.b;
        r6 = new android.content.Intent;
        r0 = "android.intent.action.VIEW";
        r1 = "http://play.google.com/store/apps/details?id=";
        r5 = java.lang.String.valueOf(r5);
        r5 = r1.concat(r5);
        r5 = android.net.Uri.parse(r5);
        r6.<init>(r0, r5);
        r4.startActivity(r6);
    L_0x004d:
        return;
        */
        throw new UnsupportedOperationException("Method not decompiled: com.kiemvang.c.a(android.view.View, java.lang.Object, int):void");
    }

    public final /* synthetic */ void a(Object obj, Object obj2, int i) {
        com.kiemvang.a.a aVar = (com.kiemvang.a.a) obj;
        a aVar2 = (a) obj2;
        aVar2.b.setText(aVar.b);
        i = BaseApplication.d();
        StringBuilder stringBuilder = new StringBuilder("http://learnlanguage.xyz/icon/");
        stringBuilder.append(aVar.a);
        stringBuilder.append(".png");
        i.a(stringBuilder.toString(), aVar2.a);
    }

    public c(Context context) {
        super(context, 2);
    }

    protected final View a(LayoutInflater layoutInflater, ViewGroup viewGroup) {
        return layoutInflater.inflate(b.row_native_thuong, viewGroup, false);
    }

    protected final /* synthetic */ Object a(View view) {
        return new a(view);
    }
}
```

Code in latest build:

```
/* compiled from: RowMyAds */
final class c extends com.generalUtils.ui.a.c<com.kiemvang.a.a, a> {

    /* compiled from: RowMyAds */
    static class a {
        ImageView a;
        TextView b;
        Button c;

        a(View view) {
            this.a = (ImageView) view.findViewById(com.kiemvang.b.a.imvIcon);
            this.b = (TextView) view.findViewById(com.kiemvang.b.a.tvTitle);
            this.c = (Button) view.findViewById(com.kiemvang.b.a.btnInstall);
        }
    }

    public final /* synthetic */ void a(View view, Object obj, int i) {
        com.kiemvang.a.a aVar = (com.kiemvang.a.a) obj;
        if (i == 1) {
            String str = aVar.a;
            Toast.makeText(BaseApplication.h_(), d.receive_200_gold_after_install, 1).show();
            TrackInstallReceiver.a();
            try {
                this.b.startActivity(new Intent("android.intent.action.VIEW", Uri.parse("market://details?id=".concat(String.valueOf(str)))));
            } catch (ActivityNotFoundException unused) {
                this.b.startActivity(new Intent("android.intent.action.VIEW", Uri.parse("http://play.google.com/store/apps/details?id=".concat(String.valueOf(str)))));
            }
        }
    }

    public final /* bridge */ /* synthetic */ void a(Object obj, com.generalUtils.ui.a.a.a.a.a.a aVar) {
        aVar.a(((a) obj).c, 1);
    }

    public final /* synthetic */ void a(Object obj, Object obj2, int i) {
        com.kiemvang.a.a aVar = (com.kiemvang.a.a) obj;
        a aVar2 = (a) obj2;
        aVar2.b.setText(aVar.b);
        com.b.a.b.d d = BaseApplication.d();
        StringBuilder sb = new StringBuilder("http://learnlanguage.xyz/icon/");
        sb.append(aVar.a);
        sb.append(".png");
        d.a(sb.toString(), aVar2.a);
    }

    public c(Context context) {
        super(context, 2);
    }

    /* access modifiers changed from: protected|final */
    public final View a(LayoutInflater layoutInflater, ViewGroup viewGroup) {
        return layoutInflater.inflate(b.row_native_thuong, viewGroup, false);
    }

    /* access modifiers changed from: protected|final|synthetic */
    public final /* synthetic */ Object a(View view) {
        return new a(view);
    }
}
```
