### ISSUE TITLE
GC Overhead Limit Reached When Decompiling APK

### ISSUE THREAD

**Issue by sledrho** [skylot/jadx#371]
Currently using JADX to decompile a relatively large android application that utilizes code obfuscation. Unfortunately when JADX starts to decompile the application it maxes out CPU utilisation at 98% and the following error can be seen in the terminal which started jadxgui. The application just hangs with a white screen and the process eventually has to be killed.

> Exception in thread "TimerQueue" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.awt.EventQueue.invokeLater(EventQueue.java:1294)
	at javax.swing.SwingUtilities.invokeLater(SwingUtilities.java:1295)
	at javax.swing.Timer$1.run(Timer.java:614)
	at javax.swing.Timer$1.run(Timer.java:612)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.swing.Timer.post(Timer.java:612)
	at javax.swing.TimerQueue.run(TimerQueue.java:186)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.Class.newReflectionData(Class.java:2511)
	at java.lang.Class.reflectionData(Class.java:2503)
	at java.lang.Class.getInterfaces(Class.java:845)
	at sun.awt.SunToolkit.isInstanceOf(SunToolkit.java:2068)
	at sun.awt.SunToolkit.isInstanceOf(SunToolkit.java:2073)
	at sun.awt.SunToolkit.isInstanceOf(SunToolkit.java:2073)
	at sun.awt.SunToolkit.isInstanceOf(SunToolkit.java:2073)
	at sun.awt.SunToolkit.isInstanceOf(SunToolkit.java:2058)
	at javax.swing.BufferStrategyPaintManager.fetchRoot(BufferStrategyPaintManager.java:573)
	at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:274)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
Exception in thread "pool-4-thread-1" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.HashMap.newNode(HashMap.java:1747)
	at java.util.HashMap.putVal(HashMap.java:631)
	at java.util.HashMap.put(HashMap.java:612)
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-4-thread-1"
Exception in thread "pool-4-thread-2" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "Timer-0" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-4-thread-3" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-4-thread-4" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-4-thread-5" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-4-thread-6" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-4-thread-7" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-4-thread-8" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "AWT-XAWT" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-4-thread-9" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-4-thread-10" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-4-thread-10"
Exception in thread "pool-4-thread-11" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-4-thread-12" java.lang.OutOfMemoryError: GC overhead limit exceeded

JADX Version: 0.8.0
System:  Xubuntu 18.04

**Comment by jpstotz** [comment]
Have you read the troubleshooting hints on the main page?
https://github.com/skylot/jadx#Troubleshooting

**Comment by sledrho** [comment]
> Have you read the troubleshooting hints on the main page?
> https://github.com/skylot/jadx#Troubleshooting

Yeah tried this but still running into the GC overhead issue.

**Comment by sergey-wowwow** [comment]
@sledrho How much memory did you specify thru ``` -Xmx ``` argument? It works great for all apps with ``` -Xmx16g ``` set

**Comment by sledrho** [comment]
> @sledrho How much memory did you specify thru `-Xmx` argument? It works great for all apps with `-Xmx16g` set

I'd set `-Xmx8g`, will try with 16gb and see!
