### ISSUE TITLE
Can't decode simple app for Android Pie

### ISSUE THREAD

**Issue by duanjason** [skylot/jadx#383]
I have a simple app that has a text field. I use Android Studio 3.2 to create it, target to API 28 (Android 9 Pie) and generate the apk.

I don't see the source when I use jadx-gui to open the apk. There are red X on the 2 dex files in the Resources folder as shown below.

<img width="256" alt="screen shot 2018-11-07 at 11 46 50 am" src="https://user-images.githubusercontent.com/22226876/48146387-dad7c600-e282-11e8-9ae5-92747030470e.png">

I got the below trace in the console:

INFO  - output directory: app-debug
INFO  - loading ...
ERROR - Failed to load file: classes.dex, error: Unexpected magic: [0x64, 0x65, 0x78, 0x0a, 0x30, 0x33, 0x39, 0x00]
com.android.dex.DexException: Unexpected magic: [0x64, 0x65, 0x78, 0x0a, 0x30, 0x33, 0x39, 0x00]
	at com.android.dex.TableOfContents.readHeader(TableOfContents.java:86)
	at com.android.dex.TableOfContents.readFrom(TableOfContents.java:72)
	at com.android.dex.Dex.loadFrom(Dex.java:142)
	at com.android.dex.Dex.<init>(Dex.java:98)
	at jadx.core.utils.files.InputFile.makeDexBuf(InputFile.java:150)
	at jadx.core.utils.files.InputFile.loadFromZip(InputFile.java:109)
	at jadx.core.utils.files.InputFile.searchDexFiles(InputFile.java:59)
	at jadx.core.utils.files.InputFile.addFilesFrom(InputFile.java:36)
	at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:124)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:87)
	at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:34)
	at jadx.gui.ui.MainWindow.openFile(MainWindow.java:172)
	at jadx.gui.ui.MainWindow.openFile(MainWindow.java:165)
	at jadx.gui.ui.MainWindow.open(MainWindow.java:127)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
ERROR - Failed to load file: classes2.dex, error: Unexpected magic: [0x64, 0x65, 0x78, 0x0a, 0x30, 0x33, 0x39, 0x00]
com.android.dex.DexException: Unexpected magic: [0x64, 0x65, 0x78, 0x0a, 0x30, 0x33, 0x39, 0x00]
	at com.android.dex.TableOfContents.readHeader(TableOfContents.java:86)
	at com.android.dex.TableOfContents.readFrom(TableOfContents.java:72)
	at com.android.dex.Dex.loadFrom(Dex.java:142)
	at com.android.dex.Dex.<init>(Dex.java:98)
	at jadx.core.utils.files.InputFile.makeDexBuf(InputFile.java:150)
	at jadx.core.utils.files.InputFile.loadFromZip(InputFile.java:109)
	at jadx.core.utils.files.InputFile.searchDexFiles(InputFile.java:59)
	at jadx.core.utils.files.InputFile.addFilesFrom(InputFile.java:36)
	at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:124)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:87)
	at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:34)
	at jadx.gui.ui.MainWindow.openFile(MainWindow.java:172)
	at jadx.gui.ui.MainWindow.openFile(MainWindow.java:165)
	at jadx.gui.ui.MainWindow.open(MainWindow.java:127)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
WARN  - Unknown 'R' class, create references to 'com.example.jasonxd.android_demo1.R'

The project is configurated as following:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    buildToolsVersion '28.0.2'
    defaultConfig {
        applicationId "com.example.jasonxd.android_demo1"
        minSdkVersion 28
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.android.support:design:28.0.0'
    testCompile 'junit:junit:4.12'
}

**Comment by skylot** [comment]
Please check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files). I merged #369 with updated dx version with dex 39 support. You will be able to open your apk, but some methods will be decompiled with errors, because jadx don't yet support new instructions added in dex 38 (#384) and dex 39 (#385)
