### ISSUE TITLE
Jadx-gui 0.8.0-b569-20b03aa fails on framework-res.apk (or any other .apk without classes.dex)

### ISSUE THREAD

**Issue by S-trace** [skylot/jadx#389]
Jadx-gui shows nothing on any framework-res.apk file.
The error messages is:
```
INFO  - output directory: framework-res
INFO  - loading ...
ERROR - Error load file: framework-res.apk
jadx.core.utils.exceptions.JadxRuntimeException: Error load file: framework-res.apk
        at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:125)
        at jadx.api.JadxDecompiler.load(JadxDecompiler.java:87)
        at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:34)
        at jadx.gui.ui.MainWindow.openFile(MainWindow.java:177)
        at jadx.gui.ui.MainWindow.open(MainWindow.java:134)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:715)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: jadx.core.utils.exceptions.DecodeException: Unsupported input file format: framework-res.apk
        at jadx.core.utils.files.InputFile.searchDexFiles(InputFile.java:81)
        at jadx.core.utils.files.InputFile.addFilesFrom(InputFile.java:36)
        at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:123)
        ... 19 common frames omitted
```

Doing following fixes this problem (jadx-gui shows resources and certificate after this actions):
```
touch classes.dex;zip framework-res.apk classes.dex
```

**Comment by skylot** [comment]
Oh, thanks! Now jadx open `.zip` file only if it contains `classes.dex`. I will fix that!

**Comment by sergey-wowwow** [comment]
@S-trace 
Seems the issue to be fixed. When I try to decompile framework-res.apk I see the following output
```
INFO  - loading ...
WARN  - No dex files found in framework-res.apk
INFO  - Can't find 'R' class in app package: android
INFO  - App 'R' class not found, put all resources ids to : 'android.R'
INFO  - processing ...
INFO  - done
```
Resources are saved, no errors

**Comment by georgedorn** [comment]
This continues to not work for me unless I add an empty `classes.dex` to my file.  I'm using release 0.9.0 and trying to decompile `ouya-framework.apk` for some timely reasons.

The workaround still works, though.
