### ISSUE TITLE
BlockSplitter.connectExceptionHandlers() throws NullPointerException

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#406]
Hi, this is a pretty popular exception, open ``` cn.jiguang.p026g.p028b.C0462c ```
and observe
```java

    /*  JADX ERROR: NullPointerException in pass: BlockSplitter
        java.lang.NullPointerException
        	at jadx.core.dex.visitors.blocksmaker.BlockSplitter.connectExceptionHandlers(BlockSplitter.java:243)
        	at jadx.core.dex.visitors.blocksmaker.BlockSplitter.setupConnections(BlockSplitter.java:226)
        	at jadx.core.dex.visitors.blocksmaker.BlockSplitter.splitBasicBlocks(BlockSplitter.java:116)
        	at jadx.core.dex.visitors.blocksmaker.BlockSplitter.visit(BlockSplitter.java:46)
        	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:27)
        	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
        	at java.base/java.util.ArrayList.forEach(ArrayList.java:1380)
        	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
        	at jadx.core.ProcessClass.process(ProcessClass.java:32)
        	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:292)
        	at jadx.api.JavaClass.decompile(JavaClass.java:62)
        	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:200)
        */
    /* renamed from: a */
    public static java.io.Serializable m7476a(android.content.SharedPreferences r6, java.lang.String r7, int r8) {
```
https://github.com/skylot/jadx/blob/master/jadx-core/src/main/java/jadx/core/dex/visitors/blocksmaker/BlockSplitter.java#L243

APK: 
https://drive.google.com/file/d/1lOYKfwbnVlOtyh6wUMQGoz5GMk8W7dXa/view?usp=sharing

**Comment by skylot** [comment]
@sergey-wowwow I can't find package `cn.jiguang` in apk you linked. Are you sure that it must be `com.airbnb.android.apk`?
Also the same problem in #405

**Comment by sergey-wowwow** [comment]
@skylot 
Yes, here is a screenshot
![image](https://user-images.githubusercontent.com/15173437/49702267-62f51680-fc07-11e8-8c78-3371df541353.png)

**Comment by skylot** [comment]
@sergey-wowwow I see, you gave the link to the previous version (18.31). But I found a class and reproduce an issue in the latest version (18.43).
Anyway thank you for the report :)

**Comment by sergey-wowwow** [comment]
@skylot 
Seems that it fails in each static initializer :( Can you look at this?

**Comment by skylot** [comment]
@sergey-wowwow I made a fix for NPE, but this method still decompiled incorrectly due to complex try/catch structure, so it is hard to understand the cause of the problem.
Anyway I hope NPE fix will help for other cases.

**Comment by skylot** [comment]
@sergey-wowwow done )
