### ISSUE TITLE
Method generation error (Error generate insn)

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#413]
Hi, method ``` com.vk.dto.polls.PollBackground.G_(...) ``` (and a lot of other classes which implement ``` com.vk.core.serialize.JSONSerialize ```)
and code
```java
    public org.json.JSONObject G_() {
        org.json.JSONObject jSONObject = new org.json.JSONObject();
        try {
            java.lang.String l = java.lang.Long.toString(f32099b.mo29678a(this.f32101c), kotlin.text.CharJVM.m120894a(
/*
Method generation error in method: com.vk.dto.polls.PollBackground.G_():org.json.JSONObject, dex: classes2.dex
jadx.core.utils.exceptions.CodegenException: Error generate insn: 0x001d: INVOKE  (r3:2 'l' java.lang.String) = (wrap: long
  0x0013: INVOKE  (r3:1 long) = (wrap: com.vk.dto.polls.PollBackground$a
  0x000f: SGET  (r3:0 com.vk.dto.polls.PollBackground$a) =  com.vk.dto.polls.PollBackground.b com.vk.dto.polls.PollBackground$a), (wrap: int
  0x0011: IGET  (r4:0 int) = (r6:0 'this' com.vk.dto.polls.PollBackground A[THIS]) com.vk.dto.polls.PollBackground.c int) com.vk.dto.polls.PollBackground.a.a(int):long type: VIRTUAL), (wrap: int
  0x0019: INVOKE  (r5:1 int) = (16 int) kotlin.text.a.a(int):int type: STATIC) java.lang.Long.toString(long, int):java.lang.String type: STATIC in method: com.vk.dto.polls.PollBackground.G_():org.json.JSONObject, dex: classes2.dex
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:227)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:204)
	at jadx.core.codegen.RegionGen.makeSimpleBlock(RegionGen.java:100)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:50)
	at jadx.core.codegen.RegionGen.makeSimpleRegion(RegionGen.java:87)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:53)
	at jadx.core.codegen.RegionGen.makeRegionIndent(RegionGen.java:93)
	at jadx.core.codegen.RegionGen.makeTryCatch(RegionGen.java:278)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:63)
	at jadx.core.codegen.RegionGen.makeSimpleRegion(RegionGen.java:87)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:53)
	at jadx.core.codegen.MethodGen.addInstructions(MethodGen.java:173)
	at jadx.core.codegen.ClassGen.addMethod(ClassGen.java:321)
	at jadx.core.codegen.ClassGen.addMethods(ClassGen.java:259)
	at jadx.core.codegen.ClassGen.addClassBody(ClassGen.java:221)
	at jadx.core.codegen.ClassGen.addClassCode(ClassGen.java:111)
	at jadx.core.codegen.ClassGen.makeClass(ClassGen.java:77)
	at jadx.core.codegen.CodeGen.visit(CodeGen.java:10)
	at jadx.core.ProcessClass.process(ProcessClass.java:38)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:292)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:200)
Caused by: jadx.core.utils.exceptions.CodegenException: Error generate insn: 0x0019: INVOKE  (r5:1 int) = (16 int) kotlin.text.a.a(int):int type: STATIC in method: com.vk.dto.polls.PollBackground.G_():org.json.JSONObject, dex: classes2.dex
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:227)
	at jadx.core.codegen.InsnGen.addArg(InsnGen.java:100)
	at jadx.core.codegen.InsnGen.generateMethodArguments(InsnGen.java:675)
	at jadx.core.codegen.InsnGen.makeInvoke(InsnGen.java:645)
	at jadx.core.codegen.InsnGen.makeInsnBody(InsnGen.java:339)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:221)
	... 21 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
	at java.base/java.util.Collections$EmptyList.get(Collections.java:4470)
	at jadx.core.codegen.InsnGen.processOverloadedArg(InsnGen.java:697)
	at jadx.core.codegen.InsnGen.generateMethodArguments(InsnGen.java:671)
	at jadx.core.codegen.InsnGen.makeInvoke(InsnGen.java:645)
	at jadx.core.codegen.InsnGen.makeInsnBody(InsnGen.java:339)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:212)
	... 26 more

*/
}
```

APK: https://drive.google.com/open?id=1FrdZasoIOrlXp4PTsPy483DOympXcEm_

**Comment by skylot** [comment]
@sergey-wowwow made a fix in `type-inference-wip` branch.
Codegen use incorrect class for call inherited static method (see [this test](https://github.com/skylot/jadx/blob/6a1717a6241f5aec3c9d5a18b539fccea12f1a9d/jadx-core/src/test/java/jadx/tests/integration/invoke/TestInheritedStaticInvoke.java#L24) for example).
