### ISSUE TITLE
Stuck on 'EDGE_INSN: B:32:0x001f->B:12:0x001f ?: BREAK  , EDGE_INSN: B:32:0x001f->B:12:0x001f ?: BREAK  , EDGE_INSN: B:32:0x001f->B:12:0x001f ?: BREAK"

### ISSUE THREAD

**Issue by arya6000** [skylot/jadx#422]
Jadx 0.8.0 gets stuck on 

`EDGE_INSN: B:32:0x001f->B:12:0x001f ?: BREAK  , EDGE_INSN: B:32:0x001f->B:12:0x001f ?: BREAK  , EDGE_INSN: B:32:0x001f->B:12:0x001f ?: BREAK`

in a endless loop until exception is thrown for lack of memory

```

 EDGE_INSN: B:32:0x001f->B:12:0x001f ?: BREAK  , EDGE_INSN: B:32:0x001f->B:12:0x001f ?: BREAK  , EDGE_INSN: B:32:0x001f->B:12:0x001f ?: BREAK  , EDGE_INSN: B:32:0x001f->B:12:0x001f ?: BREAK  , EDGE_INSN: B:32:0x001f->B:12:0x001f ?: BREAK  , EDGE_INSN: B:32:0x001f->B:12:0x001f ?: BREAK  , EDGE_INSN: B:32:0x001f->B:12:0x001f ?: BREAK  , EDGE_INSN: B:32:0x001f->B:12:0x001f ?: BREAK  , EDGE_INSN: B:32:0x001f->B:12:0x001f ?: BREAK  , EDGE_INSN: B:32:0x001f->B:12:0x001f ?: BREAK  , EDGE_INSN: B:32:0x001f->B:12:0x001f ?: BREAK  , EDGE_INSN: B:32:0x001f->B:12:0x001f ?: BREAK  , EDGE_INSN: B:32:0x001f->B:12:0x001f ?: BREAK  , EDGE_INSN: B:32:0x001f->B:12:0x001f ?: BREAK  , EDGE_INSN: B:32:0x001f->B:12:0x001f ?: BREAK  } in method: org.joda.time.convert.d.a(java.lang.Class):org.joda.time.convert.Converter, dex: classes5.dex
WARN  - Removed duplicated region for block: B:5:0x0012  in method: org.joda.time.convert.d.a(java.lang.Class):org.joda.time.convert.Converter, dex: classes5.dex
ERROR - Error saving class: org.joda.time.convert.d
jadx.core.utils.exceptions.JadxRuntimeException: Code not generated for class org.joda.time.convert.d
	at jadx.core.dex.visitors.SaveCode.save(SaveCode.java:21)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:202)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-1-thread-3" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:207)
	at java.lang.StringBuilder.toString(StringBuilder.java:407)
	at java.util.Formatter.toString(Formatter.java:2355)
	at java.lang.String.format(String.java:2940)
	at jadx.core.utils.InsnUtils.formatOffset(InsnUtils.java:48)
	at jadx.core.dex.nodes.BlockNode.toString(BlockNode.java:195)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at jadx.core.dex.attributes.nodes.EdgeInsnAttr.toString(EdgeInsnAttr.java:46)
	at jadx.core.utils.Utils$$Lambda$40/1256563195.apply(Unknown Source)
	at jadx.core.utils.Utils.listToString(Utils.java:56)
	at jadx.core.utils.Utils.listToString(Utils.java:43)
	at jadx.core.utils.Utils.listToString(Utils.java:35)
	at jadx.core.dex.attributes.AttrList.toString(AttrList.java:28)
	at jadx.core.dex.attributes.AttributeStorage.getAttributeStrings(AttributeStorage.java:109)
	at jadx.core.dex.attributes.AttributeStorage.toString(AttributeStorage.java:120)
	at jadx.core.dex.attributes.AttrNode.getAttributesString(AttrNode.java:97)
	at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:78)
	at jadx.core.dex.visitors.regions.RegionMaker.processIf(RegionMaker.java:655)
	at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:122)
	at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:85)
	at jadx.core.dex.visitors.regions.RegionMaker.processLoop(RegionMaker.java:209)
	at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:105)
	at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:85)
	at jadx.core.dex.visitors.regions.RegionMakerVisitor.visit(RegionMakerVisitor.java:49)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:27)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
	at jadx.core.dex.visitors.DepthTraversal$$Lambda$11/765024237.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
	at jadx.core.ProcessClass.process(ProcessClass.java:32)
Exception in thread "pool-1-thread-2" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.sun.imageio.plugins.png.PNGImageWriter.encodePass(PNGImageWriter.java:817)
	at com.sun.imageio.plugins.png.PNGImageWriter.write_IDAT(PNGImageWriter.java:942)
	at com.sun.imageio.plugins.png.PNGImageWriter.write(PNGImageWriter.java:1158)
	at javax.imageio.ImageWriter.write(ImageWriter.java:615)
	at javax.imageio.ImageIO.doWrite(ImageIO.java:1612)
	at javax.imageio.ImageIO.write(ImageIO.java:1536)
	at jadx.core.xmlgen.ResourcesSaver.save(ResourcesSaver.java:71)
	at jadx.core.xmlgen.ResourcesSaver.saveResources(ResourcesSaver.java:48)
	at jadx.core.xmlgen.ResourcesSaver.run(ResourcesSaver.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-1-thread-5" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.awt.image.ComponentSampleModel.<init>(ComponentSampleModel.java:150)
	at java.awt.image.PixelInterleavedSampleModel.<init>(PixelInterleavedSampleModel.java:87)
	at java.awt.image.PixelInterleavedSampleModel.createCompatibleSampleModel(PixelInterleavedSampleModel.java:144)
	at java.awt.image.BufferedImage.getData(BufferedImage.java:1448)
	at com.sun.imageio.plugins.png.PNGImageWriter.encodePass(PNGImageWriter.java:818)
	at com.sun.imageio.plugins.png.PNGImageWriter.write_IDAT(PNGImageWriter.java:942)
	at com.sun.imageio.plugins.png.PNGImageWriter.write(PNGImageWriter.java:1158)
	at javax.imageio.ImageWriter.write(ImageWriter.java:615)
	at javax.imageio.ImageIO.doWrite(ImageIO.java:1612)
	at javax.imageio.ImageIO.write(ImageIO.java:1536)
	at jadx.core.xmlgen.ResourcesSaver.save(ResourcesSaver.java:71)
	at jadx.core.xmlgen.ResourcesSaver.saveResources(ResourcesSaver.java:48)
	at jadx.core.xmlgen.ResourcesSaver.run(ResourcesSaver.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-1-thread-4" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.awt.image.PixelInterleavedSampleModel.createCompatibleSampleModel(PixelInterleavedSampleModel.java:144)
	at java.awt.image.BufferedImage.getData(BufferedImage.java:1448)
	at com.sun.imageio.plugins.png.PNGImageWriter.encodePass(PNGImageWriter.java:818)
	at com.sun.imageio.plugins.png.PNGImageWriter.write_IDAT(PNGImageWriter.java:942)
	at com.sun.imageio.plugins.png.PNGImageWriter.write(PNGImageWriter.java:1158)
	at javax.imageio.ImageWriter.write(ImageWriter.java:615)
	at javax.imageio.ImageIO.doWrite(ImageIO.java:1612)
	at javax.imageio.ImageIO.write(ImageIO.java:1536)
	at jadx.core.xmlgen.ResourcesSaver.save(ResourcesSaver.java:71)
	at jadx.core.xmlgen.ResourcesSaver.saveResources(ResourcesSaver.java:48)
	at jadx.core.xmlgen.ResourcesSaver.run(ResourcesSaver.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-1-thread-1" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-1-thread-8" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-1-thread-7" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "pool-1-thread-11" java.lang.OutOfMemoryError: GC overhead limit exceeded

```

**Comment by skylot** [comment]
@arya6000 can you attach apk file so I can reproduce this problem? Repeated `EDGE_INSN` is not normal and can be a result of an infinite loop while processing loop :(

**Comment by rocco8620** [comment]
This apk replicates the problem 
https://drive.google.com/open?id=11i9O-vS4NfM34zOxcAdM0hTRCF0WpSrC
@skylot

**Comment by asashour** [comment]
Can you check with latest [build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files), I couldn't get this infinite loop from GUI.
