### ISSUE TITLE
JADX ERROR: JadxOverflowException in pass: BlockProcessor

### ISSUE THREAD

**Issue by jzk4khan** [skylot/jadx#441]
Hi i trying to decompile an apk using jadx-gui-0.8.0-b642-8c7140d6 all other code decompile but one of the class not compiling and throwing this exception

JADX ERROR: JadxOverflowException in pass: BlockProcessor
        jadx.core.utils.exceptions.JadxOverflowException: Failed compute block dominance frontier
        	at jadx.core.utils.ErrorsCounter.addError(ErrorsCounter.java:48)
        	at jadx.core.utils.ErrorsCounter.methodError(ErrorsCounter.java:82)
        	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:29)
        	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
        	at java.base/java.util.ArrayList.forEach(Unknown Source)
        	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
        	at jadx.core.ProcessClass.process(ProcessClass.java:32)
        	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:292)
        	at jadx.api.JavaClass.decompile(JavaClass.java:62)
        	at jadx.api.JavaClass.getCode(JavaClass.java:48)

i m attaching the apk file and class name is g
[speed.zip](https://github.com/skylot/jadx/files/2854911/speed.zip)

**Comment by jzk4khan** [comment]
Have you find any solution regarding this issue??

**Comment by skylot** [comment]
@jzk4khan this method is very big and has many different issues, so I don't think I will able to fix them all, sorry :(

**Comment by jzk4khan** [comment]
Please try it. I want this code. i will be very thank full to you. Please take a look again i need it badly

**Comment by jzk4khan** [comment]
Hello, Please tell me about my issue is Problem Solved ??

**Comment by skylot** [comment]
@jzk4khan no, I fixed some issues, but some not yet solved. 
Anyway, you can view inconsistent code and it is very close to correct one, check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files).
And I can't fix other issues because method is very big and I can't view CFG, all programs just hangup (`dot` from GraphViz for example), so I will close this issue, sorry.
