### ISSUE TITLE
JadxArgsValidateException Output directory exists as file

### ISSUE THREAD

**Issue by otwayz** [skylot/jadx#447]
jadx.core.utils.exceptions.JadxArgsValidateException: Output directory exists as file /Users/gucheng/Downloads/qianji.apk

please help me, I have uninstall and clone install many times, but can not fix this error.

I can not find the out dir. 

求助，已经不能够正常使用了，用了下 网上推荐的 jadx-gui -d out ***.apk 命令。

删除  重新安装都没啥用。

**Comment by otwayz** [comment]
@skylot

**Comment by sergey-wowwow** [comment]
> -d out ***.apk

Use different value for ``` -d ``` parameter

**Comment by otwayz** [comment]
> > -d out ***.apk
> 
> Use different value for `-d` parameter

I try many different apks , but always this error

**Comment by skylot** [comment]
@otwayz I can't reproduce your issue. 
Maybe you need to escape some characters in your file name or put it inside quotes (like `jadx-gui "app.apk"`)
Please add `-v` option and post full command line and full output, also post jadx version you use?

P.S. I don't see the reason to add `-d` option to jadx-gui, because output path will be asked on export start.

**Comment by sergey-wowwow** [comment]
I believe he tries to use ``` -d app.apk ```

**Comment by otwayz** [comment]
I use `jadx-gui` in command line and select app.apk by file system. This error  occured.  Maybe I have used error command and dirty the jadx env.  What can I do to clean the jadx env?

**Comment by otwayz** [comment]
```
./jadx-gui -v ~/Downloads/release/app-google-release.apk
ERROR - Error load file: /Users/gucheng/Downloads/release/app-google-release.apk
jadx.core.utils.exceptions.JadxArgsValidateException: Output directory exists as file /Users/gucheng/Downloads/qianji.apk
	at jadx.api.JadxArgsValidator.checkDir(JadxArgsValidator.java:102)
	at jadx.api.JadxArgsValidator.validateOutDirs(JadxArgsValidator.java:62)
	at jadx.api.JadxArgsValidator.validate(JadxArgsValidator.java:18)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:83)
	at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:36)
	at jadx.gui.ui.MainWindow.openFile(MainWindow.java:187)
	at jadx.gui.ui.MainWindow.open(MainWindow.java:144)
	at jadx.gui.JadxGUI$$Lambda$16/741669172.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
DEBUG - Loaded settings: {"lastOpenFilePath":"/Users/gucheng/Downloads/release","lastSaveFilePath":"/Users/gucheng","flattenPackage":false,"checkForUpdates":false,"recentFiles":["/Users/gucheng/Downloads/release/classes.dex","/Users/gucheng/Downloads/release/classes2.dex","/Users/gucheng/Downloads/release/app-google-release.apk","/Users/gucheng/Downloads/qianji.apk","/Users/gucheng/Downloads/biquge.apk","/Users/gucheng/tools/jadx-0.8.0/bin/dr"],"fontStr":"","editorThemePath":"/org/fife/ui/rsyntaxtextarea/themes/default.xml","langLocale":{"locale":"zh_CN"},"autoStartJobs":false,"excludedPackages":"","showHeapUsageBar":true,"settingsVersion":7,"windowPos":{"SearchDialog":{"windowId":"SearchDialog","x":440,"y":286,"width":800,"height":500}},"outDir":"out","outDirRes":"/Users/gucheng/Downloads/qianji.apk","skipResources":false,"skipSources":false,"exportAsGradleProject":false,"threadsCount":1,"showInconsistentCode":false,"useImports":true,"replaceConsts":true,"escapeUnicode":false,"respectBytecodeAccessModifiers":false,"deobfuscationOn":false,"deobfuscationMinLength":3,"deobfuscationMaxLength":64,"deobfuscationForceSave":true,"deobfuscationUseSourceNameAsAlias":true,"cfgOutput":false,"rawCfgOutput":false,"fallbackMode":false,"printVersion":false}
DEBUG - Saving settings: {"lastOpenFilePath":"/Users/gucheng/Downloads/release","lastSaveFilePath":"/Users/gucheng","flattenPackage":false,"checkForUpdates":false,"recentFiles":["/Users/gucheng/Downloads/release/app-google-release.apk","/Users/gucheng/Downloads/release/classes.dex","/Users/gucheng/Downloads/release/classes2.dex","/Users/gucheng/Downloads/qianji.apk","/Users/gucheng/Downloads/biquge.apk","/Users/gucheng/tools/jadx-0.8.0/bin/dr"],"fontStr":"","editorThemePath":"/org/fife/ui/rsyntaxtextarea/themes/default.xml","langLocale":{"locale":"zh_CN"},"autoStartJobs":false,"excludedPackages":"","showHeapUsageBar":true,"settingsVersion":7,"windowPos":{"SearchDialog":{"windowId":"SearchDialog","x":440,"y":286,"width":800,"height":500}},"outDir":"out","outDirRes":"/Users/gucheng/Downloads/qianji.apk","skipResources":false,"skipSources":false,"exportAsGradleProject":false,"threadsCount":1,"showInconsistentCode":false,"useImports":true,"replaceConsts":true,"escapeUnicode":false,"respectBytecodeAccessModifiers":false,"deobfuscationOn":false,"deobfuscationMinLength":3,"deobfuscationMaxLength":64,"deobfuscationForceSave":true,"deobfuscationUseSourceNameAsAlias":true,"cfgOutput":false,"rawCfgOutput":false,"fallbackMode":false,"printVersion":false}
```

This is detail info . in this log, the out dir is my first time to  use jadx to decompile apk, but that maybe 15 days ago.

**Comment by otwayz** [comment]
Oh ,  I only delete the first time decompiled apk file `"outDirRes":"/Users/gucheng/Downloads/qianji.apk"` , The error fixed !   Thanks for your help,  maybe you need init the env when error occured.

**Comment by skylot** [comment]
@otwayz thank you! Output directories must not be saved in settings, I have fixed that in latest commit.
And if you want to reset jadx-gui settings you can press `Reset` button in the settings dialog, this is another solution for your issue.
