### ISSUE TITLE
Not initialized variable reg 

### ISSUE THREAD

**Issue by jpstotz** [skylot/jadx#468]
APK: [WhatsApp Messenger_v2.19.53](https://apkpure.com/de/whatsapp-messenger/com.whatsapp/download/452688-APK?from=variants%2Fversion)

Class: `com.whatsapp.messaging.m`
Method: `final void a(java.net.InetSocketAddress r11, int r12, boolean r13, com.whatsapp.util.a.a<java.net.Socket> r14)`

The decompilation fails with the message:

```
JADX ERROR: JadxRuntimeException in pass: SSATransform
        jadx.core.utils.exceptions.JadxRuntimeException: Not initialized variable reg: 6, insn: 0x0033: INVOKE  (r0 java.net.InetAddress) = (r6 java.net.InetSocketAddress) java.net.InetSocketAddress.getAddress():java.net.InetAddress type: VIRTUAL, block:B:15:0x002c
        	at jadx.core.dex.visitors.ssa.SSATransform.renameVarsInBlock(SSATransform.java:157)
        	at jadx.core.dex.visitors.ssa.SSATransform.renameVariables(SSATransform.java:129)
        	at jadx.core.dex.visitors.ssa.SSATransform.process(SSATransform.java:51)
        	at jadx.core.dex.visitors.ssa.SSATransform.visit(SSATransform.java:41)
        	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:27)
        	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
        	at java.util.ArrayList.forEach(ArrayList.java:1257)
        	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
        	at jadx.core.ProcessClass.process(ProcessClass.java:32)
        	at jadx.core.ProcessClass.lambda$processDependencies$0(ProcessClass.java:51)
        	at java.lang.Iterable.forEach(Iterable.java:75)
        	at jadx.core.ProcessClass.processDependencies(ProcessClass.java:51)
        	at jadx.core.ProcessClass.process(ProcessClass.java:37)
        	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:292)
        	at jadx.api.JavaClass.decompile(JavaClass.java:62)
```

However looking at the code dump `r6` is assigned right at the beginning of the method:

```
final void a(java.net.InetSocketAddress r11, int r12, boolean r13, com.whatsapp.util.a.a<java.net.Socket> r14) {
        r10 = this;
        r3 = 1;
        r6 = r11;	 Catch:{ IOException | ClassCastException -> 0x001e, all -> 0x005c }
```

Therefore it is impossible for `r6` not to be initialized - or do I oversee something?

**Comment by jpstotz** [comment]
I had to look at the smali code to fully understand what you mean. From my understanding the problem is that Jadx assumes that the first assignment to a register is equivalent to an variable declaration + assignment in Java. And if this declaration happens inside a try-catch environment the variable is limited to this section. However on smali/dex level we have registers and registers don't stop being valid when we are leaving the try-catch section it has been defined in.

Therefore moving the code for r6 initialization outside of the try-catch block would work as it can't throw any exception. However when moving an instruction around you really have to be carefully with potential goto labels at the beginning of the try-catch block. Otherwise you may alter the code semantics.

**Comment by skylot** [comment]
No, jadx don't apply any java scopes to registers. I mean different branches in CFG, jadx make exception handler branch before start of try/catch block to correctly treat registers liveness and values if the exception is thrown from first instruction without moving result or executing other instructions.
CFG of this method:
![cfg](https://user-images.githubusercontent.com/118523/54614006-bda2d780-4a6c-11e9-9d13-42f20a65e88c.png)
I made a fix for that in a recent commit.

But that is **not** main issue here, I was wrong (((
There is a missing edge from end of try block to exception handler (
Now I am trying to write small test case to reproduce it.
