### ISSUE TITLE
gui: "Text Search" does not show any window

### ISSUE THREAD

**Issue by asashour** [skylot/jadx#501]
In `master`, whenever any APK is opened in GUI, I can't open the "Text Search", there is a logged error, but I am not sure if it is related.

Is it only me? Since it wasn't there few days back

```
ERROR - Failed to parse '.arsc' file
jadx.core.utils.exceptions.JadxException: Error decode: resources.arsc
	at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:76)
	at jadx.core.dex.nodes.RootNode.loadResources(RootNode.java:84)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:91)
	at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:39)
	at jadx.gui.ui.MainWindow.openFile(MainWindow.java:203)
	at jadx.gui.ui.MainWindow.openFile(MainWindow.java:196)
	at jadx.gui.ui.MainWindow.open(MainWindow.java:158)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.IOException: Expected entry start, expected offset: 0x717b0, actual: 0x717af
	at jadx.core.xmlgen.ParserStream.checkPos(ParserStream.java:123)
	at jadx.core.xmlgen.ResTableParser.parseTypeChunk(ResTableParser.java:210)
	at jadx.core.xmlgen.ResTableParser.parsePackage(ResTableParser.java:167)
	at jadx.core.xmlgen.ResTableParser.decodeTableChunk(ResTableParser.java:114)
	at jadx.core.xmlgen.ResTableParser.decode(ResTableParser.java:62)
	at jadx.core.dex.nodes.RootNode.lambda$0(RootNode.java:86)
	at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:71)
	... 20 common frames omitted

```

**Comment by asashour** [comment]
Please see #500, as a first step.

**Comment by skylot** [comment]
Looks like `Error decode: resources.arsc` exception was introduced in PR #487.
But I don't think it is related to text search window, because parsing executed of file open.

**Comment by skylot** [comment]
@asashour I made a fix for resource decoding exception. Can you check your issue with search dialog? If it still exists I need a way to reproduce it, because it works well for me.

**Comment by asashour** [comment]
Thanks, but I still have the issue, possibly because I am now not with the docking station, so the window may be somewhere else. I would check this on Monday again.

Steps:

1. Open GUI
2. Open file
3. Go to any class, to see its code
4. Navigation -> Text Search
5. "Decompiling" is progressing
6. "Indexing" is progressing
7. Nothing happens.

Expected: a window to search for the text.

This also happens for the "Class Search"

**Comment by skylot** [comment]
This is strange, and I can't reproduce it.
Only I can suggest is to reset settings ("Reset" button in preference dialog), because jadx save position and size of all windows, maybe somehow was saved zero size or wrong location. Or, check that values in Tools -> Log Viewer -> change log level to Debug and check first string started with `Loaded settings: ` at `"windowPos"` variable. Hope we will find the source of this issue.

**Comment by asashour** [comment]
Thanks, that solves it.

I guess this is potential enhancement, to check if the values are outside the current resolution.

I am closing this for now.
