### ISSUE TITLE
jadx.core.utils.exceptions.DecodeException: Error decode class: 

### ISSUE THREAD

**Issue by bunnyblue** [skylot/jadx#57]
jadx.core.utils.exceptions.DecodeException: Error decode class: android.support.v4.app.ActivityCompat
	at jadx.core.dex.nodes.ClassNode.<init>(ClassNode.java:135) ~[jadx-core-0.5.5-dev.jar:na]
	at jadx.core.dex.nodes.DexNode.loadClasses(DexNode.java:53) ~[jadx-core-0.5.5-dev.jar:na]
	at jadx.core.dex.nodes.RootNode.load(RootNode.java:56) ~[jadx-core-0.5.5-dev.jar:na]
	at jadx.api.JadxDecompiler.parse(JadxDecompiler.java:261) ~[jadx-core-0.5.5-dev.jar:na]
	at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:118) ~[jadx-core-0.5.5-dev.jar:na]
	at jadx.api.JadxDecompiler.loadFile(JadxDecompiler.java:103) ~[jadx-core-0.5.5-dev.jar:na]
	at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:32) ~[jadx-gui-0.5.5-dev.jar:na]
	at jadx.gui.ui.MainWindow.openFile(MainWindow.java:164) [jadx-gui-0.5.5-dev.jar:na]
	at jadx.gui.ui.MainWindow.open(MainWindow.java:123) [jadx-gui-0.5.5-dev.jar:na]
	at jadx.gui.JadxGUI$1.run(JadxGUI.java:27) [jadx-gui-0.5.5-dev.jar:na]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [na:1.8.0_31]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749) [na:1.8.0_31]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [na:1.8.0_31]
	at java.awt.EventQueue$3.run(EventQueue.java:702) [na:1.8.0_31]
	at java.awt.EventQueue$3.run(EventQueue.java:696) [na:1.8.0_31]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_31]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75) [na:1.8.0_31]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719) [na:1.8.0_31]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_31]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_31]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_31]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_31]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_31]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_31]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 24
	at jadx.core.dex.nodes.parser.AnnotationsParser.readAnnotation(AnnotationsParser.java:89) ~[jadx-core-0.5.5-dev.jar:na]
	at jadx.core.dex.nodes.parser.AnnotationsParser.readAnnotationSet(AnnotationsParser.java:79) ~[jadx-core-0.5.5-dev.jar:na]
	at jadx.core.dex.nodes.parser.AnnotationsParser.parse(AnnotationsParser.java:67) ~[jadx-core-0.5.5-dev.jar:na]
	at jadx.core.dex.nodes.ClassNode.loadAnnotations(ClassNode.java:154) ~[jadx-core-0.5.5-dev.jar:na]
	at jadx.core.dex.nodes.ClassNode.<init>(ClassNode.java:107) ~[jadx-core-0.5.5-dev.jar:na]
	... 23 common frames omitted

**Comment by skylot** [comment]
Hello,
Can you provide link to .apk or .dex file you trying to decompile, because it is unclear how to fix this issue.

**Comment by bunnyblue** [comment]
https://drive.google.com/file/d/0B4IvHmkRqgS4UXFTdktmdXVYTHc/view?usp=sharing  
I upload dex to Google Driver
