### ISSUE TITLE
NullPointerException in pass: ModVisitor

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#595]
Hi, jadx throws a NPE in ``` com/paypal/android/foundation/presentation/operations/BiometricAuthenticatorsDeregistrationOperation.java ```
```java
    /*  JADX ERROR: NullPointerException in pass: ModVisitor
        java.lang.NullPointerException
        	at jadx.core.dex.visitors.ModVisitor.getParentInsnSkipMove(ModVisitor.java:284)
        	at jadx.core.dex.visitors.ModVisitor.getArgsToFieldsMapping(ModVisitor.java:258)
        	at jadx.core.dex.visitors.ModVisitor.processAnonymousConstructor(ModVisitor.java:209)
        	at jadx.core.dex.visitors.ModVisitor.replaceStep(ModVisitor.java:79)
        	at jadx.core.dex.visitors.ModVisitor.visit(ModVisitor.java:66)
        	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:27)
        	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
        	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
        	at jadx.core.ProcessClass.process(ProcessClass.java:30)
        	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:290)
        	at jadx.api.JavaClass.decompile(JavaClass.java:62)
        	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:196)
        */
    BiometricAuthenticatorsDeregistrationOperation(java.lang.String r1, java.util.List<com.paypal.android.foundation.auth.model.Authenticators> r2) {
        /*
        r0 = this;
        r0.m28836init(r1)
        r0.mAuthenticatorsList = r2
        return
        */
        throw new UnsupportedOperationException("Method not decompiled: com.paypal.android.foundation.presentation.operations.BiometricAuthenticatorsDeregistrationOperation.m28834init(java.lang.String, java.util.List):void");
    }
```

APK: https://drive.google.com/file/d/16O--dtXt35zB1Ahx-9qEYvCmyeF1n0AG/view?usp=sharing

**Comment by asashour** [comment]
Can't reproduced with `master`, possibly fixed in https://github.com/skylot/jadx/commit/4cb9f23a7ddaea5509db27f4e5ca57849546bbb6

**Comment by sergey-wowwow** [comment]
@asashour 
It doesn't trigger all the time. Please try to use jadx-cli with arguments
```
--no-replace-consts --show-bad-code --threads-count 8 --deobf --deobf-min 2 --no-imports --deobf-rewrite-cfg
```

**Comment by sergey-wowwow** [comment]
@skylot 
Thanks! Fixed!
