### ISSUE TITLE
Some classes are not decompiled because of OutOfMemoryError

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#604]
Hi, I've noticed that some classes e.g. ``` kz.kaspi.mobile.core.NavigationActivity ``` (you can see it in jadx-gui, but it will never open) are missing. I've assigned ``` -Xmx32g ``` to jadx when launched, but anyway it's not enough. I believe here is a bug. Stack trace
```
Exception in thread "pool-1-thread-5" Exception in thread "pool-1-thread-4" Exception in thread "pool-1-thread-2" java.lang.OutOfMemoryError
        at java.base/java.lang.AbstractStringBuilder.hugeCapacity(AbstractStringBuilder.java:214)
        at java.base/java.lang.AbstractStringBuilder.newCapacity(AbstractStringBuilder.java:206)
        at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:173)
        at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:538)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:174)
        at jadx.core.codegen.CodeWriter.addLineIndent(CodeWriter.java:152)
        at jadx.core.codegen.CodeWriter.startLine(CodeWriter.java:61)
        at jadx.core.codegen.CodeWriter.startLineWithNum(CodeWriter.java:81)
        at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:221)
        at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:210)
        at jadx.core.codegen.RegionGen.makeSimpleBlock(RegionGen.java:109)
        at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:55)
        at jadx.core.codegen.RegionGen.makeSimpleRegion(RegionGen.java:92)
        at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:58)
        at jadx.core.codegen.MethodGen.addInstructions(MethodGen.java:196)
        at jadx.core.codegen.ClassGen.addMethod(ClassGen.java:325)
        at jadx.core.codegen.ClassGen.addMethods(ClassGen.java:262)
        at jadx.core.codegen.ClassGen.addClassBody(ClassGen.java:224)
        at jadx.core.codegen.InsnGen.inlineAnonymousConstructor(InsnGen.java:617)
```

APK: https://drive.google.com/file/d/1GGRxg2nMzUNAZqDXjIamg0Zdso-gvcz2/view?usp=sharing

**Comment by jpstotz** [comment]
This app contains some really mind-twisting code:

Using the latest Jadx code from master I am getting a StackoverflowError when Jadx tries to process `kz.kaspi.mobile.core.NavigationActivity$onRegionSelected$1.<init>`. There seems to an endless loop.

I assume this is because Jadx rekognizes `kz.kaspi.mobile.core.NavigationActivity$onRegionSelected$1` as anonymous inner class. 
In it's `create(..)` method it creates another instance of itself - which should be as far as I know impossible for a regular Java anonymous inner class. Therefore Jadx assumes that the anonymous inner class is defined where it's constructor is called and starts to build this class which ends up in the endless loop. 

However the app seems to be compiled from Kotlin and there seems to be way to create new instances of anonymous inner classes that are defined else (because an anonymous class can't be defined in itself).  
At least I found two times the constructor of `kz.kaspi.mobile.core.NavigationActivity$onRegionSelected$1` is called: 

One in the main class `NavigationActivity` and one in the anonymous inner class itself: `NavigationActivity$onRegionSelected$1`.

**Comment by asashour** [comment]
I guess it is similar behavior to #579

**Comment by jpstotz** [comment]
I made a simple workaround that prevents the unlimited recursion. Instead the code generation of `kz.kaspi.mobile.core.NavigationActivity$onRegionSelected$1.create(..)` now fails, which is IMHO better than a StackOverflowException or an OutOfMemoryError which prevents decompiling the whole class:

https://github.com/jpstotz/jadx/commit/2d885f7738f38ba832133c5d65115bb8b9e82b55

I haven't made a PR because this is just an experiment and I think there must be a better solution. 
The only "real solution" to handle such cases I can think of would be to convert the anonymous inner class to a named inner class. This would make it possible to reference the constructor at both places it is used. Or have I missed an alternative way to handle this?

**Comment by skylot** [comment]
@jpstotz you are right, this is better than StackOverflow.
The main problems with anonymous classes is incorrect detection, current pattern sometimes fail (like in this case - class created twice ).
To make correct detection jadx must collect usage stats for every classes, the only way is to scan all instructions before decompilation, but this will be slow or highly increase memory usage. Also this stats will help to fix some issues with classes decompilation order.
Another option is: not inline anonymous classes at all (i.e not mark any class as anonymous). This will show them as inner clasess and this issue will be fixed, but decompiled code will be very verbose. For this I will add such option to the settings (and cli) like I suggest in #598.

**Comment by jpstotz** [comment]
@skylot Is it possible for you to estimate the compromise of both ways:

Anonymous inner classes instantiated multiple times seems to happen rarely. Therefore may be the optimistic approach would be better: Assume that it is an inner class (as it is done at the moment). 
Using additional code like I presented in https://github.com/jpstotz/jadx/commit/2d885f7738f38ba832133c5d65115bb8b9e82b55 we ensure that we detect the rare cases. I such a case we throw a special exception and/or set a special flag for the specific inner class. 

When the class has been decompiled successfully and has such a flag we know that something went wrong so we throw away the generated code and start over. As we now know which classes have to be treated as named one we can avoid the errors in the second run. Do you think that this would be possible without an big effort?

**Comment by skylot** [comment]
@jpstotz nice idea! I think it will work.

**Comment by skylot** [comment]
@jpstotz I implement your idea, thanks!
Anyway, usage statistics is really necessary to make common fix for this issue :(
