### ISSUE TITLE
NPE in ClassGen.useType

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#608]
Hi, I've noticed that some code is not decompiled because of error. Stack trace from ``` kz.kaspi.mobile.core.navigation.SetPincodeRoute ```:
```java
                        public final 
/*
Method generation error in method: kz.kaspi.mobile.core.navigation.SetPincodeRoute$SetPinCodeTarget$Companion$startProcess$1.invoke(java.lang.Object, java.lang.Object):null, dex: classes2.dex
java.lang.NullPointerException
	at jadx.core.codegen.ClassGen.useType(ClassGen.java:447)
	at jadx.core.codegen.MethodGen.addDefinition(MethodGen.java:102)
	at jadx.core.codegen.ClassGen.addMethod(ClassGen.java:316)
	at jadx.core.codegen.ClassGen.addMethods(ClassGen.java:262)
	at jadx.core.codegen.ClassGen.addClassBody(ClassGen.java:224)
	at jadx.core.codegen.InsnGen.inlineAnonymousConstructor(InsnGen.java:617)
	at jadx.core.codegen.InsnGen.makeConstructor(InsnGen.java:559)
	at jadx.core.codegen.InsnGen.makeInsnBody(InsnGen.java:345)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:218)
	at jadx.core.codegen.InsnGen.addArg(InsnGen.java:102)
	at jadx.core.codegen.InsnGen.generateMethodArguments(InsnGen.java:729)
	at jadx.core.codegen.InsnGen.makeInvoke(InsnGen.java:669)
	at jadx.core.codegen.InsnGen.makeInsnBody(InsnGen.java:349)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:231)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:210)
	at jadx.core.codegen.RegionGen.makeSimpleBlock(RegionGen.java:109)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:55)
	at jadx.core.codegen.RegionGen.makeSimpleRegion(RegionGen.java:92)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:58)
	at jadx.core.codegen.RegionGen.makeRegionIndent(RegionGen.java:98)
	at jadx.core.codegen.RegionGen.makeIf(RegionGen.java:127)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:62)
	at jadx.core.codegen.RegionGen.makeSimpleRegion(RegionGen.java:92)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:58)
	at jadx.core.codegen.RegionGen.makeSimpleRegion(RegionGen.java:92)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:58)
	at jadx.core.codegen.MethodGen.addInstructions(MethodGen.java:196)
	at jadx.core.codegen.ClassGen.addMethod(ClassGen.java:325)
	at jadx.core.codegen.ClassGen.addMethods(ClassGen.java:262)
	at jadx.core.codegen.ClassGen.addClassBody(ClassGen.java:224)
	at jadx.core.codegen.ClassGen.addClassCode(ClassGen.java:110)
	at jadx.core.codegen.ClassGen.addInnerClasses(ClassGen.java:237)
	at jadx.core.codegen.ClassGen.addClassBody(ClassGen.java:223)
	at jadx.core.codegen.ClassGen.addClassCode(ClassGen.java:110)
	at jadx.core.codegen.ClassGen.addInnerClasses(ClassGen.java:237)
	at jadx.core.codegen.ClassGen.addClassBody(ClassGen.java:223)
	at jadx.core.codegen.ClassGen.addClassCode(ClassGen.java:110)
	at jadx.core.codegen.ClassGen.makeClass(ClassGen.java:76)
	at jadx.core.codegen.CodeGen.generate(CodeGen.java:14)
	at jadx.core.ProcessClass.process(ProcessClass.java:36)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:290)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:196)

*/
```
The cause of that error could be different issue e.g. https://github.com/skylot/jadx/issues/604, but I'm reporting it just in case

APK: https://drive.google.com/file/d/1GGRxg2nMzUNAZqDXjIamg0Zdso-gvcz2/view?usp=sharing

**Comment by skylot** [comment]
Looks like this NPE is not reproducible anymore.
