### ISSUE TITLE
Unexpected magic when decompile sealed.dex

### ISSUE THREAD

**Issue by MichaelElianKevin** [skylot/jadx#665]
i have dex file named sealed1.dex from an APK. I have tried to decompille it using jadx-gui but errors occurs.
```java
ERROR - Error load file: /home/clown/appsealing.dex
jadx.core.utils.exceptions.JadxRuntimeException: Error load file: /home/clown/appsealing.dex
        at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:125)
        at jadx.api.JadxDecompiler.load(JadxDecompiler.java:87)
        at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:36)
        at jadx.gui.ui.MainWindow.openFile(MainWindow.java:187)
        at jadx.gui.ui.MainWindow.openFile(MainWindow.java:180)
        at jadx.gui.ui.MainWindow.open(MainWindow.java:142)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: com.android.dex.DexException: Unexpected magic: [0x50, 0x4b, 0x03, 0x04, 0x14, 0x00, 0x08, 0x08]
        at com.android.dex.TableOfContents.readHeader(TableOfContents.java:86)
        at com.android.dex.TableOfContents.readFrom(TableOfContents.java:72)
        at com.android.dex.Dex.loadFrom(Dex.java:141)
        at com.android.dex.Dex.<init>(Dex.java:120)
        at jadx.core.utils.files.InputFile.searchDexFiles(InputFile.java:51)
        at jadx.core.utils.files.InputFile.addFilesFrom(InputFile.java:36)
        at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:123)
        ... 18 common frames omitted
INFO  - output directory: appsealing-dex2jar
INFO  - loading ...
INFO  - converting to dex: appsealing-dex2jar.jar ...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.rits.cloning.Cloner (file:/home/clown/Downloads/jadx-0.9.0/lib/cloning-1.9.11.jar) to field java.util.TreeSet.m
WARNING: Please consider reporting this to the maintainers of com.rits.cloning.Cloner
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARN  - Missing block: B:31:0x00c1, code skipped:
            throw new java.io.IOException("Invalid chunk type (" + r1 + ").");
     in method: com.inka.appsealing.android.content.res.AXmlResourceParser.doNext():void, dex: 
INFO  - output directory: sealed1
INFO  - loading ...
ERROR - Error load file: /home/clown/sealed1.dex
jadx.core.utils.exceptions.JadxRuntimeException: Error load file: /home/clown/sealed1.dex
        at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:125)
        at jadx.api.JadxDecompiler.load(JadxDecompiler.java:87)
        at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:36)
        at jadx.gui.ui.MainWindow.openFile(MainWindow.java:187)
        at jadx.gui.ui.MainWindow.openFile(MainWindow.java:180)
        at jadx.gui.ui.MainWindow$3.actionPerformed(MainWindow.java:355)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
        at java.desktop/java.awt.Component.processEvent(Component.java:6397)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: com.android.dex.DexException: Unexpected magic: [0x4f, 0xf7, 0xb1, 0x88, 0x0b, 0x9f, 0x6b, 0x83]
        at com.android.dex.TableOfContents.readHeader(TableOfContents.java:86)
        at com.android.dex.TableOfContents.readFrom(TableOfContents.java:72)
        at com.android.dex.Dex.loadFrom(Dex.java:141)
        at com.android.dex.Dex.<init>(Dex.java:120)
        at jadx.core.utils.files.InputFile.searchDexFiles(InputFile.java:51)
        at jadx.core.utils.files.InputFile.addFilesFrom(InputFile.java:36)
        at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:123)
        ... 43 common frames omitted
```
how to fix that?

**Comment by skylot** [comment]
@MichaelElianKevin looks like this is not dex file inside.
Dex file must start with string `dex`, read more [here](https://source.android.com/devices/tech/dalvik/dex-format#dex-file-magic).

**Comment by jpstotz** [comment]
Base on the name I would assume that the dex file is encrypted and therefore can't be processed by Jadx. 
There is an Android obfuscation framework named "appsealing" which claims to use encrypted dex files.

**Comment by MichaelElianKevin** [comment]
@jpstotz You're right. The application is using appsealing. Do you know how to decompile it?
