### ISSUE TITLE
Type inference failed: simple test case

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#668]
Hi, in class ``` com/paypal/android/p2pmobile/animation/AnimationType.java ```
```java

    /* JADX WARNING: type inference failed for: r3v2, types: [java.lang.String] */
    /* JADX WARNING: type inference failed for: r3v3, types: [com.paypal.android.p2pmobile.animation.AnimationType] */
    /* JADX WARNING: type inference failed for: r3v4, types: [java.lang.String] */
    /* JADX WARNING: type inference failed for: r3v6, types: [com.paypal.android.p2pmobile.animation.AnimationType] */
    /* JADX WARNING: type inference failed for: r3v7, types: [com.paypal.android.p2pmobile.animation.AnimationType] */
    /* JADX WARNING: type inference failed for: r3v9 */
    /* JADX WARNING: type inference failed for: r3v10 */
    /* JADX WARNING: type inference failed for: r3v11 */
    /* JADX WARNING: Multi-variable type inference failed. Error: jadx.core.utils.exceptions.JadxRuntimeException: No candidate types for var: r3v9
  assigns: [com.paypal.android.p2pmobile.animation.AnimationType]
  uses: [java.lang.String, com.paypal.android.p2pmobile.animation.AnimationType]
  mth insns count: 21
    	at jadx.core.dex.visitors.typeinference.TypeSearch.fillTypeCandidates(TypeSearch.java:237)
    	at java.util.ArrayList.forEach(ArrayList.java:1257)
    	at jadx.core.dex.visitors.typeinference.TypeSearch.run(TypeSearch.java:53)
    	at jadx.core.dex.visitors.typeinference.TypeInferenceVisitor.runMultiVariableSearch(TypeInferenceVisitor.java:99)
    	at jadx.core.dex.visitors.typeinference.TypeInferenceVisitor.visit(TypeInferenceVisitor.java:92)
    	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:27)
    	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
    	at java.util.ArrayList.forEach(ArrayList.java:1257)
    	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
    	at jadx.core.ProcessClass.process(ProcessClass.java:30)
    	at jadx.core.ProcessClass.lambda$processDependencies$0(ProcessClass.java:49)
    	at java.util.ArrayList.forEach(ArrayList.java:1257)
    	at jadx.core.ProcessClass.processDependencies(ProcessClass.java:49)
    	at jadx.core.ProcessClass.process(ProcessClass.java:35)
    	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:311)
    	at jadx.api.JavaClass.decompile(JavaClass.java:62)
    	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:217)
     */
    /* JADX WARNING: Unknown variable types count: 4 */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public static com.paypal.android.p2pmobile.animation.AnimationType toAnimationType(java.lang.String str) {
        ? r3;
        ? r32;
        if (android.text.TextUtils.isEmpty(str)) {
            return FADE_IN_HOLD;
        }
        ? upperCase = str.trim().toUpperCase();
        try {
            r32 = upperCase;
            ? valueOf = valueOf(upperCase);
            r3 = valueOf;
        } catch (java.lang.IllegalArgumentException unused) {
            java.lang.String name = com.paypal.android.p2pmobile.animation.AnimationType.class.getName();
            java.lang.StringBuilder sb = new java.lang.StringBuilder();
            sb.append("Unable to get enum for value: ");
            sb.append(r32);
            android.util.Log.e(name, sb.toString());
            r3 = FADE_IN_HOLD;
        }
        return r3;
    }
```
APK: https://drive.google.com/file/d/1WEvevcmoQ0ryOFMPAHzzbWA67k3W3Wpc/view?usp=sharing

**Comment by sergey-wowwow** [comment]
@skylot 
Thanks!
