### ISSUE TITLE
Jadx decompilation error on com.s4m.apk

### ISSUE THREAD

**Issue by romainthomas** [skylot/jadx#673]
Hello @skylot 

Thank you again to provide such project. It's awesome how Jadx is well designed and working on almost all Java based obfuscated app! 

Nevertheless, I found this sample: [com.s4m.apk](https://koodous.com/apks/2fc9d470fcfc537cf5a6bdc10a893bb55d9e447f0d3adefeadf44a121c62a75c) - ``2fc9d470fcfc537cf5a6bdc10a893bb55d9e447f0d3adefeadf44a121c62a75c`` 

where Jadx fails to decompile the method ``xn()`` in the class ``com.gemalto.medl.rd``:

```console
        JADX ERROR: NullPointerException in pass: RegionMakerVisitor
        java.lang.NullPointerException
        	at java.util.BitSet.and(BitSet.java:916)
        	at jadx.core.utils.BlockUtils.getPathCross(BlockUtils.java:437)
        	at jadx.core.dex.visitors.regions.RegionMaker.processTryCatchBlocks(RegionMaker.java:963)
        	at jadx.core.dex.visitors.regions.RegionMakerVisitor.visit(RegionMakerVisitor.java:52)
        	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:27)
        	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
        	at java.util.ArrayList.forEach(ArrayList.java:1257)
        	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
        	at jadx.core.ProcessClass.process(ProcessClass.java:30)
        	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:311)
        	at jadx.api.JavaClass.decompile(JavaClass.java:62)
        	at jadx.api.JavaClass.getCode(JavaClass.java:48)
```

Tested with Jadx master branch - commit: 123ba2ba

**Comment by sergey-wowwow** [comment]
Seems to be fixed
