### ISSUE TITLE
a batch errors like this 

### ISSUE THREAD

**Issue by guangliang2014** [skylot/jadx#69]
static {
        /* JADX: method processing error */
/*
        Error: jadx.core.utils.exceptions.DecodeException: Load method exception in method: com.android.contacts.dialpad.DialpadFragment.<clinit>():void
	at jadx.core.dex.nodes.MethodNode.load(MethodNode.java:113)
	at jadx.core.dex.nodes.ClassNode.load(ClassNode.java:256)
	at jadx.core.ProcessClass.process(ProcessClass.java:34)
	at jadx.core.ProcessClass.processDependencies(ProcessClass.java:59)
	at jadx.core.ProcessClass.process(ProcessClass.java:42)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:281)
	at jadx.api.JavaClass.decompile(JavaClass.java:59)
	at jadx.api.JadxDecompiler$1.run(JadxDecompiler.java:161)
Caused by: jadx.core.utils.exceptions.DecodeException:  in method: com.android.contacts.dialpad.DialpadFragment.<clinit>():void
	at jadx.core.dex.instructions.InsnDecoder.decodeInsns(InsnDecoder.java:46)
	at jadx.core.dex.nodes.MethodNode.load(MethodNode.java:98)
	... 7 more
Caused by: java.lang.IllegalArgumentException: bogus opcode: 00e9
	at com.android.dx.io.OpcodeInfo.get(OpcodeInfo.java:1196)
	at com.android.dx.io.OpcodeInfo.getFormat(OpcodeInfo.java:1212)
	at com.android.dx.io.instructions.DecodedInstruction.decode(DecodedInstruction.java:72)
	at jadx.core.dex.instructions.InsnDecoder.decodeInsns(InsnDecoder.java:43)
	... 8 more
*/
        /*
        // Can't load method instructions.
        */
        throw new UnsupportedOperationException("Method not decompiled: com.android.contacts.dialpad.DialpadFragment.<clinit>():void");
    }

some static can work well. For example:
private static final int[] DEFAULT_RESOURCES_ID;
and
DEFAULT_RESOURCES_ID = new int[] { 21308......};

I think this maybe one bug for all statution like this.

Beat Regards.

**Comment by guangliang2014** [comment]
This error found for he dex file decomplied from odex file.
Hope has help for this bug.

**Comment by skylot** [comment]
```
 java.lang.IllegalArgumentException: bogus opcode: 00e9
```
This opcode INVOKE_VIRTUAL_QUICK(0xE9) is internal opcode in Android ART it contains only in odex (oat) files and not valid for normal dex. And even worse, this opcode in dalvik odex has different instruction type - IPUT_WIDE_VOLATILE. See [Dalvik Opcode Changes in ART](https://github.com/anestisb/oatdump_plus#dalvik-opcode-changes-in-art).
Currently for parse dex files I use android dx library and can't parse those opcodes. 
I think this issue must be solved in deodexer apps, which can do proper conversion. Because for resolve INVOKE_VIRTUAL_QUICK (refers to method position in virtual table) needed full classpath from your android device.
May be in future jadx will support odex files but not now, sorry )
