### ISSUE TITLE
[core]java.lang.NoClassDefFoundError: ch/qos/logback/core/joran/spi/JoranException

### ISSUE THREAD

**Issue by ljsalm089** [skylot/jadx#698]
**Describe error**
can not run the jadx-gui and jadx, and when i tried to unzip logback-core jar file, i got this:
```shell
> unzip logback-core-1.2.3.jar
Archive:  logback-core-1.2.3.jar
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of logback-core-1.2.3.jar or
        logback-core-1.2.3.jar.zip, and cannot find logback-core-1.2.3.jar.ZIP, period.
```
- provide full name of method or class with error
- provide full java stacktrace
> Failed to instantiate SLF4J LoggerFactory

Reported exception:
```java
java.lang.NoClassDefFoundError: ch/qos/logback/core/joran/spi/JoranException
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at jadx.gui.JadxGUI.<clinit>(JadxGUI.java:15)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.joran.spi.JoranException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 6 more
Exception in thread "main" java.lang.NoClassDefFoundError: ch/qos/logback/core/joran/spi/JoranException
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at jadx.gui.JadxGUI.<clinit>(JadxGUI.java:15)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.joran.spi.JoranException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 6 more
```

**Comment by jpstotz** [comment]
I am sorry but I don't see the connection between your problem unzipping a defect `logback-core-1.2.3.jar` and jadx. For running jadx you don't need to do anything with logback. Just download jadx, unzip the downloaded file and run jadx.

**Comment by skylot** [comment]
@ljsalm089 I think redownload jadx bundle will help, if not please let us know.

**Comment by ljsalm089** [comment]
@skylot  it works after i redownload it, thx!
