### ISSUE TITLE
Downloading gradle-5.4.1-bin.zip occured an Error:Reason: zip END header not found

### ISSUE THREAD

**Issue by Joovo** [skylot/jadx#715]
```java
(python35) ➜  jadx git:(master) ./gradlew dist
Downloading https://services.gradle.org/distributions/gradle-5.4.1-bin.zip
..
Could not unzip /Users/jo/.gradle/wrapper/dists/gradle-5.4.1-bin/e75iq110yv9r9wt1a6619x2xm/gradle-5.4.1-bin.zip to /Users/jo/.gradle/wrapper/dists/gradle-5.4.1-bin/e75iq110yv9r9wt1a6619x2xm.
Reason: zip END header not found
Exception in thread "main" java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1470)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1371)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1378)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1209)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1172)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:719)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:239)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:183)
	at org.gradle.wrapper.Install.unzip(Install.java:219)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:75)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
```

**Comment by jpstotz** [comment]
Download errors can occur at any time in any application (download from a defect mirror, network interruption, ...). 

You should just delete the mentioned file (if it still exists) and retry the build process. The liked file exists, can be downloaded and the content is a perfect valid ZIP file (just tested).

**Comment by Joovo** [comment]
@jpstotz  Thx a lot! I am a newbie about Java and Android.

**Comment by jpstotz** [comment]
If you are a "newbie about Java and Android" why do you try to compile jadx yourself instead of using the pre-compiled stable or unstable releases?

**Comment by Joovo** [comment]
@jpstotz A very insterseting question..Because I live in China and for some reasons(GFW)  the download speed of the newest stable release very  slow. Although using vpn, the connection of amazon server is too slow. The oldder releases are easy to get in other sites.
