### ISSUE TITLE
StackOverflowError Exception on multiple APKs

### ISSUE THREAD

**Issue by umurkaragoz** [skylot/jadx#721]
I tried to decompile some 50 of the top apps, and I got `StackOverflowError` quite frequently.
I noted down those APKs and retried, and was able to reproduce the error consistently.

### APKs

I get `java.lang.StackOverflowError` for following APKs;

* [The Sims™ Mobile](https://apkpure.com/the-sims-mobile/com.ea.gp.simsmobile/download/60-APK)
* [cure.fit](https://apkpure.com/cure-fit-food-delivery-fitness-personal-doctor/fit.cure.android/download/3000753-APK)
* [Pokémon GO](https://apkpure.com/pokemon-go/com.nianticlabs.pokemongo/download/2019042400-APK)
* [Chat Alternative](https://apkpure.com/chat-alternative-%E2%80%94-android-app/com.chatroullete.alternative/variant/6.3.6-APK)
* [Doctor On Demand](https://apkpure.com/doctor-on-demand/com.doctorondemand.android.patient/download/74501-APK)
* [Google Slides](https://apkpure.com/google-slides/com.google.android.apps.docs.editors.slides/download/191520482-APK)

### Errors
I tried processing these APKs **with two jadx versions**, and they produce slightly different variations of the error.

With **jadx-0.9.0**, I get following error;
```
Exception in thread "pool-1-thread-1" java.lang.StackOverflowError
        at jadx.core.dex.nodes.InsnNode.getArgsCount(InsnNode.java:81)
        at jadx.core.dex.instructions.InvokeNode.copy(InvokeNode.java:55)
        at jadx.core.dex.nodes.InsnNode.copyCommonParams(InsnNode.java:298)
        at jadx.core.dex.nodes.InsnNode.copy(InsnNode.java:315)
        at jadx.core.codegen.InsnGen.inlineMethod(InsnGen.java:763)
        at jadx.core.codegen.InsnGen.makeInvoke(InsnGen.java:619)
        at jadx.core.codegen.InsnGen.makeInsnBody(InsnGen.java:340)
        at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:213)
        at jadx.core.codegen.InsnGen.addArg(InsnGen.java:101)
        at jadx.core.codegen.InsnGen.addArg(InsnGen.java:91)
        at jadx.core.codegen.InsnGen.makeInsnBody(InsnGen.java:441)
        at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:213)
        at jadx.core.codegen.InsnGen.inlineMethod(InsnGen.java:779)
        at jadx.core.codegen.InsnGen.makeInvoke(InsnGen.java:619)
        at jadx.core.codegen.InsnGen.makeInsnBody(InsnGen.java:340)
        ... (last pattern repeats for couple hundred times)
```

With **jadx-1.0.0-b1105**, I get following error;
```
Exception in thread "pool-1-thread-1" java.lang.StackOverflowError
        at jadx.core.dex.instructions.IfNode.isSame(IfNode.java:123)
        at jadx.core.dex.visitors.MarkFinallyVisitor.sameInsns(MarkFinallyVisitor.java:448)
        at jadx.core.dex.visitors.MarkFinallyVisitor.compareBlocks(MarkFinallyVisitor.java:433)
        at jadx.core.dex.visitors.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:405)
        at jadx.core.dex.visitors.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:408)
        at jadx.core.dex.visitors.MarkFinallyVisitor.checkBlocksTree(MarkFinallyVisitor.java:408)
        ... (last line repeats for couple hundred times)
```

**Comment by sergey-wowwow** [comment]
Closing as a dup of https://github.com/skylot/jadx/issues/579
