### ISSUE TITLE
 JADX ERROR: UnsupportedOperationException in pass: BlockProcessor

### ISSUE THREAD

**Issue by fgfg54321** [skylot/jadx#744]
used version jadx-gui-1.0.0 get two questions
--------------------------------------------------------------------------------------
```java
  JADX ERROR: IndexOutOfBoundsException in pass: ClassModifier
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    	at java.util.ArrayList.rangeCheck(Unknown Source)
    	at java.util.ArrayList.get(Unknown Source)
    	at jadx.core.dex.visitors.ClassModifier.removeFieldUsageFromConstructor(ClassModifier.java:113)
    	at jadx.core.dex.visitors.ClassModifier.removeSyntheticFields(ClassModifier.java:87)
    	at jadx.core.dex.visitors.ClassModifier.visit(ClassModifier.java:55)
    	at jadx.core.dex.visitors.ClassModifier.visit(ClassModifier.java:49)
    	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:12)
    	at jadx.core.ProcessClass.process(ProcessClass.java:30)
    	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:311)
    	at jadx.api.JavaClass.decompile(JavaClass.java:62)
```
```java
  JADX ERROR: UnsupportedOperationException in pass: BlockProcessor
            java.lang.UnsupportedOperationException
            	at jadx.core.utils.EmptyBitSet.set(EmptyBitSet.java:42)
            	at jadx.core.dex.visitors.blocksmaker.BlockProcessor.calcDominators(BlockProcessor.java:228)
            	at jadx.core.dex.visitors.blocksmaker.BlockProcessor.computeDominators(BlockProcessor.java:212)
            	at jadx.core.dex.visitors.blocksmaker.BlockProcessor.processBlocksTree(BlockProcessor.java:58)
            	at jadx.core.dex.visitors.blocksmaker.BlockProcessor.visit(BlockProcessor.java:45)
            	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:27)
            	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
            	at java.util.ArrayList.forEach(Unknown Source)
            	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
            	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$0(DepthTraversal.java:13)
            	at java.util.ArrayList.forEach(Unknown Source)
            	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:13)
            	at jadx.core.ProcessClass.process(ProcessClass.java:30)
            	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:311)
            	at jadx.api.JavaClass.decompile(JavaClass.java:62)
```
then used version jadx-gui-1.0.0-b1141-db892adf get this:
```java
  JADX ERROR: UnsupportedOperationException in pass: BlockProcessor
        java.lang.UnsupportedOperationException
        	at jadx.core.utils.EmptyBitSet.set(EmptyBitSet.java:42)
        	at jadx.core.dex.visitors.blocksmaker.BlockProcessor.calcDominators(BlockProcessor.java:228)
        	at jadx.core.dex.visitors.blocksmaker.BlockProcessor.computeDominators(BlockProcessor.java:212)
        	at jadx.core.dex.visitors.blocksmaker.BlockProcessor.processBlocksTree(BlockProcessor.java:55)
        	at jadx.core.dex.visitors.blocksmaker.BlockProcessor.visit(BlockProcessor.java:45)
```
[class.zip](https://github.com/skylot/jadx/files/3553700/class.zip)

**Comment by skylot** [comment]
@fgfg54321 this is really weird dex. All methods contain only NOPs, like this:
```java
.method public clear()V
    .registers 3

    .line 799
    :try_start_0
    nop

    nop
    nop
    nop

    nop
    :try_end_5
    .catch Ljava/io/EOFException; {:try_start_0 .. :try_end_5} :catch_6

    nop

    :catch_6
    nop

    .line 801
    nop
    nop
    nop
    nop
    nop
    nop
.end method
```
So there is nothing to decompile here :)
And I made a fix to correctly handle such cases.
Thank you for the report! :+1:
