### ISSUE TITLE
jadx.core.utils.exceptions.JadxRuntimeException: Regions count limit reached

### ISSUE THREAD

**Issue by steelbytes** [skylot/jadx#753]
lots of Regions count limit reached in various classes.  using jadx 1.0.0 (via jadx-gui.bat)

example

ERROR: JadxRuntimeException in pass: RegionMakerVisitor in method: com.google.android.exoplayer.extractor.mp3.Mp3Extractor.synchronize(com.google.android.exoplayer.extractor.ExtractorInput, boolean):boolean, dex: classes.dex
jadx.core.utils.exceptions.JadxRuntimeException: Regions count limit reached
	at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:89)
	at jadx.core.dex.visitors.regions.RegionMaker.makeEndlessLoop(RegionMaker.java:368)
	at jadx.core.dex.visitors.regions.RegionMaker.processLoop(RegionMaker.java:172)
	at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:106)
	at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:86)
	at jadx.core.dex.visitors.regions.RegionMakerVisitor.visit(RegionMakerVisitor.java:49)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:27)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:14)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:14)
	at jadx.core.ProcessClass.process(ProcessClass.java:30)
	at jadx.core.ProcessClass.lambda$processDependencies$0(ProcessClass.java:49)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at jadx.core.ProcessClass.processDependencies(ProcessClass.java:49)
	at jadx.core.ProcessClass.process(ProcessClass.java:35)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:311)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by sergey-wowwow** [comment]
It's impossible to fix anything until you provide a sample code which causes this error

**Comment by steelbytes** [comment]
@sergey-wowwow you can see in the first line of this call stack that it is in Google's com.google.android.exoplayer library.  I suggest trying the example apps for that (using proguard and com.android.tools.build:gradle:3.4 and build tools 29.0.2)
