### ISSUE TITLE
lots of Method generation error in method

### ISSUE THREAD

**Issue by steelbytes** [skylot/jadx#754]
jadx 1.0.0

ERROR: Method generation error in method: com.myapp.someclass.-$$Lambda$ITQEjCrpuSIGnLBnCaFYuS4VA5c.run():null, dex: classes.dex
java.lang.NullPointerException: null
	at jadx.core.codegen.ClassGen.useType(ClassGen.java:442)
	at jadx.core.codegen.MethodGen.addDefinition(MethodGen.java:109)
	at jadx.core.codegen.ClassGen.addMethod(ClassGen.java:311)
	at jadx.core.codegen.ClassGen.addMethods(ClassGen.java:262)
	at jadx.core.codegen.ClassGen.addClassBody(ClassGen.java:225)
	at jadx.core.codegen.InsnGen.inlineAnonymousConstructor(InsnGen.java:661)
	at jadx.core.codegen.InsnGen.makeConstructor(InsnGen.java:595)
	at jadx.core.codegen.InsnGen.makeInsnBody(InsnGen.java:353)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:223)
	at jadx.core.codegen.InsnGen.addArg(InsnGen.java:105)
	at jadx.core.codegen.InsnGen.generateMethodArguments(InsnGen.java:773)
	at jadx.core.codegen.InsnGen.makeInvoke(InsnGen.java:713)
	at jadx.core.codegen.InsnGen.makeInsnBody(InsnGen.java:357)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:239)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:213)
	at jadx.core.codegen.RegionGen.makeSimpleBlock(RegionGen.java:109)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:55)
	at jadx.core.codegen.RegionGen.makeSimpleRegion(RegionGen.java:92)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:58)
	at jadx.core.codegen.RegionGen.makeRegionIndent(RegionGen.java:98)
	at jadx.core.codegen.RegionGen.makeIf(RegionGen.java:138)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:62)
	at jadx.core.codegen.RegionGen.makeSimpleRegion(RegionGen.java:92)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:58)
	at jadx.core.codegen.RegionGen.makeSimpleRegion(RegionGen.java:92)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:58)
	at jadx.core.codegen.MethodGen.addRegionInsns(MethodGen.java:210)
	at jadx.core.codegen.MethodGen.addInstructions(MethodGen.java:203)
	at jadx.core.codegen.ClassGen.addMethod(ClassGen.java:316)
	at jadx.core.codegen.ClassGen.addMethods(ClassGen.java:262)
	at jadx.core.codegen.ClassGen.addClassBody(ClassGen.java:225)
	at jadx.core.codegen.InsnGen.inlineAnonymousConstructor(InsnGen.java:661)
	at jadx.core.codegen.InsnGen.makeConstructor(InsnGen.java:595)
	at jadx.core.codegen.InsnGen.makeInsnBody(InsnGen.java:353)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:239)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:213)
	at jadx.core.codegen.RegionGen.makeSimpleBlock(RegionGen.java:109)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:55)
	at jadx.core.codegen.RegionGen.makeSimpleRegion(RegionGen.java:92)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:58)
	at jadx.core.codegen.MethodGen.addRegionInsns(MethodGen.java:210)
	at jadx.core.codegen.MethodGen.addInstructions(MethodGen.java:203)
	at jadx.core.codegen.ClassGen.addMethod(ClassGen.java:316)
	at jadx.core.codegen.ClassGen.addMethods(ClassGen.java:262)
	at jadx.core.codegen.ClassGen.addClassBody(ClassGen.java:225)
	at jadx.core.codegen.InsnGen.inlineAnonymousConstructor(InsnGen.java:661)
	at jadx.core.codegen.InsnGen.makeConstructor(InsnGen.java:595)
	at jadx.core.codegen.InsnGen.makeInsnBody(InsnGen.java:353)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:223)
	at jadx.core.codegen.InsnGen.addArg(InsnGen.java:105)
	at jadx.core.codegen.InsnGen.generateMethodArguments(InsnGen.java:773)
	at jadx.core.codegen.InsnGen.makeInvoke(InsnGen.java:713)
	at jadx.core.codegen.InsnGen.makeInsnBody(InsnGen.java:357)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:223)
	at jadx.core.codegen.InsnGen.addArg(InsnGen.java:105)
	at jadx.core.codegen.InsnGen.addArgDot(InsnGen.java:88)
	at jadx.core.codegen.InsnGen.makeInvoke(InsnGen.java:682)
	at jadx.core.codegen.InsnGen.makeInsnBody(InsnGen.java:357)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:223)
	at jadx.core.codegen.InsnGen.addArg(InsnGen.java:105)
	at jadx.core.codegen.InsnGen.addArgDot(InsnGen.java:88)
	at jadx.core.codegen.InsnGen.makeInvoke(InsnGen.java:682)
	at jadx.core.codegen.InsnGen.makeInsnBody(InsnGen.java:357)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:223)
	at jadx.core.codegen.InsnGen.addArg(InsnGen.java:105)
	at jadx.core.codegen.InsnGen.addArgDot(InsnGen.java:88)
	at jadx.core.codegen.InsnGen.makeInvoke(InsnGen.java:682)
	at jadx.core.codegen.InsnGen.makeInsnBody(InsnGen.java:357)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:239)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:213)
	at jadx.core.codegen.RegionGen.makeSimpleBlock(RegionGen.java:109)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:55)
	at jadx.core.codegen.RegionGen.makeSimpleRegion(RegionGen.java:92)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:58)
	at jadx.core.codegen.RegionGen.makeRegionIndent(RegionGen.java:98)
	at jadx.core.codegen.RegionGen.makeIf(RegionGen.java:138)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:62)
	at jadx.core.codegen.RegionGen.makeSimpleRegion(RegionGen.java:92)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:58)
	at jadx.core.codegen.RegionGen.makeSimpleRegion(RegionGen.java:92)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:58)
	at jadx.core.codegen.RegionGen.makeRegionIndent(RegionGen.java:98)
	at jadx.core.codegen.RegionGen.makeIf(RegionGen.java:138)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:62)
	at jadx.core.codegen.RegionGen.makeSimpleRegion(RegionGen.java:92)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:58)
	at jadx.core.codegen.RegionGen.makeSimpleRegion(RegionGen.java:92)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:58)
	at jadx.core.codegen.MethodGen.addRegionInsns(MethodGen.java:210)
	at jadx.core.codegen.MethodGen.addInstructions(MethodGen.java:203)
	at jadx.core.codegen.ClassGen.addMethod(ClassGen.java:316)
	at jadx.core.codegen.ClassGen.addMethods(ClassGen.java:262)
	at jadx.core.codegen.ClassGen.addClassBody(ClassGen.java:225)
	at jadx.core.codegen.ClassGen.addClassCode(ClassGen.java:110)
	at jadx.core.codegen.ClassGen.makeClass(ClassGen.java:76)
	at jadx.core.codegen.CodeGen.wrapCodeGen(CodeGen.java:44)
	at jadx.core.codegen.CodeGen.generateJavaCode(CodeGen.java:32)
	at jadx.core.codegen.CodeGen.generate(CodeGen.java:20)
	at jadx.core.ProcessClass.process(ProcessClass.java:36)
	at jadx.api.JadxDecompiler.processClass(JadxDecompiler.java:311)
	at jadx.api.JavaClass.decompile(JavaClass.java:62)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by sergey-wowwow** [comment]
It's impossible to fix anything until you provide a sample code which causes this error
