### ISSUE TITLE
[core]

### ISSUE THREAD

**Issue by xmhwws** [skylot/jadx#759]
I use jadx v1.0.0-b1144-bd9e1096,the lastest version
decompile jar error

link: https://raw.githubusercontent.com/xmhwws/AApk/master/charles.jar

class:`com.xk72.charles.gui.SplashWindow`

detail:

/*  JADX ERROR: Method load error
        jadx.core.utils.exceptions.DecodeException: Load method exception: Unknown instruction: 'invoke-custom' in method: com.xk72.charles.gui.SplashWindow.showRegistrationStatus():void, dex: charles.jar
        	at jadx.core.dex.nodes.MethodNode.load(MethodNode.java:151)
        	at jadx.core.dex.nodes.ClassNode.load(ClassNode.java:286)
        	at jadx.core.ProcessClass.process(ProcessClass.java:36)
        	at java.util.ArrayList.forEach(ArrayList.java:1257)
        	at jadx.core.ProcessClass.generateCode(ProcessClass.java:59)
        	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:273)
        Caused by: jadx.core.utils.exceptions.DecodeException: Unknown instruction: 'invoke-custom'
        	at jadx.core.dex.instructions.InsnDecoder.decode(InsnDecoder.java:588)
        	at jadx.core.dex.instructions.InsnDecoder.process(InsnDecoder.java:78)
        	at jadx.core.dex.nodes.MethodNode.load(MethodNode.java:136)
        	... 5 more
        */
    public void showRegistrationStatus() {
        /*
        // Can't load method instructions: Load method exception: Unknown instruction: 'invoke-custom' in method: com.xk72.charles.gui.SplashWindow.showRegistrationStatus():void, dex: charles.jar
        */
        throw new UnsupportedOperationException("Method not decompiled: com.xk72.charles.gui.SplashWindow.showRegistrationStatus():void");
    }

I think this is a protection against JADX, preventing its own important methods from being decompiled by jadx.

**Comment by jpstotz** [comment]
The instruction type 'invoke-custom' is not yet supported, see #384.
