### ISSUE TITLE
[core] Jadx can NOT be launch on macOS 10.15 : NullPointerException

### ISSUE THREAD

**Issue by amoxicillin** [skylot/jadx#762]
I got this error log when I try to launch jadx with "jadx-gui" command.

Jadx : 
1.0.0

System : 
macOS 10.15 catalina

Java : java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

```java
Exception in thread "main" java.lang.ExceptionInInitializerError
	at jadx.gui.settings.JadxSettingsAdapter$1.shouldSkipField(JadxSettingsAdapter.java:36)
	at com.google.gson.internal.Excluder.excludeField(Excluder.java:184)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.excludeField(ReflectiveTypeAdapterFactory.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.excludeField(ReflectiveTypeAdapterFactory.java:65)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:154)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.Gson.fromJson(Gson.java:926)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.google.gson.Gson.fromJson(Gson.java:813)
	at jadx.gui.settings.JadxSettingsAdapter.fromString(JadxSettingsAdapter.java:88)
	at jadx.gui.settings.JadxSettingsAdapter.load(JadxSettingsAdapter.java:59)
	at jadx.gui.JadxGUI.main(JadxGUI.java:21)
Caused by: java.lang.NullPointerException
	at sun.font.FontDesignMetrics.getDefaultFrc(FontDesignMetrics.java:157)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:278)
	at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1113)
	at javax.swing.JComponent.getFontMetrics(JComponent.java:1626)
	at org.fife.ui.rtextarea.RTextAreaBase.updateMarginLineX(RTextAreaBase.java:1187)
	at org.fife.ui.rtextarea.RTextAreaBase.setFont(RTextAreaBase.java:985)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.setFont(RSyntaxTextArea.java:2532)
	at javax.swing.plaf.basic.BasicTextUI.installDefaults(BasicTextUI.java:307)
	at javax.swing.plaf.basic.BasicTextAreaUI.installDefaults(BasicTextAreaUI.java:83)
	at org.fife.ui.rtextarea.RTextAreaUI.installDefaults(RTextAreaUI.java:360)
	at javax.swing.plaf.basic.BasicTextUI.installUI(BasicTextUI.java:787)
	at org.fife.ui.rtextarea.RTextAreaUI.installUI(RTextAreaUI.java:419)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.text.JTextComponent.setUI(JTextComponent.java:328)
	at org.fife.ui.rtextarea.RTextAreaBase.setRTextAreaUI(RTextAreaBase.java:1132)
	at org.fife.ui.rtextarea.RTextAreaBase.init(RTextAreaBase.java:658)
	at org.fife.ui.rtextarea.RTextArea.init(RTextArea.java:876)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.init(RSyntaxTextArea.java:1937)
	at org.fife.ui.rtextarea.RTextAreaBase.<init>(RTextAreaBase.java:82)
	at org.fife.ui.rtextarea.RTextArea.<init>(RTextArea.java:191)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.<init>(RSyntaxTextArea.java:355)
	at jadx.gui.settings.JadxSettings.<clinit>(JadxSettings.java:40)
	... 14 more
```

**Comment by jpstotz** [comment]
This bug is also files in a few other projects, mostly in combination with exactly the same Java versions you use. Therefore I would recommend to try a more recent Java (11 preferred) version instead. If you don't want and can't accept the Oracle license I recommend the [AdoptOpenJDK](https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot) builds for OSX to you.

**Comment by amoxicillin** [comment]
I updated my java from Oracle-1.8.0_172-b11 to AdoptOpenJDK-11.0.4,  then restart system, jadx-gui work properly.
Before the system update(macOS 10.14.6), jadx-gui work properly with oracle java caused me to ignore this point.
Thank you, @jpstotz :)
