### ISSUE TITLE
[core] No such map item: -4096 on GUI, on CLI reporting "done" but doesn't decompile (framework.jar from MIUI, Android Q)

### ISSUE THREAD

**Issue by kacskrz** [skylot/jadx#778]
**Checks before report**
- check [latest unstable build](https://bintray.com/skylot/jadx/unstable/_latestVersion#files) (maybe issue already fixed) - checked, same
- check [Troubleshooting Q&A](https://github.com/skylot/jadx/wiki/Troubleshooting-Q&A) section on wiki - it is not needed, checked on Windows 10 desktop and Linux Debian server
- search existing issues by exception message - not found same issue

**Describe error**
- GUI and CLI doesn't decompile framework.jar - output contains only dex files, which can't decompile as well.
- provide full java stacktrace
```ERROR: Failed to load dex file: classes.dex, error: No such map item: -4096
java.lang.IllegalArgumentException: No such map item: -4096
	at com.android.dex.TableOfContents.getSection(TableOfContents.java:171)
	at com.android.dex.TableOfContents.readMap(TableOfContents.java:129)
	at com.android.dex.TableOfContents.readFrom(TableOfContents.java:73)
	at com.android.dex.Dex.<init>(Dex.java:81)
	at com.android.dex.Dex.<init>(Dex.java:75)
	at jadx.core.utils.files.InputFile.loadDexBufFromPath(InputFile.java:166)
	at jadx.core.utils.files.InputFile.addDexFile(InputFile.java:155)
	at jadx.core.utils.files.InputFile.loadFromZip(InputFile.java:117)
	at jadx.core.utils.files.InputFile.searchDexFiles(InputFile.java:71)
	at jadx.core.utils.files.InputFile.addFilesFrom(InputFile.java:40)
	at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:119)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:88)
	at jadx.gui.JadxWrapper.openFile(JadxWrapper.java:42)
	at jadx.gui.ui.MainWindow.open(MainWindow.java:281)
	at jadx.gui.ui.MainWindow.openFileOrProject(MainWindow.java:208)
	at jadx.gui.ui.MainWindow.processCommandLineArgs(MainWindow.java:162)
	at jadx.gui.ui.MainWindow.init(MainWindow.java:157)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```
- attach or provide link to apk file (double check apk version)
http://anglov.pl/~orjon/framework.jar

**Comment by skylot** [comment]
@kacskrz thank you for the nice sample!
Unfortunately, this issue is hard to fix because I use `dx` library as a dex parser, and I need to fix that library to resolve this issue :(
Anyway, I have plans to use another dex parser or maybe made it by myself because dx is no longer supported.

But there is a piece of good news: Smali project can parse this sample, so you can convert it to smali and next convert smali back to dex and this dex will be parsable by jadx ! )))

**Comment by kacskrz** [comment]
Yeah, I decompiled via apktool, built and decompiled via jadx successfully :)
Thanks!

**Comment by skylot** [comment]
Now jadx own dex parser can handle this sample :)
