### ISSUE TITLE
Decompilation error，com.android.dex.DexException: Unexpected magic:   [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]

### ISSUE THREAD

**Issue by zhangstar666** [skylot/jadx#785]
Hello there,
I got the following error when I tried to decompile a dex file.(Download link: [`https://star666.cn/failed.dex`)](https://star666.cn/failed.dex)

Here is the stacktrace:
```
ERROR - jadx error: Error load file: failed.dex
jadx.core.utils.exceptions.JadxRuntimeException: Error load file: failed.dex
        at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:138)
        at jadx.api.JadxDecompiler.load(JadxDecompiler.java:102)
        at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:32)
        at jadx.cli.JadxCLI.main(JadxCLI.java:18)
Caused by: com.android.dex.DexException: Unexpected magic: [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        at com.android.dex.TableOfContents.readHeader(TableOfContents.java:86)
        at com.android.dex.TableOfContents.readFrom(TableOfContents.java:72)
        at com.android.dex.Dex.loadFrom(Dex.java:141)
        at com.android.dex.Dex.<init>(Dex.java:120)
        at jadx.core.utils.files.InputFile.searchDexFiles(InputFile.java:55)
        at jadx.core.utils.files.InputFile.addFilesFrom(InputFile.java:40)
        at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:136)
        ... 3 common frames omitted
```

**Environment:**
-  jadx version: 1.0.0
- Java version: 1.8.0_71
- OS：Windows

**Comment by jpstotz** [comment]
Did you try to load this file manually into Jadx? If yes, are you sure that the content (except for the magic bytes at the beginning) is a dex file?

**Comment by zhangstar666** [comment]
> Did you try to load this file manually into Jadx? If yes, are you sure that the content (except for the magic bytes at the beginning) is a dex file?
I think I got the wrong dex file.
