### ISSUE TITLE
[core] Jadx decompilation regression 

### ISSUE THREAD

**Issue by romainthomas** [skylot/jadx#788]
**Describe error**
In version **0.9.0** Jadx correctly managed to provide the pseudo core of the method ``com.airwatch.core.AirWatchDevice.getOem()``  but since version **1.1.0** it fails.

0.9.0:

```java
public static String getOem() {
        try {
            String str;
            switch (getOemId()) {
                case HTC:
                    return "htc";
                case KNOX:
                case SAFE:
                    return "samsung";
                case Lenovo:
                    return "lenovo";
```

1.1.0:

```java
/*  JADX ERROR: JadxRuntimeException in pass: BlockSplitter
        jadx.core.utils.exceptions.JadxRuntimeException: Can't find block by offset: 0x002a in list []
        	at jadx.core.utils.BlockUtils.getBlockByOffset(BlockUtils.java:44)
        	at jadx.core.dex.instructions.SwitchNode.initBlocks(SwitchNode.java:64)
        	at jadx.core.dex.visitors.blocksmaker.BlockSplitter.lambda$initBlocksInTargetNodes$0(BlockSplitter.java:71)
        	at java.util.ArrayList.forEach(ArrayList.java:1257)
        	at jadx.core.dex.visitors.blocksmaker.BlockSplitter.initBlocksInTargetNodes(BlockSplitter.java:68)
        	at jadx.core.dex.visitors.blocksmaker.BlockSplitter.visit(BlockSplitter.java:53)
        */
public static String getOem() {
   ...
    throw new UnsupportedOperationException("Method not decompiled: com.airwatch.core.AirWatchDevice.getOem():java.lang.String");
}
```

APK: [cdbc0b5a670cf37159f43d9259c9642d70affdec35871788a4c222a1d862919e](https://romainthomas.fr/application.apk)

**Comment by skylot** [comment]
@romainthomas thank you for this report!
I will try to fix this but the method is big and mix switch with try/catch so this can take a while :(

**Comment by romainthomas** [comment]
Yes no problem :) 
Thank you!
