### ISSUE TITLE
[core] Stackoverflows for Twitter app

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#809]
Hi, when I try to decompile Twitter app, I see a lot of stackoverflows like
```
"pool-1-thread-4" #15 prio=5 os_prio=0 cpu=19984.38ms elapsed=743.20s tid=0x00000023f0927000 nid=0xee4 runnable  [0x0000002382af9000]
   java.lang.Thread.State: RUNNABLE
        at java.util.HashMap.keySet(java.base@12.0.1/HashMap.java:903)
        at java.util.HashSet.iterator(java.base@12.0.1/HashSet.java:173)
        at java.util.AbstractCollection.addAll(java.base@12.0.1/AbstractCollection.java:351)
        at jadx.core.dex.regions.conditions.IfInfo.merge(IfInfo.java:52)
        at jadx.core.dex.visitors.regions.IfMakerHelper.mergeIfInfo(IfMakerHelper.java:295)
        at jadx.core.dex.visitors.regions.IfMakerHelper.mergeNestedIfNodes(IfMakerHelper.java:224)
        at jadx.core.dex.visitors.regions.IfMakerHelper.searchNestedIf(IfMakerHelper.java:55)
        at jadx.core.dex.visitors.regions.IfMakerHelper.mergeNestedIfNodes(IfMakerHelper.java:226)
        at jadx.core.dex.visitors.regions.IfMakerHelper.searchNestedIf(IfMakerHelper.java:55)
        at jadx.core.dex.visitors.regions.IfMakerHelper.mergeNestedIfNodes(IfMakerHelper.java:226)
        at jadx.core.dex.visitors.regions.IfMakerHelper.searchNestedIf(IfMakerHelper.java:55)
        at jadx.core.dex.visitors.regions.IfMakerHelper.mergeNestedIfNodes(IfMakerHelper.java:226)
        at jadx.core.dex.visitors.regions.IfMakerHelper.searchNestedIf(IfMakerHelper.java:55)
        at jadx.core.dex.visitors.regions.IfMakerHelper.mergeNestedIfNodes(IfMakerHelper.java:226)
        at jadx.core.dex.visitors.regions.IfMakerHelper.searchNestedIf(IfMakerHelper.java:55)
        at jadx.core.dex.visitors.regions.IfMakerHelper.mergeNestedIfNodes(IfMakerHelper.java:226)
        at jadx.core.dex.visitors.regions.IfMakerHelper.searchNestedIf(IfMakerHelper.java:55)
        at jadx.core.dex.visitors.regions.IfMakerHelper.mergeNestedIfNodes(IfMakerHelper.java:226)
        at jadx.core.dex.visitors.regions.IfMakerHelper.searchNestedIf(IfMakerHelper.java:55)
        at jadx.core.dex.visitors.regions.IfMakerHelper.mergeNestedIfNodes(IfMakerHelper.java:226)
        at jadx.core.dex.visitors.regions.IfMakerHelper.searchNestedIf(IfMakerHelper.java:55)
        at jadx.core.dex.visitors.regions.IfMakerHelper.mergeNestedIfNodes(IfMakerHelper.java:226)
        at jadx.core.dex.visitors.regions.IfMakerHelper.searchNestedIf(IfMakerHelper.java:55)
```

Arguments
```
--no-replace-consts --show-bad-code --threads-count 4 --no-inline-anonymous --no-imports --deobf --deobf-min 2 --deobf-rewrite-cfg
```

APK: https://drive.google.com/file/d/1WAf3xb7uznY0XKlL-6UDcfiDVm9_hvUg/view?usp=sharing

**Comment by huku-** [comment]
Hello,

I was unable to reproduce with latest version of jadx.

By the way, this doesn't seem like an error. It looks like a normal stack trace of a thread showing what the thread in question is currently executing.

Are you executing jadx directly from the command line or from within, let's say, an IDE? I suspect your runtime environment enables some kind of thread debugging, which results in this information being printed on the console. I'm not a Java expert, just guessing here.

Also, is this the complete error log or you have trimmed it down?

**Comment by sergey-wowwow** [comment]
@huku- 
> It looks like a normal stack trace of a thread showing what the thread in question is currently executing

It's a part of a huge stacktrace, I didn't want to provide tons of repeating lines

> Are you executing jadx directly from the command line

Command line

> your runtime environment enables some kind of thread debugging, which results in this information being printed on the console

This is ``` jstack ```

**Comment by sergey-wowwow** [comment]
The same bug can be reproduced in this app https://drive.google.com/file/d/1Gp9NewayWK26qDOMZ6vwwyhDzBseIG3y/view?usp=sharing

**Comment by skylot** [comment]
@sergey-wowwow  thanks for report! Looks like this a regression added in d1a6841 for #699

**Comment by sergey-wowwow** [comment]
Seems to be fixed, verified in multiple apps. Thanks!
