### ISSUE TITLE
Resources not decoded fully if an error occurs

### ISSUE THREAD

**Issue by f1ac** [skylot/jadx#82]
Decoding of resources stops for https://play.google.com/store/apps/details?id=com.coasia.airmentor after the following error occurs. The error is shown only during saving of results to HDD, however remaining resources are missing both in GUI and on disk. Missing resources include res/strings for example. Reproducible for both JADX/JADX-GUI 0.6.1 build 211 and 0.6.0 stable release. Not reproducible for the online version at http://www.javadecompilers.com/apk/ , however the exception itself is still there.

>INFO : processing ...
ERROR: Decode error
jadx.core.utils.exceptions.JadxException: Error decode: assets/logback.xml
	at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:65) ~[jadx-core-0.6.1-dev-build211.jar:na]
	at jadx.api.ResourcesLoader.loadContent(ResourcesLoader.java:82) ~[jadx-core-0.6.1-dev-build211.jar:na]
	at jadx.api.ResourceFile.getContent(ResourceFile.java:52) [jadx-core-0.6.1-dev-build211.jar:na]
	at jadx.api.JadxDecompiler$2.run(JadxDecompiler.java:179) [jadx-core-0.6.1-dev-build211.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_55]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_55]
	at java.lang.Thread.run(Unknown Source) [na:1.7.0_55]
Caused by: java.io.IOException: Decode error: Version is not 3, position: 0x2
	at jadx.core.xmlgen.CommonBinaryParser.die(CommonBinaryParser.java:96) ~[jadx-core-0.6.1-dev-build211.jar:na]
	at jadx.core.xmlgen.BinaryXMLParser.decode(BinaryXMLParser.java:95) ~[jadx-core-0.6.1-dev-build211.jar:na]
	at jadx.core.xmlgen.BinaryXMLParser.parse(BinaryXMLParser.java:88) ~[jadx-core-0.6.1-dev-build211.jar:na]
	at jadx.api.ResourcesLoader.loadContent(ResourcesLoader.java:106) ~[jadx-core-0.6.1-dev-build211.jar:na]
	at jadx.api.ResourcesLoader.access$000(ResourcesLoader.java:25) ~[jadx-core-0.6.1-dev-build211.jar:na]
	at jadx.api.ResourcesLoader$1.decode(ResourcesLoader.java:89) ~[jadx-core-0.6.1-dev-build211.jar:na]
	at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:63) ~[jadx-core-0.6.1-dev-build211.jar:na]
	... 6 common frames omitted
INFO : done

**Comment by f1ac** [comment]
I guess a try{} block would be useful at JadxDecompiler.java:179

**Comment by skylot** [comment]
For now jadx don't restore resources from 'resources.arsc' file, your can view dump from '.arsc' file in jadx-gui, but there are no pretty xml files for strings, also images decoding not supported.
Online http://www.javadecompilers.com/apk/ uses [apktool](https://ibotpeaches.github.io/Apktool/) for decode resources.
So, error you mention don't break resource decoding, decode for missing files  just not implemented yet )
Anyway I will make detection of plain text xml files for fix this issue.
