### ISSUE TITLE
jadx.core.utils.exceptions.DecodeException: java class to dex conversion error

### ISSUE THREAD

**Issue by ankasani** [skylot/jadx#822]
I am using the latest version of jadx 1.1.0

INFO  - loading ...
ERROR - jadx error: Error load file: C:\Users\ankasani\Downloads\files1\workspace\test-classes\com\automation\AI\testBase\BaseTest.class
jadx.core.utils.exceptions.JadxRuntimeException: Error load file: C:\Users\ankasani\Downloads\files1\workspace\test-classes\com\automation\AI\testBase\BaseTest.class
        at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:121)
        at jadx.api.JadxDecompiler.load(JadxDecompiler.java:88)
        at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:34)
        at jadx.cli.JadxCLI.main(JadxCLI.java:19)
Caused by: jadx.core.utils.exceptions.DecodeException: java class to dex conversion error:
 dx exception: Java to dex conversion error, code: 1
        at jadx.core.utils.files.InputFile.loadFromJar(InputFile.java:200)
        at jadx.core.utils.files.InputFile.loadFromClassFile(InputFile.java:217)
        at jadx.core.utils.files.InputFile.searchDexFiles(InputFile.java:65)
        at jadx.core.utils.files.InputFile.addFilesFrom(InputFile.java:40)
        at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:119)
        ... 3 common frames omitted
Caused by: jadx.core.utils.exceptions.JadxException: dx exception: Java to dex conversion error, code: 1
        at jadx.core.utils.files.JavaToDex.convert(JavaToDex.java:63)
        at jadx.core.utils.files.InputFile.loadFromJar(InputFile.java:191)
        ... 7 common frames omitted
Caused by: jadx.core.utils.exceptions.JadxException: Java to dex conversion error, code: 1
        at jadx.core.utils.files.JavaToDex.convert(JavaToDex.java:52)
        ... 8 common frames omitted

Any idea why it was causing this issue ?

**Comment by skylot** [comment]
@ankasani sorry about that, but now jadx use deprecated and unsupported `dx` library and it does not support the latest java class versions.
As a workaround, you can use [`d8`](https://developer.android.com/studio/command-line/d8) util to convert a class file to dex and open that dex in jadx or...  just use another java decompiler like [cfr](https://www.benf.org/other/cfr/).
I open a new issue #823 to replace dx with d8 in jadx, so you can check progress on this work.
