### ISSUE TITLE
[core] Cannot open .jar file

### ISSUE THREAD

**Issue by TheInterestingSoul** [skylot/jadx#838]
OS: Debian 10 buster
Kernel: x86_64 Linux 4.19.0

```bash
tis@theinterestingsoul-pc:~/文档$ jadx iapp-jar包.jar
INFO  - loading ...
ERROR - jadx error: Error load file: iapp-jar包.jar
jadx.core.utils.exceptions.JadxRuntimeException: Error load file: iapp-jar包.jar
	at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:121)
	at jadx.api.JadxDecompiler.load(JadxDecompiler.java:88)
	at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:34)
	at jadx.cli.JadxCLI.main(JadxCLI.java:19)
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1535)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1436)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1443)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1274)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1237)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
	at jadx.core.utils.files.InputFile.loadFromZip(InputFile.java:99)
	at jadx.core.utils.files.InputFile.searchDexFiles(InputFile.java:76)
	at jadx.core.utils.files.InputFile.addFilesFrom(InputFile.java:40)
	at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:119)
	... 3 common frames omitted
```

[File.zip](https://github.com/skylot/jadx/files/4113379/iapp-jar.zip)

**Comment by jpstotz** [comment]
The error message indicates that the JAR files is defect (potentially truncated). 

You can test this e.g. by executing `zip -T iapp-jar包.jar`.
Most likely you will get some messages that the ZIP file is corrupt.

You may be able to fix the errors and recover at least some parts of the JAR file. To do so please read https://superuser.com/questions/23290/terminal-tool-linux-for-repair-corrupted-zip-files

**Comment by TheInterestingSoul** [comment]
@jpstotz Soory. I downloaded a backup on my netdisk and opened it successfully. There may be a problem with _KDE Connect_ .:cold_sweat:
