### ISSUE TITLE
[core] Small app is decompiled within long time

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#846]
APK: https://drive.google.com/file/d/1MC4DiEojEOLGqKKzt3mspD8jMYQtrBe3/view?usp=sharing

jstack shows the following output
```
   java.lang.Thread.State: RUNNABLE
	at java.util.BitSet.and(java.base@13.0.1/BitSet.java:921)
	at jadx.core.utils.BlockUtils.calcPartialPostDominance(BlockUtils.java:713)
	at jadx.core.utils.BlockUtils.calcPartialImmediatePostDominator(BlockUtils.java:750)
	at jadx.core.dex.visitors.regions.RegionMaker.calcPostDomOut(RegionMaker.java:869)
	at jadx.core.dex.visitors.regions.RegionMaker.processSwitch(RegionMaker.java:761)
	at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:130)
	at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:88)
	//...
```

Maybe there is an error preventing it from being decompiled much faster?

**Comment by skylot** [comment]
Fixed. The cause was a new switch processing method implemented in #826. I add some additional checks to skip not relevant paths, this makes decompilation much faster in this case.
