### ISSUE TITLE
[core] Decompilation stucked at 25% for YouTube Go

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#854]
Hi, 
APK: https://drive.google.com/file/d/1m0ClYvNESTgedIlna9CyZg4L5iruioHA/view?usp=sharing

Stacktrace
```
"pool-6-thread-3" #54 prio=5 os_prio=31 cpu=287073.40ms elapsed=833.57s tid=0x00007fcc7857b800 nid=0x1661f runnable  [0x000070001bfe9000]
   java.lang.Thread.State: RUNNABLE
	at jadx.core.dex.visitors.typeinference.TypeCompare.compareTypes(TypeCompare.java:44)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.checkBound(TypeUpdate.java:212)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.inBounds(TypeUpdate.java:204)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.updateTypeForSsaVar(TypeUpdate.java:129)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.updateTypeChecked(TypeUpdate.java:115)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.allSameListener(TypeUpdate.java:346)
	at jadx.core.dex.visitors.typeinference.TypeUpdate$$Lambda$228/0x0000000800d89040.update(Unknown Source)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.runListeners(TypeUpdate.java:189)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.requestUpdate(TypeUpdate.java:170)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.requestUpdateForSsaVar(TypeUpdate.java:141)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.updateTypeForSsaVar(TypeUpdate.java:135)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.updateTypeChecked(TypeUpdate.java:115)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.allSameListener(TypeUpdate.java:341)
	at jadx.core.dex.visitors.typeinference.TypeUpdate$$Lambda$228/0x0000000800d89040.update(Unknown Source)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.runListeners(TypeUpdate.java:189)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.requestUpdate(TypeUpdate.java:170)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.requestUpdateForSsaVar(TypeUpdate.java:147)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.updateTypeForSsaVar(TypeUpdate.java:135)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.updateTypeChecked(TypeUpdate.java:115)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.ifListener(TypeUpdate.java:436)
	at jadx.core.dex.visitors.typeinference.TypeUpdate$$Lambda$231/0x0000000800dd0440.update(Unknown Source)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.runListeners(TypeUpdate.java:189)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.requestUpdate(TypeUpdate.java:170)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.updateTypeChecked(TypeUpdate.java:117)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.ifListener(TypeUpdate.java:436)
	at jadx.core.dex.visitors.typeinference.TypeUpdate$$Lambda$231/0x0000000800dd0440.update(Unknown Source)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.runListeners(TypeUpdate.java:189)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.requestUpdate(TypeUpdate.java:170)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.requestUpdateForSsaVar(TypeUpdate.java:147)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.updateTypeForSsaVar(TypeUpdate.java:135)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.updateTypeChecked(TypeUpdate.java:115)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.apply(TypeUpdate.java:71)
	at jadx.core.dex.visitors.typeinference.TypeUpdate.applyWithWiderAllow(TypeUpdate.java:55)
	at jadx.core.dex.visitors.typeinference.TypeInferenceVisitor.tryWiderObjects(TypeInferenceVisitor.java:456)
	at jadx.core.dex.visitors.typeinference.TypeInferenceVisitor.tryDeduceType(TypeInferenceVisitor.java:351)
	at jadx.core.dex.visitors.typeinference.TypeInferenceVisitor.runTypePropagation(TypeInferenceVisitor.java:119)
	at jadx.core.dex.visitors.typeinference.TypeInferenceVisitor.visit(TypeInferenceVisitor.java:77)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:31)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:16)
	at jadx.core.dex.visitors.DepthTraversal$$Lambda$278/0x0000000800e36840.accept(Unknown Source)
	at java.util.ArrayList.forEach(java.base@13.0.1/ArrayList.java:1507)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:16)
	at jadx.core.ProcessClass.process(ProcessClass.java:41)
	- locked <0x00000004408442b0> (a jadx.core.dex.info.ClassInfo)
	at jadx.core.ProcessClass$$Lambda$293/0x0000000800e49c40.accept(Unknown Source)
	at java.util.ArrayList.forEach(java.base@13.0.1/ArrayList.java:1507)
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:59)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:297)
	- locked <0x0000000440b08bc8> (a jadx.core.dex.nodes.ClassNode)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:276)
	at jadx.api.JavaClass.decompile(JavaClass.java:57)
	at jadx.gui.jobs.DecompileJob$$Lambda$276/0x0000000800e30040.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@13.0.1/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@13.0.1/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@13.0.1/Thread.java:830)

```

**Comment by sergey-wowwow** [comment]
@skylot 
Can you also please look at this one? There are a few more APKs which cannot be decompiled

**Comment by skylot** [comment]
@sergey-wowwow this case is fixed.

**Comment by sergey-wowwow** [comment]
@skylot 
Thanks! That works perfect now :)
