### ISSUE TITLE
[core] JadxRuntimeException in pass: SSATransform

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#858]
Hi, I've noticed an error in decompiled code, class ``` sg.bigo.live.model.live.end.a ```
```java

    /*  JADX ERROR: JadxRuntimeException in pass: SSATransform
        jadx.core.utils.exceptions.JadxRuntimeException: Not initialized variable reg: 5, insn: 0x0000: IPUT  (r5 I:sg.bigo.live.model.live.end.LiveEndComponent), (r4 I:sg.bigo.live.model.live.end.a) sg.bigo.live.model.live.end.a.z sg.bigo.live.model.live.end.LiveEndComponent, block:B:0:0x0000
        	at jadx.core.dex.visitors.ssa.SSATransform.renameVarsInBlock(SSATransform.java:165)
        	at jadx.core.dex.visitors.ssa.SSATransform.renameVariables(SSATransform.java:137)
        	at jadx.core.dex.visitors.ssa.SSATransform.process(SSATransform.java:55)
        	at jadx.core.dex.visitors.ssa.SSATransform.visit(SSATransform.java:41)
        */
    C13037a(
/*
Method generation error in method: sg.bigo.live.model.live.end.a.<init>(long):void, dex: classes4.dex
    jadx.core.utils.exceptions.JadxRuntimeException: Code variable not set in r4v0 ?
    	at jadx.core.dex.instructions.args.SSAVar.getCodeVar(SSAVar.java:189)
    	at jadx.core.codegen.MethodGen.addMethodArguments(MethodGen.java:161)
    	at jadx.core.codegen.MethodGen.addDefinition(MethodGen.java:133)
    	at jadx.core.codegen.ClassGen.addMethodCode(ClassGen.java:317)
    	at jadx.core.codegen.ClassGen.addMethod(ClassGen.java:275)
    	at jadx.core.codegen.ClassGen.lambda$addInnerClsAndMethods$3(ClassGen.java:244)
    	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
    	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
    	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
    	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
    	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
    	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
    	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
    	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
    	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
    	at jadx.core.codegen.ClassGen.addInnerClsAndMethods(ClassGen.java:240)
    	at jadx.core.codegen.ClassGen.addClassBody(ClassGen.java:231)
    	at jadx.core.codegen.ClassGen.addClassCode(ClassGen.java:115)
    	at jadx.core.codegen.ClassGen.makeClass(ClassGen.java:81)
    	at jadx.core.codegen.CodeGen.wrapCodeGen(CodeGen.java:45)
    	at jadx.core.codegen.CodeGen.generateJavaCode(CodeGen.java:34)
    	at jadx.core.codegen.CodeGen.generate(CodeGen.java:22)
    	at jadx.core.ProcessClass.generateCode(ProcessClass.java:61)
    	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:297)
    	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:276)
    
*/
```

APK: https://drive.google.com/file/d/1JHN2y5aNkdaCMzjrJy-sjIBKnt-_a1y7/view?usp=sharing

**Comment by sergey-wowwow** [comment]
Updated error
```java
    /*  JADX ERROR: JadxRuntimeException in pass: SSATransform
        jadx.core.utils.exceptions.JadxRuntimeException: Not initialized variable reg: 5, insn: 0x0000: IPUT  (r5 I:sg.bigo.live.model.live.end.LiveEndComponent), (r4 I:sg.bigo.live.model.live.end.a) sg.bigo.live.model.live.end.a.z sg.bigo.live.model.live.end.LiveEndComponent, block:B:0:0x0000
        	at jadx.core.dex.visitors.ssa.SSATransform.renameVarsInBlock(SSATransform.java:165)
        	at jadx.core.dex.visitors.ssa.SSATransform.renameVariables(SSATransform.java:137)
        	at jadx.core.dex.visitors.ssa.SSATransform.process(SSATransform.java:55)
        	at jadx.core.dex.visitors.ssa.SSATransform.visit(SSATransform.java:41)
        */
    /*  JADX ERROR: NullPointerException in pass: ConstInlineVisitor
        java.lang.NullPointerException
        	at jadx.core.dex.visitors.ConstInlineVisitor.checkForSynchronizeBlock(ConstInlineVisitor.java:121)
        	at jadx.core.dex.visitors.ConstInlineVisitor.checkInsn(ConstInlineVisitor.java:86)
        	at jadx.core.dex.visitors.ConstInlineVisitor.process(ConstInlineVisitor.java:53)
        	at jadx.core.dex.visitors.ConstInlineVisitor.visit(ConstInlineVisitor.java:45)
        */
    /*  JADX ERROR: NullPointerException in pass: ConstructorVisitor
        java.lang.NullPointerException
        	at jadx.core.dex.instructions.mods.ConstructorInsn.<init>(ConstructorInsn.java:47)
        	at jadx.core.dex.visitors.ConstructorVisitor.processInvoke(ConstructorVisitor.java:64)
        	at jadx.core.dex.visitors.ConstructorVisitor.replaceInvoke(ConstructorVisitor.java:48)
        	at jadx.core.dex.visitors.ConstructorVisitor.visit(ConstructorVisitor.java:37)
        */
    /*  JADX ERROR: NullPointerException in pass: ProcessVariables
        java.lang.NullPointerException
        	at jadx.core.dex.visitors.regions.variables.ProcessVariables$1.processBlock(ProcessVariables.java:77)
        	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseInternal(DepthRegionTraversal.java:60)
        	at jadx.core.dex.visitors.regions.DepthRegionTraversal.lambda$traverseInternal$0(DepthRegionTraversal.java:64)
        	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
        	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverseInternal(DepthRegionTraversal.java:64)
        	at jadx.core.dex.visitors.regions.DepthRegionTraversal.traverse(DepthRegionTraversal.java:19)
        	at jadx.core.dex.visitors.regions.variables.ProcessVariables.removeUnusedResults(ProcessVariables.java:70)
        	at jadx.core.dex.visitors.regions.variables.ProcessVariables.visit(ProcessVariables.java:45)
        */
    C12941a(long r4) {
        /*
            r3 = this;
            r4.f59230z = r5
            r0 = 8200(0x2008, double:4.0513E-320)
            r2 = 1000(0x3e8, double:4.94E-321)
            r4.<init>(r0, r2)
            return
        */
        throw new UnsupportedOperationException("Method not decompiled: sg.bigo.live.model.live.end.C12941a.<init>(sg.bigo.live.model.live.end.LiveEndComponent):void");
    }
```

**Comment by skylot** [comment]
@sergey-wowwow fixed.

**Comment by sergey-wowwow** [comment]
@skylot 
There are a lot of warning in code, check out `okio/Buffer$outputStream$1.java`
```java
     /* JADX WARN: Incorrect args count in method signature: ()V */
     Pipe$sink$1(okio.Pipe pipe) {
         this.this$0 = pipe;
     }
```
