### ISSUE TITLE
[core] JadxRuntimeException in pass: MethodInvokeVisitor

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#867]
Hi, I've noticed an error that prevents a method from being decompiled, class ``` com.ss.android.e.d$2 ```
```java

    /* renamed from: com.ss.android.e.d$2 */
    class C11912 implements java.lang.Runnable {
        /*  JADX ERROR: JadxRuntimeException in pass: MethodInvokeVisitor
            jadx.core.utils.exceptions.JadxRuntimeException: Not class type: E
            	at jadx.core.dex.info.ClassInfo.checkClassType(ClassInfo.java:60)
            	at jadx.core.dex.info.ClassInfo.fromType(ClassInfo.java:31)
            	at jadx.core.dex.nodes.DexNode.resolveClass(DexNode.java:143)
            	at jadx.core.dex.nodes.RootNode.resolveClass(RootNode.java:183)
            	at jadx.core.dex.nodes.utils.MethodUtils.processMethodArgsOverloaded(MethodUtils.java:75)
            	at jadx.core.dex.nodes.utils.MethodUtils.collectOverloadedMethods(MethodUtils.java:54)
            	at jadx.core.dex.visitors.MethodInvokeVisitor.processOverloaded(MethodInvokeVisitor.java:108)
            	at jadx.core.dex.visitors.MethodInvokeVisitor.processInvoke(MethodInvokeVisitor.java:101)
            	at jadx.core.dex.visitors.MethodInvokeVisitor.processInsn(MethodInvokeVisitor.java:72)
            	at jadx.core.dex.visitors.MethodInvokeVisitor.visit(MethodInvokeVisitor.java:65)
            */
        public void run() {
            /*
                r5 = this;
                r4 = 0
                r1 = 0
                com.ss.android.e.d r0 = com.ss.android.p065e.C1189d.this     // Catch:{ Throwable -> 0x0031 }
                com.ss.android.e.d r2 = com.ss.android.p065e.C1189d.this     // Catch:{ Throwable -> 0x0031 }
                com.ss.android.e.e r2 = r2.f1434b     // Catch:{ Throwable -> 0x0031 }
                java.lang.String r2 = r2.modelCachePath()     // Catch:{ Throwable -> 0x0031 }
                com.ss.android.e.d r3 = com.ss.android.p065e.C1189d.this     // Catch:{ Throwable -> 0x0031 }
                com.ss.android.e.e r3 = r3.f1434b     // Catch:{ Throwable -> 0x0031 }
                java.lang.String r3 = r3.modelUrl()     // Catch:{ Throwable -> 0x0031 }
                java.io.InputStream r1 = r0.mo14467a(r2, r3)     // Catch:{ Throwable -> 0x0031 }
                if (r1 != 0) goto L_0x0022
                com.ss.android.p065e.C16114b.closeQuietly(r1)
                com.ss.android.e.d r0 = com.ss.android.p065e.C1189d.this
                r0.isDownloading = r4
            L_0x0021:
                return
            L_0x0022:
                com.ss.android.e.d r0 = com.ss.android.p065e.C1189d.this     // Catch:{ Throwable -> 0x0031 }
                E r0 = r0.f1433a     // Catch:{ Throwable -> 0x0031 }
                r0.loadEvaluator(r1)     // Catch:{ Throwable -> 0x0031 }
                com.ss.android.p065e.C16114b.closeQuietly(r1)
                com.ss.android.e.d r0 = com.ss.android.p065e.C1189d.this
                r0.isDownloading = r4
                goto L_0x0021
            L_0x0031:
                r0 = move-exception
                com.ss.android.e.d r2 = com.ss.android.p065e.C1189d.this     // Catch:{ all -> 0x0059 }
                r3 = 2
                r2.f1435c = r3     // Catch:{ all -> 0x0059 }
                com.ss.android.e.d r2 = com.ss.android.p065e.C1189d.this     // Catch:{ all -> 0x0059 }
                com.ss.android.e.d r3 = com.ss.android.p065e.C1189d.this     // Catch:{ all -> 0x0059 }
                com.ss.android.e.e r3 = r3.f1434b     // Catch:{ all -> 0x0059 }
                java.lang.String r3 = r3.modelCachePath()     // Catch:{ all -> 0x0059 }
                r2.mo14468a(r3)     // Catch:{ all -> 0x0059 }
                com.ss.android.e.d r2 = com.ss.android.p065e.C1189d.this     // Catch:{ all -> 0x0059 }
                com.ss.android.e.g r2 = r2.listener     // Catch:{ all -> 0x0059 }
                if (r2 == 0) goto L_0x0051
                com.ss.android.e.d r2 = com.ss.android.p065e.C1189d.this     // Catch:{ all -> 0x0059 }
                com.ss.android.e.g r2 = r2.listener     // Catch:{ all -> 0x0059 }
                r2.onModelLoadFailed(r0)     // Catch:{ all -> 0x0059 }
            L_0x0051:
                com.ss.android.p065e.C16114b.closeQuietly(r1)
                com.ss.android.e.d r0 = com.ss.android.p065e.C1189d.this
                r0.isDownloading = r4
                goto L_0x0021
            L_0x0059:
                r0 = move-exception
                com.ss.android.p065e.C16114b.closeQuietly(r1)
                com.ss.android.e.d r1 = com.ss.android.p065e.C1189d.this
                r1.isDownloading = r4
                throw r0
            */
            throw new UnsupportedOperationException("Method not decompiled: com.ss.android.p065e.C1189d.C11912.run():void");
        }

        C11912() {
        }
    }
```
APK: https://drive.google.com/file/d/1wrBR3UgxGNoIpSMmuyqEC1fXcgiFmJvq/view?usp=sharing

**Comment by skylot** [comment]
@sergey-wowwow fixed.
