### ISSUE TITLE
[core] JadxRuntimeException: Method info already added

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#868]
Hi, class ``` com.bytedance.jedi.arch.ext.list.LoadStrategyKt$Prepend$1 ```
```java

    /*  JADX ERROR: Method load error
        jadx.core.utils.exceptions.DecodeException: Load method exception: Method info already added: kotlin.collections.CollectionsKt.plus(java.util.Collection, java.lang.Iterable):java.util.List in method: com.bytedance.jedi.arch.ext.list.LoadStrategyKt$Prepend$1.invoke(java.util.List<? extends T>, java.util.List<? extends T>):java.util.List<T>, dex: classes3.dex
        	at jadx.core.dex.nodes.MethodNode.load(MethodNode.java:154)
        	at jadx.core.dex.nodes.ClassNode.load(ClassNode.java:306)
        	at jadx.core.ProcessClass.process(ProcessClass.java:36)
        	at jadx.core.ProcessClass.generateCode(ProcessClass.java:58)
        	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:297)
        	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:276)
        Caused by: jadx.core.utils.exceptions.JadxRuntimeException: Method info already added: kotlin.collections.CollectionsKt.plus(java.util.Collection, java.lang.Iterable):java.util.List
        	at jadx.core.dex.info.InfoStorage.putMethod(InfoStorage.java:42)
        	at jadx.core.dex.info.MethodInfo.fromDex(MethodInfo.java:50)
        	at jadx.core.dex.instructions.InsnDecoder.invoke(InsnDecoder.java:678)
        	at jadx.core.dex.instructions.InsnDecoder.decode(InsnDecoder.java:528)
        	at jadx.core.dex.instructions.InsnDecoder.process(InsnDecoder.java:78)
        	at jadx.core.dex.nodes.MethodNode.load(MethodNode.java:139)
        	... 5 more
        */
    public final java.util.List<T> invoke(java.util.List<? extends T> r1, java.util.List<? extends T> r2) {
        /*
            r1 = this;
            java.lang.String r0 = "list"
            kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull(r2, r0)
            java.lang.String r0 = "refresh"
            kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull(r3, r0)
            java.util.Collection r3 = (java.util.Collection) r3
            java.lang.Iterable r2 = (java.lang.Iterable) r2
            java.util.List r0 = kotlin.collections.CollectionsKt.plus(r3, r2)
            return r0
        */
        throw new UnsupportedOperationException("Method not decompiled: com.bytedance.jedi.arch.ext.list.LoadStrategyKt$Prepend$1.invoke(java.util.List, java.util.List):java.util.List");
    }
```

APK: https://drive.google.com/file/d/1wrBR3UgxGNoIpSMmuyqEC1fXcgiFmJvq/view?usp=sharing

**Comment by skylot** [comment]
@sergey-wowwow fixed.
Looks like it was a multithreading issue, please check to be sure fix is working.

**Comment by sergey-wowwow** [comment]
@skylot 
Thanks, seems to be fixed!
