### ISSUE TITLE
Caused by: jadx.core.utils.exceptions.JadxException: Java to dex conversion error, code: 1

### ISSUE THREAD

**Issue by hktalent** [skylot/jadx#905]
```
 jadx --version
1.1.0

 jadx -ds srcpsu_for_weblogic10.3.6/psu_200414/p30857748_1036_Generic/Q3ZB.jar
INFO  - loading ...
ERROR - jadx error: Error load file: weblogic/psu_for_weblogic10.3.6/psu_200414/p30857748_1036_Generic/Q3ZB.jar
jadx.core.utils.exceptions.JadxRuntimeException: Error load file: weblogic/psu_for_weblogic10.3.6/psu_200414/p30857748_1036_Generic/Q3ZB.jar
        at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:121)
        at jadx.api.JadxDecompiler.load(JadxDecompiler.java:88)
        at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:34)
        at jadx.cli.JadxCLI.main(JadxCLI.java:19)
Caused by: jadx.core.utils.exceptions.DecodeException: java class to dex conversion error:
 dx exception: Java to dex conversion error, code: 1
        at jadx.core.utils.files.InputFile.loadFromJar(InputFile.java:200)
        at jadx.core.utils.files.InputFile.searchDexFiles(InputFile.java:80)
        at jadx.core.utils.files.InputFile.addFilesFrom(InputFile.java:40)
        at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:119)
        ... 3 common frames omitted
Caused by: jadx.core.utils.exceptions.JadxException: dx exception: Java to dex conversion error, code: 1
        at jadx.core.utils.files.JavaToDex.convert(JavaToDex.java:63)
        at jadx.core.utils.files.InputFile.loadFromJar(InputFile.java:191)
        ... 6 common frames omitted
Caused by: jadx.core.utils.exceptions.JadxException: Java to dex conversion error, code: 1
        at jadx.core.utils.files.JavaToDex.convert(JavaToDex.java:52)
        ... 7 common frames omitted
```

**Comment by skylot** [comment]
@hktalent  sorry, but from provided stacktrace is not clear why jar to dex failed.
Anyway, native java bytecode support is very poor now in jadx and I don't think it will be fixed soon (check the progress on #823 issue).
Also, check suggessions in [this](https://github.com/skylot/jadx/issues/911#issuecomment-616103889) comment.
