### ISSUE TITLE
[core] Multiple errors during decompilation

### ISSUE THREAD

**Issue by angervision** [skylot/jadx#908]
```
INFO  - loading ...
INFO  - processing ...
ERROR - StackOverflow in pass: RegionMakerVisitor in method: androidx.core.content.res.FontResourcesParserCompat.parse(org.xmlpull.v1.XmlPullParser, android.content.res.Resources):androidx.core.content.res.FontResourcesParserCompat$FamilyResourceEntry, dex: classes.dex, details: 
ERROR - Method code generation error in method: com.androidplot.xy.XYLegendWidget.<clinit>():void, dex: classes.dex
jadx.core.utils.exceptions.CodegenException: Error generate insn: 0x0002: CONSTRUCTOR  (r0v0 ? I:com.androidplot.xy.a) =  call: com.androidplot.xy.a.<init>():void type: CONSTRUCTOR in method: com.androidplot.xy.XYLegendWidget.<clinit>():void, dex: classes.dex
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:256)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:221)
	at jadx.core.codegen.RegionGen.makeSimpleBlock(RegionGen.java:109)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:55)
	at jadx.core.codegen.RegionGen.makeSimpleRegion(RegionGen.java:92)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:58)
	at jadx.core.codegen.MethodGen.addRegionInsns(MethodGen.java:211)
	at jadx.core.codegen.MethodGen.addInstructions(MethodGen.java:204)
	at jadx.core.codegen.ClassGen.addMethodCode(ClassGen.java:318)
	at jadx.core.codegen.ClassGen.addMethod(ClassGen.java:271)
	at jadx.core.codegen.ClassGen.lambda$addInnerClsAndMethods$2(ClassGen.java:240)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at jadx.core.codegen.ClassGen.addInnerClsAndMethods(ClassGen.java:236)
	at jadx.core.codegen.ClassGen.addClassBody(ClassGen.java:227)
	at jadx.core.codegen.ClassGen.addClassCode(ClassGen.java:112)
	at jadx.core.codegen.ClassGen.makeClass(ClassGen.java:78)
	at jadx.core.codegen.CodeGen.wrapCodeGen(CodeGen.java:44)
	at jadx.core.codegen.CodeGen.generateJavaCode(CodeGen.java:33)
	at jadx.core.codegen.CodeGen.generate(CodeGen.java:21)
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:61)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:273)
	at jadx.api.JavaClass.getCodeInfo(JavaClass.java:53)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:201)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: jadx.core.utils.exceptions.JadxRuntimeException: Code variable not set in r0v0 ?
	at jadx.core.dex.instructions.args.SSAVar.getCodeVar(SSAVar.java:189)
	at jadx.core.codegen.InsnGen.makeConstructor(InsnGen.java:620)
	at jadx.core.codegen.InsnGen.makeInsnBody(InsnGen.java:364)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:250)
	... 34 common frames omitted
ERROR - IndexOutOfBoundsException in pass: RegionMakerVisitor in method: com.google.android.gms.dynamite.DynamiteModule.getRemoteVersion(android.content.Context, java.lang.String, boolean):int, dex: classes.dex
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at jadx.core.dex.nodes.InsnNode.getArg(InsnNode.java:101)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:611)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.processMonitorEnter(RegionMaker.java:561)
	at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:133)
	at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:86)
	at jadx.core.dex.visitors.regions.RegionMaker.processIf(RegionMaker.java:693)
	at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:123)
	at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:86)
	at jadx.core.dex.visitors.regions.RegionMaker.processMonitorEnter(RegionMaker.java:598)
	at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:133)
	at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:86)
	at jadx.core.dex.visitors.regions.RegionMakerVisitor.visit(RegionMakerVisitor.java:49)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:31)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:16)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:16)
	at jadx.core.ProcessClass.process(ProcessClass.java:41)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:59)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:273)
	at jadx.api.JavaClass.getCodeInfo(JavaClass.java:53)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:201)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
ERROR - StackOverflow in pass: MarkFinallyVisitor in method: com.google.android.gms.internal.measurement.zzwx.zza(java.lang.Object, com.google.android.gms.internal.measurement.zzxi, com.google.android.gms.internal.measurement.zzuz):void, dex: classes.dex, details: 
ERROR - StackOverflow in pass: RegionMakerVisitor in method: com.google.common.io.BaseEncoding.3.read():int, dex: classes.dex, details: 
ERROR - StackOverflow in pass: MarkFinallyVisitor in method: com.google.common.util.concurrent.InterruptibleTask.run():void, dex: classes.dex, details: 
ERROR - IndexOutOfBoundsException in pass: RegionMakerVisitor in method: com.google.firebase.iid.zzat.zze(android.os.Bundle):android.os.Bundle, dex: classes.dex
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at jadx.core.dex.nodes.InsnNode.getArg(InsnNode.java:101)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:611)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.processMonitorEnter(RegionMaker.java:561)
	at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:133)
	at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:86)
	at jadx.core.dex.visitors.regions.RegionMaker.processIf(RegionMaker.java:693)
	at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:123)
	at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:86)
	at jadx.core.dex.visitors.regions.RegionMakerVisitor.visit(RegionMakerVisitor.java:49)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:31)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:16)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:16)
	at jadx.core.ProcessClass.process(ProcessClass.java:41)
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:58)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:273)
	at jadx.api.JavaClass.getCodeInfo(JavaClass.java:53)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:201)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
ERROR - StackOverflow in pass: RegionMakerVisitor in method: io.reactivex.internal.operators.observable.ObservableDistinct.DistinctObserver.poll():T, dex: classes2.dex, details: 
ERROR - StackOverflow in pass: RegionMakerVisitor in method: io.reactivex.internal.operators.observable.ObservableFilter.FilterObserver.poll():T, dex: classes2.dex, details: 
ERROR - StackOverflow in pass: MarkFinallyVisitor in method: kotlin.concurrent.LocksKt.write(java.util.concurrent.locks.ReentrantReadWriteLock, kotlin.jvm.functions.Function0):T, dex: classes2.dex, details: 
ERROR - StackOverflow in pass: MarkFinallyVisitor in method: kotlinx.coroutines.internal.ExceptionsConstuctorKt.tryCopyException(java.lang.Throwable):E, dex: classes2.dex, details: 
ERROR - IndexOutOfBoundsException in pass: RegionMakerVisitor in method: rx.internal.operators.OperatorMerge.MergeSubscriber.emitScalar(java.lang.Object, long):void, dex: classes2.dex
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at jadx.core.dex.nodes.InsnNode.getArg(InsnNode.java:101)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:611)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.processMonitorEnter(RegionMaker.java:561)
	at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:133)
	at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:86)
	at jadx.core.dex.visitors.regions.RegionMaker.processIf(RegionMaker.java:693)
	at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:123)
	at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:86)
	at jadx.core.dex.visitors.regions.RegionMaker.processHandlersOutBlocks(RegionMaker.java:1008)
	at jadx.core.dex.visitors.regions.RegionMaker.processTryCatchBlocks(RegionMaker.java:978)
	at jadx.core.dex.visitors.regions.RegionMakerVisitor.visit(RegionMakerVisitor.java:52)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:31)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:16)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:16)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$0(DepthTraversal.java:15)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:15)
	at jadx.core.ProcessClass.process(ProcessClass.java:41)
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:58)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:273)
	at jadx.api.JavaClass.getCodeInfo(JavaClass.java:53)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:201)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
ERROR - IndexOutOfBoundsException in pass: RegionMakerVisitor in method: rx.internal.operators.OperatorMerge.MergeSubscriber.emitScalar(rx.internal.operators.OperatorMerge$InnerSubscriber, java.lang.Object, long):void, dex: classes2.dex
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at jadx.core.dex.nodes.InsnNode.getArg(InsnNode.java:101)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:611)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.traverseMonitorExits(RegionMaker.java:619)
	at jadx.core.dex.visitors.regions.RegionMaker.processMonitorEnter(RegionMaker.java:561)
	at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:133)
	at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:86)
	at jadx.core.dex.visitors.regions.RegionMaker.processIf(RegionMaker.java:693)
	at jadx.core.dex.visitors.regions.RegionMaker.traverse(RegionMaker.java:123)
	at jadx.core.dex.visitors.regions.RegionMaker.makeRegion(RegionMaker.java:86)
	at jadx.core.dex.visitors.regions.RegionMaker.processHandlersOutBlocks(RegionMaker.java:1008)
	at jadx.core.dex.visitors.regions.RegionMaker.processTryCatchBlocks(RegionMaker.java:978)
	at jadx.core.dex.visitors.regions.RegionMakerVisitor.visit(RegionMakerVisitor.java:52)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:31)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$1(DepthTraversal.java:16)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:16)
	at jadx.core.dex.visitors.DepthTraversal.lambda$visit$0(DepthTraversal.java:15)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at jadx.core.dex.visitors.DepthTraversal.visit(DepthTraversal.java:15)
	at jadx.core.ProcessClass.process(ProcessClass.java:41)
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:58)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:273)
	at jadx.api.JavaClass.getCodeInfo(JavaClass.java:53)
	at jadx.api.JadxDecompiler.lambda$appendSourcesSave$0(JadxDecompiler.java:201)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
ERROR - 14 errors occurred in following nodes:
ERROR -   Method: androidx.core.content.res.FontResourcesParserCompat.parse(org.xmlpull.v1.XmlPullParser, android.content.res.Resources):androidx.core.content.res.FontResourcesParserCompat$FamilyResourceEntry
ERROR -   Method: com.androidplot.xy.XYLegendWidget.<clinit>():void
ERROR -   Method: com.google.android.gms.dynamite.DynamiteModule.getRemoteVersion(android.content.Context, java.lang.String, boolean):int
ERROR -   Method: com.google.android.gms.internal.measurement.zzwx.zza(java.lang.Object, com.google.android.gms.internal.measurement.zzxi, com.google.android.gms.internal.measurement.zzuz):void
ERROR -   Method: com.google.common.io.BaseEncoding.3.read():int
ERROR -   Method: com.google.common.util.concurrent.InterruptibleTask.run():void
ERROR -   Method: com.google.firebase.iid.zzat.zze(android.os.Bundle):android.os.Bundle
ERROR -   Method: io.reactivex.internal.operators.observable.ObservableDistinct.DistinctObserver.poll():T
ERROR -   Method: io.reactivex.internal.operators.observable.ObservableFilter.FilterObserver.poll():T
ERROR -   Method: kotlin.concurrent.LocksKt.write(java.util.concurrent.locks.ReentrantReadWriteLock, kotlin.jvm.functions.Function0):T
ERROR -   Method: kotlinx.coroutines.internal.ExceptionsConstuctorKt.tryCopyException(java.lang.Throwable):E
ERROR -   Method: rx.internal.operators.OperatorMerge.MergeSubscriber.emitScalar(java.lang.Object, long):void
ERROR -   Method: rx.internal.operators.OperatorMerge.MergeSubscriber.emitScalar(rx.internal.operators.OperatorMerge$InnerSubscriber, java.lang.Object, long):void
ERROR - finished with errors, count: 14

```

**Comment by sergey-wowwow** [comment]
@angervision it happens. All of the previously reported issues cover some reasons of such errors

**Comment by angervision** [comment]
Thanks @sergey-wowwow, very useful answer!
