### ISSUE TITLE
Unexpected magic: [100, 101, 120, 10, 48, 51, 54, 0]

### ISSUE THREAD

**Issue by rogov-sa** [skylot/jadx#92]
I use jadx 0.6.0.
Hi, I try to decompile wincaService.apk(or its classes.dex) and get the next exception:

$ ../tools/jadx/bin/jadx -v  -d out4 ../apks_and_firmwares/wincaService/wincaService.apk 
ERROR - jadx error: Unexpected magic: [100, 101, 120, 10, 48, 51, 54, 0]
com.android.dex.DexException: Unexpected magic: [100, 101, 120, 10, 48, 51, 54, 0]
	at com.android.dex.TableOfContents.readHeader(TableOfContents.java:79) ~[dx-1.10.jar:na]
	at com.android.dex.TableOfContents.readFrom(TableOfContents.java:69) ~[dx-1.10.jar:na]
	at com.android.dex.Dex.<init>(Dex.java:81) ~[dx-1.10.jar:na]
	at com.android.dex.Dex.<init>(Dex.java:75) ~[dx-1.10.jar:na]
	at jadx.core.utils.files.InputFile.loadFromZip(InputFile.java:99) ~[jadx-core-0.6.0.jar:na]
	at jadx.core.utils.files.InputFile.loadDexBuffer(InputFile.java:44) ~[jadx-core-0.6.0.jar:na]
	at jadx.core.utils.files.InputFile.<init>(InputFile.java:32) ~[jadx-core-0.6.0.jar:na]
	at jadx.api.JadxDecompiler.loadFiles(JadxDecompiler.java:113) ~[jadx-core-0.6.0.jar:na]
	at jadx.cli.JadxCLI.processAndSave(JadxCLI.java:29) ~[jadx-cli-0.6.0.jar:na]
	at jadx.cli.JadxCLI.main(JadxCLI.java:18) ~[jadx-cli-0.6.0.jar:na]

**Comment by CunningLogic** [comment]
Can you post this dex?

**Comment by rogov-sa** [comment]
Yes.
It's here: https://cloud.mail.ru/public/2fst/Z2vsCctpo

**Comment by CunningLogic** [comment]
Interesting, where is this from? The dex version on this is 36, which is not valid.

**Comment by rogov-sa** [comment]
It is from Winca S150  car android head unit firmware.
This is the main service, which provide varios features. (like switching audio channels, BT phone, parsing codes from MCU(which connected to CAN bus), etc...)
Also see the http://forum.xda-developers.com/wiki/Winca-Roadnav_S100/S150#S150

**Comment by CunningLogic** [comment]
Then its running a modified dalvikvm/art

**Comment by rogov-sa** [comment]
Does it mean that this is an exclusion and there is no possibility to decompile this dex by jadx? 
But dex2jar can process it. 
Is it possible that decompilation results is depend on the fact that I use dex2jar or decompile whole dex?

**Comment by CunningLogic** [comment]
Already told you how to make it work, change byte 0x6 to 0x35

**Comment by rogov-sa** [comment]
Thanks

**Comment by CunningLogic** [comment]
on second thought, this is the short lived dex version 36, not really seen, was discountinued after ICS. Can you dump the full /system for me? If I have time ill see if i can add support

**Comment by rogov-sa** [comment]
Yep. It's here:https://cloud.mail.ru/public/472R/UmJegaBoo

**Comment by jamuir** [comment]
I was examining an apk built inside my 7.1.1 aosp tree and encountered the "Unexpected magic" error above.

I was able to work around it by rebuilding jadx after replacing `jadx-core/lib/dx-1.10.jar` with the version generated in my tree:  `out/host/linux-x86/framework/dx.jar`
