### ISSUE TITLE
[core] Use of static fields instead of enum constants

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#924]
Class `com.google.android.gms.internal.vision.zzjd`
```java
package com.google.android.gms.internal.vision;

/*  JADX ERROR: JadxRuntimeException in pass: EnumVisitor
    jadx.core.utils.exceptions.JadxRuntimeException: Method arg registers not loaded: com.google.android.gms.internal.vision.zzje.<init>(java.lang.String, int, com.google.android.gms.internal.vision.zzji, int):void, class status: NOT_LOADED
    	at jadx.core.dex.nodes.MethodNode.getArgRegs(MethodNode.java:293)
    	at jadx.core.dex.attributes.nodes.SkipMethodArgsAttr.<init>(SkipMethodArgsAttr.java:47)
    	at jadx.core.dex.attributes.nodes.SkipMethodArgsAttr.skipArg(SkipMethodArgsAttr.java:27)
    	at jadx.core.dex.visitors.EnumVisitor.markArgsForSkip(EnumVisitor.java:346)
    	at jadx.core.dex.visitors.EnumVisitor.createEnumFieldByConstructor(EnumVisitor.java:302)
    	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByField(EnumVisitor.java:249)
    	at jadx.core.dex.visitors.EnumVisitor.extractEnumFields(EnumVisitor.java:216)
    	at jadx.core.dex.visitors.EnumVisitor.convertToEnum(EnumVisitor.java:142)
    	at jadx.core.dex.visitors.EnumVisitor.visit(EnumVisitor.java:77)
    */
public enum zzjd {
    public static final com.google.android.gms.internal.vision.zzjd zzabu = new com.google.android.gms.internal.vision.zzjd(com.google.android.gms.internal.vision.zzji.DOUBLE, 1);
    public static final com.google.android.gms.internal.vision.zzjd zzabv = new com.google.android.gms.internal.vision.zzjd(com.google.android.gms.internal.vision.zzji.FLOAT, 5);
    public static final com.google.android.gms.internal.vision.zzjd zzabw = new com.google.android.gms.internal.vision.zzjd(com.google.android.gms.internal.vision.zzji.LONG, 0);
    //...
```

APK: https://drive.google.com/file/d/1ICfL4A22K-KhVkw5RwvWdLJA8111iYvG/view?usp=sharing

**Comment by sergey-wowwow** [comment]
And one more error in the same app
```java
package com.google.android.gms.internal.vision;

/* JADX INFO: Failed to restore enum class, 'enum' modifier removed */
final class zzje extends com.google.android.gms.internal.vision.zzjd {
    zzje(java.lang.String str, int i, com.google.android.gms.internal.vision.zzji zzji, int i2) {
        super(str, 8, zzji, 2, null);
    }
}
```

**Comment by skylot** [comment]
@sergey-wowwow fixed.
`zzjd` class now looks correct and `zzje` inlined in `zzjd`, so `zzje` is not generated.

**Comment by sergey-wowwow** [comment]
Thanks! Looks like there are a few more error cases, I will open new ticket
