### ISSUE TITLE
Problem while building jadx-0.7.0

### ISSUE THREAD

**Issue by samyak-jn** [skylot/jadx#943]
Hii,

I'm trying to build the package for version 0.7.0, which has Gradle support of 4.x.

While, on building the package locally on my system, I'm getting the following error:

```
* What went wrong:
A problem occurred evaluating project ':jadx-gui'.
> Could not resolve all files for configuration ':jadx-gui:compile'.
   > Could not resolve uk.com.robust-it:cloning:1.9.9.
     Required by:
         project :jadx-gui > project :jadx-core
      > No cached version of uk.com.robust-it:cloning:1.9.9 available for offline mode.
      > No cached version of uk.com.robust-it:cloning:1.9.9 available for offline mode.
* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':jadx-gui'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:92)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:199)
	at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:204)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:61)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:58)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:41)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:64)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$100(LifecycleProjectEvaluator.java:34)
```
Any pointers why it is failing?

**Comment by skylot** [comment]
> No cached version of uk.com.robust-it:cloning:1.9.9 available for offline mode.

Looks like you run gradle in `offline` mode, please check answers at https://stackoverflow.com/questions/37409265/no-cached-version-available-for-offline-mode

**Comment by samyak-jn** [comment]
Hi @skylot, Thanks for the reply.

I'm trying to package **Kotlin** for version 1.3.30. The build system wants `kotlin-gradle-plugin` in offline mode because the build system requires all the dependencies to be installed locally in our system.

Plus we can't use the Gradle 6.4 to provide those jar files, as the newer Gradle highly depends upon the Kotlin dependency. It's kind of circular dependency if I understood it correctly..

Is there any other way for `kotlin-gradle-plugin` to provide these jar?
To be specific `kotlin-gradle-plugin:1.3.30-eap-28`.
