### ISSUE TITLE
[core] Method code generation error

### ISSUE THREAD

**Issue by alissonlauffer** [skylot/jadx#946]
Class `android.support.v4.content.ModernAsyncTask`

```java
    public final ModernAsyncTask<Params, Progress, Result> executeOnExecutor(Executor executor, Params... paramsArr) {
        Executor executor2 = executor;
        Params[] paramsArr2 = paramsArr;
        if (this.mStatus != Status.PENDING) {
            switch (this.mStatus) {
                case Status.RUNNING
                /*  JADX ERROR: Method code generation error
                    java.lang.ClassCastException: class jadx.core.dex.nodes.InsnNode cannot be cast to class jadx.api.plugins.input.data.annotations.EncodedValue (jadx.core.dex.nodes.InsnNode and jadx.api.plugins.input.data.annotations.EncodedValue are in unnamed module of loader 'app')
                    	at jadx.core.dex.attributes.FieldInitAttr.getEncodedValue(FieldInitAttr.java:35)
                    	at jadx.core.codegen.RegionGen.addCaseKey(RegionGen.java:291)
                    	at jadx.core.codegen.RegionGen.makeSwitch(RegionGen.java:270)
                    	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:65)
                    	at jadx.core.codegen.RegionGen.makeSimpleRegion(RegionGen.java:93)
                    	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:59)
                    	at jadx.core.codegen.RegionGen.makeRegionIndent(RegionGen.java:99)
                    	at jadx.core.codegen.RegionGen.makeIf(RegionGen.java:143)
                    	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:63)
                    	at jadx.core.codegen.RegionGen.makeSimpleRegion(RegionGen.java:93)
                    	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:59)
                    	at jadx.core.codegen.MethodGen.addRegionInsns(MethodGen.java:244)
                    	at jadx.core.codegen.MethodGen.addInstructions(MethodGen.java:237)
                    	at jadx.core.codegen.ClassGen.addMethodCode(ClassGen.java:347)
                    	at jadx.core.codegen.ClassGen.addMethod(ClassGen.java:300)
                    	at jadx.core.codegen.ClassGen.lambda$addInnerClsAndMethods$3(ClassGen.java:269)
                    	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
                    	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
                    	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
                    	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
                    */
                /*
                    this = this;
                    r0 = r7
                    r1 = r8
                    r2 = r9
                    r3 = r0
                    android.support.v4.content.ModernAsyncTask$Status r3 = r3.mStatus
                    android.support.v4.content.ModernAsyncTask$Status r4 = android.support.v4.content.ModernAsyncTask.Status.PENDING
                    if (r3 == r4) goto L_0x0039
                    int[] r3 = android.support.v4.content.ModernAsyncTask.AnonymousClass4.$SwitchMap$android$support$v4$content$ModernAsyncTask$Status
                    r4 = r0
                    android.support.v4.content.ModernAsyncTask$Status r4 = r4.mStatus
                    int r4 = r4.ordinal()
                    r3 = r3[r4]
                    switch(r3) {
                        case 1: goto L_0x0023;
                        case 2: goto L_0x002e;
                        default: goto L_0x0018;
                    }
                L_0x0018:
                    java.lang.IllegalStateException r3 = new java.lang.IllegalStateException
                    r6 = r3
                    r3 = r6
                    r4 = r6
                    java.lang.String r5 = "We should never reach this state"
                    r4.<init>(r5)
                    throw r3
                L_0x0023:
                    java.lang.IllegalStateException r3 = new java.lang.IllegalStateException
                    r6 = r3
                    r3 = r6
                    r4 = r6
                    java.lang.String r5 = "Cannot execute task: the task is already running."
                    r4.<init>(r5)
                    throw r3
                L_0x002e:
                    java.lang.IllegalStateException r3 = new java.lang.IllegalStateException
                    r6 = r3
                    r3 = r6
                    r4 = r6
                    java.lang.String r5 = "Cannot execute task: the task has already been executed (a task can be executed only once)"
                    r4.<init>(r5)
                    throw r3
                L_0x0039:
                    r3 = r0
                    android.support.v4.content.ModernAsyncTask$Status r4 = android.support.v4.content.ModernAsyncTask.Status.RUNNING
                    r3.mStatus = r4
                    r3 = r0
                    r3.onPreExecute()
                    r3 = r0
                    android.support.v4.content.ModernAsyncTask$WorkerRunnable<Params, Result> r3 = r3.mWorker
                    r4 = r2
                    r3.mParams = r4
                    r3 = r1
                    r4 = r0
                    java.util.concurrent.FutureTask<Result> r4 = r4.mFuture
                    r3.execute(r4)
                    r3 = r0
                    r0 = r3
                    return r0
                    switch-data {1->0x0023, 2->0x002e, }
                */
                throw new UnsupportedOperationException("Method not decompiled: android.support.v4.content.ModernAsyncTask.executeOnExecutor(java.util.concurrent.Executor, java.lang.Object[]):android.support.v4.content.ModernAsyncTask");
            }
```

### Additional info
 - This regression was introduced in build 1299 (ae31fee8).
 - This app was built with AIDE.
 - The same error is seen several times in the code.
 - Even after turning on "Show inconsistent code" option it still gives that error.

APK: https://drive.google.com/file/d/1RQesxeywrcHQveXEZGFiv9EfIczF2Q3X/view

**Comment by skylot** [comment]
Fixed.
@alissonlauffer thanks for report!

**Comment by alissonlauffer** [comment]
> Fixed.

Thanks! These commits also fixes some unneeded variables that were being assigned (Mostly because of AIDE):
![image](https://user-images.githubusercontent.com/29029632/83458858-a49c0180-a439-11ea-9ae6-71552dd08047.png)
