### ISSUE TITLE
[core]when I type it as Maven project and integrate it into spring project, sometimes there will be error message

### ISSUE THREAD

**Issue by jgswp** [skylot/jadx#973]
when I type it as Maven project and integrate it into spring project, sometimes there will be error message，
like this

![Uploading 图片.png…]()
Caused by: java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0
        at java.time.temporal.ValueRange.checkValidValue(ValueRange.java:311)
        at java.time.temporal.ChronoField.checkValidValue(ChronoField.java:703)
        at java.time.LocalDate.of(LocalDate.java:267)
        at java.time.LocalDateTime.of(LocalDateTime.java:336)

JDK and OPENJDK date verification is inconsistent
Can you give me some advice？

**Comment by jpstotz** [comment]
May be Maven tried to interpret a git commit hash as time?
