### ISSUE TITLE
jadx-gui save file error in Windows

### ISSUE THREAD

**Issue by PrinC** [skylot/jadx#98]
When I save all source file in windows, cmd print lots of error, mainly have two types:
```
java.io.FileNotFoundException: G:\Project\apksample\baidu\tv\pps\module\player\v
ideo\a\aux.java
        at java.io.FileOutputStream.open(Native Method) ~[na:1.8.0_31]
        at java.io.FileOutputStream.<init>(Unknown Source) ~[na:1.8.0_31]
        at java.io.FileOutputStream.<init>(Unknown Source) ~[na:1.8.0_31]
        at java.io.PrintWriter.<init>(Unknown Source) ~[na:1.8.0_31]
        at java.io.PrintWriter.<init>(Unknown Source) ~[na:1.8.0_31]
        at jadx.core.codegen.CodeWriter.save(CodeWriter.java:296) [jadx-core-0.6
.0.jar:na]
        at jadx.core.codegen.CodeWriter.save(CodeWriter.java:277) [jadx-core-0.6
.0.jar:na]
        at jadx.core.dex.visitors.SaveCode.save(SaveCode.java:31) [jadx-core-0.6
.0.jar:na]
        at jadx.api.JadxDecompiler$1.run(JadxDecompiler.java:162) [jadx-core-0.6
.0.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na
:1.8.0_31]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [n
a:1.8.0_31]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_31]
```

```
java.io.FileNotFoundException: G:\Project\apksample\baidu\tv\pps\module\player\v
ideo\bean\con.java (系统找不到指定的文件。)
        at java.io.FileOutputStream.open(Native Method) ~[na:1.8.0_31]
        at java.io.FileOutputStream.<init>(Unknown Source) ~[na:1.8.0_31]
        at java.io.FileOutputStream.<init>(Unknown Source) ~[na:1.8.0_31]
        at java.io.PrintWriter.<init>(Unknown Source) ~[na:1.8.0_31]
        at java.io.PrintWriter.<init>(Unknown Source) ~[na:1.8.0_31]
        at jadx.core.codegen.CodeWriter.save(CodeWriter.java:296) [jadx-core-0.6
.0.jar:na]
        at jadx.core.codegen.CodeWriter.save(CodeWriter.java:277) [jadx-core-0.6
.0.jar:na]
        at jadx.core.dex.visitors.SaveCode.save(SaveCode.java:31) [jadx-core-0.6
.0.jar:na]
        at jadx.api.JadxDecompiler$1.run(JadxDecompiler.java:162) [jadx-core-0.6
.0.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na
:1.8.0_31]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [n
a:1.8.0_31]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_31]
ERROR - Decode error
jadx.core.utils.exceptions.JadxException: Error decode: res/color/detail_forum_t
ext_color.xml
        at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:65) ~[jadx
-core-0.6.0.jar:na]
        at jadx.api.ResourcesLoader.loadContent(ResourcesLoader.java:82) ~[jadx-
core-0.6.0.jar:na]
        at jadx.api.ResourceFile.getContent(ResourceFile.java:52) [jadx-core-0.6
.0.jar:na]
        at jadx.api.JadxDecompiler$2.run(JadxDecompiler.java:173) [jadx-core-0.6
.0.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na
:1.8.0_31]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [n
a:1.8.0_31]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_31]
Caused by: java.io.IOException: Decode error: Type: 0x104 not yet implemented, p
osition: 0x2aa
        at jadx.core.xmlgen.CommonBinaryParser.die(CommonBinaryParser.java:96) ~
[jadx-core-0.6.0.jar:na]
        at jadx.core.xmlgen.BinaryXMLParser.decode(BinaryXMLParser.java:128) ~[j
adx-core-0.6.0.jar:na]
        at jadx.core.xmlgen.BinaryXMLParser.parse(BinaryXMLParser.java:88) ~[jad
x-core-0.6.0.jar:na]
        at jadx.api.ResourcesLoader.loadContent(ResourcesLoader.java:106) ~[jadx
-core-0.6.0.jar:na]
        at jadx.api.ResourcesLoader.access$000(ResourcesLoader.java:25) ~[jadx-c
ore-0.6.0.jar:na]
        at jadx.api.ResourcesLoader$1.decode(ResourcesLoader.java:89) ~[jadx-cor
e-0.6.0.jar:na]
        at jadx.api.ResourcesLoader.decodeStream(ResourcesLoader.java:63) ~[jadx
-core-0.6.0.jar:na]
        ... 6 common frames omitted
ERROR - Decode error
```

These error results in that many source file cannot save.

**Comment by jpstotz** [comment]
The file name "aux" is a reserved name on Windows. You can not create files of that name.

There are some other reserved names with will cause the same problem: CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9

**Comment by PrinC** [comment]
It's the problem, thanks!
