### ISSUE TITLE
[core] Add parameter to disable all debug comments

### ISSUE THREAD

**Issue by sergey-wowwow** [skylot/jadx#998]
Hey @skylot,
Can you implement a flag please that disables all comments such as:
```java
    /* JADX INFO: this call moved to the top of the method (can break code semantics) */
    public /* synthetic */ AudioPlayer(java.lang.String str, com.wickr.calling.media.audio.AudioFormat audioFormat2, com.wickr.calling.media.audio.AudioPlayer.Callback callback2, com.wickr.calling.media.audio.AECHelper aECHelper, int i, kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker) {
        this(str, audioFormat2, callback2, (i & 8) != 0 ? null : aECHelper);
    }
```
```java
    public final /* synthetic */ class WhenMappings {
```
```java
    /*  JADX ERROR: JadxRuntimeException in pass: InlineMethods
        jadx.core.utils.exceptions.JadxRuntimeException: Failed to process method for inline
        	at jadx.core.dex.visitors.InlineMethods.processInvokeInsn(InlineMethods.java:68)
        	at jadx.core.dex.visitors.InlineMethods.visit(InlineMethods.java:43)
        Caused by: jadx.core.utils.exceptions.JadxRuntimeException: Class not yet loaded at codegen stage
        	at jadx.core.dex.nodes.ClassNode.reloadAtCodegenStage(ClassNode.java:589)
        	at jadx.core.dex.visitors.InlineMethods.processInvokeInsn(InlineMethods.java:60)
        	... 1 more
        */
    @org.jetbrains.annotations.NotNull
    public static final java.lang.String getTAG(@org.jetbrains.annotations.NotNull java.lang.Object r3) {
        /*
            java.lang.String r0 = "$this$TAG"
            kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull(r3, r0)
            java.lang.String r3 = r3.toString()
            r0 = 0
            java.lang.String r1 = "."
            r2 = 2
            java.lang.String r3 = kotlin.text.StringsKt.substringAfterLast$default(r3, r1, r0, r2, r0)
            return r3
        */
        throw new UnsupportedOperationException("Method not decompiled: com.wickr.calling.Extensions.getTAG(java.lang.Object):java.lang.String");
    }
```

**Comment by alissonlauffer** [comment]
We could do a logging level option there. E.g.: `info` log level shows `info` and upper levels, `error` log level just shows errors and omits `info` and `warning` messages.

**Comment by sergey-wowwow** [comment]
@alissonlauffer 
Is that option about outputs into sources? I thought that argument affects only console logs

**Comment by alissonlauffer** [comment]
> Is that option about outputs into sources?
Yes.

**Comment by skylot** [comment]
Ok. I will add separate option to set jadx code comments level. Level names will be similar to log level names.

**Comment by bagipro** [comment]
Hey @skylot @alissonlauffer,

I tried to play with those options (such as `--quiet` or `--log-level ERROR` that theoretically should disable all the comments). However, that doesn't work. I still receive messages in sources such as
```java
/* loaded from: classes5.dex */
```
and
```java
     /* access modifiers changed from: private */
```

Am I doing something wrong, or is the feature not working via the logging option?

Thanks!

**Comment by skylot** [comment]
@bagipro this feature not implemented yet, sorry.
> I tried to play with those options (such as --quiet or --log-level ERROR

These options control only output log levels.

**Comment by bagipro** [comment]
@skylot 
Oh, okay, thanks for your reply. Hopefully, it will be implemented soon :)
