### ISSUE TITLE
[core] JadxRuntimeException in pass: InlineMethods for a small method

### ISSUE THREAD

**Issue by bagipro** [skylot/jadx#999]
Hey, class `com.wickr.calling.Extensions`
```java
    /*  JADX ERROR: JadxRuntimeException in pass: InlineMethods
        jadx.core.utils.exceptions.JadxRuntimeException: Failed to process method for inline
        	at jadx.core.dex.visitors.InlineMethods.processInvokeInsn(InlineMethods.java:68)
        	at jadx.core.dex.visitors.InlineMethods.visit(InlineMethods.java:43)
        Caused by: jadx.core.utils.exceptions.JadxRuntimeException: Class not yet loaded at codegen stage
        	at jadx.core.dex.nodes.ClassNode.reloadAtCodegenStage(ClassNode.java:589)
        	at jadx.core.dex.visitors.InlineMethods.processInvokeInsn(InlineMethods.java:60)
        	... 1 more
        */
    @org.jetbrains.annotations.NotNull
    public static final java.lang.String getTAG(@org.jetbrains.annotations.NotNull java.lang.Object r3) {
        /*
            java.lang.String r0 = "$this$TAG"
            kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull(r3, r0)
            java.lang.String r3 = r3.toString()
            r0 = 0
            java.lang.String r1 = "."
            r2 = 2
            java.lang.String r3 = kotlin.text.StringsKt.substringAfterLast$default(r3, r1, r0, r2, r0)
            return r3
        */
        throw new UnsupportedOperationException("Method not decompiled: com.wickr.calling.Extensions.getTAG(java.lang.Object):java.lang.String");
    }
```

APK: https://drive.google.com/file/d/1XlE3s-W5H5N5RfjP_1wGtdBwk6ycYGD8/view?usp=sharing

**Comment by skylot** [comment]
@bagipro thanks! Fixed. That was stupid bug :rofl:
